### ISSUE TITLE
redshift vacuum command fails because it's within a transaction block

### ISSUE THREAD

**Issue by ashthom** [flyway/flyway#1367] opened 2016-07-18 13:02 UTC
###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I added a vacuum command in afterMigrate.sql.
Then I did "mvn flyway:migrate"

I got the below error:
[ERROR] SQL State  : 25001
[ERROR] Error Code : 500310
[ERROR] Message    : [Amazon](500310) Invalid operation: VACUUM cannot run inside a transaction block;

###### What did you expect to see?

afterMigrate.sql containing the vacuum command runs successfully

###### What did you see instead?

[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:4.0.3:migrate (default-cli) on project auto-db-deployment: org.flywaydb.core.internal.dbsupport.FlywaySqlScript
Exception:
[ERROR] Migration afterMigrate.sql failed
[ERROR] SQL State  : 25001
[ERROR] Error Code : 500310
[ERROR] Message    : [Amazon](500310) Invalid operation: VACUUM cannot run inside a transaction block;

**Comment by axelfontaine** [comment] 2016-07-18 14:19
Duplicate of #851

**Closed by axelfontaine** 2016-07-18 14:19 UTC
