### ISSUE TITLE
Make DbSupport object pluggable

### ISSUE THREAD

**Issue by jochenw** [flyway/flyway#1472] opened 2016-11-20 12:10 UTC
###### What version of Flyway are you using?

4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Neither, I am using Flyway within my unit tests, and in the application.

###### What database are you using (type & version)?

Derby 10.13.1.1

###### What operating system are you using?

Variuos

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Trying to find a workaround for #1331. If I could replace the DbSupport object with my own, then this issue wouldn't bother me, and I could continue using a stuck Flyway. So, I am forced to work with my own, modified version. (Changes outlined in #1331.)
 

###### What did you expect to see?

Something like a method

  protected DbSupport newDbSupport(Connection connection, boolean printInfo);

in Flyway. I could overwrite that with my own implementation.

###### What did you see instead?

The static method DbSupportFactory.createDbSupport(Connection connection, boolean printInfo) is used, on which I have no influence.

**Comment by axelfontaine** [comment] 2016-11-21 13:14
Duplicate of #1137

**Closed by axelfontaine** 2016-11-21 13:14 UTC

**Comment by jochenw** [comment] 2016-11-22 10:01
Please reopen, and reconsider: The required changes are very small (basically, wrap the call to DbSupportFactory.createDbSupport in a protected method), and there is no risk.

OTOH, the fact that there is a duplicate, might be interpreted as "There is some need."

Thanks,

Jochen
