### ISSUE TITLE
SBT tasks should be executed in forked JVM processes

### ISSUE THREAD

**Issue by nartamonov** [flyway/flyway#1621] opened 2017-05-04 08:35 UTC
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

SBT plugin

###### What database are you using (type & version)?

PostgreSQL 9.6.2

###### What operating system are you using?

Windows 7 SP1

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I've created JdbcMigration-derived repeatable script written in Scala. **Migration script has transitive dependencies on various staff from Scala standard library 2.12 which is used in my application.** Then I've tried to run flywayInfo task within SBT console.

###### What did you expect to see?

I expected to see results of flywayInfo task.

###### What did you see instead?

Flyway SBT plugin has successfully found my migration script (from logs), then tried to call `getChecksum` on that script, which is failed because script transitively depends on Scala library 2.12, but flywayInfo task actually executes with Scala 2.10 library:

```
[debug] Found class: ru.voentelecom.uds.db.migrations.R__LoadShipments
java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
        at pureconfig.DurationConvert$.<init>(DurationConvert.scala:74)
        at pureconfig.DurationConvert$.<clinit>(DurationConvert.scala)
        at pureconfig.LowPriorityConfigConvertImplicits.$init$(ConfigConvert.scala:464)
        at pureconfig.ConfigConvert$.<init>(ConfigConvert.scala:57)
        at pureconfig.ConfigConvert$.<clinit>(ConfigConvert.scala)
        at ru.voentelecom.uds.db.migrations.Settings.migrationSettings(Settings.scala:6)
        at ru.voentelecom.uds.db.migrations.Settings.migrationSettings$(Settings.scala:6)
        at ru.voentelecom.uds.db.migrations.R__LoadShipments.migrationSettings$lzycompute(R__LoadShipments.scala:15)
        at ru.voentelecom.uds.db.migrations.R__LoadShipments.migrationSettings(R__LoadShipments.scala:15)
        at ru.voentelecom.uds.db.migrations.R__LoadShipments.getChecksum(R__LoadShipments.scala:32)
        at org.flywaydb.core.internal.resolver.jdbc.JdbcMigrationResolver.extractMigrationInfo(JdbcMigrationResolver.java:114)
        at org.flywaydb.core.internal.resolver.jdbc.JdbcMigrationResolver.resolveMigrationsForSingleLocation(JdbcMigrationResolver.java:93)
        at org.flywaydb.core.internal.resolver.jdbc.JdbcMigrationResolver.resolveMigrations(JdbcMigrationResolver.java:78)
        at org.flywaydb.core.internal.resolver.jdbc.JdbcMigrationResolver.resolveMigrations(JdbcMigrationResolver.java:41)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:123)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:105)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:91)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:44)
        at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:112)
        at org.flywaydb.core.Flyway$4.execute(Flyway.java:1115)
        at org.flywaydb.core.Flyway$4.execute(Flyway.java:1097)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1464)
        at org.flywaydb.core.Flyway.info(Flyway.java:1097)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$45$$anonfun$apply$6.apply(FlywayPlugin.scala:212)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$45$$anonfun$apply$6.apply(FlywayPlugin.scala:211)
        at org.flywaydb.sbt.FlywayPlugin$.withContextClassLoader(FlywayPlugin.scala:248)
        at org.flywaydb.sbt.FlywayPlugin$.org$flywaydb$sbt$FlywayPlugin$$withPrepared(FlywayPlugin.scala:231)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$45.apply(FlywayPlugin.scala:211)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$45.apply(FlywayPlugin.scala:211)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

###### How to solve that problem?

Flyway SBT tasks should be executed in context of Scala library which are used by application code (and migration scripts). Currently SBT compiled against Scala 2.10, but applications usually use 2.11 or 2.12.

To solve this issue Flyway SBT plugin should run Flyway commands in forked JVM processes with correct aplication classpath which includes scala standard library used by application. For example, such technique is used by Vaadin plugin, see https://github.com/henrikerola/sbt-vaadin-plugin/blob/master/src/main/scala/org/vaadin/sbt/tasks/CompileThemesTask.scala#L45-L50

###### Similar reports

These issue was raised early in #1461 but was closed by mistake I believe.

**Comment by axelfontaine** [comment] 2017-05-05 11:36
Duplicate of #1461 . We have now plans to support this at this time.

**Closed by axelfontaine** 2017-05-05 11:36 UTC

**Comment by nartamonov** [comment] 2017-05-05 21:42
@axelfontaine I suppose you can't implement this for now, it's ok. Can you elaborate, do you think this feature would be helpful? Would PR from community be welcomed? Thanks!

**Comment by axelfontaine** [comment] 2017-05-07 10:40
@nartamonov I just feel it will complicate the release process for very little added benefit, and I currently don't think that tradeoff is worth it.
