### ISSUE TITLE
Parser Limitations - Infinite `flyway migrate` executions

### ISSUE THREAD

**Issue by andhrelja** [flyway/flyway#3677] opened 2023-05-25 12:53 UTC
###### Which version and edition of Flyway are you using?

Flyway Community Edition 9.19.1 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

It is the latest version, however I cannot reproduce with an older version (Community Edition 8.5.0)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

Snowflake 7.17

###### Which operating system are you using?

Windows/Ubuntu (issue is happening on both)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Included the following script to Flyway's filesystem:
```sql
-- R__VW_DUMMY_VIEW.sql
CREATE VIEW DUMMY_VIEW AS SELECT 1 AS DECLARE_VARIABLE_INDICATOR;
```

**EDIT**: The same behavior does not happen when deploying a Stored Procedure with a DECLARE keyword, i.e. the following is deployed successfully:
```sql
CREATE OR REPLACE PROCEDURE find_flyway_record(installed_rank INTEGER)
RETURNS TABLE (installed_rank INTEGER, script VARCHAR)
LANGUAGE SQL
AS
$$
DECLARE
  res RESULTSET DEFAULT (SELECT installed_rank, script FROM flyway_schema_history WHERE installed_rank = :installed_rank);
BEGIN
  RETURN TABLE(res);
END;
$$
;
```

###### What did you expect to see?

A successful migration - a new Snowflake `DUMMY_VIEW` view, and the following logs:
```log
NOTE: Picked up JDK_JAVA_OPTIONS: --add-opens java.base/java.nio=ALL-UNNAMED
Flyway Community Edition 9.19.1 by Redgate
See release notes here: https://rd.gt/416ObMi

Database: jdbc:snowflake://oua84053.snowflakecomputing.com:443/ (Snowflake 7.17)
QUOTED_IDENTIFIERS_IGNORE_CASE option is true
Successfully validated 2 migrations (execution time 00:02.087s)
Current version of schema "SCHEMA1": 1
Migrating schema "SCHEMA1" with repeatable migration "VW DUMMY VIEW"
Successfully applied 1 migration to schema "SCHEMA1" (execution time 00:16.706s)
```

###### What did you see instead?

An infinitely running migration, logs hang as follows:

```log
NOTE: Picked up JDK_JAVA_OPTIONS: --add-opens java.base/java.nio=ALL-UNNAMED
Flyway Community Edition 9.19.1 by Redgate
See release notes here: https://rd.gt/416ObMi

Database: jdbc:snowflake://oua84053.snowflakecomputing.com:443/ (Snowflake 7.17)
QUOTED_IDENTIFIERS_IGNORE_CASE option is true
Successfully validated 2 migrations (execution time 00:02.059s)
Current version of schema "SCHEMA1": 1
```

###### Workaround & Conclusion

Included the following script to Flyway's filesystem:
```sql
-- R__VW_DUMMY_VIEW.sql
CREATE VIEW DUMMY_VIEW AS SELECT 1 AS "DECLARE_VARIABLE_INDICATOR";
```

To conclude the created issue, my question is why did this migration work with Flyway 8.5.0 and is not working with Flyway 9.19.1? Is this an expected Parser Limitation caused by a new Java engine, or is it a bug that ca be fixed so that behavior from v8.5.0 is retained?

Thanks!

**Comment by JasonLuo-Redgate** [comment] 2023-06-20 16:46
Hi @andhrelja , this issue should be fixed already in the latest Flyway version, may I confirm with you that it's fixed?

**Comment by JasonLuo-Redgate** [comment] 2023-07-10 14:18
Hi @andhrelja , we consider this might be the same issue as https://github.com/flyway/flyway/issues/3702, which caused by the `DECLARE `prefix in `DECLARE_VARIABLE_INDICATOR`.

**Closed** 2023-07-10 14:19 UTC
Labels: r: duplicate
