### ISSUE TITLE
Support for NoSQL

### ISSUE THREAD

**Issue by ThiyaguE** [flyway/flyway#1505] opened 2017-01-15 16:23 UTC
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command Line

###### What database are you using (type & version)?
MongoDB 3.4

###### What operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Would like to use flyway for Mongodb

###### What did you expect to see?
Would like to use flyway for Mongodb

###### What did you see instead?
Would like to use flyway for Mongodb

**Comment by khatkar** [comment] 2017-01-18 21:01
Checkout this PR https://github.com/flyway/flyway/pull/1482

**Comment by axelfontaine** [comment] 2017-01-29 23:01
Duplicate of #810

**Closed by axelfontaine** 2017-01-29 23:01 UTC
