### ISSUE TITLE
Feature request: Offline validation of schema change scripts

### ISSUE THREAD

**Issue by drogin** [flyway/flyway#1321] opened 2016-05-24 13:00 UTC
## 
###### What database are you using (type & version)?

Postgres
###### What operating system are you using?

Linux
###### What did you do?

Feature request: If there isn't a simple way to do this already, would it be beneficial to add an "offline check"(ie, only validate naming conventions etc for scripts), without touching a remote(or local) database? This could be used in a version control hook to make sure there are no version-conflicts when merging long-lived branches, wrong naming conventions etc in the schema script files
## 
##

**Comment by axelfontaine** [comment] 2017-11-26 22:45
Duplicate of #986

**Closed by axelfontaine** 2017-11-26 22:45 UTC
Labels: t: feature
