### ISSUE TITLE
Flyway recommends update if connected to PostgreSQL 11.x

### ISSUE THREAD

**Issue by ssonnenberg** [flyway/flyway#2238] opened 2018-12-11 13:22 UTC
###### Which version and edition of Flyway are you using?
5.2.4 community edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin

###### Which database are you using (type & version)?

PostgreSQL 11.1 (Debian 11.1-1.pgdg90+1)

###### Which operating system are you using?
Linux
Distributor ID: Debian
Description:    Debian GNU/Linux 9.6 (stretch)
Release:        9.6
Codename:       stretch

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

flyway-maven-plugin:5.2.4:migrate (default-cli) @ database-migration

###### What did you expect to see?

I expect to see no warning, everything is working smoothly.
PostgreSQL 11 is released in October 11.1 in November as a first bugfix release.
flyway should support this release.

###### What did you see instead?

[INFO] Flyway Community Edition 5.2.4 by Boxfuse
[INFO] Database: jdbc:postgresql://localhost:9876/database (PostgreSQL 11.1)
[WARNING] Flyway upgrade recommended: PostgreSQL 11.1 is newer than this version of Flyway and support has not been tested.
[INFO] Successfully validated 26 migrations (execution time 00:01.208s)
[INFO] Current version of schema "public": 1.25
[INFO] Schema "public" is up to date. No migration necessary.
[WARNING] Flyway upgrade recommended: PostgreSQL 11.1 is newer than this version of Flyway and support has not been tested.

**Comment by axelfontaine** [comment] 2018-12-11 13:46
Duplicate of #2178

**Closed by axelfontaine** 2018-12-11 13:46 UTC

**Comment by koterpillar** [comment] 2019-01-20 22:37
This is not a duplicate: #2178 is about adding support for PostgreSQL 11; this one is about the warning message which is printed.

**Comment by ssonnenberg** [comment] 2019-01-21 07:39
And still no fixed version available, PostgreSQL 11.1 has been released November 2018.
