### ISSUE TITLE
Schemas are not created if the first schema is 'public' [redshift]

### ISSUE THREAD

**Issue by samay-kapadia-zocdoc** [flyway/flyway#1612] opened 2017-04-24 21:43 UTC
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
SBT

###### What database are you using (type & version)?
AWS Redshift

###### What operating system are you using?
OS X

###### What did you do?
In my build.sbt, this is the buggy code:
`flywaySchemas := Seq("public", "otherSchema")`
Which results in this:
```
[info] Successfully validated 0 migrations (execution time 00:00.125s)
[info] Creating Metadata table: "public"."schema_version"
[info] Current version of schema "public": << Empty Schema >>
[info] Schema "public" is up to date. No migration necessary.
[success] Total time: 2 s, completed Apr 24, 2017 5:37:38 PM
```
Notice how otherSchema was not created.

However, with this code: 
`flywaySchemas := Seq("schema1", "schema2", "schema3")`
We get this:
```
[info] Creating schema "schema1" ...
[info] Creating schema "schema2" ...
[info] Creating schema "schema3" ...
[info] Creating Metadata table: "schema1"."schema_version"
```

###### What did you expect to see?
```
[info] Creating schema "otherSchema" ...
```

###### What did you see instead?
` `

**Comment by axelfontaine** [comment] 2017-11-15 14:58
Duplicate of #1328

**Closed by axelfontaine** 2017-11-15 14:58 UTC
Labels: d: Redshift
