### ISSUE TITLE
Java Migrations are scanned, found but then ignored

### ISSUE THREAD

**Issue by jcgarnier** [flyway/flyway#2483] opened 2019-08-26 07:56 UTC
###### Which version and edition of Flyway are you using?
Community Edition Flyway 6.0.0 (but I experienced the problem with 5.2.0 and 5.2.4 and 6.0.0-beta2)

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
It's the last version when I'm writing the issue.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle Plugin. I experienced the problem with Gradle 4.9, and now with Gradle 5.4.1

###### Which database are you using (type & version)?
Oracle 18c

###### Which operating system are you using?
Centos 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I'm running flywayInfo, or flywayMigrate, and I see that flyway knows about my SQL migrations, but ignores completely my Java migrations. It's like they don't exist. 
When I run with debug logs, or attach a debugger to the gradle task execution, I see that the classes are scanned properly, and actually added to the classes list in the Scanner. But when the code reaches Scanner.getClasses, the statement ` if (!implementedInterface.isAssignableFrom(clazz)) {` is returning false for all my classes. `implementedInterface` is `org.flywaydb.core.api.migration.JavaMigration`, and `clazz` is my class, e.g. `cern.acctesting.db.migrations.base.V1_1__InsertEnum`

V1_1__InsertEnum is declared the following way
```
import org.flywaydb.core.api.migration.BaseJavaMigration;
...
public class V1_1__InsertEnum extends BaseJavaMigration {
...
```

###### What did you expect to see?
I expect my classes to be assignable from the JavaMigration interface, and flywayInfo to take them into account and flywayMigrate to apply them.

###### What did you see instead?
I cannot run my migrations and my classes seem not to be assignableFrom JavaMigration.

It seems to be a problem with the ClassLoader maybe. Because a simple unit test like this is fine
```
    @Test
    public void isAssignableFrom(){
        assertTrue(JavaMigration.class.isAssignableFrom(V1_1__InsertEnum.class));
    }
```

I tried the command line tool, after producing a jar containing my migrations. It's even more confusing because some Java migrations are recognized (e.g. V1_1__InsertEnum is ok), but others are not, while all are configured the smae. 

Thank you for your help
Jc
ps: here is a confused and confusing post I put on stackoverflow a while ago, maybe it will give you some hints: https://stackoverflow.com/questions/57311404/most-but-not-all-java-flyway-migrations-are-skipped

**Comment by alextercete** [comment] 2019-08-27 10:20
@jcgarnier Thanks for the thorough report, we'll have a go at reproducing the issue.

In the meantime, any chance you could put together examples of Java migrations that are/aren't recognized when you use the CLI?

**Comment by jcgarnier** [comment] 2019-08-27 13:19
Hi @alextercete and thank you for having a look already.

Here is the content of my database (the jump is version number is explained because in this DB we do not run all migrations, we have so called base migrations and content migrations, here only the base are applied):
```
1	1	1.0	create initial db	SQL	V1_0__create_initial_db.sql	-2113371634	ACCTESTING_DEV	10-FEB-16 11.51.56.194171000 AM	1236	1
2	2	1.1	InsertEnum	JDBC	cern.acctesting.db.migrations.base.V1_1__InsertEnum		ACCTESTING_DEV	10-FEB-16 11.51.56.301783000 AM	84	1
3	3	1.2	InsertDefaultCampaign	JDBC	cern.acctesting.db.migrations.base.V1_2__InsertDefaultCampaign		ACCTESTING_DEV	10-FEB-16 11.51.56.393767000 AM	78	1
4	4	1.5	test campaigns update trigger	SQL	V1_5__test_campaigns_update_trigger.sql	1393567149	ACCTESTING_DEV	10-FEB-16 11.51.56.444262000 AM	37	1
5	5	1.6	create default phase	SQL	V1_6__create_default_phase.sql	-495548740	ACCTESTING_DEV	10-FEB-16 11.51.56.491560000 AM	33	1
6	6	1.7	delete default test campaign	SQL	V1_7__delete_default_test_campaign.sql	279939136	ACCTESTING_DEV	10-FEB-16 11.51.56.533669000 AM	30	1
7	7	1.8	create sign only tests table	SQL	V1_8__create_sign_only_tests_table.sql	1329190327	ACCTESTING_DEV	10-FEB-16 11.51.56.597730000 AM	52	1
8	8	2.0	CreateTestRunPermissionTable	SQL	V2_0__CreateTestRunPermissionTable.sql	-1439991998	ACCTESTING_DEV	10-FEB-16 11.51.56.642723000 AM	30	1
9	9	2.1	RenameTestRunPermissionsTable	SQL	V2_1__RenameTestRunPermissionsTable.sql	699172657	ACCTESTING_DEV	10-FEB-16 11.51.56.671802000 AM	16	1
10	10	2.2	create test progress email recipients table	SQL	V2_2__create_test_progress_email_recipients_table.sql	815082874	ACCTESTING_DEV	10-FEB-16 11.51.56.717939000 AM	33	1
11	11	2.5	IncreaseCommentColumnLength	JDBC	cern.acctesting.db.migrations.base.V2_5__IncreaseCommentColumnLength		ACCTESTING_DEV	10-FEB-16 11.51.56.975207000 AM	242	1
12	12	2.8.0	Add HWC EE EXPERT Role	JDBC	cern.acctesting.db.migrations.base.V2_8_0__Add_HWC_EE_EXPERT_Role		ACCTESTING_DEV	10-FEB-16 11.51.57.001290000 AM	14	1
13	13	3.6	create molr tests table	SQL	V3_6__create_molr_tests_table.sql	-329158039	ACCTESTING_DEV	20-JUN-19 10.23.46.480466000 AM	178	1
```

Here is the report from flyway CLI 6.0.0:
```
+-----------+---------+---------------------------------------------+------+---------------------+---------+
| Category  | Version | Description                                 | Type | Installed On        | State   |
+-----------+---------+---------------------------------------------+------+---------------------+---------+
| Versioned | 1.0     | create initial db                           | SQL  | 2016-02-10 11:51:56 | Success |
| Versioned | 1.1     | InsertEnum                                  | JDBC | 2016-02-10 11:51:56 | Success |
| Versioned | 1.2     | InsertDefaultCampaign                       | JDBC | 2016-02-10 11:51:56 | Missing |
| Versioned | 1.5     | test campaigns update trigger               | SQL  | 2016-02-10 11:51:56 | Success |
| Versioned | 1.6     | create default phase                        | SQL  | 2016-02-10 11:51:56 | Success |
| Versioned | 1.7     | delete default test campaign                | SQL  | 2016-02-10 11:51:56 | Success |
| Versioned | 1.8     | create sign only tests table                | SQL  | 2016-02-10 11:51:56 | Success |
| Versioned | 2.0     | CreateTestRunPermissionTable                | SQL  | 2016-02-10 11:51:56 | Success |
| Versioned | 2.1     | RenameTestRunPermissionsTable               | SQL  | 2016-02-10 11:51:56 | Success |
| Versioned | 2.2     | create test progress email recipients table | SQL  | 2016-02-10 11:51:56 | Success |
| Versioned | 2.5     | IncreaseCommentColumnLength                 | JDBC | 2016-02-10 11:51:56 | Missing |
| Versioned | 2.8.0   | Add HWC EE EXPERT Role                      | JDBC | 2016-02-10 11:51:57 | Success |
| Versioned | 3.6     | create molr tests table                     | SQL  | 2019-06-20 10:23:46 | Success |
+-----------+---------+---------------------------------------------+------+---------------------+---------+
```
I attached the 4 JDBC migrations here (as java.txt):

[lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V2_8_0__Add_HWC_EE_EXPERT_Role.java.txt](https://github.com/flyway/flyway/files/3546255/lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V2_8_0__Add_HWC_EE_EXPERT_Role.java.txt)
[lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V2_5__IncreaseCommentColumnLength.java.txt](https://github.com/flyway/flyway/files/3546256/lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V2_5__IncreaseCommentColumnLength.java.txt)
[lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V1_2__InsertDefaultCampaign.java.txt](https://github.com/flyway/flyway/files/3546257/lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V1_2__InsertDefaultCampaign.java.txt)
[lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V1_1__InsertEnum.java.txt](https://github.com/flyway/flyway/files/3546258/lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V1_1__InsertEnum.java.txt)

Maybe I'm missing something obvious but I don't see it.

None of the classes is missing from the jar:
```
[user@host flyway-6.0.0]$ unzip -l jars/lhc-hwc-acctesting-db-2.2.1.jar | grep V1_1
     3518  08-26-2019 09:46   cern/acctesting/db/migrations/base/V1_1__InsertEnum.class
[user@host flyway-6.0.0]$ unzip -l jars/lhc-hwc-acctesting-db-2.2.1.jar | grep V1_2
     3753  08-26-2019 09:46   cern/acctesting/db/migrations/base/V1_2__InsertDefaultCampaign.class
[user@host flyway-6.0.0]$ unzip -l jars/lhc-hwc-acctesting-db-2.2.1.jar | grep V2_5
     4115  08-26-2019 09:46   cern/acctesting/db/migrations/base/V2_5__IncreaseCommentColumnLength.class
[user@host flyway-6.0.0]$ unzip -l jars/lhc-hwc-acctesting-db-2.2.1.jar | grep V2_8_0
     1211  08-26-2019 09:46   cern/acctesting/db/migrations/base/V2_8_0__Add_HWC_EE_EXPERT_Role.class
```

Thank you
Jc

**Comment by alextercete** [comment] 2019-08-28 12:56
@jcgarnier Thanks for the details.

I noticed that the Java migrations attached extend `JdbcMigration` instead of `BaseJavaMigration`. The former was deprecated in Flyway 5 and removed in Flyway 6. This doesn't look like the cause of your issue (because you mention in StackOverflow you tried extending `BaseJavaMigration` without success), but be aware you'll need make changes when upgrading to version 6.

I'm starting to suspect your problem might be the same as #2482, judging by this line from your StackOverflow question:

```
13:43:01.265 [QUIET] [system.out] [DEBUG] - Skipping non-instantiable class (invocation error): cern.acctesting.db.migrations.content.V2_3_2__CreateTestPhaseAndSignOnlyTestsForBeamLossMonitors
```

**Comment by jcgarnier** [comment] 2019-08-28 14:12
hum my bad, I made a mistake trying to go fast and I failed, sending you files from the wrong branch and making you lose time. 
Here I attach the correct ones the file is the same except that indeed it extends BaseJavaMigration and uses an org.flywaydb.core.api.migration.Context instead of the java.sql.Connection directly. 
And indeed in my setup the class is not skipped and properly loaded during the scanning as it extends properly BaseJavaMigration that implements JavaMigration, but it is not used in a later stage in the getClasses for some obscure reason.

Please try with these files:
[lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V2_8_0__Add_HWC_EE_EXPERT_Role.java.txt](https://github.com/flyway/flyway/files/3551287/lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V2_8_0__Add_HWC_EE_EXPERT_Role.java.txt)
[lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V2_5__IncreaseCommentColumnLength.java.txt](https://github.com/flyway/flyway/files/3551288/lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V2_5__IncreaseCommentColumnLength.java.txt)
[lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V1_2__InsertDefaultCampaign.java.txt](https://github.com/flyway/flyway/files/3551289/lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V1_2__InsertDefaultCampaign.java.txt)
[lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V1_1__InsertEnum.java.txt](https://github.com/flyway/flyway/files/3551286/lhc-hwc-acctesting-db_src_java_cern_acctesting_db_migrations_base_V1_1__InsertEnum.java.txt)

And if you don't manage to reproduce it that means the issue is definitely on my side, but I got no clue where yet.

**Comment by alextercete** [comment] 2019-08-28 16:26
@jcgarnier Just to confirm, are you not seeing the `Skipping <class>` debug message in Flyway 6?

**Comment by jcgarnier** [comment] 2019-08-29 07:56
I don't see the Skipping message in Flyway 6. I was seeing it in Flyway 5.2.4 though

**Comment by alextercete** [comment] 2019-08-29 08:25
@jcgarnier This might be a long shot, but could there be a mismatch between the version of the Flyway Gradle plugin and the Flyway Core dependency? Any chance you can share the relevant parts of your `build.gradle` file?

**Comment by jcgarnier** [comment] 2019-08-29 10:06
Sure!
You must know that we're also using a kind of wrapper which is our (compulsory and standard) internal build tool. But I tried with plain gradle as well on a tiny project and reached the same error.

Here is the build.gradle
```
apply from: 'src/main/resources/gradle/flyway-migration.gradle'

flywayMigrate.mustRunAfter flywayClean
build.mustRunAfter flywayMigrate

configurations {
    all*.exclude group: 'org.slf4j', module: 'slf4j-jdk14'
}

dependencies {
    compile project(':lhc-hwc-acctesting-core')
}
```

And the flyway.gradle:
```
import org.flywaydb.gradle.FlywayPlugin

buildscript {
    repositories {
        maven { url 'http://artifactory.cern.ch/development' }
    }
    dependencies {
        classpath 'org.flywaydb:flyway-gradle-plugin:6.0.0'
    }
}
project.getPlugins().apply(org.flywaydb.gradle.FlywayPlugin.class)


project.dependencies {
    /* Local Groovy needed to avoid Eclipse errors */
    runtime localGroovy()
    compile "org.flywaydb:flyway-core:6.0.0"
}


project.afterEvaluate {
    logger.info("flyway-migration.gradle: acctesting.database=[{}]", System.getProperty("acctesting.database"))
    logger.info("flyway-migration.gradle: lsa.database=[{}]", System.getProperty("lsa.database"))

    configureFlyway()
}

gradle.taskGraph.whenReady { taskGraph ->
    /* Check the Gradle task graph if it contains tasks which should NOT be executed on PRO database */
    logger.info "Gradle task DAG ready !"
    logger.info "Checking the following tasks will be executed: [flywayBaseline, flywayClean, flywayMigrate]..."
    if (gradle.taskGraph.hasTask(project.flywayBaseline) ||
            gradle.taskGraph.hasTask(project.flywayClean) ||
            gradle.taskGraph.hasTask(project.flywayMigrate)){

        /* Terminate the build if we try to invoke the tasks on the PRO database */
        logger.info "Checking if we are executing the Flyway migration on the PRO database..."
        failIfProductionDatabase(defineTargetDatabase())
    }
}

/* ---------- START Flyway Migration Functions --------------------------------------------------------------------- */

void configureFlyway() {
    logger.info("=================== START Configure Flyway =====================================")

    // load properties
    loadFlywayConfiguration()

    // load flyway locations
    def String flywayLocations = getFlywayLocationsForCurrentMigration()
    logger.info "Flyway locations: {}", flywayLocations
    project.ext["flyway.locations"] = flywayLocations

    // dump configuration
    logFlywayProjectProperties()
    logger.info("===================  END  Configure Flyway =====================================")
}

String defineTargetDatabase() {
    try {
        logger.info("Looking for property: targetDatabase...")
        String tDB = "${targetDatabase}".trim()
        logger.info("Property targetDatabase = {}", tDB)
        return tDB
    } catch (MissingPropertyException missingPropertyException) {
        logger.warn "Unable to find the target database.  Fall back to dev database. Did you specify the targetDatabase property?"
        return "dev"
    }
}

String getFlywayLocationsForCurrentMigration() {
    String flywayLocations = "cern/acctesting/db/migrations/base"
    logger.info "Looking for property 'migrateDatabaseContent'..."
    try {
        String migrateDatabaseContentValue = "${migrateDatabaseContent}"
        logger.info("Found property 'migrateDatabaseContent', value={}", migrateDatabaseContentValue)
        if (migrateDatabaseContentValue == "true") {
            logger.warn "Property 'migrateDatabaseContent' found and true, base + content migration will be performed."
            flywayLocations += ",cern/acctesting/db/migrations/content"
        }
    } catch (MissingPropertyException missingPropertyException) {
        logger.warn "Property 'migrateDatabaseContent' not found, only the base migration will be performed."
    }

    return flywayLocations
}

void loadFlywayConfiguration() {
    String targetDatabase = defineTargetDatabase();
    String acctestingDbPropertyFilePath = "src/java/cern/acctesting/db/acctesting-db-${targetDatabase}.properties"
    String acctestingDbPropertyResource = "cern/acctesting/db/acctesting-db-${targetDatabase}.properties"

    String flywayPropertyFilePath = "src/java/cern/acctesting/db/flyway.properties"
    String flywayPropertyResource = "cern/acctesting/db/flyway.properties"

    /* Load AccTesting DB properties from file into ant.properties */
    if (project.hasProperty("accTestingDbJarPath")) {
        logger.info("Trying to load AccTesting DB properties: CLASSPATH: [{}], Resource: [{}]",
                project.ext.accTestingDbJarPath, acctestingDbPropertyResource)
        ant.property(classpath: project.ext.accTestingDbJarPath, resource: acctestingDbPropertyResource)
    } else {
        logger.info("Trying to load AccTesting DB properties from file: {}", acctestingDbPropertyFilePath)
        ant.property(file: acctestingDbPropertyFilePath)
    }

    /* Load Flyway properties from file into ant.properties */
    if (project.hasProperty("accTestingDbJarPath")) {
        logger.info("Trying to load Flyway DB properties: CLASSPATH: [{}], Resource: [{}]",
                project.ext.accTestingDbJarPath, flywayPropertyResource)
        ant.property(classpath: project.ext.accTestingDbJarPath, resource: flywayPropertyResource)
    } else {
        logger.info("Trying to load Flyway properties from file: {}", flywayPropertyFilePath)
        ant.property(file: flywayPropertyFilePath)
    }

    /* set the loaded properties on the project */
    /* ant.properties = Map<String, String> */
    for (def e in ant.properties) {
        if (e.key.startsWith("flyway.")) {
            project.ext[e.key] = e.value
            logger.info("Set project property: {} = {}", e.key, e.key == "flyway.password" ? "<<NOT SHOWN>>" : e.value)
        }
    }
}

public void logAntBuilderProperties(def antBuilder) {
    logger.info("Currently loaded Ant properties for AntBuilder: {}", antBuilder)
    antBuilder.properties.each {
        logger.info("Ant property: [{}]=[{}]", it.key, it.key.contains("password") ? "<<NOT SHOWN>>" : it.value)
    }
}

String failIfProductionDatabase(String targetDatabase) {
    if (targetDatabase.equalsIgnoreCase("pro")) {
        throw new RuntimeException("You tried to work on the ${targetDatabase} AccTesting DB, which is forbidden")
    }
    return targetDatabase
}

void logFlywayProjectProperties() {
    logger.info("------------------- START Gradle project - Flyway properties -------------------")
    for (def e in project.properties) {
        if (e.key.startsWith("flyway.")) {
            logger.info("{} = {}", e.key, e.key == "flyway.password" ? "<<NOT SHOWN>>" : e.value)
        }
    }
    logger.info("-------------------  END  Gradle project - Flyway properties -------------------")
}
/* ----------  END  Flyway Migration Functions --------------------------------------------------------------------- */

```

**Comment by alextercete** [comment] 2019-08-29 11:08
@jcgarnier I think you're right that this is related to the `ClassLoader`.

The Gradle plugin provides [its own `ClassLoader`](https://github.com/flyway/flyway/blob/master/flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java#L501-L516), so could you please run Gradle [in debug mode](https://docs.gradle.org/current/userguide/logging.html) and see if the `Adding directory to Classpath: (...)` messages are what you expect?

**Comment by jcgarnier** [comment] 2019-08-29 12:27
This is what I expect:
```
13:41:17.449 [QUIET] [system.out] [DEBUG] - Adding directory to Classpath: file:/opt/garnierj/intellijws/acctesting/lhc-hwc-acctesting-db/build/classes/java/main/
13:41:27.887 [QUIET] [system.out] [DEBUG] - Adding directory to Classpath: file:/opt/garnierj/intellijws/acctesting/lhc-hwc-acctesting-db/build/resources/main/
13:41:33.951 [QUIET] [system.out] [DEBUG] - Adding directory to Classpath: file:/opt/garnierj/intellijws/acctesting/lhc-hwc-acctesting-db/build/classes/java/test/
13:41:42.341 [QUIET] [system.out] [DEBUG] - Adding directory to Classpath: file:/opt/garnierj/intellijws/acctesting/lhc-hwc-acctesting-db/build/resources/test/
```
Then the ClassPathScanner behaves as expected (the delay in time is because I attached a debugger to the gradle process):
```
14:06:14.887 [QUIET] [system.out] [DEBUG] - Found class: cern.acctesting.db.migrations.base.V1_1__InsertEnum
14:06:26.052 [QUIET] [system.out] [DEBUG] - Found class: cern.acctesting.db.migrations.base.V1_2__InsertDefaultCampaign
14:07:17.991 [QUIET] [system.out] [DEBUG] - Found class: cern.acctesting.db.migrations.base.V2_5__IncreaseCommentColumnLength
14:08:17.387 [QUIET] [system.out] [DEBUG] - Found class: cern.acctesting.db.migrations.base.V2_8_0__Add_HWC_EE_EXPERT_Role
```
And the classes are added to the Scanner.classes field:
```
classes = {ArrayList@12085}  size = 4
 0 = {Class@11975} "class cern.acctesting.db.migrations.base.V1_1__InsertEnum"
 1 = {Class@12004} "class cern.acctesting.db.migrations.base.V1_2__InsertDefaultCampaign"
 2 = {Class@12048} "class cern.acctesting.db.migrations.base.V2_5__IncreaseCommentColumnLength"
 3 = {Class@12065} "class cern.acctesting.db.migrations.base.V2_8_0__Add_HWC_EE_EXPERT_Role"
```
But later they're filtered out:
![unassignableJavaMigration](https://user-images.githubusercontent.com/7524505/63940074-0c678b00-ca69-11e9-8060-86b3be941724.png)

**Comment by alextercete** [comment] 2019-08-29 16:34
@jcgarnier Thanks for all your help so far, I think we're getting to the bottom of it.

It looks like [this StackOverflow answer](https://stackoverflow.com/a/3026141/1288760) explains this behaviour, particularly in this [slightly modified] bit:

```java
ClassLoader loader = new URLClassLoader(urls, null);
Class<?> c = loader.loadClass("net.torokpeter.Foo");
System.out.println(Foo.class.isAssignableFrom(c)); // false
```

So my hypothesis is that there are two class loaders in play and that [the one we're getting from Gradle](https://github.com/flyway/flyway/blob/master/flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java#L511) doesn't have the "current" class loader as its parent, and that's why the `isAssignableFrom` check fails. I'll do some debugging to test this.

**Comment by alextercete** [comment] 2019-08-30 12:41
@jcgarnier Any chance you're using [multi-project builds](https://docs.gradle.org/current/userguide/multi_project_builds.html)?

**Comment by jcgarnier** [comment] 2019-08-30 13:00
yes I am

**Comment by alextercete** [comment] 2019-08-30 15:53
I haven't been able to reproduce your issue, but so far I've only done testing with single-project builds.

I suspect that changing [this line](https://github.com/flyway/flyway/blob/master/flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java#L511) would fix the issue:

```patch
-                    getProject().getBuildscript().getClassLoader());
+                    getProject().getRootProject().getBuildscript().getClassLoader());
```

Sadly, I'm not very experienced with Gradle, so I haven't been able to set up a multi-project build that reproduces your issue yet (which would also allow me to check if the change above fixes it).

@jcgarnier Is this something you could help me with?

**Comment by jcgarnier** [comment] 2019-09-02 08:25
Hi @alextercete 

To configure a gradle multi project, I simply define the list of sub-projects in my root's folder's settings.gradle. Then each sub-project has its own build.gradle. How could I help you?
Basically I have a root project that contains this
```
rootProject.name = 'acctesting'
//...
include 'lhc-hwc-acctesting-db'
//...
```
And acctesting-db has then the build.gradle that I already gave you a few days ago.

**Comment by alextercete** [comment] 2019-09-02 10:58
@jcgarnier That's already helpful, thanks! Here's a project that attempts to reproduce your issue:

[gradle-multi-project-java-migrations.zip](https://github.com/flyway/flyway/files/3565707/gradle-multi-project-java-migrations.zip)
```
.
├── build.gradle
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradle-multi-project-db
│   ├── build.gradle
│   └── src
│       ├── main
│       │   ├── java
│       │   │   └── db
│       │   │       └── migration
│       │   │           └── V1__Initial.java
│       │   └── resources
│       └── test
│           ├── java
│           └── resources
├── gradlew
├── gradlew.bat
├── settings.gradle
└── src
    ├── main
    │   ├── java
    │   └── resources
    └── test
        ├── java
        └── resources
```

Unfortunately, that doesn't seem to do it -- it still finds the migrations successfully.

I noticed that you're using `apply from` to load a file from resources, but I wasn't able to adapt my Gradle project to match that (this is were my Gradle knowledge starts to lack), so I was hoping you could help me reproduce your issue in a minimal sample project such as the one I shared above.

**Comment by jcgarnier** [comment] 2019-09-02 12:34
@alextercete It seems you got a good lead with the `apply from`!

With the project that you attached, I have no issue, until I do the `apply from`.

For instance here is what you can do:
Here's the content of the build.gradle:
```
buildscript {
    dependencies {
        classpath 'com.h2database:h2:1.4.197'
    }
}

plugins {
    id 'java'
    id 'idea'
}

apply from: 'src/flyway.gradle'

group 'org.flyway.sample'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile "org.flywaydb:flyway-core:6.0.1"
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```

Here's the content of the src/flyway.gradle:
```
import org.flywaydb.gradle.FlywayPlugin

buildscript {
    repositories {
        maven { url 'http://artifactory.cern.ch/development' }
    }
    dependencies {
        classpath 'org.flywaydb:flyway-gradle-plugin:6.0.1'
    }
}
project.getPlugins().apply(org.flywaydb.gradle.FlywayPlugin.class)


project.dependencies {
    /* Local Groovy needed to avoid Eclipse errors */
    runtime localGroovy()
    compile "org.flywaydb:flyway-gradle-plugin:6.0.1"
}

flyway {
    url = 'jdbc:h2:file:./target/foobar'
    user = 'sa'
    locations = [
            'classpath:db/migration'
    ]
}
```

And I can reproduce the issue this way in both multi and non-multi project.

**Comment by jcgarnier** [comment] 2019-09-03 12:56
@alextercete 
I managed to refactor my gradle build scripts/configuration in a way that fixes my project.
First, it does `apply from` because we wanted to define numerous methods that allow us to configure the flyway properties differently, as we use 5 DBs for various level of testing, staging and production. 

But the application of the flyway plugin doesn't need to be performed in the source file that is applied.

So now the build.gradle takes care of loaded the dependencies for the buildscript and the project, and applies the plugin, and then it applies the custom source file. 

Did you find a solution on your side?

**Comment by alextercete** [comment] 2019-09-03 13:56
@jcgarnier I have managed to reproduce the issue based on your instructions, but I haven't been able to come up with a solution yet. Would you mind sharing the changes you've made to get your project to work for future reference?

I'm unsure about whether we should pursue a solution any further, as I'm not sure this a common enough issue or whether there's anything we could change in Flyway to prevent it. Therefore, I'm tempted to remove the `bug` tag due to lack of evidence and close it as `invalid`.

What do you think?

**Comment by jcgarnier** [comment] 2019-09-03 15:02
@alextercete 

Here is the build.gradle
```
buildscript {
    repositories {
        maven { url 'http://artifactory.cern.ch/development' }
    }
    dependencies {
        classpath 'org.flywaydb:flyway-gradle-plugin:6.0.1'
    }
}
project.getPlugins().apply(org.flywaydb.gradle.FlywayPlugin.class)

flywayMigrate.mustRunAfter compileJava
flywayMigrate.mustRunAfter flywayClean
build.mustRunAfter flywayMigrate


apply from: 'src/main/resources/gradle/flyway-migration.gradle'

configurations {
    all*.exclude group: 'org.slf4j', module: 'slf4j-jdk14'
}


test {
    systemProperty 'acctesting.database', 'test'
    systemProperty 'lsa.database', 'dev'
    systemProperty 'java.security.egd', 'file:///dev/./urandom'
}

// Dependencies block created by multi-project migration script
dependencies {
    compile project(':lhc-hwc-acctesting-core')
    runtime localGroovy()
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'org.flywaydb', name: 'flyway-core', version:'6.0.1'
    compile group: 'org.flywaydb', name: 'flyway-gradle-plugin', version:'6.0.1'
    compile group: 'com.oracle', name: 'ojdbc8', version:'19.1.0'
}
```

And the flyway-migration.gradle remains with all the tasks that were defined previously, but nothing related to flyway, plugings, buildscript and so on.

I looked through Gradle's documentation and it mentions nothing about `apply from` and risks like this... 
I share your uncertainty about having a fix in flyway about this, maybe we could post it to the [Gradle github issues](https://github.com/gradle/gradle/issues) and see what they propose.

**Comment by alextercete** [comment] 2019-09-03 15:11
@jcgarnier I'm closing this for now until we have more evidence that this is worth pursuing. I'll create an issue in Gradle asking for advice to see what they say.

I'm glad you managed to get it working, and thanks for your collaboration!

**Closed by alextercete** 2019-09-03 15:11 UTC
Labels: r: invalid

**Comment by jcgarnier** [comment] 2019-09-03 15:27
Thank you for your precious help @alextercete, I would not have made it without you!
Greetings
Jc

**Comment by SVaeth** [comment] 2020-04-29 22:41
I am having this issue. Starting up the spring server applies jdbc migrations, but running `gradle flywayInfo` says they are in the missing or future state. 

If I run `gradle flywayClean` then `gradle flywayInfo` then I see only the SQL migrations detected and pending

If I run `gradle flywayMigrate` then `gradle flywayInfo` then I see only the SQL migrations were applied. JDBC migrations are totally ignored.
