### ISSUE TITLE
PostgreSQL Procedures cause an error during `clean`

### ISSUE THREAD

**Issue by beedaan** [flyway/flyway#2618] opened 2020-01-08 20:55 UTC
###### Which version and edition of Flyway are you using?

6.0.8
Community Edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

PostgreSQL 12.1

###### Which operating system are you using?

macOS 10.15.2

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I attempt to clean the database using `flyway clean`.  My database has a few procedures, which seem to be causing the issues.  Here is one of the procedures

```sql
CREATE PROCEDURE add_theme(name VARCHAR)
  LANGUAGE plpgsql
AS
$$
BEGIN
  INSERT INTO theme (theme_name)
  VALUES (name);
END;
$$;
```

###### What did you expect to see?

I expect to see a successful exit after the clean

###### What did you see instead?

```
ERROR:
Unable to clean schema "public"
-------------------------------
SQL State  : 42809
Error Code : 0
Message    : ERROR: public.add_theme(character varying) is not a function
```

It seems that the procedures are causing the issues.  Everything seems to work fine with functions.  If I remove them by hand, flyway is then able to perform the clean.

**Comment by alextercete** [comment] 2020-01-09 09:36
@beedaan A fix for this issue was released in Flyway 6.1.1, so I recommend you upgrade to the latest version.

Duplicate of https://github.com/flyway/flyway/issues/2578.

**Closed by alextercete** 2020-01-09 09:36 UTC
