### ISSUE TITLE
Add a squash command

### ISSUE THREAD

**Issue by schmitch** [flyway/flyway#1101] opened 2015-10-01 13:12 UTC
Currently it would be good to have something like a squash command, where you could have lots of migrations and squash them into a single (or multiple less than before) files. Currently I think with java migrations this is hard to do, but with SQL it shouldn't be a problem at all!

**Comment by nycjay** [comment] 2015-10-02 15:11
+1

This would be very helpful. During the development process, we may create a table, then later in a new script alter the table to add a new column, then again and again. So, at the end of the day, we could have several scripts just to create a single table. This accurately represents the development process, but is not necessarily ideal when it comes to our "real" environments, including production. 

In DB2 for example, after some number of table alters (lets say 5) to add a column (or other reorg recommended operations), the table goes into reorg pending state. This is going to be unavoidable at some level. But, if we could squash multiple alters from a given release into a single alter, we can at least push back on that limit a bit longer.

**Comment by schmitch** [comment] 2015-10-02 15:35
Currently this would work on production aswell, if you squashed lots of migrations, you could just delete the flyway table on production and let it recreate it.

**Comment by nycjay** [comment] 2015-10-05 17:35
Deleting the flyway table in production seems like a high cost to pay to get this functionality. We would loose our years of history.

**Comment by schmitch** [comment] 2015-10-05 18:31
if you have over 10.000 migration files it something you will pay. especially for a consumer product where running 1000 migrations per version could take a while. 
I mean people that running there software inside the cloud don't have the same problem than running their software on multiple servers and multiple customers.

Mostly if we have something like 
Version 1.1.1 which has a extra column in 1.1 while 2.0 has that inside a bigger migration we could just ignore the history in between. since we want to rebase the current database to 2.0 we mostly have a second set to upgrade from latest minor to new major which will upgrade / migrate the database and then starts from a single entry inside the flyway table.

**Comment by axelfontaine** [comment] 2015-10-27 14:54
Duplicate of #470

**Closed by axelfontaine** 2015-10-27 14:54 UTC
Labels: t: feature
