### ISSUE TITLE
support hive in flyway

### ISSUE THREAD

**Issue by luminglei** [flyway/flyway#3446] opened 2022-05-16 06:58 UTC
###### Which version and edition of Flyway are you using?

8.5.10

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Hive

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I want to use flyway for the hive, however, it looks like it's not supported natively, I only see one old PR: https://github.com/flyway/flyway/pull/1322, the PR is so old and seems can't work in the latest version of the flyway for master branch

###### What did you expect to see?
I hope flyway support hive too

###### What did you see instead?
flyway don't support hive

**Comment by DoodleBobBuffPants** [comment] 2022-05-16 09:24
Closing as duplicate of https://github.com/flyway/flyway/issues/142

**Closed by DoodleBobBuffPants** 2022-05-16 09:24 UTC
