### ISSUE TITLE
SQL Server migration hangs on very long string

### ISSUE THREAD

**Issue by zhaldybin** [flyway/flyway#2366] opened 2019-04-25 08:12 UTC
###### Which version and edition of Flyway are you using?
5.2.4, community edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
The 5.2.4 seems to be the latest release at the moment. The issue is not reproducible with 6.0.0-beta, however.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API, the issue is also reproducible with the command-line application.

###### Which database are you using (type & version)?
Microsoft SQL Server 2017

###### Which operating system are you using?
MacOS Mojave

###### What did you do?
Our project is a Spring Boot application that uses MS SQL Server. We use Flyway to set up the local development database every time a developer starts the application on their machine.

###### What did you expect to see?
The expectation is that the application starts up successfully, with Flyway applying all the migrations to the database.

###### What did you see instead?
The application startup hangs on the database migration step for a very long time - tens of minutes.

The migration script that inserts data into the local development environment database contains very long strings - up to 200000 characters (they are binary data). I tracked down the problem to these strings and to the SQLServerSqlStatementBuilder class, specifically, to its 'cleanToken' method. The code calls the java.util.regex.Matcher's 'find' method, trying to find all the matches for the "(.*')(LIKE|AS)$" pattern in the provided string. Since this input string is extremely long, the 'find' methods spends a lot of time on its task.
I might be missing something, but I do not see it necessary to try and find all the matching substrings in the input string token in this case. I think that using java.util.regex.Matcher.match instead of 'find' could be enough. I tested this, and it worked just fine, without spending excessive amount of time in the SQLServerSqlStatementBuilder.

The issue is also reproducible with the 5.2.4 version of the Flyway command line tool. The 6.0.0-beta version of the command line tool does not have this issue, it seems. However, it might be useful to fix this on 5.2.x branch, I think - even after the 6.0.0 version is released, it might take some time before it is adopted by Spring Boot, for example.

I can provide a reproducer on request.

**Comment by axelfontaine** [comment] 2019-04-25 08:24
Duplicate of #2364 

The 6.0.0 release contains a brand new high performance parser that indeed fixes this and a number of other issues, both in terms of performance and correctness. We have no plans to backport it.

Note that you can easily use Flyway 6.0.0 with Spring Boot if you use your own bean definition instead of the built-in one.

**Closed by axelfontaine** 2019-04-25 08:24 UTC
