### ISSUE TITLE
Running anonymous block as part of Flyway migration script in Snowflake fails with error code 90232

### ISSUE THREAD

**Issue by RaduCStefanescu** [flyway/flyway#3485] opened 2022-07-18 16:53 UTC
###### Which version and edition of Flyway are you using?
Using Flyway Maven plugin version 8.5.12 to run migration scripts.

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I was not able to test this feature on the latest release.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using? (Type & version)
Snowflake.

###### Which operating system are you using?
Running the maven plugin on Linux.

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
The issue is that I have a migration script that has to run an anonymous block.
The anonymous block looks something similar to this - I can provide the entire SQL per request: 

```
EXECUTE IMMEDIATE
$$
DECLARE
        hierarchy_id NUMBER(38,0);
        BEGIN
            SELECT id INTO :hierarchy_id FROM SCHEMA.HIERARCHY WHERE name = 'Hierarchy';
            CREATE OR REPLACE TEMPORARY TABLE COMMON_CONFIG_DATA_LOADS AS
                SELECT DISTINCT COMMON_DATA_LOAD_ID, CONFIG_DATA_LOAD_ID
                FROM SCHEMA.DATA_LOAD
                WHERE REQUIRES_COMMON_AND_CONFIG
                AND COMMON_DATA_LOAD_ID IS NOT NULL
                ORDER BY 1;

            INSERT INTO INTEGRATION_SCHEMA.ORG_HIERARCHY_NODE
            (
               fields....
            )
            SELECT
                fields...
            FROM SCHEMA.LEGAL_ENTITY_HIERARCHY leh
            JOIN COMMON_CONFIG_DATA_LOADS ccdl ON leh.data_load_id = ccdl.CONFIG_DATA_LOAD_ID
            ORDER BY
                leh.LEGAL_ENTITY_LEVEL ASC,
                leh.LEGAL_ENTITY_1 ASC,
                leh.LEGAL_ENTITY_2 ASC NULLS FIRST,
                leh.LEGAL_ENTITY_3 ASC NULLS FIRST,
                leh.LEGAL_ENTITY_4 ASC NULLS FIRST
            ;
END;
$$
;
```

###### What did you expect to see?
I expected the anonymous block to be executed correctly. 
The anonymous block, copied from the script (the text between the $$) executes correctly when ran from the Snowflake Web UI.

###### What did you see instead?
The script fails with the following error: 
build	18-Jul-2022 17:06:27	[ERROR] SQL State  : 25000
build	18-Jul-2022 17:06:27	[ERROR] Error Code : 90232
build	18-Jul-2022 17:06:27	[ERROR] Message    : Stored procedure execution error: Scoped transaction started in stored procedure is incomplete and it was rolled back.

There is no scoped transaction being opened in the text of the anonymous block.

**Comment by pachu** [comment] 2022-08-30 08:06
Hi, 
I reported something symilar here: https://github.com/flyway/flyway/issues/3512. For me, direct addition of below line helped. 

`ALTER SESSION SET AUTOCOMMIT = TRUE;`

**Comment by DoodleBobBuffPants** [comment] 2022-08-30 12:14
I was unable to reproduce this from the information provided, could you provide a reproduction?

**Comment by DoodleBobBuffPants** [comment] 2022-09-06 10:00
Closing until further activity

**Closed by DoodleBobBuffPants** 2022-09-06 10:00 UTC
Labels: s: waiting for feedback

**Comment by HelmutSchuster** [comment] 2023-11-03 08:42
One can try to enclose it with a single apostroph:
EXECUTE IMMEDIATE '
... your script
';

Note: All single quotes have to get another one.  ('->'')
