### ISSUE TITLE
Any command freeze in WSL2 and Windows 10

### ISSUE THREAD

**Issue by Tab3r** [flyway/flyway#3375] opened 2022-01-12 16:12 UTC
###### Which version and edition of Flyway are you using?
8.3.0 and 8.4.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes, same problem in 8.4.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
H2

###### Which operating system are you using?
WSL2 (ubuntu 20.04) on Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I'm trying to do the "First steps" tutorial, over a local h2 database.

The file ./conf/flyway.conf:

```
flyway.url=jdbc:h2:file:./foobardb
flyway.user=SA
flyway.password=
```
And in ./sql directory, the first migrate file called 'V1__Create_person_table.sql'. Like the tutorial.

Then, i try to do first migration:

`./flyway migrate`

###### What did you expect to see?

Something :)... a simple migration.

###### What did you see instead?
Nothing. 

The command is launched, but nothing is show in the console. No error, or log in the screen.  Only the process wait without end. The "-X" flag doesn't help.

But i use a wrong command, the error is show. Or if i use the help, it shows in the screen. But command like "migrate", "info", not works.

In powershell (with the windows version), no problem at all, migration works.

**Comment by tjs145** [comment] 2022-01-12 16:36
We've been unable to reproduce this. Could you provide a minimal reproduction project?

**Comment by Tab3r** [comment] 2022-01-13 07:33
My scenario:
- Windows 10 (not admin user) with WSL2 with root rights. 
- Java local version (i think that flyway use its local jre)
- I have followed the download instructions: `wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.4.1/flyway-commandline-8.4.1-linux-x64.tar.gz | tar xvz`
- I have modified the file `./conf/flyway.conf` adding in the last lines:
```
[... original file ...]
flyway.url=jdbc:h2:file:./foobardb
flyway.user=SA
flyway.password=
```
- Then add in `./sql` directory, the file `V1__Create_person_table.sql`, with the sql:
```
create table PERSON (
    ID int not null,
    NAME varchar(100) not null
);
```
- Then i use in the shell: `./flyway info -X`. Black screen, nothing happens:
![image](https://user-images.githubusercontent.com/784833/149284808-5852947c-772a-41ef-a2b3-1ec6fba96014.png)
- But i only use: `./flyway`, i had the following output:
![image](https://user-images.githubusercontent.com/784833/149285162-443385b5-a100-4259-85be-0acf0bf3786a.png)

I dont know which other info you need, but ask me for anything. 

I could generate more debug log, but i dont know how.

Thank you very much!!!

**Comment by Barry-RG** [comment] 2022-01-13 11:30
Hi @Tab3r,
Are you running flyway on a machine which has internet access? Additionally, how long have you been leaving flyway before cancelling the command?

**Comment by Tab3r** [comment] 2022-01-14 08:27
The machine has internet access. The wildfly files are outside de wsl "virtual" storage (/mnt/...).

I have waited more than 1 hour... 

The point is if i launch in powershell (even the linux version), it works ok!...

How can debug this?...

**Comment by tjs145** [comment] 2022-01-18 16:47
Could you try running flyway again, but with the `-community` and `-skipCheckForUpdate` flags?
So something like:
```
./flyway info -X -community -skipCheckForUpdate
```

**Comment by tjs145** [comment] 2022-01-24 10:42
Closing this issue until further activity

**Closed by tjs145** 2022-01-24 10:42 UTC
Labels: s: waiting for feedback

**Comment by Tab3r** [comment] 2022-01-24 12:18
Using the parameter: "-skipCheckForUpdate", all commands works as expected!.

But, why it's happen? WSL is blocked by windows?

Thank you very much for your help!
