### ISSUE TITLE
Writing more than one procedure in one sql file is not being recognised by flyway.

### ISSUE THREAD

**Issue by Niraj5152** [flyway/flyway#2534] opened 2019-10-17 06:03 UTC
###### Which version and edition of Flyway are you using?
6.0.6

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven Plugin

###### Which database are you using (type & version)?

ojdbc8.jar and orai18n.jar

###### Which operating system are you using?
Linux (Git)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I have procedures, packages and views written where there are many PL/SQL blocks written in single sql files and they are finishing with END; /.
Now Flyway is executing those files without errors but the packages, procedures and views are not getting created giving error "PLS-00103: Encountered the symbol “/”", when i remove this "/" from the script then it gives me error  "PLS-00103: Encountered the symbol “CREATE”"

I have used flyway 4.2.0 version with oracle 10 and it was working fine there.

###### What did you expect to see?

We should be able to write multiple PL/SQL blocks in single sql file.

###### What did you see instead?
It is not working with latest version.

**Comment by alextercete** [comment] 2019-10-17 09:46
I think this might be related to #2530, which was a regression introduced in 6.0.2. We plan to release a fix in 6.0.7, so I'd advise you upgrade once the new version is out to see if the problem persists.

Alternatively, you could try downgrading to [version 6.0.1](https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/6.0.1/) to see if that works.

**Comment by alextercete** [comment] 2019-10-17 14:34
@Niraj5152 Flyway 6.0.7 has now been released. Would you mind upgrading and seeing if it fixes your issue?

**Comment by Niraj5152** [comment] 2019-10-18 05:48
It worked well with 6.0.1 thanks. Today i will try with 6.0.7 also

**Comment by alextercete** [comment] 2019-10-18 11:59
@Niraj5152 That's good to hear.

I'm confident that this is a duplicate of #2530, so I'll close this one.

**Closed by alextercete** 2019-10-18 11:59 UTC
Labels: d: Oracle, t: bug
