### ISSUE TITLE
Error while migrating the scnowflake DB in maven failed during selecting from the schema versions table.

### ISSUE THREAD

**Issue by shetaksroc** [flyway/flyway#1606] opened 2017-04-16 18:12 UTC
###### What version of Flyway are you using?

4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Maven

###### What database are you using (type & version)?
Snowflake

###### What operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I ran a migrate for a snowflake DB.

###### What did you expect to see?

Migrate to the versions specified in the files

###### What did you see instead?
Error
<img width="1280" alt="screenshot 2017-04-16 23 39 54" src="https://cloud.githubusercontent.com/assets/6781245/25073171/397d4144-22fe-11e7-85d9-e5ab6b7047a6.png">

**Comment by axelfontaine** [comment] 2017-04-16 21:15
Duplicate of 1605

**Closed by axelfontaine** 2017-04-16 21:15 UTC
