### ISSUE TITLE
Display oracle sql output with command without all extra DEBUG information

### ISSUE THREAD

**Issue by coredigitalmedia** [flyway/flyway#2437] opened 2019-07-10 18:40 UTC
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by coredigitalmedia** [comment] 2019-07-10 18:42
Hello:

how to display oracle sql command and output without all DEBUG information?
we just need to see sql command and result not whole DEBUG information.
it is very hard to see sql command and output with all debug info in it.

**Comment by alextercete** [comment] 2019-09-06 10:12
@coredigitalmedia Could you try upgrading to the latest version, 6.0.1, and see if you still have this problem?

**Comment by coredigitalmedia** [comment] 2019-09-10 15:56
Hi @alextercete how to download new version with existing key?

**Comment by alextercete** [comment] 2019-09-11 10:43
@coredigitalmedia You can download the latest version from the [website](https://flywaydb.org/download/). Your license key will work with the new version as long as it hasn't expired.

**Comment by coredigitalmedia** [comment] 2019-09-11 15:54
Hi @alextercete still prints all debug information with version 6.0.2 while applying script.

**Comment by alextercete** [comment] 2019-09-13 09:11
@coredigitalmedia I'm not sure I understand your request. The debug information is omitted by default (it's only shown if you [provide the `-X`](https://flywaydb.org/documentation/commandline/#debug-output) CLI flag).

Is there anything that's currently only shown in debug mode that you'd like to see in the normal output?

**Comment by coredigitalmedia** [comment] 2019-09-13 16:34
@alextercete correct, debug information is omitted by default and which is good!
but how do we know which sql got executed (it doesn't print sql statement like when we do "echo on" on sqlplus)?

**Comment by coredigitalmedia** [comment] 2019-09-13 16:36
Yes, in debug mode it display sql statement.
we'd like to see only sql statement which is being executed and result of sql statement.

**Comment by alextercete** [comment] 2019-10-31 14:02
Duplicate of #2550.

**Closed by alextercete** 2019-10-31 14:02 UTC
Labels: d: Oracle, e: enterprise, e: pro, t: feature
