### ISSUE TITLE
Snowflake support

### ISSUE THREAD

**Issue by mbreault** [flyway/flyway#1735] opened 2017-08-06 15:13 UTC
Snowflake is a hosted data warehousing solution.

Home: https://www.snowflake.net/
Driver:  https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/

Currently get: ERROR: Unsupported Database: Snowflake 2.5

**Comment by alexlevene** [comment] 2017-10-10 22:26
Added support for Snowflake to a fork of v4.2.0 and submitted a pull request #1776. We've put it through its paces in development, but it would be great to get some more feedback. Please review.

**Comment by bobtiernay-okta** [comment] 2019-07-24 14:31
Any update on this? Would be great to have Snowflake support.

**Comment by rjungwirth** [comment] 2019-09-05 17:28
I took over ownership of pr #1776 when alex left the company.  We've been using this feature branch ever since and it's working flawlessly.  Please re-consider it for inclusion.  

If I were to port this code to the V6 branch would it have a better chance?

**Comment by juliahayward** [comment] 2019-09-13 10:20
We're going to talk to Snowflake about the commercial details of a testing account for us. I'll let you know the outcome of that; if good, then a port to v6 would be very welcome.

**Comment by blian7432** [comment] 2019-09-20 03:24
Hi @juliahayward Do you have an ETA of Snowflake support?

**Comment by juliahayward** [comment] 2019-09-23 12:54
Not yet, we're still setting up a meeting with them.

**Comment by juliahayward** [comment] 2019-11-07 14:03
We're now working on Snowflake for 6.1. I have a question for people who are using it; in a new database connection without a schema specified in the URL, `SELECT CURRENT_SCHEMA()` returns null; what would you all expect Flyway's behavior to be:
- you would specify a current schema in the connection URL
- you would expect Flyway to default to `PUBLIC` until specified otherwise by `USE SCHEMA xxx` 
- you would fully qualify all object names in migration scripts?

**Comment by rjungwirth** [comment] 2019-11-07 14:12
The second option, always assume public unless specified on the URL or by a use schema command in a migration script.

**Comment by bobtiernay-okta** [comment] 2019-11-07 14:13
This is what we've done to get this to work:

```java

/**
 * Snowflake implementation of a Flyway Connection.
 */
@SuppressWarnings("rawtypes")
@SuppressFBWarnings("SQL_PREPARED_STATEMENT_GENERATED_FROM_NONCONSTANT_STRING")
public class SnowflakeConnection extends Connection<SnowflakeDatabase> {

    private static final Log LOG = LogFactory.getLog(SnowflakeConnection.class);

    private final String originalRole;

    public SnowflakeConnection(Configuration configuration, SnowflakeDatabase database, java.sql.Connection connection, boolean originalAutoCommit) {
        super(configuration, database, connection, originalAutoCommit);
        LOG.debug("Creating new SnowflakeConnection");

        try {
            this.originalRole = jdbcTemplate.queryForString("SELECT CURRENT_ROLE()");
        } catch (SQLException e) {
            throw new FlywaySqlException("Unable to determine current role", e);
        }
    }

    //
    // NOTE: the following methods are overridden to provide an implementation
    //

    @Override
    protected String getCurrentSchemaNameOrSearchPath() throws SQLException {
        String result = jdbcTemplate.queryForString("SELECT CURRENT_SCHEMA()");
        LOG.debug("Current Snowflake schema is " + (result != null ? result : "none"));
        return requireNonNullElse(result, "PUBLIC");
    }

    @Override
    public Schema getSchema(String name) {
        return new SnowflakeSchema(jdbcTemplate, database, name);
    }

    //
    // NOTE: the following methods are overridden to change the implementation
    //

    @Override
    protected void doRestoreOriginalState() throws SQLException {
        // Reset the role to its original value in case a migration or callback changed it
        jdbcTemplate.execute("USE ROLE " + originalRole);
    }

    @Override
    protected void doChangeCurrentSchemaOrSearchPathTo(String schemaNameOrSearchPath) throws SQLException {
        LOG.debug("Switching to Snowflake schema " + schemaNameOrSearchPath);
        jdbcTemplate.execute("USE SCHEMA " + database.quote(schemaNameOrSearchPath));
    }

}
```

Also note the need to consider `CURRENT_ROLE`

**Comment by rjungwirth** [comment] 2019-11-07 14:19
Yeah, that’s understandable.  SF doesn’t have a global default for user role.  Most logins are associated with a default role but it is not required.

Default warehouse is somewhere in between.  have a DEMO_WH warehouse provisioned by default.  Most migrations will not require a warehouse as DML commands don’t need a warehouse.   Any migrations that have non-dml statements like inserts, deletes, selects etc. will require a warehouse to execute.

**Comment by blian7432** [comment] 2019-11-07 22:11
Agree with option 2

**Comment by juliahayward** [comment] 2019-11-08 11:52
So with CURRENT_ROLE(), is that not a local property of the connection? I'm just working through some test cases and it appears to me that a migration which calls `USE ROLE Foo` doesn't affect anything outside its own session.

**Comment by rjungwirth** [comment] 2019-11-08 13:02
That is true.  Roles are assigned at the session level.  I haven’t confirmed myself, but it may be safe to assume that a user will always be assigned a role.

**Comment by juliahayward** [comment] 2019-11-25 13:09
Closing this issue as we're releasing imminently. Please start new issues for any problems that arise!

**Closed by juliahayward** 2019-11-25 13:09 UTC
Labels: t: database support, t: feature
