### ISSUE TITLE
Flyway Enterprise or Oracle upgrade required

### ISSUE THREAD

**Issue by remmeier** [flyway/flyway#2034] opened 2018-06-04 11:45 UTC
``org.flywaydb.core.internal.exception.FlywayEnterpriseUpgradeRequiredException: Flyway Enterprise or Oracle upgrade required: Oracle 11 is past regular support by Oracle and no longer supported by Flyway Open Source or Pro, but still supported by Flyway Enterprise.``

you are kidding, right?

**Comment by axelfontaine** [comment] 2018-06-04 12:12
Duplicate of #1913

**Closed by axelfontaine** 2018-06-04 12:12 UTC

**Comment by ohecker** [comment] 2018-06-05 13:38
No longer supporting Oracle 11 also breaks support for "Oracle Database 11g Express Edition" (short Oracle XE) which is still an active Oracle Product. It seems to be questionable to force to use the Enterprise Version of Flyway to get support for the "Free to develop, deploy, and distribute" version of Oracle.

**Comment by bnii** [comment] 2018-06-22 07:47
it would make sense to be explicit about that Oracle XE is not supported (as of now) in Community Edition, as the last version is 11g.
maybe its just me, but it took me quite a long time to figure out.

**Comment by Masterxilo** [comment] 2019-01-23 16:13
As a workaround: Instead of oracle db 11g (11.2)-xe via https://hub.docker.com/r/wnameless/oracle-xe-11g, I have now switched to using the newer 18c - xe, via https://github.com/fuzziebrain/docker-oracle-xe for local testing of an oracle db app.

**Comment by bugnvl** [comment] 2020-09-01 20:40
This is bad..

**Comment by bugnvl** [comment] 2020-09-01 20:41
wasted lot of time setting this up.. and incorporating this with rest of the pipe line..
