### ISSUE TITLE
Unable to migrate due to present but un-openable file

### ISSUE THREAD

**Issue by colinphanna** [flyway/flyway#1835] opened 2017-11-20 13:42 UTC
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command Line

###### What database are you using (type & version)?
RDS Postgres 9.6.3

###### What operating system are you using?
Mac OS X 10.12.6 x86_64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
`./flyway migrate`

###### What did you expect to see?
Migrations running

###### What did you see instead?
```Flyway 4.2.0 by Boxfuse

DEBUG: Java 9.0.1 (Oracle Corporation)
DEBUG: Mac OS X 10.12.6 x86_64

DEBUG: Loading config file: /Users/colin/Projects/tahi-api/db/flyway-4.2.0/conf/flyway.conf
DEBUG: Unable to load config file: /Users/colin/flyway.conf
DEBUG: Unable to load config file: /Users/colin/Projects/tahi-api/db/flyway-4.2.0/flyway.conf
Database user: tahisa
Database password:
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /Users/colin/Projects/tahi-api/db/flyway-4.2.0/jars
DEBUG: flyway.locations -> filesystem:/Users/colin/Projects/tahi-api/db/flyway-4.2.0/sql
DEBUG: flyway.url -> jdbc://postgresql://tahisa:92$2Dwnv%25LXHCSXz@tahi-db.ccpaiwvns9cs.us-east-2.rds.amazonaws.com:5432/tahi
DEBUG: flyway.user -> tahisa
DEBUG: flyway.password -> **************************************************************************
DEBUG: Adding location to classpath: /Users/colin/Projects/tahi-api/db/flyway-4.2.0/drivers/derby-10.12.1.1.jar
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Unable to load /Users/colin/Projects/tahi-api/db/flyway-4.2.0/drivers/derby-10.12.1.1.jar
	at org.flywaydb.core.internal.util.ClassUtils.addJarOrDirectoryToClasspath(ClassUtils.java:156)
	at org.flywaydb.commandline.Main.loadJdbcDrivers(Main.java:305)
	at org.flywaydb.commandline.Main.main(Main.java:95)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.flywaydb.core.internal.util.ClassUtils.addJarOrDirectoryToClasspath(ClassUtils.java:151)
	... 2 more```

**Comment by axelfontaine** [comment] 2017-11-20 13:48
Duplicate of #1545

**Closed by axelfontaine** 2017-11-20 13:48 UTC
