### ISSUE TITLE
New Feature - Support Generating SQL without Run

### ISSUE THREAD

**Issue by ernieshu** [flyway/flyway#1337] opened 2016-06-09 18:33 UTC
In many of the environments I am working in using Flyway, controlled environments (PROD in particular) are locked down - thus, FlywayDB cannot be directly used against the database.

What would be useful is a feature that would support 'dry run' SQL generation - that is, generate the SQL that would be run , _inclusive of the schema_version updates_, to retain audit traceability.  The generated SQL file could then be reviewed, and passed to DB Ops for manual run (even though that's kind of the opposite purpose of Flyway, sigh).  That would allow us to use Flyway in all environments we control, and yet be compliant with the orgs retaining admin control over 'key' environments, and have the 'schema_version' meta-data still maintained in the environment(s) this generated script was run.  

Example usage would be 'Generate a SQL script containing all migrations between v5 to v9', and contained in the generated file would be the contents of the corresponding Flyway migration scripts, and also the additions to the 'schema_version' table.  

I have some code written for this, compatible with Flyway 3.x, but if there were interest in this feature, I'd take the time to migrate this to Flyway 4.  

Liquibase has a feature called 'SQL Output', which is similar in functionality, but requires access to the DB.

**Comment by axelfontaine** [comment] 2016-06-09 19:54
Duplicate of #87

**Closed by axelfontaine** 2016-06-09 19:54 UTC

**Comment by ernieshu** [comment] 2016-06-09 20:03
Thanks very much Axel ... apologies for the duplication, thought I culled
through the feature request list pretty thoroughly ... apparently not well
enough :)

Cheers,

e.
