### ISSUE TITLE
ERROR StatusLogger No Log4j 2 configuration file found

### ISSUE THREAD

**Issue by luoy1991** [flyway/flyway#3029] opened 2020-12-14 02:56 UTC
###### Which version and edition of Flyway are you using?

flyway-7.0.+

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I reproduced this problem in the new version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line
java version "1,8,0_211"

###### Which database are you using (type & version)?

mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper

###### Which operating system are you using?
CentOS Linux release 7.4.1708 (Core)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I want to output the execution log through log4j。
I try to use flyway-7.0.4、flyway-7.3.1。Copy log4j-api-2.11.2.jar log4j-core-2.11.2.jar to lib/enterprise and create log4j2.xml In flyway sibling directory。

###### What did you expect to see?

I want to see SQL log output。

###### What did you see instead?
./flyway -enterprise baseline 
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2。

When I replaced flyway-6.0.4,Do the same thing, the execution was successful。

**Comment by luoy1991** [comment] 2020-12-14 08:09
I can use logback normally

**Comment by DoodleBobBuffPants** [comment] 2020-12-14 09:13
I have been unable to reproduce this. Could you ensure your `log4j2.xml` is in the Flyway root directory? See [our docs](https://flywaydb.org/documentation/usage/commandline/#output) on this for an example directory structure.

If that doesn't work, could you provide a minimal Flyway project that reproduces this?

**Comment by luoy1991** [comment] 2020-12-15 04:30
|-- lib
|   |-- community
|   |   |-- flyway-commandline-7.3.1.jar
|   |   `-- flyway-core-7.3.1.jar
|   |-- enterprise
|   |   |-- flyway-commandline-7.3.1.jar
|   |   |-- flyway-core-7.3.1.jar
|   |   |-- **log4j-api-2.11.2.jar**
|   |   `-- **log4j-core-2.11.2.jar**
|   |-- gson-2.8.6.jar
|   `-- jansi-1.18.jar
|-- licenses
|   |-- flyway-community.txt
|   |-- flyway-teams.txt
|   `-- LICENSES-THIRD-PARTY.txt
|-- **log4j2.xml**
|-- README.txt
`-- sql
    |-- put-your-sql-migrations-here.txt
    |-- V1.0.0__test.sql

**Comment by luoy1991** [comment] 2020-12-15 04:33
flyway-7.3.1
|-- lib
|   |-- community
|   |   |-- flyway-commandline-7.3.1.jar
|   |   `-- flyway-core-7.3.1.jar
|   |-- enterprise
|   |   |-- flyway-commandline-7.3.1.jar
|   |   |-- flyway-core-7.3.1.jar
|   |   |-- log4j-api-2.11.2.jar
|   |   `-- log4j-core-2.11.2.jar
|   |-- gson-2.8.6.jar
|   `-- jansi-1.18.jar
|-- licenses
|   |-- flyway-community.txt
|   |-- flyway-teams.txt
|   `-- LICENSES-THIRD-PARTY.txt
|-- log4j2.xml
|-- README.txt
-- sql
    |-- put-your-sql-migrations-here.txt
    |-- V1.0.0__test.sql

**Comment by luoy1991** [comment] 2020-12-15 04:41
1、wget  https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/7.3.1/flyway-commandline-7.3.1-linux-x64.tar.gz
2、cp log4j-core-2.11.2.jar flyway-7.3.1/lib/enterprise    cp log4j-api-2.11.2.jar flyway-7.3.1/lib/enterprise
3、cd flyway-7.3.1 && vi log4j2.xml
4、cd flyway-7.3.1 && ./flyway -enterprise baseline
`<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
    </Console>
  </Appenders>
  <Loggers>
    <Root level="trace">
      <AppenderRef ref="Console"/>
    </Root>
  </Loggers>
</Configuration>`

**Comment by luoy1991** [comment] 2020-12-15 04:42
`<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
    </Console>
  </Appenders>
  <Loggers>
    <Root level="trace">
      <AppenderRef ref="Console"/>
    </Root>
  </Loggers>
</Configuration>`

**Comment by luoy1991** [comment] 2020-12-15 04:49
[root@localhost flyway-7.3.1]# ls
conf  drivers  flyway  flyway.cmd  jars  jre  lib  licenses  log4j2.xml  README.txt  sql
[root@localhost flyway-7.3.1]# ./flyway -enterprise baseline
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
07:51:02.361 [main] ERROR org.flywaydb.core.internal.license.VersionPrinter - Your 30 day limited Flyway trial license has expired and is no longer valid. You must upgrade to a full Flyway Teams Edition license immediately to keep on using this software.

**Comment by DoodleBobBuffPants** [comment] 2020-12-15 11:57
Could you zip and share a Flyway folder that reproduces this?

**Comment by luoy1991** [comment] 2020-12-16 06:05
https://raw.githubusercontent.com/luoy1991/flyway-7.3.1/main/flyway-7.3.1.zip

**Comment by DoodleBobBuffPants** [comment] 2020-12-16 09:02
Thanks for sharing. Line 75 of the `flyway` bash script should be:
```
CP="$CLASSPATH;$INSTALLDIR/lib/*:$INSTALLDIR/lib/$FLYWAY_EDITION/*:$INSTALLDIR/drivers/*"
```
The classpath was missing the classpath! Using the above line should fix your issue for now, and we will have this fixed in the next release

**Closed by DoodleBobBuffPants** 2020-12-16 09:02 UTC
