### ISSUE TITLE
JavaMigration  interface's canExecuteInTransaction() not working as expected

### ISSUE THREAD

**Issue by ajmalrahman** [flyway/flyway#3143] opened 2021-04-12 14:28 UTC
###### Which version and edition of Flyway are you using?

7.7.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

It is the latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle plugin

###### Which database are you using? (Type & version)

Postgres - 10

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

My (java) migration class is Implementing : JavaMigration and Overriding the method: canExecuteInTransaction() to return false. When running a migration (which would eventually create an index concurrently ( CREATE INDEX CONCURRENTLY..) , it doesn't seem to respect the configuration and throws the error: 

```
ERROR: CREATE INDEX CONCURRENTLY cannot run inside a transaction block
```
`
###### What did you expect to see?

I expected the query to run outside a transaction

###### What did you see instead?

It was still trying to run within a transaction, and throwing an error as a result

**Comment by DoodleBobBuffPants** [comment] 2021-04-15 10:03
I'm unable to reproduce this

Could you provide a minimal reproduction project with a Java migration that produces this error?

**Comment by DoodleBobBuffPants** [comment] 2021-04-19 15:33
Closing until we can get a reproduction

**Closed by DoodleBobBuffPants** 2021-04-19 15:33 UTC
Labels: s: waiting for feedback
