### ISSUE TITLE
Detecting @Entity change and update DB

### ISSUE THREAD

**Issue by SAM-BI** [flyway/flyway#1920] opened 2018-02-09 08:22 UTC
Hello everybody,
if I change the structure of an Entity (column name, ...) in my  hibernate spring (not boot)  application, is Flyway able to detect it and generate the appropriate DDL for it and update the database or should I use hibernate hbm2ddl to generate the SQL script?

It will be nice if flyway oofers us a DdlExporter that we can use and avoid a self exporter implementation :)

thanks!

**Comment by axelfontaine** [comment] 2018-02-09 11:07
Duplicate of #648

**Closed by axelfontaine** 2018-02-09 11:07 UTC
