### ISSUE TITLE
Could not migrate several schema in same time

### ISSUE THREAD

**Issue by leccyril** [flyway/flyway#1938] opened 2018-02-27 14:40 UTC
###### Which version and edition of Flyway are you using?

4.2.0 /4.0.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Could not use the latest version because we have oracle 11 on few projects and it is not supported on communauty edition

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API and Maven plugin

###### Which database are you using (type & version)?

postgres 10, oracle 11, mysql 5.5 sqlserver 2012/2014

###### Which operating system are you using?

windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

migrate with several schemas `flyway.migrate`

###### What did you expect to see?

all schemas updated once or created

###### What did you see instead?

only the first one is updated

We can not update several schema , however we can specify several schema in configuration ?

2018-02-27 15:24:56 DEBUG Flyway:40 - DDL Transactions Supported: true
2018-02-27 15:24:56 DEBUG Flyway:40 - Schemas: bdl,public,test
2018-02-27 15:24:56 DEBUG FeatureDetector:40 - Spring Jdbc available: false
2018-02-27 15:24:56 DEBUG SqlScriptFlywayCallback:40 - Scanning for SQL callback
2018-02-27 15:24:56 DEBUG Table:40 - Locking table "bdl"."schema_version"...
2018-02-27 15:24:56 DEBUG Table:40 - Lock acquired for table "bdl"."schema_versi2018-02-27 15:24:56 INFO  DbMigrate:44 - Schema "bdl" is up to date. No migratio
n necessary.

i don't see the response clear for the defect #1039 what is the status ?

**Comment by axelfontaine** [comment] 2018-02-27 14:56
Duplicate of #1039

**Closed by axelfontaine** 2018-02-27 14:56 UTC

**Comment by leccyril** [comment] 2018-02-27 15:00
i am sorry but we have no clear response not too easy to close like this

**Comment by axelfontaine** [comment] 2018-02-27 15:06
See https://stackoverflow.com/questions/27546313/flyway-database-migration-to-multiple-schemas/27588444#27588444
