### ISSUE TITLE
make migration description optional

### ISSUE THREAD

**Issue by jknack** [flyway/flyway#1052] opened 2015-07-09 16:06 UTC
Hi,

 First of thanks for this great tool! It is really useful, lightweight and easy to use.

 Have a small enhancement to suggest. I think it will be nice if you make the description optional for migration scripts and if not present just use the version as description.

Some example:

```
v0.0.1.sql -> description will be 'v0.0.1'
v0.0.2__Small_change.sql -> description will be 'Small change'
```

As I said, it is a small change but think it is useful if you don't want to explicitly add a description (usually bc developer are too lazy). But also, if the script has several changes it is hard to describe the change with one generic description.

Again, thanks for this great tool.

**Comment by axelfontaine** [comment] 2017-02-07 16:47
Duplicate of #936

**Closed by axelfontaine** 2017-02-07 16:47 UTC
