### ISSUE TITLE
Flyway support for SQL Server windows authentication

### ISSUE THREAD

**Issue by kusumat** [flyway/flyway#1990] opened 2018-04-21 03:12 UTC
###### Which version and edition of Flyway are you using?
4.0.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Exists in latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
JAVA

###### Which database are you using (type & version)?
SQLServer 2016

###### Which operating system are you using?
WINDOWS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
we want to have support for windows authentication without username password like
Ex: flyway.setDataSource(connectionUrl);

###### What did you expect to see?
Expect to login without user and password

###### What did you see instead?
Login failed with user '' passed dummy user

**Comment by axelfontaine** [comment] 2018-04-21 06:03
Duplicate of #1646

**Closed by axelfontaine** 2018-04-21 06:03 UTC

**Comment by kusumat** [comment] 2018-04-21 09:11
Hi axelfontaine,

Why this closed as duplicate as the issue reported in JAVA API. 
We might need to fix the Flywya.java,DriverDatasource.java to handle
Thanks,
Kusuma

**Comment by axelfontaine** [comment] 2018-04-22 03:04
You are right, this is not an exact duplicate.

Did you set the user and password arguments to `null` when creating the datasource?

**Comment by kusumat** [comment] 2018-04-23 05:40
Passing null worked. Thanks.
