### ISSUE TITLE
schema clean fails on DB2 z/OS with sqlcode -669 rc 0001

### ISSUE THREAD

**Issue by rvjansen** [flyway/flyway#1592] opened 2017-04-04 11:26 UTC
###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API, Command-line

###### What database are you using (type & version)?
DB2 z/OS V11

###### What operating system are you using?
z/OS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
tried $flyway clean in the API version

###### What did you expect to see?
a cleaned up schema

###### What did you see instead?
-669   THE OBJECT CANNOT BE EXPLICITLY DROPPED. REASON reason-code
This because a table in an explicitly created tablespace cannot be explicitly dropped.

**Comment by axelfontaine** [comment] 2017-04-04 14:25
@cteig Can you take a look at this?

**Comment by Muni10** [comment] 2017-04-10 11:48
@rvjansen @axelfontaine Looking at this issue

**Comment by Muni10** [comment] 2017-04-19 10:52
@rvjansen I need som more information on this issue, I am unable to reproduce the error.
Could you describe in more detailt the course of action that results in this error. I assume you have done all changes at DDL level through flyway? Please include a description of the table and tablespace as well.

**Comment by rvjansen** [comment] 2017-04-19 12:55
[Rexx and Flyway.pdf](https://github.com/flyway/flyway/files/934530/Rexx.and.Flyway.pdf)

@Muni10 Sten, yes, all done using flyway, as in attached pdf pp 16 and 17. It appears that if you don't have implicit tablespaces, you can't drop the table. So in this case, flyway should just drop the tablespaces, this will get rid of the tables. And more.

**Comment by axelfontaine** [comment] 2017-11-27 08:16
Closing as DB2 z/OS support has been discontinued.

**Closed by axelfontaine** 2017-11-27 08:16 UTC
Labels: d: DB2 z/OS, s: pull request welcome, t: bug
