### ISSUE TITLE
The value of `latest` for the `target` parameter is causing an exception

### ISSUE THREAD

**Issue by twerthi** [flyway/flyway#3573] opened 2022-11-23 18:22 UTC
###### Which version and edition of Flyway are you using?
Flyway 9.8.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using? (Type & version)
MySql 8.0

###### Which operating system are you using?
Hosted on Azure

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
The value of `latest` is causing an error for the `target` parameter.

flyway migrate -url="jdbc:mysql://od-solutions-mysql-uscentral.mysql.database.azure.com:3306/target_nginx_development_carrental?serverTimezone=UTC&useSSL=true&enabledTLSProtocols=TLSv1.2" -user="********@od-solutions-mysql-uscentral.mysql.database.azure.com" -password="********" -target="latest"

###### What did you expect to see?
Successful database deployment.

###### What did you see instead?
ERROR: Version may only contain 0..9 and . (dot). Invalid version: "latest"

**Comment by twerthi** [comment] 2022-11-25 16:01
Looks to have been resolved.

**Comment by twerthi** [comment] 2022-11-28 17:59
Still a problem in 9.8.3

**Comment by twerthi** [comment] 2022-11-28 18:00
I also received another error stating that the jdbc connection url was incorrect and needed to start with jdbc, which it did.  Reverting to 9.7.0 is a workaround.

**Comment by DoodleBobBuffPants** [comment] 2022-11-29 11:20
I'm unable to reproduce this - could you provide a minimal reproduction project that we can run, with instructions on how to reproduce this?

At first glance, I wonder if the issue is the `"` double quotes around your parameters - does removing them help?

**Comment by twerthi** [comment] 2022-11-29 20:00
There is an issue with PowerShell Core 7.3.x on Linux, there appears to be a change to how quoted arguments are handled which is causing this to fail.  I've encountered this in other areas, I just found that PowerShell version on the machine that was executing it.

**Comment by DoodleBobBuffPants** [comment] 2022-11-30 10:53
Thanks for identifying this

We're unlikely to make any changes for this specific case unless this gets more interest, so closing for now

**Closed by DoodleBobBuffPants** 2022-11-30 10:53 UTC
Labels: s: waiting for feedback

**Comment by twerthi** [comment] 2022-11-30 15:29
Adding this for anyone else who encounters this issue

https://devblogs.microsoft.com/powershell/powershell-7-3-general-availability/#improvement-to-native-command-argument-passing
