### ISSUE TITLE
flyway-core 8.5.12 not supporting H2 db 2.x , I see it's supporting only 1.4.196 . with 2.x it give issue of compatibility mode.

### ISSUE THREAD

**Issue by rajk1729** [flyway/flyway#3466] opened 2022-06-17 01:56 UTC
###### Which version and edition of Flyway are you using?
8.5.12

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
maven plugin

###### Which database are you using? (Type & version)
H2 database , 2.x

###### Which operating system are you using?
Running spring boot application in intellij in  mac

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
If I  upgrade H2 db from 1.4.196, error thrown is for compatibility mode undetermined. While for H2 DB 1.4.196 , flyway-core 8.5.12 , is working well except for enum creation.

###### What did you expect to see?
Wanted to see it's be compatible with H2. ALso for csv read file to insert data , there might be some issue in reading timestamp. I manually need to remove space between seconds and timezone.

###### What did you see instead?
incompatibility

**Comment by tjs145** [comment] 2022-06-22 09:53
We haven't been able to repro this error on H2 2.x. It looks like it could be a problem with determining the [compatibility mode](http://www.h2database.com/html/features.html#compatibility) of the database, rather than a lack of support. Would you be able to provide us with a reproduction project?

**Comment by DoodleBobBuffPants** [comment] 2022-07-04 13:25
Could you provide a reproduction?

**Comment by DoodleBobBuffPants** [comment] 2022-07-08 10:34
Closing until we can get a reproduction

**Closed by DoodleBobBuffPants** 2022-07-08 10:34 UTC
Labels: s: waiting for feedback
