### ISSUE TITLE
Flyway to provide feedback for successful stmt excutions #1174 - Reopen

### ISSUE THREAD

**Issue by ThiyaguE** [flyway/flyway#1176] opened 2016-01-22 09:00 UTC
![flyway-delete-shows-no-feedback](https://cloud.githubusercontent.com/assets/13992997/12506334/33c3f380-c114-11e5-8a7e-903cf51b141d.jpg)

Im using command line option with -X flag.

Axel, As you see in the attached image, there is no feedback like ( no rows deleted/2 rows deleted) All it shows as successfully completed and commited Migration 1.3.

We want to have that kind of feedback.

**Comment by axelfontaine** [comment] 2016-01-22 09:04
Duplicate of #1174

**Closed by axelfontaine** 2016-01-22 09:04 UTC

**Comment by ThiyaguE** [comment] 2016-01-22 09:17
Axel, I ran Flyway with -X and Flyway logs dont show the update count. Im using flyway-3.2.1
