### ISSUE TITLE
[Bug]  Freeze during db migration in spring boot

### ISSUE THREAD

**Issue by junbeomlee** [flyway/flyway#3015] opened 2020-11-21 05:42 UTC
###### Which version and edition of Flyway are you using?
flyway-core:6.0.8

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
no

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
postgres 9.6

###### Which operating system are you using?
ubuntu

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
run spring boot application(enabled flyway) with 8 migration sql files.

###### What did you expect to see?
successful db migration

###### What did you see instead?
During migration, the migration pending is maintained after `the migrating schema to version x message` appears.
And The table to which the migration was applied seemed to be locked. In the pending state, the table could not be accessed.
After restarting the DB, it was successfully migrated.(We were running an application with 3 replicas in k8s. The system was being updated.)

**Comment by DoodleBobBuffPants** [comment] 2020-11-23 09:15
Are you able to reproduce this issue in the latest version? We have had issues with PostgreSQL locking in the past which have been addressed in newer versions, so upgrading may help

**Comment by junbeomlee** [comment] 2020-11-24 08:15
The issue is not reproduced even for the current version(flyway-core:6.0.8). I also checked the issue you were talking about, but the version used for that issue was a very low version. I am curious if the problem occurs in version 6.0.8. 
And I wonder if it is recommended to update to the latest version. 
Thank you

**Comment by junbeomlee** [comment] 2020-11-24 08:16
It looked like there was a shared lock on the table.

**Comment by DoodleBobBuffPants** [comment] 2020-11-24 09:29
We have since 6.0.8 done some work to improve PostgreSQL locking, specifically deadlock cases such as this, and it is recommended to update to the latest version

One of the features that may help in your case is the [lockRetryCount](https://flywaydb.org/documentation/configuration/parameters/lockRetryCount) option which lets you configure how many times we should try to obtain the lock before giving up, preventing deadlock

**Closed by DoodleBobBuffPants** 2020-11-24 09:29 UTC
Labels: s: waiting for feedback
