### ISSUE TITLE
Way to hook into Flyway migrate process to get fully resolved SQL text

### ISSUE THREAD

**Issue by LRomano72** [flyway/flyway#2073] opened 2018-07-09 17:47 UTC
###### Which version and edition of Flyway are you using?
Lastest

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
Azure SQL

###### Which operating system are you using?
Windows/Linux

###### What did you do?
Is there a way to retrieve the full list of SQL statements that are about to run BEFORE the migration and AFTER  all the "placeholders" are resolved? We need a way to check all the SQL scripts to ensure the scripts don't run specific commands such as CREATE USER, DROP DATABASE, etc. as we running this in a controlled environment and though that those commands work great during development, they can't be run in PRODUCTION. In Production the database user will have elevated privileges so we need to check the scripts before running them. I see the Dry Runs Pro feature but that just writes to a file. We'd like to get this data back on a callback and then we can validate it prior to the migration running.

Can you tell us what if there are callbacks to hook into or if there are Interfaces we should use?

**Comment by axelfontaine** [comment] 2018-07-10 07:34
This will be possible in Flyway Pro and Enterprise Edition 5.2 with statement-level callbacks. Duplicate of #1289

**Closed by axelfontaine** 2018-07-10 07:34 UTC
