### ISSUE TITLE
What version of snowflake flyway support currently , dose it support snowflake ver 6.7.0

### ISSUE THREAD

**Issue by supermanvsbatman** [flyway/flyway#3410] opened 2022-03-11 06:56 UTC

**Comment by DoodleBobBuffPants** [comment] 2022-03-11 09:20
Support has been tested up to version 5.1, however newer versions will continue to work albeit with a warning until we can test support on newer versions

Closing as duplicate of https://github.com/flyway/flyway/issues/3386

**Closed by DoodleBobBuffPants** 2022-03-11 09:20 UTC
