### ISSUE TITLE
Get ERROR: Unable to rollback transaction during the execution of update statement

### ISSUE THREAD

**Issue by YuliaSim** [flyway/flyway#2907] opened 2020-08-24 14:44 UTC
###### Which version and edition of Flyway are you using?

Flyway Community Edition 6.4.4 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Jenkins calls for flyway 

###### Which database are you using (type & version)?

Postgres 12.2 on AWS

###### Which operating system are you using?

Ubuntu

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I tried to run database migration by Jenkins that calls for Flyway.
The migration failed during the execution of the following update: 

UPDATE devices
SET collection_enabled=false
WHERE device_type_id=100 
AND site_id IN (SELECT site_id FROM sites WHERE site_name IN ('A1','A2')) 
AND device_id NOT IN (SELECT device_id FROM shared_devices sd);

This command updates 2500 rows and when I execute it manually it runs successfully.

###### What did you expect to see?

No errors

###### What did you see instead?

Get the following errors:

```
15:19:26  Current version of schema "flyway": 2020.08.20.01
15:19:27  Executing SQL callback: beforeEachMigrate - set applicative role
15:19:27  Migrating schema "flyway" to version 2020.08.23.01 - disable collection of non shared weather devices
15:19:27  Executing SQL callback: afterEachMigrate - set flyway role
15:19:27  ERROR: Unable to rollback transaction
[2020-08-24T12:19:27.397Z] org.postgresql.util.PSQLException: This connection has been closed.
[2020-08-24T12:19:27.397Z] 	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:857)
[2020-08-24T12:19:27.397Z] 	at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:864)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:82)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:279)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:71)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.Flyway$1.execute(Flyway.java:199)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.Flyway$1.execute(Flyway.java:159)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.Flyway.execute(Flyway.java:530)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.Flyway.migrate(Flyway.java:159)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.commandline.Main.executeOperation(Main.java:198)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.commandline.Main.main(Main.java:127)
[2020-08-24T12:19:27.397Z] ERROR: Unable to restore autocommit to original value for connection
[2020-08-24T12:19:27.397Z] org.postgresql.util.PSQLException: This connection has been closed.
[2020-08-24T12:19:27.397Z] 	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:857)
[2020-08-24T12:19:27.397Z] 	at org.postgresql.jdbc.PgConnection.setAutoCommit(PgConnection.java:786)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:97)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:279)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:71)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.Flyway$1.execute(Flyway.java:199)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.Flyway$1.execute(Flyway.java:159)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.Flyway.execute(Flyway.java:530)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.core.Flyway.migrate(Flyway.java:159)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.commandline.Main.executeOperation(Main.java:198)
[2020-08-24T12:19:27.397Z] 	at org.flywaydb.commandline.Main.main(Main.java:127)
[2020-08-24T12:19:27.397Z] ERROR: Unable to release PostgreSQL advisory lock
[2020-08-24T12:19:27.397Z] Caused by: org.postgresql.util.PSQLException: This connection has been closed.
```

**Comment by DoodleBobBuffPants** [comment] 2020-08-25 13:09
I've been unable to reproduce this error. It is likely that the issue is that you may be manually disposing of the connection in the callback or the connection is timing out. You could try adjusting a timeout property, such as the `socketTimeout`, as in the [PostgreSQL JDBC docs](https://jdbc.postgresql.org/documentation/92/connect.html).

**Comment by YuliaSim** [comment] 2020-08-30 13:03
Hi , 
The process failed immediately after the update started to run (no wait for timeout). We got the same error on three different environments. I reviewed our callbacks and config files and didn't find any special configured parameters. 
What additional info can I provide in order to help with the issue's investigation?

**Comment by DoodleBobBuffPants** [comment] 2020-09-01 08:09
Can you run it in debug mode and send the full output? (run with `-X`)

**Comment by YuliaSim** [comment] 2020-09-02 08:41
Hi, please find the output of migration in the debug mode:

Executing SQL callback: beforeEachMigrate - set applicative role
DEBUG: Executing SQL: set role entities
DEBUG: Update Count: 0
Migrating schema "flyway" to version 2020.08.23.01 - disable collection of non shared weather devices
DEBUG: Executing SQL: UPDATE devices
SET collection_enabled=false
WHERE device_type_id=504 -- weather
AND site_id IN (SELECT site_id FROM sites WHERE site_name IN ('US Weather Service','Israel Meteorological Service')) --only on these 2 sites, not the same ID on all envs
AND device_id NOT IN (SELECT device_id FROM shared_devices sd)
DEBUG: Update Count: 2638
DEBUG: Successfully completed migration of schema "flyway" to version 2020.08.23.01 - disable collection of non shared weather devices
DEBUG: Parsing afterEachMigrate__set_flyway_role.sql ...
DEBUG: Found statement at line 1: set role flyway
Executing SQL callback: afterEachMigrate - set flyway role
DEBUG: Executing SQL: set role flyway
DEBUG: Update Count: 0
DEBUG: Rolling back transaction...
ERROR: Unable to rollback transaction
org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:857)
	at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:864)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:82)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:279)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:71)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:206)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:158)
	at org.flywaydb.core.Flyway.execute(Flyway.java:527)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:158)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:198)
	at org.flywaydb.commandline.Main.main(Main.java:127)
ERROR: Unable to restore autocommit to original value for connection
org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:857)
	at org.postgresql.jdbc.PgConnection.setAutoCommit(PgConnection.java:786)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:97)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:279)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:71)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:206)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:158)
	at org.flywaydb.core.Flyway.execute(Flyway.java:527)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:158)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:198)
	at org.flywaydb.commandline.Main.main(Main.java:127)
DEBUG: Memory usage: 31 of 256M
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Unable to release PostgreSQL advisory lock
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:86)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:206)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:158)
	at org.flywaydb.core.Flyway.execute(Flyway.java:527)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:158)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:198)
	at org.flywaydb.commandline.Main.main(Main.java:127)
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:857)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1763)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:410)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:346)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.execute(JdbcTemplate.java:223)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:84)
	... 10 more

**Comment by DoodleBobBuffPants** [comment] 2020-09-02 12:21
Can you provide a minimal project to reproduce this as I have been unable to reproduce this myself.

**Comment by DoodleBobBuffPants** [comment] 2020-09-23 09:13
Without a reproduction project we can't debug this, so closing until something is provided.

**Comment by DoodleBobBuffPants** [comment] 2020-10-07 16:31
Commit 289cbadf12dcf1813394615ac8848737a0475763 should help with this issue in the release of 7.0.2, as it should unveil the underlying error

**Comment by DoodleBobBuffPants** [comment] 2020-10-14 14:19
Closing due to inactivity

**Closed by DoodleBobBuffPants** 2020-10-14 14:19 UTC
Labels: s: waiting for feedback

**Comment by mazyvan** [comment] 2024-12-04 04:43
@YuliaSim did you find a solution? I'm having the same issue
