### ISSUE TITLE
The very useful feature of using Flyway in a pipeline using -configFiles=-, where you can pipe in config items, (especially useful with GPG) seems to have stopped working in the latest edition

### ISSUE THREAD

**Issue by Phil-Factor** [flyway/flyway#3618] opened 2023-02-09 15:09 UTC
###### Which version and edition of Flyway are you using?
Flyway Teams Edition 9.14.1 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command-line

###### Which database are you using? (Type & version)
Database system? Oracle

###### Which operating system are you using?
Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I used to run this fine in last month's version (it is still in front of me on the screen with the results) Then I upgraded to the latest version  and it was no longer working and errored out because it had no connection info

gpg -d -q c:\Users\Phil\oracle_pubsOracle_main.conf.gpg|flyway -configFiles=- info

###### What did you expect to see?
before, it gave me the info.
DEBUG: Java Version: 17.0.5+8
DEBUG: Loading config file: <path toInstall>\flyway.conf
DEBUG: Loading config file: C:\Users\phil\flyway.conf
DEBUG: Loading config file: <pathToProject>\flyway.conf
DEBUG: Using configuration:
DEBUG: Attempting to load configuration from standard input
Loaded configuration from standard input
DEBUG: flyway.configFiles -> -
DEBUG: flyway.installedBy -> Phil Factor ...etc...

###### What did you see instead?
 
Now it says
DEBUG: Java Version: 17.0.5+8
DEBUG: Loading config file: <path toInstall>\flyway.conf
DEBUG: Loading config file: C:\Users\phil\flyway.conf
DEBUG: Loading config file: <pathToProject>\flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.configFiles -> -
DEBUG: flyway.installedBy -> Phil Factor ...etc...
--

**Comment by Peter-Laws** [comment] 2023-02-10 10:31
Thank you for reporting it, I'll look to replicate and verify where the issue was introduced. 
As you have a working version available, what is it please? That would help narrow the search.

**Comment by Phil-Factor** [comment] 2023-02-10 15:35
the version in Chocolatey is working fine.  I usually only upgrade when a release gets to Chocolatey. This release had problems for me  because I'm a teams customer using teams features so I did a manual upgrade to the latest teams release. After I did so, my encryped configurations no longer worked. I I use an oracle wallet which requires Teams.

**Comment by Peter-Laws** [comment] 2023-02-10 15:42
Thanks for the pointer, that looks to be 9.11, I'll explore and come back to you.

**Comment by Phil-Factor** [comment] 2023-03-02 12:09
Can you please confirm that this feature - doumented here - is now working? https://flywaydb.org/documentation/usage/commandline/#configuration-from-standard-input
I've tried all the examples on  Teams version 9.15.1  on the commandline and PowerShell and can't get them to run.

**Comment by Peter-Laws** [comment] 2023-03-02 12:29
I'm afraid I cannot, it's still being worked on. 
When it is addressed we'll both update this issue and it will be referenced in the releaser notes. I'll follow up on the issue our side at the next meeting.

**Comment by Peter-Laws** [comment] 2023-03-15 16:26
Hello @Phil-Factor 

Please could you test the fix implemented in 9.16.0 and report back?

**Comment by Phil-Factor** [comment] 2023-03-27 13:18
other apps have suffered the same bug, it seems
https://stackoverflow.com/questions/7421612/slf4j-failed-to-load-class-org-slf4j-impl-staticloggerbinder

**Comment by Peter-Laws** [comment] 2023-03-27 13:22
That tracks with what I'm seeing, we're working on resolving it currently.

**Comment by Peter-Laws** [comment] 2023-04-13 13:33
I anticipate your code is fine; once the issue is fixed we'll update this thread.

**Comment by Phil-Factor** [comment] 2023-06-30 16:50
Still keen to have the feature back.

**Comment by Peter-Laws** [comment] 2023-07-04 10:59
The request remains on the dev teams board, it necessitates an architectural alteration that's already planned.
We will update this issue once implemented.

**Comment by Peter-Laws** [comment] 2023-11-02 10:24
Good morning @Phil-Factor 

As of v10s release, this issue should now be resolved. Please do let us know your findings.

**Closed** 2023-12-18 16:44 UTC
Labels: s: waiting for feedback
