### ISSUE TITLE
Repair should honor baseline

### ISSUE THREAD

**Issue by xiechao00** [flyway/flyway#954] opened 2015-02-18 05:14 UTC
user scenario: (in MySQL)
1. extract the existing base db DDL and insert statement sql, save them into 
db/migration/V1__base.sql, 
db/migration/V1_1__seeding.sql
while we start migration from the existing one that has already been in 1.1.
2. baseline existing db , designating the baseline version = 1.1
3. create migration sql, save them into
db/migration/V2__amendingTables.sql
db/migration/V2_1__seeding.sql
4. do the migration, result is successful, showing 1.1 migrated to 2, and 2 -> 2.1
5. do the migration again, 
   expecting: nothing happens, while showing successful
   actual: showing failure for validation, the V2__amendingTables checksum not matching to available db

I think the error shown in the step5 is not reasonable since based on our migration process, it should identify the correct version and report properly.

workaround: run flyway:repair, which will modify the schema-version table to recalculate the checksum and populate all version migration (1, 1.1, 2, 2.1) replacing the previous ones (1.1--generated from the baseline step, 2, 2.1), after repairing, the flyway:migrate show successful with nothing being done.

hope this is clear to investigate this issue.

**Comment by axelfontaine** [comment] 2015-02-18 13:21
Thanks for reporting this. I see two issues here:
1. repair should honor baseline => clearly a bug
2. the checksum mismatch => hmmm. I'll need to investigate this one. Are you sure it has nothing to do with Git & CRLF/LF line endings?

Cheers
Axel

**Comment by xiechao00** [comment] 2015-02-18 22:34
today  I tried again the whole process but nothing wrong happening, which is strange a bit. but I did meet that error mentioned yesterday, no worries, I will keep update to you and thank you for the quick response. btw: is there any possible operation changing the checksum , to make the validation error?

**Comment by axelfontaine** [comment] 2015-03-05 14:55
Unable to reproduce. Closing.

**Closed by axelfontaine** 2015-03-05 14:55 UTC
Labels: bug, Core
