### ISSUE TITLE
Odd appearances of $xxx$ pattern cause early termination of the migration script

### ISSUE THREAD

**Issue by tdakanalis** [flyway/flyway#1996] opened 2018-04-26 09:11 UTC
###### Which version and edition of Flyway are you using?
5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
PostgreSQL 9.4.15

###### Which operating system are you using?
Debian GNU/Linux 8 (jessie)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Some of the table data that are get inserted by the COPY commands in the baseline script, contains the $xxx$ pattern where xxx any characters. If that patterns appears **ODD** times the script finishes after executing successfully the COPY command with the last apearance of that pattern but the migration ends there by reporting a successfull migration. It seems that flyway takes that last pattern as the end of the migration file.

This does not happen when the pattern apperas **EVEN** times.

###### What did you expect to see?
I expected to see all migration file to get applied into db

###### What did you see instead?
Part of the migration script got applied into db. All data/indices/constrains etc after the last aprearance of the $xxx$ pattern get ingnored.

**Comment by axelfontaine** [comment] 2018-04-26 10:18
Thanks for the report. Can you share a small example SQL file that triggers the issue?

**Comment by tdakanalis** [comment] 2018-04-26 10:57
Here is a small migration script. Table test1 will be populated with data while test2 will be empty.

```sql
CREATE TABLE test1 (
    id integer primary key,
    name TEXT NOT NULL
);

CREATE TABLE test2 (
    id integer primary key,
    name TEXT NOT NULL
);

COPY test1 (id, name) FROM stdin;
2	$test1$
3	$test2$
4	$test3$
\.

COPY test2 (id, name) FROM stdin;
2	$test1$
3	$test2$
4	$test3$
\.
```

**Comment by axelfontaine** [comment] 2018-05-23 10:07
Duplicate of #1876

**Closed by axelfontaine** 2018-05-23 10:07 UTC
Labels: d: PostgreSQL, s: waiting for feedback, t: bug
