### ISSUE TITLE
Be able to ignore exceptions

### ISSUE THREAD

**Issue by edwagner** [flyway/flyway#1673] opened 2017-06-15 20:25 UTC
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
Oracle

###### What did you do?
SQL*Plus provides a mechanism to continue processing a file even when a statement fails. The commands are `WHENEVER SQLERROR CONTINUE` and `WHENEVER SQLERROR EXIT FAILURE `. These are handy if your environments aren't completely in sync and you have some statements that you expect to fail in certain environments (e.g. if the object already exists) but that you nevertheless want to run in all cases.

###### What did you expect to see?
When I run a file with flyway that has `WHENEVER SQLERROR CONTINUE`, it would be nice if flyway would print out warnings for exceptions (after the `WHENEVER SQLERROR CONTINUE` statement) but continue processing.

###### What did you see instead?
flyway stops the migration on the first error.

**Comment by axelfontaine** [comment] 2017-11-29 15:25
Duplicate of #1845

**Closed by axelfontaine** 2017-11-29 15:25 UTC
Labels: d: Oracle, t: feature
