### ISSUE TITLE
db2zos detection seems broken

### ISSUE THREAD

**Issue by wemu** [flyway/flyway#1251] opened 2016-03-22 15:56 UTC
###### What version of Flyway are you using?
Flyway 4.0

###### What database are you using (type & version)?
DB2 z/OS

###### What operating system are you using?
z/OS

###### What did you do?
We upgraded Flyway from 3.2.1 to 4.0 and during the "migrate" the following script error occurs:

```
Script failed
-------------
SQL State  : 42704
Error Code : -204
Message    : DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=ZusernameD.T_FLYWAY_VERSION_vr_idx, DRIVER=4.15.82
Line       : 17
Statement  : DROP INDEX "ZusernameD"."T_FLYWAY_VERSION_vr_idx"

```
Other than moving from flyway 3.2.1 to 4.0 no changes to the sql scripts where made.

###### What did you expect to see?
The flyway table index suffix it wants to drop ends with: _vr_idx
but it seems it should be uppercase. The flyway sources contain no such names in upgradeMetaDataTable.sql for db2zos - so it seems flyway chooses the db2 scripts instead of the db2zos scripts? Or the oracle scripts? (see below, we do two migrations during the build)

The db2zos database properties:
```
Database: DB2/DSN11015
Driver name: IBM Data Server Driver for JDBC and SQLJ
Driver version: 4.17.29
JDBC version: 4.1
Case sensitivity: UPPER (quoted: EXACT)
```
The class DB2zosDbSupport contains a method getScriptLocation which seems to point to a wrong location? But It also looks as if it is not used anymore. So I am not sure where the db2 scripts get mixed up :/

We tried to set
```
flyway.driver=com.ibm.db2.jcc.DB2Driver
```
in the flyway.properties but that had no effect.

What also might be a problem: we do two database setups (oracle and db2zos) within one build. First one is oracle, the second one is the db2zos. Oracle works fine. But we do a "new Flyway()" for each configuration. So maybe the loading of the driver is the issue?
(we use the Java API)

###### What did you see instead?
Flyway tries to migrate the versions table but uses the wrong(?) scripts.

Is this on purpose or how can this be fixed?

**Comment by axelfontaine** [comment] 2016-03-22 16:34
@cteig Thoughts?

**Comment by cteig** [comment] 2016-03-22 20:03
Hi,
The upgrade for DB2zOS did not reach the 4.0 release. Just now the upgrade script for DB2zOS is the same as for DB2 LUW. So I don´t think flyway chose the wrong script, but the script is buggy. 

I see a new update for pull request #1237 is accepted and merged into master yesterday. This pull request contains a fix for upgrade to 4.0 and some other improvements to the createMetadata-script

Christine

**Comment by axelfontaine** [comment] 2016-03-22 23:47
Duplicate of #1237

**Closed by axelfontaine** 2016-03-22 23:47 UTC
Labels: d: DB2 z/OS, s: pull request welcome

**Comment by wemu** [comment] 2016-03-23 12:33
Thanks for the hints. I did not notice that master is already ahead of 4.0.

I've copied the db2zos scripts into 4.0 and give it a try. The current scripts from master work from what I can say on our db2zos instances.

So I'm looking forward for the next release.

Thanks! :+1:
