### ISSUE TITLE
No value provided for placeholder expressions

### ISSUE THREAD

**Issue by Me1gireesh** [flyway/flyway#2423] opened 2019-07-01 09:04 UTC
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by Me1gireesh** [comment] 2019-07-01 09:44
Hi Alex, 
I am getting an error of 
"org.flywaydb.core.api.FlywayException: No value provided for placeholder expressions:  & .  Check your configuration! "

I am not using any placeholder files, Rather have an '&' in one of the comments.
Flyway treats that as placeholder value and is looking for a placeholder configuration.
Infact the '&' is mentioned on a  commented line '--' 

I am raising this as a bug for Flyway Enterprise Edition (trial) 5.2.4 .

**Comment by Me1gireesh** [comment] 2019-07-01 09:46
The error is thrown while parsing the migrations.

ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: No value provided for placeholder expressions:  & .  Check your configuration!
	at org.flywaydb.core.internal.database.oracle.pro.SQLPlusPlaceholderReplacer.replacePlaceholders(SQLPlusPlaceholderReplacer.java:154)
	at org.flywaydb.core.internal.line.PlaceholderReplacingLine.<init>(PlaceholderReplacingLine.java:25)
	at org.flywaydb.core.internal.sqlscript.SqlScript.extractStatements(SqlScript.java:108)
	at org.flywaydb.core.internal.sqlscript.SqlScript.<init>(SqlScript.java:86)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.addMigrations(SqlMigrationResolver.java:140)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:107)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:47)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:136)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:118)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:104)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:46)
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:133)
	at org.flywaydb.core.internal.command.DbInfo.info(DbInfo.java:52)
	at org.flywaydb.core.Flyway$5.execute(Flyway.java:1528)
	at org.flywaydb.core.Flyway$5.execute(Flyway.java:1521)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
	at org.flywaydb.core.Flyway.info(Flyway.java:1521)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:167)
	at org.flywaydb.commandline.Main.main(Main.java:108)

**Comment by axelfontaine** [comment] 2019-07-01 09:53
This sounds similar to https://github.com/flyway/flyway/issues/2321

Can you check whether the issue persists after upgrading to 6.0.0-beta2?

**Comment by MikielAgutu** [comment] 2019-07-31 13:15
Any news?

**Comment by alextercete** [comment] 2019-09-06 10:17
Closing as a duplicate of #2432.

**Closed by alextercete** 2019-09-06 10:17 UTC
Labels: d: Oracle, s: waiting for feedback

**Comment by mohammad-sk** [comment] 2021-03-02 15:00
org.flywaydb.core.api.FlywayException: No value provided for placeholder: ${USER_NAME}.  Check your configuration!
