### ISSUE TITLE
Class not found exception JavaUtilLogCreator

### ISSUE THREAD

**Issue by altinukshini** [flyway/flyway#2090] opened 2018-07-18 09:13 UTC
###### Which version and edition of Flyway are you using?
5.1.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Postgresql 9.6

###### Which operating system are you using?
CentOS 7

###### What did you do?
Using ant and flyway-ant: https://mvnrepository.com/artifact/cz.net21.flyway.ant/flyway-ant/1.1.4
Ran `<flyway:info />` with ant

###### What did you expect to see?
Info table

###### What did you see instead?
     Could not create type antlib:org.flywaydb.ant:repair due to java.lang.ExceptionInInitializerError
     ...
     Caused by: org.flywaydb.core.api.FlywayException: Unable to instantiate class org.flywaydb.core.internal.util.logging.javautil.JavaUtilLogCreator : org.flywaydb.core.internal.util.logging.javautil.JavaUtilLogCreator
     ....
     Caused by: java.lang.ClassNotFoundException: org.flywaydb.core.internal.util.logging.javautil.JavaUtilLogCreator

**Comment by ttulka** [comment] 2018-07-18 11:39
The issue is already addressed in https://github.com/flyway/flyway-ant/issues/4

**Comment by ttulka** [comment] 2018-07-18 11:56
Was already fixed by https://github.com/flyway/flyway-ant/commit/ef14d5f79596ee55003b53d0edff64669c68bba8
I suggest to close this issue.

**Closed as completed** 2018-08-01 20:24 UTC
Labels: r: invalid
