### ISSUE TITLE
Comment at the end of the line makes flyway fail migration of an ALTER TABLE statement in Oracle

### ISSUE THREAD

**Issue by gemisigo** [flyway/flyway#2117] opened 2018-08-28 09:17 UTC
###### Which version and edition of Flyway are you using?
5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
This is current to my best knowledge

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Using command line client

###### Which database are you using (type & version)?
Oracle 12.2

###### Which operating system are you using?
Window 10 Pro

###### What did you do?
There's a comment on the same line the ALTER TABLE statement is.

`alter table kar_sys_log add constraint fk_kar_sys_log$sys_app_user                                  foreign key ( sys_app_user_id ) references kar_sys_app_user ( sys_app_user_id ); -- This FK is created with table kar_sys_app_user
`

###### What did you expect to see?
This is expected to execute successfully.

###### What did you see instead?
It failed with an error message stating 

> ORA-01735: invalid ALTER TABLE option

Remove the comment from the end of the line and it executes without any errors. The statement with the comment also executes successfully from other clients (eg. Oracle SQL Developer).

**Comment by axelfontaine** [comment] 2018-08-28 09:18
Duplicate of #63

**Closed by axelfontaine** 2018-08-28 09:18 UTC
