### ISSUE TITLE
Flyway doesn't support Mariadb 10.3 by using latest jdbc-driver

### ISSUE THREAD

**Issue by eerokosk** [flyway/flyway#2339] opened 2019-03-28 10:19 UTC
Latest Flyway Core (version 5.2.4) doesn't support MariaDB version 10.3 when you are using MariaDB Java Client version 2.4.0 or 2.4.1. 

Snippet from Gradle:

compile group: 'org.flywaydb', name: 'flyway-core', version: '5.2.4'
compile group: 'org.mariadb.jdbc', name: 'mariadb-java-client', version: '2.4.1'

Using versions mentioned up causes following exception:

org.flywaydb.core.api.FlywayException: Unsupported Database: MariaDB 10.3
	at org.flywaydb.core.internal.jdbc.DatabaseType.fromDatabaseProductNameAndPostgreSQLVersion(DatabaseType.java:168)
	at org.flywaydb.core.internal.jdbc.DatabaseType.fromJdbcConnection(DatabaseType.java:117)
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:90)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1670)
	at org.flywaydb.core.Flyway.clean(Flyway.java:1499)

Best,
Eero.

**Comment by jonathanlermitage** [comment] 2019-04-07 13:52
Latest versions of MariaDB Connector/J driver return "MariaDB" server type instead of "MySQL", that's why Flyway worked with previous versions of this driver.  

To make it work with 2.4.x: simply add `useMysqlMetadata=true` to your jdbc url -> driver will return "MySQL" server type.

Source: https://mariadb.com/kb/en/library/about-mariadb-connector-j/#essential-parameters -> `useMysqlMetadata`

**Comment by axelfontaine** [comment] 2019-04-08 09:13
Duplicate of #2289

**Closed by axelfontaine** 2019-04-08 09:13 UTC

**Comment by tomas-silhavy** [comment] 2019-05-10 20:32
@jonathanlermitage 
> To make it work with 2.4.x: simply add `useMysqlMetadata=true` to your jdbc url -> driver will return "MySQL" server type.

Did this actually work for you? It has no effect when I try :/

**Comment by vasilemihali** [comment] 2019-05-23 06:15
I have the same issue, and even with useMysqlMetadata=true prop, still does not work, any new suggestions are welcome, thx.

**Comment by axelfontaine** [comment] 2019-05-23 06:18
@vasilemihali 6.0.0-beta contains a fix for this.

**Comment by datmt** [comment] 2022-09-27 08:45
In my experience, even with MariaDB, you still need to use MySQL's syntax. That means you treat a MariaDB connection as a MySQL connection.

I documented my finding here: https://datmt.com/backend/java/spring/flyway-spring-boot-integration-guide/#Very_important_note_for_MySQLMariaDB_users
