### ISSUE TITLE
Clean() fails on Sybase ASE trying to DROP TABLE inside a transaction

### ISSUE THREAD

**Issue by richard-emerson** [flyway/flyway#1595] opened 2017-04-05 11:37 UTC
It looks like schema.clean() does not check the 'DDL transactions supported' setting and tries to do DROP TABLE inside a TransactionTemplate, but Sybase ASE doesn't like that.

###### What version of Flyway are you using?
4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
Sybase ASE 15.7 via jTDS 1.3.1

###### What operating system are you using?
JDK 1.8.0_60 on Win7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
		Flyway flyway = new Flyway();
		flyway.setDataSource(dboDataSource);
		flyway.setSchemas("dbo");
		flyway.clean();
		flyway.migrate();

###### What did you expect to see?
Expected the existing tables in the schema to be dropped

###### What did you see instead?
INFO  main: VersionPrinter - Flyway 4.1.2 by Boxfuse
INFO  main: DbSupportFactory - Database: jdbc:jtds:sybase: (ASE 15.70)
DEBUG main: Flyway - DDL Transactions Supported: false
[...]
DEBUG main: DbClean - Cleaning schema dbo ...
org.flywaydb.core.internal.dbsupport.FlywaySqlException: 
Unable to clean schema dbo
SQL State  : S1000
Error Code : 2762
Message    : The 'DROP TABLE' command is not allowed within a multi-statement transaction in the 'eosregional' database.
	at org.flywaydb.core.internal.dbsupport.Schema.clean(Schema.java:150)
	at org.flywaydb.core.internal.command.DbClean$4.call(DbClean.java:184)
	at org.flywaydb.core.internal.command.DbClean$4.call(DbClean.java:181)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
	at org.flywaydb.core.internal.command.DbClean.cleanSchema(DbClean.java:181)
	at org.flywaydb.core.internal.command.DbClean.clean(DbClean.java:130)
	at org.flywaydb.core.Flyway$3.execute(Flyway.java:1041)
	at org.flywaydb.core.Flyway$3.execute(Flyway.java:1037)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1413)
	at org.flywaydb.core.Flyway.clean(Flyway.java:1037)

**Comment by axelfontaine** [comment] 2017-04-05 20:53
@super132 What do you think?

**Comment by super132** [comment] 2017-04-06 08:57
@axelfontaine I think it is a bug in `DbClean` not to read `DbSupport.supportDdlTransactions()` to determine whether a transaction is used when doing clean up. The fix would be adding logic in `DbClean.cleanSchema()` to read the ddl transaction support flag, and use simple JDBC call without transactions to do clean up instead of always applying transactions.

**Comment by axelfontaine** [comment] 2017-04-06 09:43
@super132 No, `DbSupport.supportDdlTransactions()` does not preclude the use of transactions. It simply states that when false DDL statements may be surrounded by implicit commits. In this case something like the PostgreSQL non-transactional statement support may be required. Can you look into this?

**Comment by super132** [comment] 2017-04-06 11:31
@axelfontaine Could you point to me where is the code of non-transnational statement support in PostgreSQL implementation? I cannot find it in PostgreSQL implementations. Thanks.

**Comment by axelfontaine** [comment] 2017-04-06 11:37
@super132 https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/postgresql/PostgreSQLSqlStatementBuilder.java#L74

**Comment by super132** [comment] 2017-04-06 12:05
@axelfontaine Thanks. After studying the code, I think it is not the case of PostgreSQL support of non-transactional statement because it is run inside `DbClean`, which always embedded with a transaction no matter the implementation of the clean up process inside schema object. The PostgreSQL example is to enable `SqlScript` to detect if both transaction and non-transaction statements are in the same migration. The case here is at the phase of doing `DbClean` which has no knowledge on it. 

I think if we need to fix this problem, I come up with the followings:

1. We could change the schema object to return a flag indicating if transaction is handled by individual schema class.
2. Change the `Schema` object to return `SqlScript` object in all operations, then the internal operation command objects (`DbClean`, `DbMigrate`, etc) will take the `SqlScript` object and use `executeInTraction()` to decide if this operation needs to be run in a transaction.

What do you think about the approaches? Thanks.

**Comment by axelfontaine** [comment] 2017-04-06 12:25
Hmmm good point. It will probably have to be a combination of both as such statements can also appear in regular migrations.

I actually like the idea of returning a `SqlScript` with all statements necessary for cleaning a schema. This would help harmonize the different clean implementations and eventually pave the way for #87 . This would be a bigger change though. I have filed #1597 for that work. This should be completed first before tackling this issue.

**Comment by axelfontaine** [comment] 2017-12-18 11:46
@richard-emerson Can you share a small SQL script that causes Flyway to trip up? (Please test with Flyway 5.0.x)

**Comment by axelfontaine** [comment] 2018-01-03 08:59
I am unable to reproduce this with Flyway 5.0.x. Closing.

**Closed by axelfontaine** 2018-01-03 08:59 UTC
Labels: c: clean(), d: Sybase ASE, m: Core, s: waiting for feedback, t: bug
