### ISSUE TITLE
Flyway v10 doesn't support Postgres v11

### ISSUE THREAD

**Issue by donalmurtagh** [flyway/flyway#3779] opened 2023-11-01 10:31 UTC
###### Which version and edition of Flyway are you using?

10.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle

###### Which database are you using? (Type & version)

Postgres v11

###### Which operating system are you using?

Mac OS X

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Changed `build.gradle` from v9.22.3 to v10.0.0 i.e.

```groovy
plugins {
    id 'org.flywaydb.flyway' version '10.0.0' // was 9.22.3
}

dependencies {
    implementation "org.flywaydb:flyway-core:10.0.0" // was 9.22.3
}
```

###### What did you expect to see?

The application starting without any errors.

###### What did you see instead?

The following exception is thrown when the (Spring Boot) app starts

```
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 11.16
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:105) ~[flyway-core-10.0.0.jar:na]
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1053) ~[flyway-core-10.0.0.jar:na]
	at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:589) ~[flyway-core-10.0.0.jar:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.configureDataSource(FlywayAutoConfiguration.java:161) ~[spring-boot-autoconfigure-3.1.5.jar:3.1.5]
	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.flyway(FlywayAutoConfiguration.java:148) ~[spring-boot-autoconfigure-3.1.5.jar:3.1.5]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.13.jar:6.0.13]
	... 233 common frames omitted
```

If support for Postgres v11 has intentionally been dropped, I would expect this to be mentioned in the [release notes](https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html). The [Postgres section of the supported databases page](https://documentation.red-gate.com/fd/supported-database-versions-143754067.html#SupporteddatabasesforFlyway-PostgreSQL) says that v11 is still supported.

**Comment by Barry-RG** [comment] 2023-11-01 10:35
This is a duplicate of a pervious issue. Please see https://github.com/flyway/flyway/issues/3774

**Closed by Barry-RG** 2023-11-01 10:35 UTC
