### ISSUE TITLE
Azure SQL Data Warehouse/Synapse support

### ISSUE THREAD

**Issue by RahulVadisetty91** [flyway/flyway#2021] opened 2018-05-21 19:28 UTC
###### Which version and edition of Flyway are you using?
Flyway Community Edition 5.0.7 by Boxfuse

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

NO

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command Line

###### Which database are you using (type & version)?

Azure MS SQL DatawareHouse (SQL server 12.0)

###### Which operating system are you using?
WIndows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
When I am trying to execute the flyway info -X it's not connecting to a dwhdb database. and it throws ANSI Null State ,need to declare  scalar variables .
Image:
![image](https://user-images.githubusercontent.com/24702792/40325834-253df4ba-5d0b-11e8-98d5-3da76ef13b8a.png)

**flyway.conf
flyway.url=jdbc:sqlserver://xxxxxxx:1433;database=dwhdb;
flyway.user=xxxxxxxx
flyway.password=xxxxxxxxxx
flyway.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
flyway.baselineOnMigrate=true
flyway.schemas=dbo,employee**

**Error Message:
C:\Users\c001609\Desktop\Terraform\dwhdb>flyway info -X
Flyway Community Edition 5.0.7 by Boxfuse

DEBUG: Java 1.8.0_152 (Oracle Corporation)
DEBUG: Windows 10 10.0 amd64

DEBUG: Loading config file: C:\Users\c001609\Desktop\Terraform\dwhdb\conf\flyway.conf
DEBUG: Unable to load config file: C:\Users\c001609\flyway.conf
DEBUG: Unable to load config file: C:\Users\c001609\Desktop\Terraform\dwhdb\flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> C:\Users\c001609\Desktop\Terraform\dwhdb\jars
DEBUG: flyway.password -> **********************
DEBUG: flyway.url -> jdbc:sqlserver://xxxxxxxx:1433;database=dwhdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;@database=dwhdb;
DEBUG: flyway.schemas -> dbo,employee
DEBUG: flyway.driver -> com.microsoft.sqlserver.jdbc.SQLServerDriver
DEBUG: flyway.baselineOnMigrate -> true
DEBUG: flyway.user -> dbloginuser
DEBUG: flyway.locations -> filesystem:C:\Users\c001609\Desktop\Terraform\dwhdb\sql
DEBUG: Adding location to classpath: C:\Users\c001609\Desktop\Terraform\dwhdb\drivers\derby-10.12.1.1.jar
DEBUG: Adding location to classpath: C:\Users\c001609\Desktop\Terraform\dwhdb\drivers\derbyclient-10.12.1.1.jar
DEBUG: Adding location to classpath: C:\Users\c001609\Desktop\Terraform\dwhdb\drivers\h2-1.4.196.jar
DEBUG: Adding location to classpath: C:\Users\c001609\Desktop\Terraform\dwhdb\drivers\hsqldb-2.4.0.jar
DEBUG: Adding location to classpath: C:\Users\c001609\Desktop\Terraform\dwhdb\drivers\jtds-1.3.1.jar
DEBUG: Adding location to classpath: C:\Users\c001609\Desktop\Terraform\dwhdb\drivers\mariadb-java-client-2.2.0.jar
DEBUG: Adding location to classpath: C:\Users\c001609\Desktop\Terraform\dwhdb\drivers\mssql-jdbc-6.4.0.jre8.jar
DEBUG: Adding location to classpath: C:\Users\c001609\Desktop\Terraform\dwhdb\drivers\postgresql-42.1.4.jre6.jar
DEBUG: Adding location to classpath: C:\Users\c001609\Desktop\Terraform\dwhdb\drivers\sqlite-jdbc-3.20.1.jar
Database: jdbc:sqlserver://xxxxxxxxxx:1433;sslProtocol=TLS;jaasConfigurationName=SQLJDBCDriver;statementPoolingCacheSize=0;serverPreparedStatementDiscardThreshold=10;enablePrepareOnFirstPreparedStatementCall=false;fips=false;socketTimeout=0;authentication=NotSpecified;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustStoreType=JKS;trustServerCertificate=false;TransparentNetworkIPResolution=true;serverNameAsACE=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;queryTimeout=-1;packetSize=8000;multiSubnetFailover=false;loginTimeout=30;lockTimeout=-1;lastUpdateCount=true;hostNameInCertificate=*.database.windows.net;encrypt=true;disableStatementPooling=true;databaseName=dwhdb;columnEncryptionSetting=Disabled;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite; (Microsoft SQL Server 12.0)
ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to determine ANSI NULLS state
------------------------------------
SQL State  : S0001
Error Code : 137
Message    : Must declare the scalar variable "@@OPTIONS".

        at org.flywaydb.core.internal.database.sqlserver.SQLServerConnection.<init>(SQLServerConnection.java:64)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerDatabase.getConnection(SQLServerDatabase.java:68)
        at org.flywaydb.core.internal.database.Database.<init>(Database.java:98)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerDatabase.<init>(SQLServerDatabase.java:49)
        at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:104)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1634)
        at org.flywaydb.core.Flyway.info(Flyway.java:1321)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:167)
        at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Must declare the scalar variable "@@OPTIONS".
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:259)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1547)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:548)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:479)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7344)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:401)
        at org.flywaydb.core.internal.util.jdbc.JdbcTemplate.queryForString(JdbcTemplate.java:222)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerConnection.<init>(SQLServerConnection.java:60)
        ... 8 more**

###### What did you expect to see?
Should connect to Database and create table

###### What did you see instead?
unable to connect to database it's expecting for scalar variable 
issue with the url  #flyway.url=jdbc:sqlserver://xxxxxxxx:1433;database=dwhdb;

**Comment by axelfontaine** [comment] 2018-05-22 07:46
Related to #1330

**Comment by MikielAgutu** [comment] 2020-03-24 15:35
This may be fixed by https://github.com/flyway/flyway/issues/2514

@rv91 can you try it?

**Comment by we814** [comment] 2020-04-08 18:36
> This may be fixed by #2514
> 
> @rv91 can you try it?

Not the same error as described by OP but I am unable to baseline flyway with my Azure SQL Data Warehouse database.

flyway baseline
Flyway Community Edition 6.3.3 by Redgate
applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite; (Microsoft SQL Server 12.0)

ERROR: Unable to release SQL Server application lock
com.microsoft.sqlserver.jdbc.SQLServerException: Stored procedure sp_releaseapplock does not exist or is not supported.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:256)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:592)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2930)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:503)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.execute(JdbcTemplate.java:224)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerApplicationLockTemplate.execute(SQLServerApplicationLockTemplate.java:76)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerConnection.lock(SQLServerConnection.java:96)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.create(JdbcTableSchemaHistory.java:97)
        at org.flywaydb.core.internal.command.DbBaseline.baseline(DbBaseline.java:77)
        at org.flywaydb.core.Flyway.doBaseline(Flyway.java:206)
        at org.flywaydb.core.Flyway.access$200(Flyway.java:74)
        at org.flywaydb.core.Flyway$5.execute(Flyway.java:352)
        at org.flywaydb.core.Flyway$5.execute(Flyway.java:344)
        at org.flywaydb.core.Flyway.execute(Flyway.java:530)
        at org.flywaydb.core.Flyway.baseline(Flyway.java:344)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:190)
        at org.flywaydb.commandline.Main.main(Main.java:128)
ERROR:
Unable to acquire SQL Server application lock
---------------------------------------------
SQL State  : S0001
Error Code : 104386
Message    : Stored procedure sp_getapplock does not exist or is not supported.

**Comment by MikielAgutu** [comment] 2020-05-04 12:25
I'll make a separate issue for this.

**Comment by MikielAgutu** [comment] 2020-05-04 12:25
@RahulVadisetty91 Can you see if #2514 fixes it?

**Comment by qzhou-hmcts** [comment] 2020-05-27 17:12
Hello @MikielAgutu  I'm facing the same problem
Flyway version

Flyway Community Edition 6.4.2 by Redgate

DB server 
Azure SQL Data Warehouse, Synapse analytics

Is there  any roadmap to support Azure DW? 

> ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to acquire SQL Server application lock
SQL State  : S0001
Error Code : 104386
Message    : Stored procedure sp_getapplock does not exist or is not supported. 
at org.flywaydb.core.internal.database.sqlserver.SQLServerApplicationLockTemplate.execute(SQLServerApplicationLockTemplate.java:64)
	at org.flywaydb.core.internal.database.sqlserver.SQLServerConnection.lock(SQLServerConnection.java:96)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.create(JdbcTableSchemaHistory.java:97)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:194)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:159)
	at org.flywaydb.core.Flyway.execute(Flyway.java:530)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:159)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:197)
	at org.flywaydb.commandline.Main.main(Main.java:126)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Stored procedure sp_getapplock does not exist or is not supported.

**Comment by MikielAgutu** [comment] 2020-05-28 09:32
@qzhou-hmcts After more internal investigation we've found that Flyway's support for Azure DW/Synapse is actually pretty broken. We can't commit to a release date for the fix yet, but it's likely to be in or after the V7 release.

**Comment by DoodleBobBuffPants** [comment] 2020-09-03 09:37
This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).

**Closed by DoodleBobBuffPants** 2020-09-03 09:37 UTC
Labels: t: database support, t: feature
