### ISSUE TITLE
Allow SQL preview and transaction cancellation in a Callback

### ISSUE THREAD

**Issue by DMironenkoBDO** [flyway/flyway#2125] opened 2018-08-29 14:59 UTC
###### Which version and edition of Flyway are you using?
5.1.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
MSSQL

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I need to validate parsed SQL (that includes replacement values) and cancel migration if validation fails. Would it be possible to do in a callback?

I implemented Callback as follows. But I cannot get information on SQL that will be executed from MigrationInfo or Context.

```
public class DatabaseActionCallback implements Callback {
    @Override
    public boolean canHandleInTransaction(Event event, Context context) {
        return true;
    }

    @Override
    public boolean supports(Event event, Context context) {
        return true;
    }

    @Override
    public void handle(Event event, Context context) {      
        if (event.name().equals("BEFORE_EACH_MIGRATE")) {
            MigrationState[] st = context.getMigrationInfo().getState().values();

            String sc = context.getMigrationInfo().getScript();
            String desc = context.getMigrationInfo().getDescription();

            MigrationState state = context.getMigrationInfo().getState();
            MigrationType type = context.getMigrationInfo().getType();
            MigrationVersion  ver = context.getMigrationInfo().getVersion();
        }
    }   
}

```

**Comment by axelfontaine** [comment] 2018-08-30 08:39
Duplicate of #1289

**Closed by axelfontaine** 2018-08-30 08:39 UTC
