### ISSUE TITLE
PostgreSQL / Error cause swallowed when releasing advisory locks

### ISSUE THREAD

**Issue by fml2** [flyway/flyway#3086] opened 2021-02-18 16:27 UTC
###### Which version and edition of Flyway are you using?

7.5.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This is the latest available version as of now.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command line

###### Which database are you using? (Type & version)
PostgreSQL 12.6

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Started a migration that should do nothing because the DB is already in the desired state.

For some reason, I got the error `Unable to release PostgreSQL advisory lock`. I wanted to find out why I get it and included the option `-X` (as advised [here](https://github.com/flyway/flyway/issues/2800#issuecomment-624695903)) and hoped to see the reason. However, the stack trace was:

```
org.flywaydb.core.api.FlywayException: Unable to release PostgreSQL advisory lock
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.unlock(PostgreSQLAdvisoryLockTemplate.java:102)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:80)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:191)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:152)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:216)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
	at org.flywaydb.core.Flyway.execute(Flyway.java:570)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:223)
	at org.flywaydb.commandline.Main.main(Main.java:144)
```

It does not reveal the real cause. The real cause is apparently swallowed, this happens in this line: https://github.com/flyway/flyway/blob/7f95adeebd3034374cf74715f7d3583560568395/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLAdvisoryLockTemplate.java#L104

In the log statement, the object `rethrow` shoud be passed as well (as a parameter).

###### What did you expect to see?

The real cause of my problem.

###### What did you see instead?
A message that does not reveal the real cause.

**Comment by DoodleBobBuffPants** [comment] 2021-02-18 17:10
The exception you are seeing originates from line [102](https://github.com/flyway/flyway/blob/7f95adeebd3034374cf74715f7d3583560568395/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLAdvisoryLockTemplate.java#L102) where there is no rethrow, and in the presence of a rethrow we log an error so that the exception in the rethrow is what is surfaced

In this case, the exception is thrown because attempting to release the lock returned false

Perhaps we could attempt retrying the unlock in this case, however it might not solve your issue since the underlying issue is that the database was unable to release the lock. If you try releasing the lock manually does it succeed? Could you also check whether the lock still exists upon failure? This would let us know whether a retry would help

**Comment by fml2** [comment] 2021-02-18 21:26
You are right, I mixed up the line numbers. But still, doesn't the line [104](https://github.com/flyway/flyway/blob/7f95adeebd3034374cf74715f7d3583560568395/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLAdvisoryLockTemplate.java#L104) swallow the root cause in the case that there was "no lock" and no SQLException?

I'll do some more experiments and report back.

**Comment by fml2** [comment] 2021-02-18 23:16
I did some more experiments (created a java project and performed the migration from there) and found out:

1. You were right: the migration itself ran OK (there was nothing to do since the DB was already in the desired state)
2. The error arose because the advisory unlocking in Postgres returned `false`. I don't know why.
3. With flyway 6.5.7 everything worked without problems.

In point 3 above I used the same configuration, same DB and same DB driver; just replaced the flyway dependency.

**Comment by DoodleBobBuffPants** [comment] 2021-02-19 09:35
In Flyway 6.5.7, and more generally in Flyway 7.5.1 and before, we weren't checking the value returned by the unlock, so while it succeeds it isn't necessarily correct

I've been unable to reproduce this, could you provide a minimal reproduction project?

**Comment by fml2** [comment] 2021-02-21 17:28
The project itself is nothing special. But it might be that we have PgBouncer in between. Would it cause such behaviour? I'll talk to the DB admins to confirm whether we have that.

**Comment by DoodleBobBuffPants** [comment] 2021-02-22 09:02
PgBouncer could be the cause due to how our locking operates - see https://github.com/flyway/flyway/issues/2895 for reference

**Comment by fml2** [comment] 2021-02-22 09:54
Thank you! I've commented in the issue you linked.

I think, my case is related but not the same. I can successfully acquire the lock but can't release it. I assume that this is because the attempt to release is made not in the same DB session as it was acquired.

I still have no confirmation about the presence of PgBouncer in our setup.

Are there plans about how to fix this? I think the setup will become more and more common.

**Comment by DoodleBobBuffPants** [comment] 2021-02-22 10:14
We haven't committed to supporting PgBouncer yet, however we do actively review feature requests on here and will take this into consideration

I'll close this issue for now as it is captured by #2895

**Closed by DoodleBobBuffPants** 2021-02-22 10:14 UTC
Labels: d: PostgreSQL, s: waiting for feedback

**Comment by fml2** [comment] 2021-02-22 10:22
OK to closing (although the situation and the error message is not the same).
