### ISSUE TITLE
SQL command not properly ended error on 3.2.1

### ISSUE THREAD

**Issue by DhruvDhaka** [flyway/flyway#1022] opened 2015-05-22 05:56 UTC
Hi,

I have an insert query which is failing on 3.2.1 with a string 'seized.lFrom'
The same query worked perfectly fine on 2.3 and 3.0

**Comment by axelfontaine** [comment] 2015-05-23 18:35
Thank for the report. Please include the full query and the type of DB you're using.

Cheers
Axel

**Comment by DhruvDhaka** [comment] 2015-05-25 04:08
Can't provide the actual table and column names.
Hope this helps.

INSERT INTO <table> (numberColumn,varchar2Column,varchar2Column,dateColumn,numberColumn,dateColumn,numberColumn,dateColumn,dateColumn,timestampColumn,timestampColumn,timestampColumn) values (1298,'seized.lFrom','From',null,0,SYSDATE,0,SYSDATE,null,SYSTIMESTAMP,null,null);

**Comment by DhruvDhaka** [comment] 2015-05-25 04:47
The DB version is Oracle 12c (12.1.0.1.0)

**Comment by DhruvDhaka** [comment] 2015-05-26 08:01
Found 2 more issues under same ORA error.

1. update table set varcharCoulmn='[EMPTY]' where numericColumn='1298'and varcharColumn2='abc';
Please note there's no space between single quote (') & and

This throws the same ORA error

2. In case of multiple SQL statements on a single line, it gives the same error.

Please note that all these 3 issues work well from SQLDeveloper and also via PUTTY.

**Comment by DhruvDhaka** [comment] 2015-06-02 14:44
Hi,

Can u please suggest on above issue...

**Comment by DhruvDhaka** [comment] 2015-06-09 04:51
Can someone please update on above concern?

**Comment by DhruvDhaka** [comment] 2015-09-22 08:55
Any idea on when the next release containing fix for above issue would be released?

**Comment by shaun1127** [comment] 2015-09-24 19:24
I have a similar issue. I think it's the word 'From' in your insert. Try making it 'Fr' || 'om'

**Comment by axelfontaine** [comment] 2015-10-28 11:33
Duplicate of #1010

**Closed by axelfontaine** 2015-10-28 11:33 UTC
Labels: s: waiting for feedback
