### ISSUE TITLE
Allow scanning multiple classpaths for migrations

### ISSUE THREAD

**Issue by Idane** [flyway/flyway#3238] opened 2021-07-26 12:25 UTC
###### Which version and edition of Flyway are you using?

7.7.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API (Via Spring Boot)

###### Which database are you using? (Type & version)

MariaDB 10.5.6

###### Which operating system are you using?

N/A

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
N/A

###### What did you expect to see?

N/A

###### What did you see instead?

Our use case is that we have multiple dependent JARs that each have database-enabled features with their own migrations located as .sql files in the JARs. Because Flyway only scans migrations with one class loader, we're only able to load migrations that are in the main project.

For example, let's say the main location is `classpath:com.example.main.db.migration` in JAR 'A'. We have a feature in JAR 'B' that has its migrations in `classpath:com.example.feature.db.migration`.

We are looking for a way to be able to specify locations with their respective class loaders to get around this issue.

**Comment by DoodleBobBuffPants** [comment] 2021-07-27 09:27
Based on the information provided I am unable to reproduce the issue

If both JARs are on the classpath, then all migrations are found with locations set to include `com.example.main.db.migration` and `com.example.feature.db.migration`.
You can also provide your own classloader when using the Java API if you need to.
We also have a fix in progress to disambiguate classloader resources if you're only using the common part of the package name i.e. `db/migration`

Closing until we can get a reproduction

**Closed by DoodleBobBuffPants** 2021-07-27 09:27 UTC
