### ISSUE TITLE
Transactional Lock False not working anymore for PostgreSQL

### ISSUE THREAD

**Issue by AlbertoEE** [flyway/flyway#3684] opened 2023-06-08 15:56 UTC
**Flyway version**: 9.9.13
**Client**: Flyway Docker Image
**Database**: PostgreSQL {latest version}

# Context
When Running this docker-compose if the SQL migration files have CONCURRENT PostgreSQL statements the migration stops forever. Previously it was solved by just adding an ENV Variable like `FLYWAY_POSTGRESQL_TRANSACTIONAL_LOCK=false`. Now it is not working.

Here is the docker-compose:
```
# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres_playground_db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./dumps/${SQL_DUMP_FILE:-/dev/null}:/docker-entrypoint-initdb.d/${SQL_DUMP_FILE}

  flyway:
    image: flyway/flyway
    container_name: flyway_playground
    command: -url=jdbc:postgresql://db/postgres -schemas=public -user=postgres -password=example -connectRetries=60 migrate
    volumes:
      - "${MIGRATION_PATH}:/flyway/sql"
    depends_on:
      - db
    environment:
      - FLYWAY_POSTGRESQL_TRANSACTIONAL_LOCK=false # https://github.com/flyway/flyway/issues/3508#issuecomment-1227173040
```

- Here is a thread that talks about this issue on an older version -> https://github.com/flyway/flyway/issues/3508#issuecomment-1227173040

- Here is the commit and line that I think it's disabling this behavior https://github.com/flyway/flyway/commit/6ea39a77e3568e69a971243ea3f0f74b0f433576#diff-e408768a33833cad4694932eca507b0e2db9c2145defb949442dbf8558ad57c1R27 (line 27 of class `flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLConfigurationExtension.java`)

# Expected behavior
`FLYWAY_POSTGRESQL_TRANSACTIONAL_LOCK=false` should work as in previous versions.

# Actual behavior

Even when adding `FLYWAY_POSTGRESQL_TRANSACTIONAL_LOCK=false` the migration stops when encountering SQL statements like this one `CREATE INDEX CONCURRENTLY ON table USING table_field;`.

**Comment by JasonLuo-Redgate** [comment] 2023-06-15 16:49
Hi @AlbertoEE , as we can see, https://github.com/flyway/flyway/issues/3682 was closed and issued confirmed to be fixed in that ticket.  So would like to confirm with you, we can also close this one?

**Closed** 2023-06-20 16:13 UTC
Labels: s: waiting for feedback

**Comment by mrinalnathtcs** [comment] 2024-02-14 06:04
We are facing this issue with flyway 10.x series 
can someone advice what is the cause and how to fix it ?

**Comment by JasonLuo-Redgate** [comment] 2024-02-14 09:19
Hi @mrinalnathtcs ,
To avoid this issue, two conditions need to be met:

- Flyway 9.19.4 version or higher
- postgresql.transactional.lock set to false
