### ISSUE TITLE
flyway command line option -X does not show update / delete count

### ISSUE THREAD

**Issue by ThiyaguE** [flyway/flyway#1177] opened 2016-01-22 09:33 UTC
![flyway-delete-shows-no-feedback](https://cloud.githubusercontent.com/assets/13992997/12506742/317a382a-c117-11e5-8ddc-54d1590dc806.jpg)

Im using flyway-3.2.1 and -X (debug mode) dont show the update count.

Axel, pls let me know where we need to see this?

**Comment by ThiyaguE** [comment] 2016-01-22 09:41
Axel, I've verified this multiple times, its not showing update counts.. Im using oracle.

**Comment by ThiyaguE** [comment] 2016-01-22 09:47
As seen in image, delete stmt @ line #1 should delete 32 rows. it dont show any update/delete count.

**Comment by axelfontaine** [comment] 2016-01-22 10:37
Duplicate of #1174 - please see my comments there on comment on that issue instead of opening new ones for the same problem

**Closed by axelfontaine** 2016-01-22 10:37 UTC
