### ISSUE TITLE
Repeatable migration hash needs to be unique (in the history of particular migration) to be applied

### ISSUE THREAD

**Issue by vovcacik** [flyway/flyway#1449] opened 2016-10-07 14:52 UTC
###### What version of Flyway are you using?

4.0.3
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

org.flywaydb:flyway-maven-plugin:4.0.3
###### What database are you using (type & version)?

PostgreSQL 9.3
###### What operating system are you using?

Windows 10
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
- setup test table

```
CREATE TABLE test (
  id smallserial NOT NULL,
  value text
);
```
- create test repeatable migration _r__testMigration.sql_ (I configured lowercase prefixes)

```
DELETE FROM test;
INSERT INTO test (id, value) VALUES (1, 'v1');
```
- run it
  `mvn flyway:migrate`

```
[INFO] --- flyway-maven-plugin:4.0.3:migrate (default-cli) @ app ---
[INFO] Flyway 4.0.3 by Boxfuse
[INFO] Database: jdbc:postgresql://app-db:5432/app (PostgreSQL 9.3)
[INFO] Successfully validated 80 migrations (execution time 00:01.379s)
[INFO] Current version of schema "public": 2016.10.07
[INFO] Migrating schema "public" with repeatable migration testMigration
[INFO] Successfully applied 1 migration to schema "public" (execution time 00:00.108s).
```

Values in db: `1;"v1"` (expected)
- edit the _r__testMigration.sql_ and rerun

```
DELETE FROM test;
INSERT INTO test (id, value) VALUES (1, 'v2');
```

```
[INFO] --- flyway-maven-plugin:4.0.3:migrate (default-cli) @ app ---
[INFO] Flyway 4.0.3 by Boxfuse
[INFO] Database: jdbc:postgresql://app-db:5432/app (PostgreSQL 9.3)
[INFO] Successfully validated 81 migrations (execution time 00:00.897s)
[INFO] Current version of schema "public": 2016.10.07
[INFO] Migrating schema "public" with repeatable migration testMigration
[INFO] Successfully applied 1 migration to schema "public" (execution time 00:00.091s).
```

Values in db: `1;"v2"` (expected)
- revert the _r__testMigration.sql_ and rerun

```
DELETE FROM test;
INSERT INTO test (id, value) VALUES (1, 'v1');
```

```
[INFO] --- flyway-maven-plugin:4.0.3:migrate (default-cli) @ app ---
[INFO] Flyway 4.0.3 by Boxfuse
[INFO] Database: jdbc:postgresql://app-db:5432/app (PostgreSQL 9.3)
[INFO] Successfully validated 81 migrations (execution time 00:00.649s)
[INFO] Current version of schema "public": 2016.10.07
[INFO] Schema "public" is up to date. No migration necessary.
```

**Values in db: `1;"v2"`** (unexpected)
###### What did you expect to see?

I expected the flyway to apply the migration. It didn't happen, so I didn't see the expected **values in db: `1;"v1"`**.
###### What did you see instead?

**Values in db: `1;"v2"`**

---

I tried to run single repeatable migration 3 times on a test database. First two runs were fine. The third run didn't apply any changes, because the hash of the migration at that time was the same with hash of the same migration from first run. I would expect flyway to apply any repeatable migration which does not match tha hash from last run.

**Comment by alkamo** [comment] 2016-11-30 23:01
This appears to be functionally equivalent to #1358.

**Comment by vovcacik** [comment] 2016-12-02 16:18
@alkamo Yes, it is. Missed that one.

**Comment by axelfontaine** [comment] 2017-01-31 10:15
Duplicate of #1358

**Closed by axelfontaine** 2017-01-31 10:15 UTC
Labels: c: migrate(), m: Core, t: bug
