### ISSUE TITLE
flyway command line option -X does not show insert / update / delete counts.

### ISSUE THREAD

**Issue by ThiyaguE** [flyway/flyway#1179] opened 2016-01-24 19:06 UTC
This is one of the show stopper for us to implement on many of our enterprise level critical app.

As it does for failed migrations ( stmt executions), Flyway needs to provide feedback , like, # of rows updated/inserted/deleted even 

successful stmt executions for verification by developers. This will help developers to check their DMLs exactly executed as they wanted. Also 

flyway could provide way for returning result set for 'select' Queries and 'dbms_output' procedure output.

-- flywaytest db is running on 10.2.3.42 host with oracle 11g
-- as SAMPLE user create a test table.

create table employees ( i int, name varchar2(10), instime date);

-- sample file has 1 create stmt, 3 insert stmts, 2 update stmts , 1 delete stmts

insert into employees values (1, 'test1', sysdate);
insert into employees values (2, 'test2', sysdate);
insert into employees values (3, 'test3', sysdate);

commit;

update employees set i=4 where name='test3';
update employees set 1=5 where name='test1';

commit;

delete from employees where i=2;

commit;

-- using command line option with oracle 11g
--flyway conf file. flywaytest db is running on 10.2.3.42.

admin$ cat conf/flyway.conf
flyway.url=jdbc:oracle:thin:@//10.2.3.42:1800/flywaytest
flyway.user=SAMPLE
flyway.password=ampletest
flyway.sqlMigrationPrefix=1215
flyway.sqlMigrationSuffix=.sql

-- do flyway baseline w/ default version and discription
admin$ ./flyway baseline

admin$ ./flyway -X migrate

<<< debug mode output wont show # rows inserted / updated / deleted. >>>

from attached image, we can see there are 3 insert, 2 update and 1 delete stmts successfully executed. But flyway doesn't show # rows 
inserted/updated/deleted even we have commit in between.

![flyway-dml-shows-norowcount](https://cloud.githubusercontent.com/assets/13992997/12538202/fe2ec1ea-c2f9-11e5-8ed8-dc758d33693a.jpg)

**Comment by axelfontaine** [comment] 2016-01-24 21:35
Duplicate of #1174

**Closed by axelfontaine** 2016-01-24 21:35 UTC
