### ISSUE TITLE
Migration of multiple Oracle schemas doesn't work. Only first schema from the list is updated.

### ISSUE THREAD

**Issue by dmitrypodshivalov** [flyway/flyway#1834] opened 2017-11-20 00:38 UTC
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
Oracle DB, 12.1

###### What operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I have many identical schemas within one Oracle DB instance. They all have the same structure and should be updated simultaneously. I defined flyway.schemas in configuration file as:
flyway.schemas=schema1,schema2

and executed 
./flyway migrate

###### What did you expect to see?
I was hoping that both schema1 and schema2 will be updated to the latest schema version,

###### What did you see instead?
Only schema 1 was updated after migraiton.

./flyway migrate
Flyway 4.2.0 by Boxfuse

Database: jdbc:oracle:thin:@//IP:1521/SID (Oracle 12.1)
Successfully validated 1 migration (execution time 00:00.013s)
Creating Metadata table: "schema1"."schema_version"
Current version of schema "schema1": << Empty Schema >>
Migrating schema "schema1" to version 1 - Customers
Successfully applied 1 migration to schema "schema1" (execution time 00:00.178s).

However the clean command: 
flyway clean 
purged data from both schemas. 
./flyway clean
Flyway 4.2.0 by Boxfuse

Database: jdbc:oracle:thin:@//IP:1521/SID (Oracle 12.1)
Successfully cleaned schema "schema1" (execution time 00:00.383s)
Successfully cleaned schema "schema2" (execution time 00:00.350s)

**Comment by axelfontaine** [comment] 2017-11-20 09:26
Duplicate of #1039

**Closed by axelfontaine** 2017-11-20 09:26 UTC
