### ISSUE TITLE
afterMigrate.sql callback runned twice in versions higher than 4.0.3.

### ISSUE THREAD

**Issue by ledj0304** [flyway/flyway#1653] opened 2017-05-29 23:05 UTC
###### What version of Flyway are you using?
3.2.1 - 4.0.3 - 4.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Gradle 3.4, SpringBoot 1.5.2

###### What database are you using (type & version)?
Mysql 5.1.38 connector

###### What operating system are you using?
Ubuntu 16.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Running SpringBoot \@DataJpaTest test with the following configuration:
`public class DatasourceConfig {
    
    @Bean
    @Profile("integration")
    FlywayMigrationStrategy integrationMigrationStrategy() {
        System.out.println("Setting Flyway integration strategy");
        FlywayMigrationStrategy strategy = new FlywayMigrationStrategy() {
            @Override
            public void migrate(Flyway flyway) {
                flyway.setLocations("/data/integration/migrations");
                flyway.clean();
                flyway.migrate();
            }
        };
        return strategy;
    }
}`

Where the said location contains:
V0.0.1__initialize.sql  -> DDL creating the schema
afterMigrate.sql          -> DML loading data in the created schema

###### What did you expect to see?
When I run a single test, I expect that the database schema is recreated and the data loaded before the tests executes.

###### What did you see instead?
The schema is recreated but the afterMigrate.sql callback  is runned twice by any Flyway versions higher than 4.0.3. This, of course, results in duplicates in the database and the test fails. Conversely, 4.0.3 and 3.2.1 work just fine.

![image](https://cloud.githubusercontent.com/assets/6115545/26563454/5656e5ea-44a0-11e7-9a71-d0a439890118.png)
Normal operation in 4.0.3

![image](https://cloud.githubusercontent.com/assets/6115545/26563500/efbe6f32-44a0-11e7-8fd9-68a928899cdf.png)
afterMigration double run in 4.2.0

**Comment by axelfontaine** [comment] 2017-11-27 10:37
I can't seem to reproduce this. Can you share a small test repo that triggers this?

**Comment by axelfontaine** [comment] 2017-11-27 10:46
Duplicate of #1625

**Closed by axelfontaine** 2017-11-27 10:46 UTC
Labels: s: waiting for feedback, t: bug
