### ISSUE TITLE
java.lang.ClassNotFoundException: oracle.jdbc.OracleDriver on v4.1.1, works fine with v4.1.0/v.3.2.1

### ISSUE THREAD

**Issue by gavenkoa** [flyway/flyway#1546] opened 2017-03-06 07:31 UTC
With  v4.1.1:

    $ gradle flywayMigrate --stacktrace

    Caused by: org.flywaydb.core.api.FlywayException: Unable to instantiate JDBC driver oracle.jdbc.OracleDriver : oracle.jdbc.OracleDriver
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.<init>(DriverDataSource.java:108)
	at org.flywaydb.core.Flyway.configure(Flyway.java:1191)
	at org.flywaydb.gradle.task.AbstractFlywayTask.createFlyway(AbstractFlywayTask.java:371)
	at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.java:295)
	... 77 more
    Caused by: java.lang.ClassNotFoundException: oracle.jdbc.OracleDriver
	at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:59)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.<init>(DriverDataSource.java:104)
	... 80 more

Works fine with v4.1.0/v.3.2.1 and same `build.gradle`:

    buildscript {
        dependencies {
            classpath 'com.oracle:ojdbc6:11.2.0.3'
        }
    }

    plugins {
        // 4.1.1 - java.lang.ClassNotFoundException: oracle.jdbc.OracleDriver
        // 3.2.1
        id "org.flywaydb.flyway" version "4.1.0"
    }

    flyway {
        url = 'jdbc:oracle:thin:@localhost:1521'
        user = 'XXX'
        password = 'YYY'
        schemas = ['ZZZ']
        locations = ['filesystem:src/main/resources/db/migration/oracle']
    }

**Comment by gavenkoa** [comment] 2017-03-06 07:32
It can be due to recent fix: https://github.com/flyway/flyway/issues/1527

**Comment by axelfontaine** [comment] 2017-03-06 10:05
Duplicate of #1539

**Closed by axelfontaine** 2017-03-06 10:05 UTC
