### ISSUE TITLE
Flyway only reads the script config file for the first script in the chain. 

### ISSUE THREAD

**Issue by TonytheEditor** [flyway/flyway#3107] opened 2021-03-12 14:17 UTC
###### Which version and edition of Flyway are you using?
Community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command line

###### Which database are you using? (Type & version)
SQL Server 2019

###### Which operating system are you using?
Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
tried to do a migration run where several of the migrations scripts had an associated config file

###### What did you expect to see?
Flyway reads config for each script

###### What did you see instead?
Flyway only reads the script config file for the first one in the chain. If a script later in the chain has a config file it just ignores it, which causes the whole migration run to blow up. You have to restart flyway and now that the later script is the first in the chain, it reads its config file

**Comment by DoodleBobBuffPants** [comment] 2021-03-12 14:23
Could you provide a reproduction and example of the error you are seeing?

**Comment by TonytheEditor** [comment] 2021-03-12 15:02
Flyway doesn't throw an error, it just ignores all but the first one. And then yes that likely causes an error due to failing to read the instruction the config - but the error 'depends' on what it was that was ignored

**Comment by DoodleBobBuffPants** [comment] 2021-03-12 15:10
I'm not able to reproduce any behavior that indicates script config files are being ignored. Could you provide a reproduction along with what you expect to happen and what is actually happening?

**Comment by DoodleBobBuffPants** [comment] 2021-03-17 10:53
Closing until we can get a reproduction

**Closed by DoodleBobBuffPants** 2021-03-17 10:53 UTC
Labels: s: waiting for feedback
