### ISSUE TITLE
Migration of wrapped package with PLS-00753

### ISSUE THREAD

**Issue by pviltard** [flyway/flyway#3376] opened 2022-01-13 18:30 UTC
###### Which version and edition of Flyway are you using?
flyway is a Community Edition 8.4.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I was in version Community Edition 7.9.1. I upgraded the version  to 8.4.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Oracle 18xe

Hi,

I have some troubles with wrapped package.
My Oracle version is 18XE on Windows
flyway is a Community Edition 8.4.1
and java is 11.0.12 "2021-07-20 LTS"

I see the #3032 issue.
I have also seen MOS  Oracle support, without great success 

The configuration file is :
flyway.url=jdbc:oracle:thin:@//localhost:1521/XEMC3
flyway.user=MXXXXXXXX
flyway.password=MZZZZ
flyway.locations=filesystem:C:\SharedFolder\Development\ORACLE\mc3production\flywaySql
flyway.encoding=UTF-8

But with this example file (https://docs.oracle.com/cd/B10500_01/appdev.920/a96624/c_wrap.htm)
CREATE OR REPLACE PACKAGE
-- Author: J. Hollings
-- Date: 10/15/99
banking AS
minimum_balance CONSTANT REAL := 25.00;
insufficient_funds EXCEPTION;
END banking;

Toad's wrap produce :
CREATE OR REPLACE PACKAGE
-- Author: J. Hollings
-- Date: 10/15/99
banking wrapped
a000000
b2
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
9
6c ae
0Na/K8ZdCZiYRGh86kyoKaiP9OMwg5SXf57WZy9EUHdBBk/KWsoup46GV9XWuerCmMjc4Lbm
3ficBgqaZnuXcLQi+LXEqqi++8huQSej2lhGJ1BYvueZhxu2HK5oubFhshcyi6uMCv3Zq9X4
dBIKYpUXQNS0jLZK/6hxyxSndtU=

/

Sqlplus works fine.

I place it into a file, runs flyway -configFiles=.\configuration\oracle_mc3production.conf migrate into a batch windows file. Flyway reports an error : warning 99999 Error 17110. Compilation of the package fails.
The line is well inserts into the table flyway_schema_history

But the package is : pls-00753 malformed or corrupted wrapped unit
Oracle recommends using wrap iname=djfhjh.pks, get the plb file but still the same error. Under sqlplus without any problems.

With the command wrap (18xE) we have this
CREATE OR REPLACE PACKAGE
-- Author: J. Hollings
-- Date: 10/15/99
banking wrapped
a000000
b2
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
9
6c ae
0Na/K8ZdCZiYRGh86kyoKaiP9OMwg5SXf57WZy9EUHdBBk/KWsoup46GV9XWuerCmMjc4Lbm
3ficBgqaZnuXcLQi+LXEqqi++8huQSej2lhGJ1BYvueZhxu2HK5oubFhshcyi6uMCv3Zq9X4
dBIKYpUXQNS0jLZK/6hxyxSndtU=

/

But still the same others
In different forums solutions are proposed but the result is identical.

Pascal

###### Which operating system are you using?
Windows 2012

**Comment by DoodleBobBuffPants** [comment] 2022-01-24 11:01
We are unable to reproduce this issue - the wrapped SQL parses and executes without error

Could you provide a minimal reproduction project?

**Comment by pviltard** [comment] 2022-01-26 09:36
yes just above the header banking package.
Pascal

**Comment by DoodleBobBuffPants** [comment] 2022-01-26 12:21
Based on your description of the problem we are unable to reproduce this

Could you upload or link to a Flyway project that reproduces this?

**Comment by pviltard** [comment] 2022-01-27 10:11
![image](https://user-images.githubusercontent.com/6979133/151337698-f3d2211f-a2dd-4d3c-9175-3c1e3ae0ddfb.png)
![image](https://user-images.githubusercontent.com/6979133/151337905-ffa199f9-2ce7-4e41-90cd-f4308005d0b7.png)
[V2.0.211__Banking.sql.txt](https://github.com/flyway/flyway/files/7949500/V2.0.211__Banking.sql.txt)
![image](https://user-images.githubusercontent.com/6979133/151338181-75cd4887-6e54-4a76-b623-73561d15e52c.png)

**Comment by pviltard** [comment] 2022-01-27 10:18
With sqlplus the result is good :
![image](https://user-images.githubusercontent.com/6979133/151339138-4e10307c-e151-4ccc-b8f9-06d998f88ab6.png)

thanks for your help
Pascal

**Comment by DoodleBobBuffPants** [comment] 2022-01-27 10:20
Your output shows you are using version 7.5.3

Could you try using the latest version, as there have been fixes to our handling of wrapped SQL since then

**Comment by pviltard** [comment] 2022-01-27 10:39
![image](https://user-images.githubusercontent.com/6979133/151342140-48a666b6-fbf8-4544-8561-7c9ceafa7cc5.png)
![image](https://user-images.githubusercontent.com/6979133/151342334-dace156c-0b93-4c8a-b9fa-2b29d0954577.png)
![image](https://user-images.githubusercontent.com/6979133/151342436-268e2b0f-f61e-4e46-bd97-f6cdca55dfed.png)

Taking a higher version  , the problem is the same

Pascal

**Comment by DoodleBobBuffPants** [comment] 2022-01-27 11:09
Could you upload the migration you are executing? The SQL you shared does not appear to reproduce this issue

**Comment by pviltard** [comment] 2022-01-27 13:50
[cmdmigrate.bat.txt](https://github.com/flyway/flyway/files/7950884/cmdmigrate.bat.txt)
[oracle_mc3production.conf.txt](https://github.com/flyway/flyway/files/7950887/oracle_mc3production.conf.txt)

not here on Friday.

Thank you for your availability
Pascal

**Comment by pviltard** [comment] 2022-01-27 14:12
[V2.0.211__Banking.sql.txt](https://github.com/flyway/flyway/files/7951074/V2.0.211__Banking.sql.txt)

**Comment by DoodleBobBuffPants** [comment] 2022-01-28 12:33
Thanks for sharing

I have reproduced this issue with the SQL you provided against Oracle 18

Running this against Oracle 19(.3) however does not produce an issue, and I can confirm we parse the SQL correctly so Flyway doesn't malform anything

The following from the documentation sticks out:
`The Wrap Utility is upward-compatible with Oracle. So, for example, you can load files processed by the V8.1.5 Wrap Utility into a V8.1.6 Oracle database. However, the Wrap Utility is not downward-compatible with Oracle. So, for example, you cannot load files processed by the V8.1.6 Wrap Utility into a V8.1.5 Oracle database.`

Could you confirm the version of the wrapping utility you are using?

**Comment by pviltard** [comment] 2022-01-31 14:41
Hello,

I make a dos batch file to produce the wrapped package and call the flyway migration.
See the files and the result.
[cmdmigbanking.bat.txt](https://github.com/flyway/flyway/files/7971572/cmdmigbanking.bat.txt)
[migwrap.log.txt](https://github.com/flyway/flyway/files/7971574/migwrap.log.txt)
[banking.pks.txt](https://github.com/flyway/flyway/files/7971576/banking.pks.txt)
[V2.0.211__Banking.sql.txt](https://github.com/flyway/flyway/files/7971580/V2.0.211__Banking.sql.txt)

Same issue.

Have a nice day.

Pascal

**Comment by pviltard** [comment] 2022-01-31 14:43
Same configuration flyway.

[oracle_mc3production.conf.txt](https://github.com/flyway/flyway/files/7971602/oracle_mc3production.conf.txt)

Pascal

**Comment by DoodleBobBuffPants** [comment] 2022-01-31 15:01
This doesn't confirm the version of the wrapping utility used, can you provide the version of the wrap tool used

As we are unable to progress on this issue, I will be closing it unless we are able to get a reproduction of an issue in Flyway

**Closed by DoodleBobBuffPants** 2022-01-31 15:01 UTC
Labels: s: waiting for feedback
