### ISSUE TITLE
SQL command not properly ended

### ISSUE THREAD

**Issue by hamdiatacanogul** [flyway/flyway#1074] opened 2015-08-07 11:22 UTC
Hi,
When I migrate the following statement by Flyway, Flyway gives an error that is "ORA-00933: SQL command not properly ended". I think cause of problem is "from" word of value. I use Oracle 12c db.

Could you help me? Thanks.

Insert into GVPP_TRUNK_DEV.AD_COLS (TABLE_NAME,COLUMN_NAME,FRIENDLY_NAME,C3_DATA_TYPE) values ('om_regtime','from_ts1','Collect Start Time','Time');

**Comment by axelfontaine** [comment] 2015-10-28 11:40
Duplicate of #1036

**Closed by axelfontaine** 2015-10-28 11:40 UTC
