### ISSUE TITLE
PostgreSQL 11.0 is not supported (clean() fails)

### ISSUE THREAD

**Issue by tinybarks** [flyway/flyway#2193] opened 2018-11-04 15:38 UTC
###### Which version and edition of Flyway are you using?

Flyway Community Edition 5.2.1.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API. Bug most likely affects all versions.

###### Which database are you using (type & version)?

PostgreSQL 11.0 (released 18 October 2018).

Unsurprisingly, Flyway reports that it does not support this version yet: `Flyway upgrade recommended: PostgreSQL 11.0 is newer than this version of Flyway and support has not been tested.`

###### Which operating system are you using?

Not relevant.

###### What did you do?

I attempted to clean a configured schema using the `Flyway.clean()` method. The `Flyway` instance can connect fine and `Flyway.migrate()` appears to work successfully. 

###### What did you expect to see?

The schema is cleaned in the database and `Flyway.clean()` doss not throw an exception.

###### What did you see instead?

The database does not appear to be modified. `Flyway.clean()` throws a `FlywaySqlException`:

```
org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to clean schema "public"
-------------------------------
SQL State  : 42703
Error Code : 0
Message    : ERROR: column pg_proc.proisagg does not exist
  Hint: Perhaps you meant to reference the column "pg_proc.prolang".
  Position: 54

      at org.flywaydb.core.internal.database.base.Schema.clean(Schema.java:151)
      at org.flywaydb.core.internal.command.DbClean$3.call(DbClean.java:172)
      at org.flywaydb.core.internal.command.DbClean$3.call(DbClean.java:169)
      at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
      at org.flywaydb.core.internal.command.DbClean.cleanSchema(DbClean.java:169)
      at org.flywaydb.core.internal.command.DbClean.clean(DbClean.java:113)
      at org.flywaydb.core.Flyway.doClean(Flyway.java:1473)
      at org.flywaydb.core.Flyway.access$300(Flyway.java:82)
      at org.flywaydb.core.Flyway$3.execute(Flyway.java:1491)
      at org.flywaydb.core.Flyway$3.execute(Flyway.java:1484)
      at org.flywaydb.core.Flyway.execute(Flyway.java:1696)
      at org.flywaydb.core.Flyway.clean(Flyway.java:1484)
```

###### Notes

PostgreSQL 11.0's [release notes](https://www.postgresql.org/docs/11/static/release-11.html) state the following:

> Replace system catalog pg_proc's proisagg and proiswindow columns with prokind (Peter Eisentraut)
>
> This new column more clearly distinguishes functions, procedures, aggregates, and window functions.

I believe the offending line of code can be found [here](https://github.com/flyway/flyway/blob/e3c9adaac18f46017ad524cbe0df26d13ab33c00/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLSchema.java#L191). The docs for the new `prokind` field are [here](https://www.postgresql.org/docs/11/static/catalog-pg-proc.html). Fixing this will require the query to be made dependent on the version of PostgreSQL somehow.

I will submit a PR to fix this issue.

**Comment by axelfontaine** [comment] 2018-11-05 16:17
Duplicate of #2178

**Closed by axelfontaine** 2018-11-05 16:17 UTC

**Comment by gavares** [comment] 2018-12-26 23:01
@axelfontaine I don't believe this is a duplicate of #2178. This issue indicates that an error message is printed when using flyway 5.2.4 to connect to Postgres 11.1. Ticket #2178 is related to a failing `clean()` operation against Postgres 11.0. 

I'm also seeing this error message printed when using flyway 5.2.4 to connect to a Postgres 11.1 database and the clean operation I'm attempting to run against that database is also failing with the error message listed above.

**Comment by brunobastosg** [comment] 2019-01-14 17:14
@gavares, I believe the fix will be available in version 6.0.0.

**Comment by rodrix** [comment] 2019-01-22 12:44
Same here. Any workaround? :}

**Comment by binakot** [comment] 2019-03-09 13:33
Same problem on `5.2.4`, downgrade to `Postgres 10` helps. 
I tried to switch to `6.0.0-beta`, it causes the fail on Application context loading.

**Comment by axelfontaine** [comment] 2019-03-11 12:40
@binakot Please file any issue you may have with 6.0.0-beta as a separate issue
