### ISSUE TITLE
Seek for suggestions about Business/Application Data

### ISSUE THREAD

**Issue by jack2gs** [flyway/flyway#3471] opened 2022-06-22 05:20 UTC
Hi,

In this artical, it suggests not to store the business/application data as script: https://dzone.com/articles/continuous-integration-and-continuous-delivery-for-2.
Is there any best practice to handle Business/Application Data with flyway? For example, there's a table named person with columns:
id=>int, primary key
name=>string.

there's one record (1, 'jack') and we want to update the name to be 'Jack'. the sql script'd be like this
`update public.person set name='Jack' where id=1`. but it might have several environments and the id'd be different between them. what's the right way to handle this kind of operations to bussiness/appliction data?

Thanks,
Jack

**Comment by DoodleBobBuffPants** [comment] 2022-10-20 15:43
This scenario is ultimately outside the scope of Flyway

Flyway is about your schema and can also be used with static data. Dynamic data doesn't fit into the current process since your migrations aren't always going to be reproducible

If this data is static, you can fix this with a new migration. If not, then it's outside the scope of Flyway

I'll be closing this for now, but at the same time, if you have any thoughts or suggestions about how Flyway could deal with these scenarios we'd love to hear it!

**Closed by DoodleBobBuffPants** 2022-10-20 15:43 UTC
