### ISSUE TITLE
Unable to parse statement with TRAN keyword

### ISSUE THREAD

**Issue by dbonetti** [flyway/flyway#2968] opened 2020-10-07 09:47 UTC
###### Which version and edition of Flyway are you using?
Flyway Community Edition 7.0.0 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-Line

###### Which database are you using (type & version)?
MS SQL SERVER 15.0.40.331 linux

###### Which operating system are you using?
Windows 10 hosting linux docker container

###### What did you do?
I'm trying to migrate a database with flyway migrate command
with version 6.0.8 it works
with version 7.0.0 it doesn't

###### What did you expect to see?
The migration applied correctly

###### What did you see instead?
we received the error "ERROR: Unable to parse statement "

it seems that the keyword TRAN instead of the keyword TRANSACTION is not recognized by the parser

**Comment by DoodleBobBuffPants** [comment] 2020-10-07 09:49
Duplicate of https://github.com/flyway/flyway/issues/2961

**Closed by DoodleBobBuffPants** 2020-10-07 09:49 UTC
