### ISSUE TITLE
ERROR: null value in column "version_rank" violates not-null constraint

### ISSUE THREAD

**Issue by boha11oran** [flyway/flyway#1954] opened 2018-03-13 21:03 UTC
###### Which version and edition of Flyway are you using?

Flyway Trial Edition 5.0.7 by Boxfuse

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
On client MACOS
BOS1002962L:flyway bohalloran$ uname -a
Darwin BOS1002962L 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
BOS1002962L:flyway bohalloran$ 

###### Which database are you using (type & version)?

PostgreSQL 9.6.3

###### Which operating system are you using?

On server
CentOS Linux release 7.3.1611 (Core)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

BOS1002962L:flyway bohalloran$ ./flyway migrate -url=jdbc:postgresql://xxx.chewy.com:5432/denver -X
Flyway Trial Edition 5.0.7 by Boxfuse
WARNING: You are using the 30 day limited Flyway Trial Edition. After 30 days you must remove this version and either upgrade to Flyway Pro Edition or Flyway Enterprise Edition or downgrade to Flyway Community Edition.

DEBUG: Java 1.8.0_161 (Oracle Corporation)
DEBUG: Mac OS X 10.13.3 x86_64

DEBUG: Loading config file: /Users/bohalloran/flyway/conf/flyway.conf
DEBUG: Unable to load config file: /Users/bohalloran/flyway.conf
DEBUG: Unable to load config file: /Users/bohalloran/flyway/flyway.conf
Database password: 
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /Users/bohalloran/flyway/jars
DEBUG: flyway.password -> ************
DEBUG: flyway.url -> jdbc:postgresql://xxx.chewy.com:5432/denver
DEBUG: flyway.mixed -> true
DEBUG: flyway.table -> schema_version
DEBUG: flyway.baselineOnMigrate -> true
DEBUG: flyway.user -> bohalloran
...
...
...
ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to insert row for version '5.76.1' in Schema History table "public"."schema_version"
-------------------------------------------------------------------------------------------
SQL State  : 23502
Error Code : 0
Message    : ERROR: null value in column "version_rank" violates not-null constraint
  Detail: Failing row contains (null, 6, 5.76.1, BulkUpload, SQL, V5.76.1__BulkUpload.sql, 1948231375, bohalloran, 2018-03-13 16:56:30.493919, 239, t).

	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.doAddAppliedMigration(JdbcTableSchemaHistory.java:171)
	at org.flywaydb.core.internal.schemahistory.SchemaHistory.addAppliedMigration(SchemaHistory.java:146)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:378)
	at org.flywaydb.core.internal.command.DbMigrate.access$400(DbMigrate.java:52)
	at org.flywaydb.core.internal.command.DbMigrate$5.call(DbMigrate.java:297)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:294)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:259)
	at org.flywaydb.core.internal.command.DbMigrate.access$300(DbMigrate.java:52)
	at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:179)
	at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:176)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:71)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:110)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:148)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:176)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:145)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1206)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1168)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1655)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1168)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:161)
	at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "version_rank" violates not-null constraint
  Detail: Failing row contains (null, 6, 5.76.1, BulkUpload, SQL, V5.76.1__BulkUpload.sql, 1948231375, bohalloran, 2018-03-13 16:56:30.493919, 239, t).
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at org.flywaydb.core.internal.util.jdbc.JdbcTemplate.update(JdbcTemplate.java:334)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.doAddAppliedMigration(JdbcTableSchemaHistory.java:165)
	... 21 more
BOS1002962L:flyway bohalloran$ 

###### What did you expect to see?
Migration success and schema_version add new row for '5.76.1'

###### What did you see instead?
ERROR: null value in column "version_rank" violates not-null constraint

**Comment by axelfontaine** [comment] 2018-03-14 08:19
Duplicate of #1925

**Closed by axelfontaine** 2018-03-14 08:19 UTC
