### ISSUE TITLE
ERROR: Unable to release PostgreSQL advisory lock

### ISSUE THREAD

**Issue by rohityadav225** [flyway/flyway#3167] opened 2021-05-10 22:53 UTC
###### Which version and edition of Flyway are you using?

Flyway Community Edition 7.8.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)

PostgreSQL 11.11

###### Which operating system are you using?
macOS Big Sur 11.3.1

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Tried running flyway migration using command line option
```/usr/local/bin/flyway -user=postgres -password=password -url=jdbc:postgresql://localhost:5432/mydb -locations=filesystem:/Users/myuser/flyway/app,filesystem:/Users/myuser/flyway/appconfig/**/* -cleanDisabled=true migrate info```

###### What did you expect to see?

Migration to succeed

###### What did you see instead?
Flyway error
```
ERROR: Unable to rollback transaction
org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:877)
        at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:884)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:82)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:261)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:234)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:140)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:69)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:140)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:100)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:214)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
        at org.flywaydb.core.Flyway.execute(Flyway.java:569)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:223)
        at org.flywaydb.commandline.Main.main(Main.java:148)
ERROR: Unable to restore autocommit to original value for connection
org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:877)
        at org.postgresql.jdbc.PgConnection.setAutoCommit(PgConnection.java:806)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:97)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:261)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:234)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:140)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:69)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:140)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:100)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:214)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
        at org.flywaydb.core.Flyway.execute(Flyway.java:569)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:223)
        at org.flywaydb.commandline.Main.main(Main.java:148)
ERROR: Migration of schema "public" with repeatable migration "labels" failed! Changes successfully rolled back.
ERROR: Unable to release PostgreSQL advisory lock
org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:877)
        at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1735)
        at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:428)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:344)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForBoolean(JdbcTemplate.java:170)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.unlock(PostgreSQLAdvisoryLockTemplate.java:101)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:80)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:140)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:100)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:214)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
        at org.flywaydb.core.Flyway.execute(Flyway.java:569)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:223)
        at org.flywaydb.commandline.Main.main(Main.java:148)
```

**Comment by DoodleBobBuffPants** [comment] 2021-05-12 08:16
You need to specify that `tcpKeepAlive` is enabled in the URL - you can see an example of this in #3080 with the URL parameters:
`?socketTimeout=0&tcpKeepAlive=true&options=-c%20statement_timeout=1h'`

The numbers used in the solution to #3080 were specific to that issue, so lower numbers may be required in your case
```
net.ipv4.tcp_keepalive_time=240   //lower this
net.ipv4.tcp_keepalive_intvl=60   //lower this
```

**Comment by rohityadav225** [comment] 2021-05-12 23:00
I updated flyway command and also lowered the numbers but i still get same error

``` /usr/local/bin/flyway -user=postgres -password=password -url=jdbc:postgresql://localhost:5432/mydb?socketTimeout=0&tcpKeepAlive=true&options=-c%20statement_timeout=1h -locations=filesystem:/Users/myuser/flyway/app,filesystem:/Users/myuser/flyway/appconfig/**/* -cleanDisabled=true migrate info```


```
sysctl net.inet.tcp | grep -E "keepidle|keepintvl|keepcnt"
net.inet.tcp.keepidle: 10000
net.inet.tcp.keepintvl: 10000
net.inet.tcp.keepcnt: 8
```

**Comment by DoodleBobBuffPants** [comment] 2021-05-13 09:37
Are you able to provide a reproduction? Could you also try the Flyway docker image, to confirm that this is actually the cause of the issue

**Comment by rohityadav225** [comment] 2021-05-14 03:56
how can i use flyway docker image to connect to my local database and run scripts from my local ?

**Comment by DoodleBobBuffPants** [comment] 2021-05-14 08:32
Instructions for using the docker image can be found [here](https://github.com/flyway/flyway-docker#official-flyway-docker-images)

To connect to a database on the host, set `localhost` in the URL to `host.docker.internal` or use port mapping. More information is [here](https://docs.docker.com/docker-for-mac/networking/)

**Comment by rohityadav225** [comment] 2021-05-16 05:52
I tried running using the docker image, i used the following command
```docker run --rm -v /Users/myuser/flyway:/flyway/sql flyway/flyway -user=postgres -password=password -url=jdbc:postgresql://host.docker.internal:5432/mydb migrate info -ignoreMissingMigrations=true -locations=filesystem:/Users/myuser/flyway/app,filesystem:/Users/myuser/flyway/appconfig/**/*```

but i get the error 
``` no matches found: -locations=filesystem:/Users/myuser/flyway/app,filesystem:/Users/myuser/flyway/appconfig/**/*```

Please let me know how to pass the locations when SQL files are divided into multiple nested directories.

**Comment by DoodleBobBuffPants** [comment] 2021-05-17 09:00
Your `locations` need to be correct for the docker container - you need to replace `/Users/myuser/flyway` with `/flyway/sql`

**Comment by rohityadav225** [comment] 2021-05-17 23:27
Thanks. I am able to run flyway migrations using docker image, so i think this is limited to macOS Big Sur ?

**Comment by DoodleBobBuffPants** [comment] 2021-05-18 09:25
Yes. It might be that `tcpkeepalive` isn't being used for the connection. See [this](https://stackoverflow.com/a/23900051) which suggests that you need to enable it per socket, or set `net.inet.tcp.always_keepalive` to `1`

Closing as there isn't any action for Flyway to take

**Closed by DoodleBobBuffPants** 2021-05-18 09:25 UTC
Labels: s: waiting for feedback
