### ISSUE TITLE
Classpath not correctly set up

### ISSUE THREAD

**Issue by mschirmacher** [flyway/flyway#2736] opened 2020-03-23 11:13 UTC
###### Which version and edition of Flyway are you using?
6.3.1 Community Edition

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using (type & version)?
Postgresql 10.5 from testcontainers

###### Which operating system are you using?
Linux, gradle-5.6.4

###### What did you do?
Executed grdale task `flywayMigrate` from https://github.com/mschirmacher/generateJooqFromTestContainers/blob/flywayBug/build.gradle.kts

###### What did you expect to see?
An error indicating there are no migrations (not yet ;-))

###### What did you see instead?

An error from testcontainers "Database name postgresql not supported" and is thrown here
https://github.com/testcontainers/testcontainers-java/blob/43a76abb5d27f322a6a7a30ffc148beb31cd5736/modules/jdbc/src/main/java/org/testcontainers/jdbc/ContainerDatabaseDriver.java#L101

TestContainers is trying to load an implementation of `JdbcDatabaseContainerProvider`from java's  `ServiceLoader` 
here:
https://github.com/testcontainers/testcontainers-java/blob/43a76abb5d27f322a6a7a30ffc148beb31cd5736/modules/jdbc/src/main/java/org/testcontainers/jdbc/ContainerDatabaseDriver.java#L92
The debugger shows, that no implementation of the interface `JdbcDatabaseContainerProvider` can be found although the dependency 
`"org.testcontainers:postgresql:$testcontainersVersion"` contains the correct mapping.

This seems to indicate, that the flyway gradle plugin sets up the classpath incorrectly

**Comment by SanderSmee** [comment] 2020-05-18 07:15
I can confirm that this issue arises, though with slightly different versions of flyway (6.4.2) and testcontainers (1.14.1).

**Comment by DoodleBobBuffPants** [comment] 2020-09-03 09:46
Have you found a workaround to this?

**Comment by mschirmacher** [comment] 2020-09-03 12:34
Unfortunately i was unable to find a workaround

**Comment by SanderSmee** [comment] 2020-09-03 18:25
O tried it again with the state my experiment was in, but no success.
I created a minimal example to reproduce the issue: https://github.com/SanderSmee/flyway-issue-2736

When executing `./gradlew flywayMigrate` the reported error is the unexpected result.

**Comment by lnhrdt** [comment] 2020-10-15 00:53
@Lyeeedar & @DoodleBobBuffPants, I saw this issue was closed in 6b8fb6a which was tagged for version 7.0.3. I tried version 7.0.3 in both @SanderSmee's example repo and my own project. In both cases, I still get the same error and cannot run migrations against a testcontainers database.

Should this issue be reopened? And can you help us resolve the error?

**Comment by DoodleBobBuffPants** [comment] 2020-10-16 10:27
The error is because Testcontainers should be run within a testing framework (e.g. JUnit). If you use the Flyway API within a test against a Testcontainers database it should work, could you try that?

**Comment by lnhrdt** [comment] 2020-10-17 17:59
Thanks for @DoodleBobBuffPants for looking into this!

I do have some tests in my applications that run within a testing framework, calling Flyway directly in setup methods. Works great there, no issues. What I'm trying to do now is add additional end-to-end system tests where I start up my application locally and run tests against it. My application is happy to use a Testcontainers database so I just need the migrations run.

I don't know if you'd consider this a valid use case, but I'd like to use the Flyway Gradle plugin to run migrations against a Testcontainers database to support this type of testing. Is it possible to fix the classpath issue that @mschirmacher was pointing out? Or is there some other way to configure the Gradle plugin to achieve this?

**Comment by DoodleBobBuffPants** [comment] 2020-10-19 09:00
The way to achieve this would be to create a test calling Flyway and then you could create a task for that specific test in order to work with Testcontainers.

There isn't a classpath issue, it's just that to run against Testcontainers you must call Flyway from within a test as Flyway doesn't handle the starting and stopping of the database containers.

**Comment by DoodleBobBuffPants** [comment] 2020-10-30 15:23
Closing due to inactivity

**Closed by DoodleBobBuffPants** 2020-10-30 15:23 UTC
Labels: m: Gradle, s: waiting for feedback
