### ISSUE TITLE
Clarification needed: ignoreMigrationPatterns

### ISSUE THREAD

**Issue by hrstoyanov** [flyway/flyway#3592] opened 2022-12-29 23:49 UTC
###### Which version and edition of Flyway are you using?
Flyway Community 9.7.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

command-line

###### Which database are you using? (Type & version)
Oracle 19

###### Which operating system are you using?
Linux

This [documentation](https://flywaydb.org/documentation/configuration/parameters/ignoreMigrationPatterns) is not very clear if the ignoreMigrationPatterns is in the Teams edition, or it is also in Community edition, but some aspects of it are in Teams. **Can you please clarify**? The following configuration, according to the above docs seems allowed in Community edition:
```
flyway.ignoreMigrationPatterns = "*:missing"
````

 but does not have any effect. If the option is for Teams edition only, can you issue an appropriate error message and not just ignore it?

**Comment by DoodleBobBuffPants** [comment] 2022-12-30 09:51
Your configuration is valid in Teams, and it would produce an appropriate error in the case it were not

Could you provide a reproduction of your issue, along with the expected and actual outcome

**Comment by hrstoyanov** [comment] 2022-12-30 18:21
I added this configuration:

```
flyway.ignoreMigrationPatterns = "*:missing"
```

to  Flyway 9.7.0, but keep getting these failures:
```
ERROR: Validate failed: Migrations have failed validation
Detected applied migration not resolved locally: dummy table.
If you removed this migration intentionally, run repair to mark the migration as deleted.
Detected applied migration not resolved locally: 01 XYZ-200-first script.
If you removed this migration intentionally, run repair to mark the migration as deleted.
Detected applied migration not resolved locally: 02 XYZ-200-second script.
If you removed this migration intentionally, run repair to mark the migration as deleted.
Detected applied migration not resolved locally: 03 XYZ-200 test data.
If you removed this migration intentionally, run repair to mark the migration as deleted.
Detected applied migration not resolved locally: 01 first script.
If you removed this migration intentionally, run repair to mark the migration as deleted.
Detected applied migration not resolved locally: 02 second script.
If you removed this migration intentionally, run repair to mark the migration as deleted
```

**Comment by DoodleBobBuffPants** [comment] 2023-01-03 09:48
Could you provide a minimal reproduction project

**Comment by hrstoyanov** [comment] 2023-01-03 20:23
ok , will do .. but he above run log should be absolutely clear as to what the issue is

**Comment by DoodleBobBuffPants** [comment] 2023-01-03 22:10
It is, however there's not enough there to reproduce or narrow down the cause of the problem

For example, it could be because you haven't (correctly) configured `flyway.locations`, so the scripts aren't being detected, or it may be a bug due as you're executing Flyway in a way we haven't anticipated

**Comment by hrstoyanov** [comment] 2023-01-05 19:39
I think I have some clarification on the issue:

**Flyway will fail the VALIDATE command even though the `-ignoreMigrationPatterns="*:missing" ` option is specified, but will successfully execute MIGRATE. I think this is not right and as it will break CI/CD pipelines that want to validate migrations otherwise, just ignore missing ones.**

Here is how to reproduce in **Flyway 9.11.0 Community Edition**:

1. Create a migrations folder **sql**

2. Put inside (a repeatable) migration  **R__01_my_migration.sql**,  containing a single line with harmless **commit;**

3. Apply the migration (using a Postgres database, for example) - all should be fine
```
flyway -url=jdbc:postgresql://localhost:5432/postgres  -locations="filesystem:./sql" -community  -user=postgres -password=admin -ignoreMigrationPatterns="*:missing" migrate
```

4. Clone the existing 01 migration file into a new one - **R__02_my_migration.sql**, and rename the old one into **__R__01_my_migartion.sql** (so that Flyway will think it went missing)

5. Run the INFO command
```
flyway -url=jdbc:postgresql://localhost:5432/postgres  -locations="filesystem:./sql" -community  -user=postgres -password=admin -ignoreMigrationPatterns="*:missing" info    
```
Flyway should report that 01 migration is Missing and 02 is Pending

6. Run VALIDATE - **this fails and is the core of the issue, since we specified explicitly that missing migrations are to be ignored!**, even for validatiion!
```
flyway -url=jdbc:postgresql://localhost:5432/postgres  -locations="filesystem:./sql" -community  -user=postgres -password=admin -ignoreMigrationPatterns="*:missing" validate    
```

7. Run MIGRATE - this succeeds, but since the previous step already failed, you CI/CD pipeline is likely failed already, and never got to execute the MIGRATE step.
```
flyway -url=jdbc:postgresql://localhost:5432/postgres  -locations="filesystem:./sql" -community  -user=postgres -password=admin -ignoreMigrationPatterns="*:missing" migrate    
```

**Comment by DoodleBobBuffPants** [comment] 2023-01-06 09:59
When I run this, the failure is due to the `pending` repeatable, not the `missing` one - `pending` migrations cause `validate` to fail too, so you would need to set `-ignoreMigrationPatterns="*:missing,*:pending"` when running `validate` (`pending` migrations don't cause a failure as part of `migrate` as they are about to be applied, but they do cause a failure as part of `validate`)

Does that solve the problem?

**Comment by hrstoyanov** [comment] 2023-01-06 18:07
hm .. no really. See how missing validation **XYZ-204 10 blabla** (worked on another Git branch) is breaking my CI/CD pipeline validation step, despite using your suggested config:
```
....
Conf file before injecting flyway.password:
flyway.user = ACE_OWN
flyway.outOfOrder = true
flyway.ignoreMigrationPatterns = "*:missing,*:pending" 
flyway.table = flyway_dbtests_schema_history
flyway.url=xxxxxxxxxxxxxxx
...
  
Moving conf file to flyway path
ls -ltR /flyway/sql
/flyway/sql:
total 4
drwxr-xr-x 4 root root 34 Jan  6 09:56 2023
-rw-r--r-- 1 root root 70 Jan  6 09:56 R__flyway_table_setup.sql
-rw-r--r-- 1 2000 2000  0 Nov  2 06:20 put-your-sql-migrations-here.txt
/flyway/sql/2023:
total 0
drwxr-xr-x 4 root root 37 Jan  6 09:56 XYZ-200
drwxr-xr-x 2 root root 26 Jan  6 09:56 XYZ-5
/flyway/sql/2023/XYZ-200:
total 0
drwxr-xr-x 2 root root 83 Jan  6 09:56 migrations
drwxr-xr-x 2 root root 41 Jan  6 09:56 tests
/flyway/sql/2023/XYZ-200/migrations:
total 8
-rw-r--r-- 1 root root 233 Jan  6 09:56 R__01_XYZ-200-first_script.sql
-rw-r--r-- 1 root root 145 Jan  6 09:56 R__02_XYZ-200-second_script.sql
/flyway/sql/2023/XYZ-200/tests:
total 4
-rw-r--r-- 1 root root 110 Jan  6 09:56 R__03_XYZ-200_test_data.sql
/flyway/sql/2023/XYZ-5:
total 4
-rw-r--r-- 1 root root 9 Jan  6 09:56 R__XYZ-5.sql
ls -ltR /flyway/conf
/flyway/conf:
total 4
-rw-r--r-- 1 root root 245 Jan  6 09:56 flyway.conf
$ flyway info # collapsed multi-line command
Flyway Community Edition 9.7.0 by Redgate
See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.7.0
Database: xxxxxxxxxxxxxxxx
Schema version: 1
+------------+---------+--------------------------+----------+---------------------+----------+
| Category   | Version | Description              | Type     | Installed On        | State    |
+------------+---------+--------------------------+----------+---------------------+----------+
|            | 1       | << Flyway Baseline >>    | BASELINE | 2022-12-21 09:33:29 | Baseline |
| Repeatable |         | flyway table setup       | SQL      | 2022-12-21 09:33:29 | Success  |
| Repeatable |         | dummy table              | SQL      | 2022-12-28 15:12:48 | Deleted  |
| Repeatable |         | 01 XYZ-200-first script  | SQL      | 2022-12-28 17:07:28 | Deleted  |
| Repeatable |         | 02 XYZ-200-second script | SQL      | 2022-12-28 17:07:28 | Deleted  |
| Repeatable |         | 03 XYZ-200 test data     | SQL      | 2022-12-28 17:12:40 | Deleted  |
| Repeatable |         | 01 first script          | SQL      | 2022-12-29 10:39:51 | Deleted  |
| Repeatable |         | 02 second script         | SQL      | 2022-12-29 10:39:51 | Deleted  |
|            |         | dummy table              | DELETE   | 2023-01-05 15:35:57 | Success  |
|            |         | 01 XYZ-200-first script  | DELETE   | 2023-01-05 15:35:57 | Success  |
|            |         | 02 XYZ-200-second script | DELETE   | 2023-01-05 15:35:57 | Success  |
|            |         | 03 XYZ-200 test data     | DELETE   | 2023-01-05 15:35:57 | Success  |
|            |         | 01 first script          | DELETE   | 2023-01-05 15:35:57 | Success  |
|            |         | 02 second script         | DELETE   | 2023-01-05 15:35:57 | Success  |
| Repeatable |         | 01 XYZ-202 test          | SQL      | 2023-01-05 15:39:[31] | Deleted  |
| Repeatable |         | 02 XYZ 202 test          | SQL      | 2023-01-05 15:[39] | Deleted  |
|            |         | 01 XYZ-202 test          | DELETE   | 2023-01-05 15:51:09 | Success  |
|            |         | 02 XYZ 202 test          | DELETE   | 2023-01-05 15:51:09 | Success  |
| Repeatable |         | 01 XYZ-200-first script  | SQL      | 2023-01-05 15:58:[42] | Success  |
| Repeatable |         | 02 XYZ-200-second script | SQL      | 2023-01-05 15:58:[43] | Success  |
| Repeatable |         | 03 XYZ-200 test data     | SQL      | 2023-01-05 15:58:43 | Success  |
| Repeatable |         | XYZ 203 10 my test       | SQL      | 2023-01-05 15:58:43 | Deleted  |
|            |         | XYZ 203 10 my test       | DELETE   | 2023-01-05 16:05:04 | Success  |
| Repeatable |         | XYZ-204 10 blabla        | SQL      | 2023-01-05 16:09:26 | Missing  |
| Repeatable |         | XYZ-5                    | SQL      |                     | Pending  |
+------------+---------+--------------------------+----------+---------------------+----------+
Flyway Community Edition 9.7.0 by Redgate
See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.7.0
Database: xxxxxxxxxxxxxxxxxxxxxxx
Automate migration testing for Database CI with Flyway Hub. Visit https://flywaydb.org/get-started-with-hub
ERROR: Validate failed: Migrations have failed validation
Detected applied migration not resolved locally: XYZ-204 10 blabla.
If you removed this migration intentionally, run repair to mark the migration as deleted.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1
```

**Comment by hrstoyanov** [comment] 2023-01-06 18:56
Here is the config file piece, if you see anything wrong with it:
```
flyway.user = ACE_OWN
flyway.outOfOrder = true
flyway.ignoreMigrationPatterns = "*:missing,*:pending" 
flyway.table = flyway_dbtests_schema_history
```

**Comment by DoodleBobBuffPants** [comment] 2023-01-06 19:07
Could you try removing the double quotes around the value for `ignoreMigrationPatterns` i.e. make it `flyway.ignoreMigrationPatterns=*:missing,*:pending`?

Could you also run it with debug logging (add `-X` when call the commandline) so we can see what configuration Flyway is actually running with (in case any values are overridden anywhere)

**Comment by DoodleBobBuffPants** [comment] 2023-01-11 17:03
Closing till further activity as there's not much we can progress without a reproduction and/or the full debug logs

Our best guess with what we can see is that the configuration isn't what you expect it to be, which the debug logs would be able to confirm

**Closed by DoodleBobBuffPants** 2023-01-11 17:03 UTC
Labels: s: waiting for feedback

**Comment by hrstoyanov** [comment] 2023-01-13 04:52
We found the issue, it was on our side. However, there is wrong
documentation that shows the option's values wrapped in " " when specified
in the config file. This wrong, one need to remove the "" !

/Hristo Stoyanov
