### ISSUE TITLE
flyway execution slowly on MacOS

### ISSUE THREAD

**Issue by chientrm** [flyway/flyway#3380] opened 2022-01-21 06:02 UTC
###### Which version and edition of Flyway are you using?

```
$ flyway --version
Flyway Community Edition 8.4.2 by Redgate
```

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

1. Azure SQL Database
2. Local docker container from image `mcr.microsoft.com/mssql/server`

The project currently with no scripts.

###### Which operating system are you using?

macOS Monterey 12.1 (21C52)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

```
flyway info
```

###### What did you expect to see?

Flyway results in output in < 1 second

###### What did you see instead?

Flyway results in output in 15+ seconds.

**Comment by DoodleBobBuffPants** [comment] 2022-01-24 11:13
This could be due to connectivity issues - could you try adding `-skipCheckForUpdate` and also forcing the Community edition with `-community`

**Comment by chientrm** [comment] 2022-01-25 05:19
> This could be due to connectivity issues - could you try adding `-skipCheckForUpdate` and also forcing the Community edition with `-community`

Forcing the Community edition with `-community` helps reduce execution time from ~15 seconds to ~9 seconds.

I have tried both on Azure SQL Database and locally on my MacBook Pro 2015 with [Docker MSSQL Image](https://hub.docker.com/_/microsoft-mssql-server).

I notice a friend of mine executes the same script in just ~1 second. He's using Windows 10 and a local [SQL Server 2019](https://www.microsoft.com/en-us/sql-server/sql-server-2019).

Does `-skipCheckForUpdate` skip checking for local SQL scripts update?

**Comment by DoodleBobBuffPants** [comment] 2022-01-25 11:35
`-skipCheckForUpdate` skips Flyway checking for a version update, however the `~15 seconds to ~9 seconds` implies that connecting to your database is slow, which is reasonable here in comparison to a local DB, and isn't due to any change in Flyway as we are unable to reproduce this, so closing until further activity

**Closed by DoodleBobBuffPants** 2022-01-25 11:35 UTC
Labels: s: waiting for feedback
