### ISSUE TITLE
No migration files yields error

### ISSUE THREAD

**Issue by johanstenberg92** [flyway/flyway#1128] opened 2015-11-11 11:41 UTC
Hi,

When not having any migration files present I get the following error:

```
Error occurred while executing flywayMigrate
Unable to scan for SQL migrations in location: classpath:db/migration
```

Is it intended that `flyway` should fail if no files?

**Comment by axelfontaine** [comment] 2015-11-11 15:26
Yes, but it's something we want to address for 4.0.

**Comment by axelfontaine** [comment] 2015-12-29 09:34
Duplicate of #477

**Closed by axelfontaine** 2015-12-29 09:34 UTC
Labels: m: Core, t: bug
