### ISSUE TITLE
Process for migrating old flyway migrated database to a newer version

### ISSUE THREAD

**Issue by nhoughto** [flyway/flyway#2328] opened 2019-03-13 21:49 UTC
###### Which version and edition of Flyway are you using?
3.2.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
The problem is with 3.x -> 4.x+ migration, so yes =)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Postgres 9.6, but I expect this would be the case with all databases

###### Which operating system are you using?
coreOS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
So we have an application that is distributed to customers on-premise and we use Flyway to manage database migrations (very successfully thanks!), at one point in time many years ago we used the `setInitOnMigrate(true)` option, this created a `schema_version` table with the first migrate of `type=INIT`. During upgrading library versions for this application recently and moving to 5.x of Flyway starting this application fails with an error relating to the removal of the previously deprecated `INIT` enum in Flyway 4.x:

```
java.lang.IllegalArgumentException: No enum constant org.flywaydb.core.api.MigrationType.INIT
```

So I understand that this option has been removed / replaced, and other changes are going on in Flyway 5.x -> 6.x. But this is effectively a breaking change to the contract between Flyway and the database, at a previous point in history Flyway wrote a record using this enum value, my expectation would be that it should gracefully handle the situation and not fail? Is there a process to migrate the `INIT` record to a supported record type?

I tried manually editing the record to change it to a `SQL` type, but then the following record checksums would change and you get more problems, it doesn't appear to be a something that can be fixed outside of Flyway itself?

The other snag to all this, is since most of the application deployments are on-premise with customers, we don't have the luxury of being able to manually change things or run CLI commands easily, abstracting away the complexity of the database migrations is the job that we use Flyway for =)

###### What did you expect to see?
Flyway fix the record, or gracefully handle the missing enum value

###### What did you see instead?
`java.lang.IllegalArgumentException: No enum constant org.flywaydb.core.api.MigrationType.`

**Comment by axelfontaine** [comment] 2019-03-14 06:20
Duplicate of #2126 

This is described *exactly* in the release notes: https://flywaydb.org/documentation/releaseNotes#5.0.0

Please take a minute to review them before upgrading across several major versions. I'll save you a lot of time.

**Comment by nhoughto** [comment] 2019-03-14 06:21
Perfect! thanks, sorry for my poor searching.

**Closed by axelfontaine** 2019-03-14 06:20 UTC
