### ISSUE TITLE
No output returned by flyway commands in windows cmd terminal

### ISSUE THREAD

**Issue by simon4360** [flyway/flyway#3568] opened 2022-11-09 16:25 UTC
###### Which version and edition of Flyway are you using?
8.4.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes, same problem with 9.7.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Windows CMD

###### Which database are you using? (Type & version)
Oracle 19c

###### Which operating system are you using?
Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
flyway migrate -url=jdbc:oracle:thin:@// <DB_URL> : <DB_PORT> / <DB_NAME> -user= <DB_USER> -password= <DB_Password> -locations=filesystem:C:\flyway-9.7.0\migrations -outputFile=C:\flyway-9.7.0\migrations\out.log

flyway info -url=jdbc:oracle:thin:@// <DB_URL> : <DB_PORT> / <DB_NAME> -user= <DB_USER> -password= <DB_Password> -outputFile=C:\flyway-9.7.0\migrations\out.log

###### What did you expect to see?
I expect to see some feedback from the commands. The migrate command should tell you if it were successful or if it encountered an error, and the info command should show the state of the target schema and preview what would be migrated.

###### What did you see instead?
Nothing. There is no output at all from the flyway command, there is also nothing in the log file that I specify it to write to. The command is successful however. The migrate command successfully ran the migration, added an entry to the flyway_schema_history table and created a (empty) log file.
The info command also successfully creates the log file, but again with nothing in the file or returned to the screen

**Comment by simon4360** [comment] 2022-11-09 16:26
![flywayoutput](https://user-images.githubusercontent.com/74009233/200885434-55b85ce9-ac9e-49db-b5c7-d728ff18f507.png)

**Comment by DoodleBobBuffPants** [comment] 2022-11-29 12:05
Apologies for the delay in getting back to you

We're unable to reproduce this. Could you provide a minimal reproduction project, including your Flyway configuration (minus connection details) and the exact steps you ran?

Also, does it work when you don't specify an `outputFile`?

**Comment by DoodleBobBuffPants** [comment] 2022-12-20 10:37
Closing till further activity

**Closed by DoodleBobBuffPants** 2022-12-20 10:37 UTC
Labels: s: waiting for feedback
