### ISSUE TITLE
Mysql: gtid mode also doesn't support “CREATE TABLE ... AS SELECT”

### ISSUE THREAD

**Issue by fanticat** [flyway/flyway#2548] opened 2019-10-30 14:05 UTC
###### Which version and edition of Flyway are you using?
**6.0.6**

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

**this bug also in the latest version**

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

**Maven**

###### Which database are you using (type & version)?

**Mysql 5.7.22**

###### Which operating system are you using?

**CentOS 7.4**

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

The code in class org.flywaydb.core.internal.database.mysql.MySQLDatabase，not only  in strict mode，but **gtid mode also doesn't support “CREATE TABLE ... AS SELECT”**

Please refer
https://dev.mysql.com/doc/refman/5.7/en/replication-gtids-restrictions.html

CREATE TABLE ... SELECT statements.  CREATE TABLE ... SELECT is not safe for statement-based replication. When using row-based replication, this statement is actually logged as two separate events—one for the creation of the table, and another for the insertion of rows from the source table into the new table just created. When this statement is executed within a transaction, it is possible in some cases for these two events to receive the same transaction identifier, which means that the transaction containing the inserts is skipped by the slave. Therefore, CREATE TABLE ... SELECT is not supported when using GTID-based replication.

```
 @Override
    public String getRawCreateScript(Table table, boolean baseline) {
        String tablespace =



                        configuration.getTablespace() == null
                        ? ""
                        : " TABLESPACE \"" + configuration.getTablespace() + "\"";

        String baselineMarker = "";
        if (baseline) {
            if (!pxcStrict) {
                baselineMarker = " AS SELECT" +
                        "     1 as \"installed_rank\"," +
                        "     '" + configuration.getBaselineVersion() + "' as \"version\"," +
                        "     '" + configuration.getBaselineDescription() + "' as \"description\"," +
                        "     '" + MigrationType.BASELINE + "' as \"type\"," +
                        "     '" + configuration.getBaselineDescription() + "' as \"script\"," +
                        "     NULL as \"checksum\"," +
                        "     '" + getInstalledBy() + "' as \"installed_by\"," +
                        "     CURRENT_TIMESTAMP as \"installed_on\"," +
                        "     0 as \"execution_time\"," +
                        "     TRUE as \"success\"\n";
            } else {
                // Percona XtraDB Cluster in strict mode doesn't support CREATE TABLE ... AS SELECT ...
                // So revert to regular insert, which unfortunately is not safe in concurrent scenarios
                // due to MySQL implicit commits after DDL statements.
                baselineMarker = ";\n" + getBaselineStatement(table);
            }
        }
```

**Comment by juliahayward** [comment] 2019-10-31 11:05
This appears to be a duplicate of #2535. In any case, a fix has been found.

**Closed** 2019-11-04 10:10 UTC
Labels: d: MySQL, r: duplicate, t: bug
