### ISSUE TITLE
schema file generation

### ISSUE THREAD

**Issue by pnicholson** [flyway/flyway#968] opened 2015-03-07 19:10 UTC
I find myself having to clean the database when switching between branches where migrations have been applied to the database which are now missing from the class path. When the number of migrations exceeds 100 or so, having to clean your development database and re-apply all migrations can be slow or have an increased chance of failing. 

I think it would be benefitial if a flyway task existed to produce the schema of that database as a .sql file. This file can then be put into source control and run whenever it is required to reset the schema of the database.

**Comment by axelfontaine** [comment] 2017-02-07 12:07
Duplicate of #470

**Closed by axelfontaine** 2017-02-07 12:07 UTC
