### ISSUE TITLE
Is there a way to run scripts with different users from one location at once?

### ISSUE THREAD

**Issue by coredigitalmedia** [flyway/flyway#2340] opened 2019-03-29 18:00 UTC
###### Which version and edition of Flyway are you using?

Flyway enterprise trial edition 5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

command line

###### Which database are you using (type & version)?

Oracle 12.1

###### Which operating system are you using?

linux x86_64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by coredigitalmedia** [comment] 2019-03-29 18:05
Let's say there is folder /flyway/sql which contains all sql scripts like below.
R__1__USER_1__script.sql
R__2__USER_2__script.sql
R__3__USER_3__script.sql
R__4__USER_4__script.sql

we'd like to run each script as its own user like:
script "R__1__USER_1__script.sql" should run as "USER_1" user,
script "R__2__USER_2__script.sql" should run as "USER_2" user, and so on.

is it possible?

**Comment by coredigitalmedia** [comment] 2019-04-02 15:21
Hello: any update on this? we need to make it work before trial expires else we can't use this tool.
Thanks.

**Comment by axelfontaine** [comment] 2019-04-08 09:02
This is currently not possible in the form you suggest. One alternative would be to have one instance of Flyway per user, with scripts for each user in a separate directory. Flyway would then have to be executed separately for each user.

Would this work for you?

If not, could you explain in a bit more detail why you need this so we can get a better understanding of your use case?

**Comment by axelfontaine** [comment] 2019-04-10 08:25
Duplicate of #1308

**Closed by axelfontaine** 2019-04-10 08:25 UTC
Labels: s: waiting for feedback
