### ISSUE TITLE
Error while adding callback script on the filepath 

### ISSUE THREAD

**Issue by Me1gireesh** [flyway/flyway#2369] opened 2019-04-26 10:20 UTC
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by Me1gireesh** [comment] 2019-04-26 10:21
Error 👍 
DEBUG: Memory usage: 25 of 147M
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.flywaydb.core.internal.database.oracle.pro.SQLPlusDefineSqlStatement.<clinit>(SQLPlusDefineSqlStatement.java:34)
	at org.flywaydb.core.internal.database.oracle.OracleSqlStatementBuilder.getSqlStatement(OracleSqlStatementBuilder.java:191)
	at org.flywaydb.core.internal.sqlscript.SqlScript.addStatement(SqlScript.java:152)
	at org.flywaydb.core.internal.sqlscript.SqlScript.extractStatements(SqlScript.java:138)
	at org.flywaydb.core.internal.sqlscript.SqlScript.<init>(SqlScript.java:86)
	at org.flywaydb.core.internal.callback.SqlScriptCallbackFactory.<init>(SqlScriptCallbackFactory.java:87)
	at org.flywaydb.core.Flyway.prepareCallbacks(Flyway.java:1808)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1705)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:161)
	at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
Flyway Enterprise Edition (trial) 5.2.4 by Boxfuse licensed to Dell until 2019-04-04
ERROR: Your 30 day limited Flyway trial license has expired and is no longer valid. You must upgrade to a full Flyway Enterprise Edition license immediately to keep on using this software.
Database: jdbc:oracle:thin:@ldap://oudsit.us.dell.com:389/SDR2D_12C,cn=ORACLECONTEXT,OU=TNSNAMES,O=APPS,dc=dell,dc=com (Oracle 12.1)
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.flywaydb.core.internal.database.oracle.pro.SQLPlusDefineSqlStatement.<clinit>(SQLPlusDefineSqlStatement.java:34)
	at org.flywaydb.core.internal.database.oracle.OracleSqlStatementBuilder.getSqlStatement(OracleSqlStatementBuilder.java:191)
	at org.flywaydb.core.internal.sqlscript.SqlScript.addStatement(SqlScript.java:152)
	at org.flywaydb.core.internal.sqlscript.SqlScript.extractStatements(SqlScript.java:138)
	at org.flywaydb.core.internal.sqlscript.SqlScript.<init>(SqlScript.java:86)
	at org.flywaydb.core.internal.callback.SqlScriptCallbackFactory.<init>(SqlScriptCallbackFactory.java:87)
	at org.flywaydb.core.Flyway.prepareCallbacks(Flyway.java:1808)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1705)
	at org.flywaydb.core.Flyway.info(Flyway.java:1521)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:167)
	at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more

**Comment by Me1gireesh** [comment] 2019-04-26 10:21
Culd you please confirm if i'm missing any ars

**Comment by Me1gireesh** [comment] 2019-04-26 10:24
Flyway Enterprise Edition (trial) 5.2.4 by Boxfuse licensed to Dell until 2019-04-04
ERROR: Your 30 day limited Flyway trial license has expired and is no longer valid. You must upgrade to a full Flyway Enterprise Edition license immediately to keep on using this software.
Database: jdbc:oracle:thin:@ldap://oudsit.us.dell.com:389/SDR2D_12C,cn=ORACLECONTEXT,OU=TNSNAMES,O=APPS,dc=dell,dc=com (Oracle 12.1)
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.flywaydb.core.internal.database.oracle.pro.SQLPlusDefineSqlStatement.<clinit>(SQLPlusDefineSqlStatement.java:34)
	at org.flywaydb.core.internal.database.oracle.OracleSqlStatementBuilder.getSqlStatement(OracleSqlStatementBuilder.java:191)
	at org.flywaydb.core.internal.sqlscript.SqlScript.addStatement(SqlScript.java:152)
	at org.flywaydb.core.internal.sqlscript.SqlScript.extractStatements(SqlScript.java:138)
	at org.flywaydb.core.internal.sqlscript.SqlScript.<init>(SqlScript.java:86)
	at org.flywaydb.core.internal.callback.SqlScriptCallbackFactory.<init>(SqlScriptCallbackFactory.java:87)
	at org.flywaydb.core.Flyway.prepareCallbacks(Flyway.java:1808)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1705)
	at org.flywaydb.core.Flyway.repair(Flyway.java:1566)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:174)
	at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
DEBUG: Loading config file: /sbil/ci/bin/flyway-5.2.4/conf/flyway.conf
DEBUG: Unable to load config file: /home/********/flyway.conf
DEBUG: Unable to load config file: /sbil/ci/bin/flyway-5.2.4/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.baselineOnMigrate -> true
DEBUG: flyway.locations -> filesystem:/sbil/ci/jenkins-slave/workspace/database-migration-recompile/repo/source
DEBUG: flyway.outOfOrder -> true
DEBUG: flyway.password -> ****************
DEBUG: flyway.oracle.sqlplus -> true
DEBUG: flyway.table -> FLYWAY_SCHEMA_HISTORY
DEBUG: flyway.schemas -> PROCESS_CICD
DEBUG: flyway.target -> 20.0502.1.190426095216
DEBUG: flyway.url -> jdbc:oracle:thin:@ldap://oudsit.us.dell.com:389/SDR2D_12C,cn=ORACLECONTEXT,OU=TNSNAMES,O=APPS,dc=dell,dc=com
DEBUG: flyway.user -> PROCESS_CICD
DEBUG: flyway.licenseKey -> FL01651DD2B9088E523126E738D02D5B0A2B594CDE40D0F0A842309E3EAA75F219B212A1D8F1D322A8BCF830AD02AFA4CB9116C9774949079C756EB57BB6D3CCC87A733C9A09A98CC85C9868314AFF75E23570A6B429F2FFFC7AE88824555190379531BD0D7256031AE5BDABBB173719CBD404450F8547EAFD89DDCB3FFF965B5E017019A23418C927537002AAAA4BBBF60297D90C028E6371F7B62A76DD90643C58A918B681A00DBDAAA0F535CA0CE29781A34BCF535C10C9C4C58DCF8052733F7A5F8FF618DA45A6ABF14D33699057C3091ED00C23772EE092912265E14C50390600E8E7B5392B075DDDAF0823E3A4C464DB6FDDABB262393FD5677763118DD879
DEBUG: flyway.jarDirs -> /sbil/ci/bin/flyway-5.2.4/jars
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/derby-10.14.2.0.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/derbyclient-10.14.2.0.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/h2-1.4.197.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/hsqldb-2.4.1.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/mssql-jdbc-7.0.0.jre8.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/jtds-1.3.1.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/mysql-connector-java-8.0.12.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/jna-4.5.2.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/jna-platform-4.5.2.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/mariadb-java-client-2.3.0.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/postgresql-42.2.5.jre6.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/sqlite-jdbc-3.23.1.jar
DEBUG: Adding location to classpath: /sbil/ci/bin/flyway-5.2.4/drivers/ojdbc7_g.jar
Flyway Enterprise Edition (trial) 5.2.4 by Boxfuse licensed to Dell until 2019-04-04
ERROR: Your 30 day limited Flyway trial license has expired and is no longer valid. You must upgrade to a full Flyway Enterprise Edition license immediately to keep on using this software.
Database: jdbc:oracle:thin:@ldap://oudsit.us.dell.com:389/SDR2D_12C,cn=ORACLECONTEXT,OU=TNSNAMES,O=APPS,dc=dell,dc=com (Oracle 12.1)
DEBUG: Driver  : Oracle JDBC driver 12.1.0.1.0
DEBUG: DDL Transactions Supported: false
DEBUG: Schema: PROCESS_CICD
DEBUG: Scanning for filesystem resources at '/sbil/ci/jenkins-slave/workspace/database-migration-recompile/repo/source'
DEBUG: Scanning for resources in path: /sbil/ci/jenkins-slave/workspace/database-migration-recompile/repo/source (/sbil/ci/jenkins-slave/workspace/database-migration-recompile/repo/source)
DEBUG: Found filesystem resource: /sbil/ci/jenkins-slave/workspace/database-migration-recompile/repo/source/README.md
DEBUG: Found filesystem resource: /sbil/ci/jenkins-slave/workspace/database-migration-recompile/repo/source/V20.0502.1.190426095216__test.sql
DEBUG: Found filesystem resource: /sbil/ci/jenkins-slave/workspace/database-migration-recompile/repo/source/afterMigrate__SDR.sql
DEBUG: Scanning for SQL callbacks ...
DEBUG: Filtering out resource: /sbil/ci/jenkins-slave/workspace/database-migration-recompile/repo/source/README.md (filename: README.md)
DEBUG: Parsing afterMigrate__SDR.sql ...
DEBUG: Found statement at line 1: WHENEVER SQLERROR CONTINUE
DEBUG: Found statement at line 3: SET TERMOUT ON
DEBUG: Found statement at line 4: SET ECHO ON
DEBUG: Found statement at line 5: SET TIMING ON
DEBUG: Found statement at line 6: SET TIME ON
DEBUG: Found statement at line 7: SET PAGESIZE 30000
DEBUG: Found statement at line 8: SET SERVEROUTPUT ON SIZE 1000000
DEBUG: Found statement at line 9: ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS'
DEBUG: Found statement at line 10: ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FXX'
DEBUG: Found statement at line 12: SELECT SYSTIMESTAMP AS start_date FROM dual
DEBUG: Found statement at line 13: SELECT * FROM v$instance
DEBUG: Found statement at line 15: SELECT SYS_CONTEXT ('userenv', 'DB_NAME') DB_NAME
     , SYS_CONTEXT ('userenv', 'CURRENT_USER') CURRENT_USER
     , SYS_CONTEXT ('userenv', 'CURRENT_SCHEMA') CURRENT_SCHEMA
     , SYS_CONTEXT ('userenv', 'SESSION_USER') SESSION_USER
     , SYS_CONTEXT ('userenv', 'ISDBA') IS_DBA
FROM DUAL
DEBUG: Memory usage: 25 of 147M
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.flywaydb.core.internal.database.oracle.pro.SQLPlusDefineSqlStatement.<clinit>(SQLPlusDefineSqlStatement.java:34)
	at org.flywaydb.core.internal.database.oracle.OracleSqlStatementBuilder.getSqlStatement(OracleSqlStatementBuilder.java:191)
	at org.flywaydb.core.internal.sqlscript.SqlScript.addStatement(SqlScript.java:152)
	at org.flywaydb.core.internal.sqlscript.SqlScript.extractStatements(SqlScript.java:138)
	at org.flywaydb.core.internal.sqlscript.SqlScript.<init>(SqlScript.java:86)
	at org.flywaydb.core.internal.callback.SqlScriptCallbackFactory.<init>(SqlScriptCallbackFactory.java:87)
	at org.flywaydb.core.Flyway.prepareCallbacks(Flyway.java:1808)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1705)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:161)
	at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
Flyway Enterprise Edition (trial) 5.2.4 by Boxfuse licensed to Dell until 2019-04-04
ERROR: Your 30 day limited Flyway trial license has expired and is no longer valid. You must upgrade to a full Flyway Enterprise Edition license immediately to keep on using this software.
Database: jdbc:oracle:thin:@ldap://oudsit.us.dell.com:389/SDR2D_12C,cn=ORACLECONTEXT,OU=TNSNAMES,O=APPS,dc=dell,dc=com (Oracle 12.1)
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.flywaydb.core.internal.database.oracle.pro.SQLPlusDefineSqlStatement.<clinit>(SQLPlusDefineSqlStatement.java:34)
	at org.flywaydb.core.internal.database.oracle.OracleSqlStatementBuilder.getSqlStatement(OracleSqlStatementBuilder.java:191)
	at org.flywaydb.core.internal.sqlscript.SqlScript.addStatement(SqlScript.java:152)
	at org.flywaydb.core.internal.sqlscript.SqlScript.extractStatements(SqlScript.java:138)
	at org.flywaydb.core.internal.sqlscript.SqlScript.<init>(SqlScript.java:86)
	at org.flywaydb.core.internal.callback.SqlScriptCallbackFactory.<init>(SqlScriptCallbackFactory.java:87)
	at org.flywaydb.core.Flyway.prepareCallbacks(Flyway.java:1808)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1705)
	at org.flywaydb.core.Flyway.info(Flyway.java:1521)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:167)
	at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more

**Comment by Me1gireesh** [comment] 2019-04-26 10:24
Please find the above message with debug level on..

**Comment by axelfontaine** [comment] 2019-04-26 10:59
Duplicate of #2368

**Closed by axelfontaine** 2019-04-26 10:59 UTC
