### ISSUE TITLE
Feature Request to Archive and Truncate the schema_version table periodically.

### ISSUE THREAD

**Issue by mehta-m** [flyway/flyway#2074] opened 2018-07-10 07:10 UTC
Version; Flyway 4.2.0
Client: Commandline
Database Engine: MS SQL Server
OS: Windows Server 2012 R2

With each migrate command - Flyway checks the checksum of the SQL files of the previously executed migrations. This obviously costs some time.   The size of this table also increases as more and more migrations are applied.

Now say in Jan 2019 all my applied migrations have gone from QA -> UAT -> Production - i really don't need flyway to check the checksums of the files applied in say Jan/Feb 18. So to speedup the deployment - it would be great if we could have a feature where the **schema_version** table would get archived to another table and empty itself. This feature could be configurable.

**Comment by axelfontaine** [comment] 2018-07-10 07:32
Duplicate of #470 

If this is just about the table, you can simply drop it and baseline the schema again.

**Closed by axelfontaine** 2018-07-10 07:32 UTC
