### ISSUE TITLE
Connection to Azure MariaDB 10.3 fails

### ISSUE THREAD

**Issue by bramant** [flyway/flyway#2531] opened 2019-10-11 08:05 UTC
###### Which version and edition of Flyway are you using?

Flyway 6.0.6 Community Edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API 

###### Which database are you using (type & version)?

MariaDB 10.3 (Database-as-a-service on Azure)

###### Which operating system are you using?

Docker based on Alpine Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

We are developing our product using Spring Boot and use Flyway to keep our schema up to date. Against a local MariaDB 10.3 docker (official image maintained by MariaDB) the Flyway migrations work as expected. But when running this against an Azure MariaDB 10.3 (Database-as-a-service), we get an Exception when Flyway tries to connect to the database:
`"Could not open JPA EntityManager for transaction; nested exception is org.flywaydb.core.internal.license.FlywayEditionUpgradeRequiredException: Flyway Enterprise Edition or MySQL upgrade required: MySQL 5.6 is no longer supported by Flyway Community Edition, but still supported by Flyway Enterprise Edition."`
It seems that Flyway gets "MySQL 5.6" back instead of "MariaDB 10.3". I have also submitted a Support Request to the Azure team and they are also looking into this.

###### What did you expect to see?
Flyway performing the migration.

###### What did you see instead?
An Exception in the logs.

**Comment by juliahayward** [comment] 2019-10-11 12:40
This sounds like it's related to #2525.

**Comment by juliahayward** [comment] 2019-10-11 13:47
The problem is definitely that Azure is reporting incorrectly. However, I have a workaround and it will be in Flyway 6.0.7.

**Closed** 2019-10-14 10:52 UTC
Labels: d: MariaDB, r: fixed
