### ISSUE TITLE
Add support for squashing migrations

### ISSUE THREAD

**Issue by rohanagarwal36** [flyway/flyway#1753] opened 2017-08-23 14:03 UTC
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Gradle plugin

###### What database are you using (type & version)?
Postgres 9.6.3

###### What operating system are you using?
Ubuntu 16.04

It would be great if we can have squashing feature for migrations. As with time, the number of migration files keeps growing, we can squash migrations which would then require less operations to be executed when those squashed migrations are run. Also, that would make migrations more neat and clean.

**Comment by axelfontaine** [comment] 2017-08-23 14:07
Duplicate of #470

**Closed by axelfontaine** 2017-08-23 14:07 UTC
