### ISSUE TITLE
Flyway command line cannot handle special character

### ISSUE THREAD

**Issue by Frantch** [flyway/flyway#1670] opened 2017-06-15 12:22 UTC
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

Redshift

###### What operating system are you using?

unix (centos) and same on osx (el capitan)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

./flyway info -user=test -password=AAYt!!$%gSL4j()($%%Gshs
or
./flyway info -user=test -password="AAYt!!$%gSL4j()($%%Gshs"

(same with all other commands..)

###### What did you expect to see?

The info of the migration

###### What did you see instead?

: [Amazon](500310) Invalid operation: password authentication failed for user "test";

Note that when I put the exact same password in the flyway.conf (flyway.password) it works perfeclty

**Comment by axelfontaine** [comment] 2017-06-17 10:32
Duplicate of #1658 

Please stop opening duplicate issues.

**Closed by axelfontaine** 2017-06-17 10:32 UTC

**Comment by ddavtian** [comment] 2017-09-18 21:15
@axelfontaine I think I maybe running into a similar issue, my username is `octo@octo-dev-db`if I if I use it as `-user=octo@octo-dev-db` I see the ending being truncated so only `octo` is being set. If I use it as `'-user=octo@octo-dev-db'` I am getting `ERROR: Invalid operation: '-user=octo@octo-dev-db'`
