### ISSUE TITLE
Request: Add validation flag to force error when newer schema in DB than in migrations

### ISSUE THREAD

**Issue by HaydenSikh** [flyway/flyway#1150] opened 2015-12-17 22:42 UTC
We have a project structure set as such:
- `App 1` with batch write-only access to schema
- `App 2` with interactive read-only access to schema
- `db-migrations` project which both depend on.

For most environments we want `App 1` to control the migrations but we have both apps pull in the migrations so that they can set up their own tests independently from each other.  However, if a developer doesn't update the version of the `db-migrations` project it pulls in then it can pass through our test stages and fail once it hits prod.

The current validation step generates a warning if it finds a newer version in `schema_versions` than what it finds in the migrations scripts.  This request is for a configuration flag to change that from a warning to an error.

In our particular circumstance we're using flyway via the SBT plugin.

**Comment by axelfontaine** [comment] 2017-02-07 13:16
Duplicate of #989

**Closed by axelfontaine** 2017-02-07 13:16 UTC
