### ISSUE TITLE
Delete my DataBases

### ISSUE THREAD

**Issue by zth1993** [flyway/flyway#3549] opened 2022-10-24 15:06 UTC
###### Which version and edition of Flyway are you using?
7.1.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Delete my databases!!!
 flyway:
    enabled: true
    clean-disabled: true # ！！！
    locations: classpath:flyway/migration-test

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
 Java API

###### Which database are you using? (Type & version)
Mysql 8.0.24

###### Which operating system are you using?
Ubuntu

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Exceute DELETE， But I don't Why！！！

-- ----------------------------
-- Records of flyway_schema_history
-- ----------------------------
INSERT INTO `flyway_schema_history` VALUES (1, '0.0.1', 'init', 'SQL', 'V0.0.1__init.sql', 785956502, 'root', '2022-10-14 10:22:13', 110, 1);
INSERT INTO `flyway_schema_history` VALUES (2, '0.0.2', 'testname', 'SQL', 'V0.0.2__level_set_alias_name.sql', 627994305, 'root', '2022-10-14 10:22:13', 11, 1);
INSERT INTO `flyway_schema_history` VALUES (3, '0.0.3', 'testname1', 'SQL', 'V0.0.3__db_table_field_update.sql', -1358006348, 'root', '2022-10-14 10:22:13', 75, 1);
INSERT INTO `flyway_schema_history` VALUES (4, '0.0.4', 'testname2', 'SQL', 'V0.0.4__config_system.sql', -607141738, 'root', '2022-10-14 10:22:13', 15, 1);
INSERT INTO `flyway_schema_history` VALUES (5, '0.0.5', 'testname3', 'SQL', 'V0.0.5__car_cloud_field.sql', -548244357, 'root', '2022-10-14 10:22:13', 60, 1);
INSERT INTO `flyway_schema_history` VALUES (6, '0.0.6', 'testname4', 'SQL', 'V0.0.6__update_data_field_system.sql', 1321413611, 'root', '2022-10-19 17:53:49', 407, 1);
INSERT INTO `flyway_schema_history` VALUES (7, '0.0.1', 'init', 'DELETE', 'V0.0.1__init.sql', 785956502, 'root', '2022-10-21 10:43:16', 0, 1);
INSERT INTO `flyway_schema_history` VALUES (8, '0.0.2', 'testname', 'DELETE', 'V0.0.2__level_set_alias_name.sql', 627994305, 'root', '2022-10-21 10:43:16', 0, 1);
INSERT INTO `flyway_schema_history` VALUES (9, '0.0.3', 'testname2', 'DELETE', 'V0.0.3__db_table_field_update.sql', -1358006348, 'root', '2022-10-21 10:43:16', 0, 1);
INSERT INTO `flyway_schema_history` VALUES (10, '0.0.4', 'testname3', 'DELETE', 'V0.0.4__config_system.sql', -607141738, 'root', '2022-10-21 10:43:16', 0, 1);
INSERT INTO `flyway_schema_history` VALUES (11, '0.0.5', 'testname4', 'DELETE', 'V0.0.5__car_cloud_field.sql', -548244357, 'root', '2022-10-21 10:43:16', 0, 1);
INSERT INTO `flyway_schema_history` VALUES (12, '0.0.6', 'testname5', 'DELETE', 'V0.0.6__update_data_field_system.sql', 1321413611, 'root', '2022-10-21 10:43:16', 0, 1);
INSERT INTO `flyway_schema_history` VALUES (13, '0.0.1', 'init', 'SQL', 'V0.0.1__init.sql', 785956502, 'root', '2022-10-21 10:47:23', 1127, 1);
INSERT INTO `flyway_schema_history` VALUES (14, '0.0.2', 'testname', 'SQL', 'V0.0.2__level_set_alias_name.sql', 627994305, 'root', '2022-10-21 10:47:23', 11, 1);
INSERT INTO `flyway_schema_history` VALUES (15, '0.0.3', 'testname2', 'SQL', 'V0.0.3__db_table_field_update.sql', -1358006348, 'root', '2022-10-21 10:47:24', 864, 1);
INSERT INTO `flyway_schema_history` VALUES (16, '0.0.4', 'testname3', 'SQL', 'V0.0.4__config_system.sql', -607141738, 'root', '2022-10-21 10:47:24', 159, 1);
INSERT INTO `flyway_schema_history` VALUES (17, '0.0.5', 'testname4', 'SQL', 'V0.0.5__car_cloud_field.sql', -548244357, 'root', '2022-10-21 10:47:25', 655, 1);
INSERT INTO `flyway_schema_history` VALUES (18, '0.0.6', 'testname5', 'SQL', 'V0.0.6__update_data_field_system.sql', 1321413611, 'root', '2022-10-21 10:47:25', 532, 1);

###### What did you expect to see?
tell me ,what should i do , that i can get the result。

**Comment by DoodleBobBuffPants** [comment] 2022-10-25 10:04
It's a bit unclear what the issue is - can you provide a reproduction, highlighting what the problematic output is and what you'd expect?

Is the issue the `DELETE` row in the history table? These were new in V7 - there's more information in [this](https://flywaydb.org/blog/flyway-7-0-0-beta) post, but to prevent this you would need to configure `locations` when running `repair` too. It's worth noting that this only marks them as deleted in the history table - your database is left unchanged

Closing till further activity

**Closed by DoodleBobBuffPants** 2022-10-25 10:04 UTC
