### ISSUE TITLE
Number of retries exceeded while attempting to acquire PostgreSQL advisory lock. Configure the number of retries with the 'lockRetryCount' configuration option

### ISSUE THREAD

**Issue by mohemianInes** [flyway/flyway#3391] opened 2022-02-07 09:15 UTC
###### What did you do? 
Our Spring Boot backend (v.2.5.6) had several problems communicating with the PostgreSQL DB after deploying with new flyway verison 8.4.2 (previous version 7.7.3) The problem started on Friday at 09:10 ( 2022-02-04 09:10:46.262 ) when the Flyway Dependency (v.8.4.2) produced an error during an update: "_org.flywaydb.core.api .FlywayException: Number of retries exceeded while attempting to acquire PostgreSQL advisory lock._" Unfortunately, after this error, even the old version of our backend (Flyway v.7.7.3) did not want to establish a successful connection to the DB and we had to restart the DB instance manually, after which everything worked normally again. Due to a configuration problem, the new version was deployed again today and the same problem occurred again.

**Comment by dmitry-sviridov** [comment] 2022-02-07 19:56
+1

I have the same problem, after deploying database to DigitalOcean droplet. I thought then the reason was in **transaction pooling mode** (described here https://github.com/flyway/flyway/issues/2895#issuecomment-784297265) but when I configured new connection pool with **session pooling mode** and use it, I've got an error described here.

**Comment by mohemianInes** [comment] 2022-02-08 07:50
The root cause of our problem was that the migration took too long and then Openshift killed the pod, however the flyway lock remained on the db and it never unlocked. Has this issue been addressed already?

**Comment by DoodleBobBuffPants** [comment] 2022-02-08 10:27
In this case this is (almost) expected behaviour. The locks we take out however should be automatically released when the session is ended, which suggests the pod wasn't killed completely

Taking out transaction-level locks might also help here (see https://github.com/flyway/flyway/issues/2895) so closing this in favour of #2895

**Closed by DoodleBobBuffPants** 2022-02-08 10:27 UTC

**Comment by joheb-mohemian** [comment] 2023-11-09 07:21
> In this case this is (almost) expected behaviour. The locks we take out however should be automatically released when the session is ended, which suggests the pod wasn't killed completely

@DoodleBobBuffPants sorry to be grave digging here, but we are affected by the same problem. What do you mean by the "pod wasn't killed completely"? I don't understand how the pod would be killed without killing all connections to the DB. Wouldn't that mean that the session that was running the flyway migration would have been ended?
