### ISSUE TITLE
fails to load main class in git-bash for Windows

### ISSUE THREAD

**Issue by hauntingEcho** [flyway/flyway#3093] opened 2021-02-25 20:53 UTC
###### Which version and edition of Flyway are you using?
7.5.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using? (Type & version)
none - `flyway -v`

###### Which operating system are you using?
Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

```
PS C:\Users\Matt\opt\flyway\flyway-7.5.4> flyway -v
Flyway Community Edition 7.5.4 by Redgate

PS C:\Users\Matt\opt\flyway\flyway-7.5.4> bash

Matt@DESKTOP-C7GV3UB MINGW64 ~/opt/flyway/flyway-7.5.4
$ flyway -v
Error: Could not find or load main class org.flywaydb.commandline.Main

Matt@DESKTOP-C7GV3UB MINGW64 ~/opt/flyway/flyway-7.5.4
$ ls
README.txt  conf  drivers  flyway  flyway.cmd  jars  jre  lib  licenses  native  sql

Matt@DESKTOP-C7GV3UB MINGW64 ~/opt/flyway/flyway-7.5.4
```

###### What did you expect to see?
same behavior in Bash as in PS

###### What did you see instead?
failure to execute.  This looks very similar to #1642 #735 and #562

**Comment by hauntingEcho** [comment] 2021-02-25 20:57
using a full path to the executable, rather than putting it in `$PATH`, does work though

**Comment by hauntingEcho** [comment] 2021-02-25 22:06
This issue does not effect version 7.5.3

**Comment by DoodleBobBuffPants** [comment] 2021-02-26 08:33
I'm unable to reproduce this

You could first try ensuring no other version of Flyway is on your `PATH`, and when adding to `PATH` that the entire installation folder is on the path (i.e. `flyway-7.5.4`)

If that doesn't work could you provide a reproduction, including exact steps and any modifications made to `PATH` or other variables

**Comment by DoodleBobBuffPants** [comment] 2021-03-01 09:14
Closing until further activity

**Closed by DoodleBobBuffPants** 2021-03-01 09:14 UTC
Labels: s: waiting for feedback

**Comment by hauntingEcho** [comment] 2021-03-01 22:48
after re-downloading and changing my path back to 7.5.4, I'm also not able to reproduce the issue anymore.  Not sure what was up.
