### ISSUE TITLE
Resolve Gradle 4 deprecation warning

### ISSUE THREAD

**Issue by ben-manes** [flyway/flyway#1710] opened 2017-07-13 19:28 UTC
> Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0.

I identified the cause is Flyway by using `gradle <task> -Dorg.gradle.deprecation.trace=true`
```
at org.gradle.api.internal.tasks.DefaultSourceSetOutput.getClassesDir(DefaultSourceSetOutput.java:79)
at org.gradle.api.internal.tasks.DefaultSourceSetOutput_Decorated.getClassesDir(Unknown Source)
at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.java:297)
```

That leads to the following [line](https://github.com/flyway/flyway/blob/0bfd37e2c4c7f1dfec9346c798464b5fb238fc86/flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java#L306),
```java
URL classesUrl = sourceSet.getOutput().getClassesDir().toURI().toURL();
```

The fix is probably to iterate over each of the directories in `getClassesDirs()` and add them to `extraURLs`.

I haven't touched the plugin for 4 years, so best that I recall was I added this to support Java migrations. But code evolves so someone more familiar should verify that is the correct change.

**Comment by acetous** [comment] 2017-08-01 12:08
This maybe a duplicate of #1686?

**Comment by axelfontaine** [comment] 2017-08-01 13:08
Thanks @acetous ! Good catch!

Duplicate of #1686

**Closed by axelfontaine** 2017-08-01 13:08 UTC
Labels: m: Gradle, t: bug
