### ISSUE TITLE
Will the table be drop by mistake?

### ISSUE THREAD

**Issue by wulinghui** [flyway/flyway#3369] opened 2021-12-31 01:40 UTC
###### Which version and edition of Flyway are you using?
3.2.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
no 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API     spring-boot 1.6.x

```java 
        @Bean
     public FlywayMigrationInitializer flywayInitializer(Flyway flyway) {
        flyway.setBaselineOnMigrate(true);
        flyway.setCleanOnValidationError(true);
        flyway.setBaselineVersionAsString("0"); 
         return new FlywayMigrationInitializer(flyway, null);  // flyway.migrate();
}
```

###### Which database are you using? (Type & version)
mysql 5.7

###### Which operating system are you using?
linux

###### What did you see instead?
mysql.log

```
/* mysql-connector-java-5.1.46 ( Revision: 9cc87a48e75c2d2e87c1a293b2862ce651cb256e ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
	行 2044714: 2021-12-30T18:11:14.273337+08:00	3396370 Query	SET NAMES utf8
	行 2044720: 2021-12-30T18:11:14.514858+08:00	3396370 Query	SET character_set_results = NULL
	行 2044721: 2021-12-30T18:11:14.526834+08:00	3396370 Query	SET autocommit=1
	行 2044736: 2021-12-30T18:11:14.771662+08:00	3396370 Query	SET autocommit=0
	行 2044737: 2021-12-30T18:11:14.796192+08:00	3396370 Query	SHOW FULL TABLES FROM `cldb` LIKE 'schema_version_ide_nmg'
	行 2044739: 2021-12-30T18:11:14.809163+08:00	3396370 Query	SHOW FULL TABLES FROM `cldb` LIKE 'schema_version_ide_nmg'
	行 2044742: 2021-12-30T18:11:14.826220+08:00	3396370 Query	SELECT `version_rank`,`installed_rank`,`version`,`description`,`type`,`script`,`checksum`,`installed_on`,`installed_by`,`execution_time`,`success` FROM `cldb`.`schema_version_ide_nmg` ORDER BY `version_rank`
	行 2044744: 2021-12-30T18:11:14.846675+08:00	3396370 Query	commit
	行 2044745: 2021-12-30T18:11:14.869189+08:00	3396370 Query	SET autocommit=1
	行 2044749: 2021-12-30T18:11:14.939687+08:00	3396370 Query	SET autocommit=0
	行 2044750: 2021-12-30T18:11:14.955675+08:00	3396370 Query	commit
	行 2044751: 2021-12-30T18:11:14.975676+08:00	3396370 Query	SET autocommit=1
	行 2044752: 2021-12-30T18:11:14.996215+08:00	3396370 Query	SHOW FULL TABLES FROM `cldb` LIKE 'schema_version_ide_nmg'
	行 2044755: 2021-12-30T18:11:15.017151+08:00	3396370 Query	SHOW FULL TABLES FROM `cldb` LIKE 'schema_version_ide_nmg'
	行 2044758: 2021-12-30T18:11:15.036198+08:00	3396370 Query	SELECT COUNT(*) FROM `cldb`.`schema_version_ide_nmg` WHERE `type`='SCHEMA'
	行 2044759: 2021-12-30T18:11:15.049167+08:00	3396370 Query	SELECT COUNT(*) FROM information_schema.schemata WHERE schema_name='cldb'
	行 2044760: 2021-12-30T18:11:15.063186+08:00	3396370 Query	SET autocommit=0
	行 2044761: 2021-12-30T18:11:15.105213+08:00	3396370 Query	SELECT event_name FROM information_schema.events WHERE event_schema='cldb'
	行 2044764: 2021-12-30T18:11:15.138190+08:00	3396370 Query	SELECT routine_name, routine_type FROM information_schema.routines WHERE routine_schema='cldb'
	行 2044767: 2021-12-30T18:11:15.150700+08:00	3396370 Query	SELECT table_name FROM information_schema.views WHERE table_schema='cldb'
	行 2044770: 2021-12-30T18:11:15.174962+08:00	3396370 Query	SET FOREIGN_KEY_CHECKS = 0
	行 2044773: 2021-12-30T18:11:15.211993+08:00	3396370 Query	SELECT table_name FROM information_schema.tables WHERE table_schema='cldb' AND table_type='BASE TABLE'
	行 2044776: 2021-12-30T18:11:15.289478+08:00	3396370 Query	select @@session.transaction_read_only
	行 2044777: 2021-12-30T18:11:15.311054+08:00	3396370 Query	DROP TABLE `cldb`.`act_adm_databasechangelog`
	行 2044778: 2021-12-30T18:11:15.357998+08:00	3396370 Query	select @@session.transaction_read_only
	行 2044779: 2021-12-30T18:11:15.376032+08:00	3396370 Query	DROP TABLE `cldb`.`act_adm_databasechangeloglock`
	行 2044783: 2021-12-30T18:11:15.420959+08:00	3396370 Query	select @@session.transaction_read_only
	行 2044785: 2021-12-30T18:11:15.435484+08:00	3396370 Query	DROP TABLE `cldb`.`act_adm_server_config`
	行 2044786: 2021-12-30T18:11:15.498571+08:00	3396370 Query	select @@session.transaction_read_only
	行 2044787: 2021-12-30T18:11:15.510503+08:00	3396370 Query	DROP TABLE `cldb`.`act_de_databasechangelog`
	行 2044788: 2021-12-30T18:11:15.557986+08:00	3396370 Query	select @@session.transaction_read_only
	行 2044789: 2021-12-30T18:11:15.571987+08:00	3396370 Query	DROP TABLE `cldb`.`act_de_databasechangeloglock`
	行 2044792: 2021-12-30T18:11:15.612463+08:00	3396370 Query	select @@session.transaction_read_only
	行 2044794: 2021-12-30T18:11:15.627999+08:00	3396370 Query	DROP TABLE `cldb`.`act_de_model`
```

**Comment by DoodleBobBuffPants** [comment] 2021-12-31 09:56
As you have said you are unable to reproduce this in the latest version of Flyway, and it isn't clear what the problem is, we recommend updating Flyway

Closing until further activity

**Closed by DoodleBobBuffPants** 2021-12-31 09:56 UTC
