### ISSUE TITLE
ORA-00911: invalid character while inserting and updating

### ISSUE THREAD

**Issue by jantwisted** [flyway/flyway#1135] opened 2015-11-23 11:41 UTC
I faced some problem while running update query through flyway. my query is UPDATE table1 SET THE_COL='FROM_DATE';

according to my investigation, it seems that the problem is with 'FROM_DATE' value. when I change it, I get no error. Furthermore, I used FROM only. Still I got the same error. I'm bit confused why it keeps giving errors with "from" value. I can execute the same query from a db client without any error. 

PS: this applies to insert statements as well.

**Comment by axelfontaine** [comment] 2015-11-23 13:19
Duplicate of #1080

**Closed by axelfontaine** 2015-11-23 13:19 UTC
Labels: r: duplicate
