### ISSUE TITLE
Vertica support not working for flyway version 4.2.0

### ISSUE THREAD

**Issue by vipul412** [flyway/flyway#2314] opened 2019-02-27 18:58 UTC
###### Which version and edition of Flyway are you using?

4.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

Vertica

###### Which operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

###### What did you expect to see?

Vertica support working for flyway

###### What did you see instead?

Flyway internally using PostgresTable class and due to difference in information_schema for vertica and postgres, Vertica support for flyway not working.

Following error comes when using for vertica:

Message    : [Vertica][VJDBC](4650) ERROR: Schema "information_schema" does not exist

	at org.flywaydb.core.internal.dbsupport.Table.exists(Table.java:52) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.upgradeIfNecessary(MetaDataTableImpl.java:95) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:1459) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:971) ~[flyway-core-4.2.0.jar:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1758) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	... 15 common frames omitted
Caused by: java.sql.SQLException: [Vertica][VJDBC](4650) ERROR: Schema "information_schema" does not exist
	at com.vertica.util.ServerErrorData.buildException(Unknown Source) ~[vertica-jdbc-9.0.1-7.jar:na]
	at com.vertica.io.ProtocolStream.readExpectedMessage(Unknown Source) ~[vertica-jdbc-9.0.1-7.jar:na]
	at com.vertica.dataengine.VDataEngine.prepareImpl(Unknown Source) ~[vertica-jdbc-9.0.1-7.jar:na]
	at com.vertica.dataengine.VDataEngine.prepare(Unknown Source) ~[vertica-jdbc-9.0.1-7.jar:na]
	at com.vertica.dataengine.VDataEngine.prepare(Unknown Source) ~[vertica-jdbc-9.0.1-7.jar:na]
	at com.vertica.jdbc.common.SPreparedStatement.<init>(Unknown Source) ~[vertica-jdbc-9.0.1-7.jar:na]
	at com.vertica.jdbc.jdbc4.S4PreparedStatement.<init>(Unknown Source) ~[vertica-jdbc-9.0.1-7.jar:na]
	at com.vertica.jdbc.VerticaJdbc4PreparedStatementImpl.<init>(Unknown Source) ~[vertica-jdbc-9.0.1-7.jar:na]
	at com.vertica.jdbc.VJDBCObjectFactory.createPreparedStatement(Unknown Source) ~[vertica-jdbc-9.0.1-7.jar:na]
	at com.vertica.jdbc.common.SConnection.prepareStatement(Unknown Source) ~[vertica-jdbc-9.0.1-7.jar:na]
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:311) ~[HikariCP-3.2.0.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[HikariCP-3.2.0.jar:na]
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.queryForBoolean(JdbcTemplate.java:181) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLTable.doExists(PostgreSQLTable.java:48) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.dbsupport.Table.exists(Table.java:50) ~[flyway-core-4.2.0.jar:na]
	... 21 common frames omitted
Caused by: com.vertica.support.exceptions.ErrorException: [Vertica][VJDBC](4650) ERROR: Schema "information_schema" does not exist
	... 36 common frames omitted

**Comment by vipul412** [comment] 2019-02-27 19:13
It requires some bug fixes to use vertica related configuration.
Like v_catalog schema instead of information_schema

**Comment by axelfontaine** [comment] 2019-02-28 03:53
Duplicate of #1855

**Closed by axelfontaine** 2019-02-28 03:53 UTC
