### ISSUE TITLE
Feature request: New callback that gets executed after a failed migration

### ISSUE THREAD

**Issue by codingthat** [flyway/flyway#1709] opened 2017-07-12 19:13 UTC
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

command-line

###### What database are you using (type & version)?

PostgreSQL 9.4.12

###### What operating system are you using?

Linux Mint 18.1 64-bit

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

https://dba.stackexchange.com/questions/179589/must-be-superuser-or-have-the-same-role-to-terminate-other-server-processes-wi

(That issue itself aside, you can see my before and after callbacks described.)

###### What did you expect to see?

I guess I had expected the afterMigrate.sql file to be executed even upon rollback.  But I realized this isn't always desirable.

###### What did you see instead?

It's not.

But unless I'm missing something, I'm probably not the only one who would want to kick users out and make them unable to connect during a migration.  Of course, after a failed migration, this automatically leaves users unable to reconnect to the now-rolled-back database.

So I propose a new callback: afterRollback, or perhaps afterMigrationWhetherFailedOrNot (but with a better name) which would make it so I wouldn't be duplicating code between afterRollback and afterMigration.

**Comment by axelfontaine** [comment] 2017-11-27 08:40
Duplicate of #1392

**Closed by axelfontaine** 2017-11-27 08:40 UTC
Labels: m: Core, t: feature
