### ISSUE TITLE
Delimiter changed inside statement, while executing procedure in flyway for MYSQL

### ISSUE THREAD

**Issue by Jawed-Aquib** [flyway/flyway#3511] opened 2022-08-29 06:49 UTC
###### Which version and edition of Flyway are you using?
8.0.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven Plugin

###### Which database are you using? (Type & version)
MySQL , 8.0.28

###### Which operating system are you using?
LINUX

###### What did you expect to see?
```
-- stored procedures
DELIMITER $$
$$
CREATE DEFINER=`master`@`%` PROCEDURE `account_management`.`internal_account_list`(
IN glAccountNumber VARCHAR(150),
...
)
BEGIN
set @whereCondition = CONCAT("WHERE ia.create_time > '","2020-01-01", "'");
case when glAccountNumber is not null then
set @whereCondition = CONCAT(@whereCondition ," AND ia.gl_account_number = '",glAccountNumber,"'");
else
....(mutiple case statements)
END case;
set @sql = concat("SELECT SQL_CALC_FOUND_ROWS ia.gl_account_number as glAccountNumber,
...
-- SELECT @sql;
PREPARE stmt FROM @sql;
EXECUTE stmt;
SELECT FOUND_ROWS() INTO total_count;
SET responseCode = 000, responseMessage = CONCAT("Response generated successfully.");
END $$
DELIMITER  ;

```

###### What did you see instead?
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:8.0.0:migrate (default-cli) on project flyway-db-migration: org.flywaydb.core.api.FlywayException: 
Unable to parse statement in C:\Users\aquib.jawed\Documents\ConnectPay\INFRA\flyway-db-migration\src\main\resources\db\migration\V1__abc.sql at line 582 col 7. See
 https://rd.gt/3ipi7Pm for more information: Delimiter changed inside statement at line 582 col 7: ;

**Comment by DoodleBobBuffPants** [comment] 2022-08-30 09:10
I am unable to reproduce this bug in the latest version Flyway, so it may already have been solved - could you try the latest version and see if that works?

Closing this until further activity

**Closed by DoodleBobBuffPants** 2022-08-30 09:10 UTC
