### ISSUE TITLE
Flyway clean lasts long in Oracle db

### ISSUE THREAD

**Issue by lukasito** [flyway/flyway#1486] opened 2016-12-09 09:10 UTC
###### What version of Flyway are you using?
- 4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
- SBT
- Gradle

###### What database are you using (type & version)?
- Oracle

###### What operating system are you using?
- Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
- flywayClean

###### What did you expect to see?
- That flywayClean lasts few seconds

###### What did you see instead?
- That flywayClean lasts 10 minutes even when only 1 table was in database. With flyway version 3.2.1 it lasts only few seconds.

**Comment by frankschmitt** [comment] 2016-12-09 15:21
FWIW, I cannot reproduce this with the flyway command line tool (version 4.0.3) - running 'flyway clean' against an 11.2 XE database running in a Docker container takes only a couple seconds.

Is your Oracle DB running locally or remotely? Which version of Oracle are you running, and which version of the oracle JDBC driver are you using to connect?

**Comment by lukasito** [comment] 2016-12-12 12:18
We're running oracle remotely, Oracle Database 11g Enterprise Edition Release 11.2.0.2.0 - 64bit Production. We're using orjdbc6 11.2.0.4 driver

**Comment by axelfontaine** [comment] 2017-01-30 20:17
Without further info on which statement may be causing the issue, I am afraid there is not much we can do. Can you debug the issue and find out?

**Comment by lukasito** [comment] 2017-01-31 14:03
There was a great delay after line: `DEBUG: Oracle Spatial Extensions are not available. No cleaning of MDSYS tables and views.` 
We were using cmdline flyway version that supports -X switch for debugging. Is it enough?

```
C:\Apps\flyway-4.0.3>flyway -X clean
Flyway 4.0.3 by Boxfuse

DEBUG: Java 1.8.0_74 (Oracle Corporation)
DEBUG: Windows 7 6.1 amd64

DEBUG: Loading config file: C:\Apps\flyway-4.0.3\conf\flyway.conf
DEBUG: Unable to load config file: C:\Users\martin.solc\flyway.conf
DEBUG: Unable to load config file: C:\Apps\flyway-4.0.3\flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.placeholders.tablespace.index -> USERS
DEBUG: flyway.jarDirs -> C:\Apps\flyway-4.0.3\jars
DEBUG: flyway.password -> *******
DEBUG: flyway.url -> jdbc:oracle:thin:@q-ora-db-scan.w****d.sys:1521/stx11de.w
irecard
DEBUG: flyway.schemas -> S****M
DEBUG: flyway.user -> s***m
DEBUG: flyway.locations -> filesystem:C:/dev/repositories/cpos/etl/evolutions
DEBUG: Adding location to classpath: C:\Apps\flyway-4.0.3\drivers\derby-10.12.1.1.jar
DEBUG: Adding location to classpath: C:\Apps\flyway-4.0.3\drivers\derbyclient-10.12.1.1.jar
DEBUG: Adding location to classpath: C:\Apps\flyway-4.0.3\drivers\h2-1.4.191.jar
DEBUG: Adding location to classpath: C:\Apps\flyway-4.0.3\drivers\hsqldb-2.3.3.jar
DEBUG: Adding location to classpath: C:\Apps\flyway-4.0.3\drivers\jtds-1.3.1.jar
DEBUG: Adding location to classpath: C:\Apps\flyway-4.0.3\drivers\mariadb-java-client-1.4.5.jar
DEBUG: Adding location to classpath: C:\Apps\flyway-4.0.3\drivers\postgresql-9.4.1208.jre6.jar
DEBUG: Adding location to classpath: C:\Apps\flyway-4.0.3\drivers\sqlite-jdbc-3.7.15-M1.jar
DEBUG: Adding location to classpath: C:\Apps\flyway-4.0.3\jars\ojdbc6-11.2.0.4.jar
Database: jdbc:oracle:thin:@q-ora-db-scan.w****d.sys:1521/stx11de.w****d (Oracle 11.2)
DEBUG: DDL Transactions Supported: false
DEBUG: Schema: S***M
DEBUG: Spring Jdbc available: false
DEBUG: Scanning for SQL callbacks ...
DEBUG: Scanning for filesystem resources at 'C:/dev/repositories/cpos/etl/evolutions' (Prefix: '', Suffix: '.sql')
DEBUG: Scanning for resources in path: C:\dev\repositories\cpos\etl\evolutions (C:/dev/repositories/cpos/etl/evolutions)
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V10__incre...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V11__fill_...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V12__more_...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V13__custo...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V14__add_m...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V15__add_c...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V16__add_r...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V17__remov...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V18__some_...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V19__add_p...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V1__Creat...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V20__remov...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V21__add_a...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V22__indic...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V23__add_o...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V24__add_b...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V25__add_p...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V26__add_i...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V27__run_l...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V2__Add_c...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V3__corre...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V4__custo...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V5__drop_...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V6__creat...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V7__fill_...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V8__incre...sql
DEBUG: Found filesystem resource: C:\dev\repositories\cpos\etl\evolutions\V9__add_s...sql
DEBUG: Cleaning schema "S***M" ...
DEBUG: Oracle Spatial Extensions are not available. No cleaning of MDSYS tables
and views.
Successfully cleaned schema "S***M" (execution time 11:42.731s)

C:\Apps\flyway-4.0.3>
```

**Comment by axelfontaine** [comment] 2017-01-31 17:19
Well the delay is there because that's when the cleaning happens. I am afraid we need more info to be able to act on this. Please debug and isolate the exact statement causing the issue.

**Comment by axelfontaine** [comment] 2017-03-20 13:47
Any news?

**Comment by lukasito** [comment] 2017-03-20 14:42
Can you please suggest me some potential solutions how to debug this issue?

**Comment by axelfontaine** [comment] 2017-03-20 14:44
Create a small test program that uses flyway-core and debug in your IDE. The SBT and Gradle plugins are only thin wrappers around the core and aren't relevant in this case.

**Comment by pauxus** [comment] 2017-03-23 13:02
I suppose the reasons are the ones addressed in #1565 / #1550 

The basically happen only when there are a lot of tables (outside of the schemas managed by flyway)

**Comment by davidepedranz** [comment] 2017-03-24 18:08
I have the same problem when running many JUnit test cases. I clean the database before each test case. In my case the database contains just 2 small tables (5-10 columns, 3-4 rows, depending on the specific test), but the clean() command lasts 18 seconds.

I am using Oracle 11g Express Edition (11.2.0-1.0, in particular I run this Docker image: https://hub.docker.com/r/alexeiled/docker-oracle-xe-11g/). I have the issue with both Flyway 4.0.3 and 4.1.2.

Can I help to debug this somehow?

**Comment by vosolovskiy** [comment] 2017-04-02 21:57
If the inefficient `doAllTables()` implementation was the reason, then this should be fixed in the master now. Try to build Flyway from master and test it.

On 4.1.2 try to log execution time for `doAllTables()` and for actual drops.

**Comment by axelfontaine** [comment] 2017-04-03 08:30
Closing as most likely fixed with recent improvements in this area. Please reopen if still present when using the latest sources.

**Closed by axelfontaine** 2017-04-03 08:30 UTC
Labels: d: Oracle, s: waiting for feedback
