### ISSUE TITLE
Support for MemSQL Database in Flyway

### ISSUE THREAD

**Issue by pradheeps** [flyway/flyway#1385] opened 2016-08-01 15:08 UTC
MemSQL is a in-memmory and disk based distributed and relational type database which is highly scalable.
MemSQL uses Mysql jdbc connector. We use flyway for database migrations for DB2 and MySQL and would like to add MemSQL to it which is going to be part of our datasystems.
Please see pull request for implementation details.

**Comment by axelfontaine** [comment] 2016-08-01 15:14
Duplicate of #1317

**Closed by axelfontaine** 2016-08-01 15:14 UTC
