### ISSUE TITLE
standard_init_linux.go:207: exec user process caused "permission denied" when running with non-root user on docker

### ISSUE THREAD

**Issue by truongkhanh** [flyway/flyway#2292] opened 2019-02-01 08:26 UTC
###### Which version and edition of Flyway are you using?
5.2.4-alpine

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command Line

###### Which database are you using (type & version)?
Postgres

###### Which operating system are you using?
macOS Mojave

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Run this command `docker run --user postgres -it boxfuse/flyway:5.2.4-alpine migrate`

###### What did you expect to see?
Start the migration process, ask database user

###### What did you see instead?
standard_init_linux.go:207: exec user process caused "permission denied"

If I run without the option `--user postgres` to run as root, it is ok.

My question is how I can run flyway migration with non-root user

**Comment by axelfontaine** [comment] 2019-02-01 08:48
Duplicate of https://github.com/flyway/flyway-docker/pull/7

**Closed by axelfontaine** 2019-02-01 08:48 UTC
