### ISSUE TITLE
Postgresql, clear extensions

### ISSUE THREAD

**Issue by tlenczyk** [flyway/flyway#942] opened 2015-01-26 22:13 UTC
Hi,

I have problem with clearing db.

In one of my migrations there is:

```
CREATE EXTENSION pg_trgm;
```

and when trying to run it using API

```
        Flyway flyway = new Flyway();
        flyway.configure(properties);
        flyway.clean();
```
It throws excepiotn

ERROR: cannot drop type gtrgm because extension pg_trgm requires it
You can drop extension pg_trgm instead.

I'm using dependencies:

```
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>3.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>9.1-901-1.jdbc4</version>
            <scope>test</scope>
        </dependency>
```

Do you have any advices?

**Comment by axelfontaine** [comment] 2015-01-28 10:15
Duplicate of #100

**Closed by axelfontaine** 2015-01-28 10:15 UTC
