### ISSUE TITLE
what is the command to migrate into multiple instance using a single command-line?

### ISSUE THREAD

**Issue by kumarjitu21** [flyway/flyway#1557] opened 2017-03-17 06:26 UTC
###### What version of Flyway are you using?

Flyway-4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

mysql 5.5

###### What operating system are you using?

Windows 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I am trying to migrate the same Query change into multiple environment in a single shot

**Comment by axelfontaine** [comment] 2017-03-17 06:55
Duplicate of #1039

**Closed by axelfontaine** 2017-03-17 06:55 UTC
