### ISSUE TITLE
Overall ordering of Java and SQL Callbacks

### ISSUE THREAD

**Issue by laurentgrangier** [flyway/flyway#2785] opened 2020-04-24 08:03 UTC
#### Context

Ordering of Callbacks is defined according to [document ](https://flywaydb.org/documentation/callbacks)this way:

> When multiple callbacks for the same event are found, they are executed in the following order:
> 
> - Java callbacks, in the order in which they are specified in the callbacks configuration property
> - SQL callbacks, in alphabetic order of their description.

We need to execute Callbacks in a specific orders and we have some Callbacks writen in SQL and some callbacks written with Java.

For instance, the 3 following Callbacks cannot be executed with Flyway in the order I would like (1, 2 and then 3): 
- AfterMigrate__1_DoSomething.java (implements Callback)
- afterMigrate__2_DoSomethingElse.sql
- AfterMigrate__3_DoSomethingElseInJava.java (implements Callback)

#### Feature Request

I expect Flyway to use a global ordering of the Callbacks independant of their types. The ordering could be done using the name of the class and the name of the scripts as it is done for versioned migrations.

**Comment by juliahayward** [comment] 2020-04-24 08:31
Hi! We are looking at both identifying Java callbacks by reflection (rather than specifying in configuration) and allowing this interleaving of Java and SQL for Flyway v7, which is not far away. It is potentially a breaking change for users who are used to the current behaviour, which is why we haven't added it to v6. (Duplicate of #2760)

**Comment by laurentgrangier** [comment] 2020-04-24 08:34
Thank you 👍

**Comment by DoodleBobBuffPants** [comment] 2020-09-03 09:36
This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).

**Closed by DoodleBobBuffPants** 2020-09-03 09:36 UTC
Labels: t: feature
