### ISSUE TITLE
bug: v7 + Snowflake - passing properties between fw and jdbc has some issue

### ISSUE THREAD

**Issue by filiprichtarik** [flyway/flyway#3109] opened 2021-03-15 10:49 UTC
###### Which version and edition of Flyway are you using

V7.7.0 Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

this issue exists from 7.0.0-beta1 to the latest 7.x, 

i assume the cause can be found in diff between tag 6.5.7 and 7.0.0-beta1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
cmdline

###### Which database are you using? (Type & version)
snowflake 5.7, can be reproduced with all JDBC versions between 3.11.1 - 3.13.1 (latest)

###### Which operating system are you using?
linux (ubuntu 16.04)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

running migrate, username and password are saved in env variables (same as before with v6) but something in passing the credentials between fw and jdbc fails with v7 (i had to obfuscate sensitive IDs from URL)

Flyway migration error log:
INFO:root:core - ERROR: Unexpected error
INFO:root:core - org.flywaydb.core.internal.exception.FlywaySqlException: 
INFO:root:core - Unable to obtain connection from database (jdbc:snowflake://#instance ID#.snowflakecomputing.com/?warehouse=#wh ID#&db=#db ID#&schema=#schema ID#&role=#role ID#) for user ****: Incorrect username or password was specified.
INFO:root:core - ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INFO:root:core - SQL State  : 08001
INFO:root:core - Error Code : 390100
INFO:root:core - Message    : Incorrect username or password was specified.
INFO:root:core - 
INFO:root:core - 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:68)
INFO:root:core - 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:69)
INFO:root:core - 	at org.flywaydb.core.Flyway.execute(Flyway.java:507)
INFO:root:core - 	at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
INFO:root:core - 	at org.flywaydb.commandline.Main.executeOperation(Main.java:223)
INFO:root:core - 	at org.flywaydb.commandline.Main.main(Main.java:144)
INFO:root:core - Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: Incorrect username or password was specified.
INFO:root:core - 	at net.snowflake.client.core.SessionUtil.newSession(SessionUtil.java:602)
INFO:root:core - 	at net.snowflake.client.core.SessionUtil.openSession(SessionUtil.java:279)
INFO:root:core - 	at net.snowflake.client.core.SFSession.open(SFSession.java:435)
INFO:root:core - 	at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initialize(DefaultSFConnectionHandler.java:103)
INFO:root:core - 	at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initializeConnection(DefaultSFConnectionHandler.java:79)
INFO:root:core - 	at net.snowflake.client.jdbc.SnowflakeConnectionV1.initConnectionWithImpl(SnowflakeConnectionV1.java:116)
INFO:root:core - 	at net.snowflake.client.jdbc.SnowflakeConnectionV1.<init>(SnowflakeConnectionV1.java:96)
INFO:root:core - 	at net.snowflake.client.jdbc.SnowflakeDriver.connect(SnowflakeDriver.java:164)
INFO:root:core - 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:325)
INFO:root:core - 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:289)
INFO:root:core - 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:59)
INFO:root:core - 	... 5 more

###### What did you expect to see?

i expected migration to succeed. 

creds are working (tried in several ways)

i tried several combinations of FW with JDBC versions,  JDBC version makes no difference here (all working with v6, all not working with v7), change from FW v6.5.7 to v7.0.0-beta1 is the breaking point, i'd look for the issue in commits from diff between v6.5.7 to v7.0.0-beta1

**Comment by Rixium** [comment] 2021-03-17 12:04
Hey @filiprichtarik ,

Can you share you full debug output (**run flyway with -X**)
and can you verify that it is using your environment variables that you set, and that they're not being overridden somewhere,

Thanks 😃

**Comment by filiprichtarik** [comment] 2021-03-17 12:31
Hi @Rixium 
no credentials override anywhere, sure of it because that would cause issue on the 6.5.7 too, tested even by moving those into flyway.conf for a few tries, but no change

migration run with -X, no obvious additional data (sorry but i had to anonymize all references to company, product or other internals)



`INFO:root:core - DEBUG: Loading config file: /var/lib/jenkins/workspace/#ANONYMIZED#/flyway/conf/flyway.conf
INFO:root:core - DEBUG: Unable to load config file: /var/lib/jenkins/flyway.conf
INFO:root:core - DEBUG: Unable to load config file: /var/lib/jenkins/workspace/_bbdata-qa-fw7/dev_operations/scripts/flyway.conf
INFO:root:core - DEBUG: Adding location to classpath: /var/lib/jenkins/workspace/#ANONYMIZED#/flyway/drivers/snowflake-jdbc-3.13.1.jar
INFO:root:core - DEBUG: Using configuration:
INFO:root:core - DEBUG: flyway.jarDirs -> /var/lib/jenkins/workspace/#ANONYMIZED#/flyway/jars
INFO:root:core - DEBUG: flyway.locations -> filesystem:/var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core
INFO:root:core - DEBUG: flyway.password -> ***************
INFO:root:core - DEBUG: flyway.placeholderPrefix -> @{
INFO:root:core - DEBUG: flyway.placeholderSuffix -> }
INFO:root:core - DEBUG: flyway.placeholders.#ANONYMIZED# -> #ANONYMIZED#
INFO:root:core - DEBUG: flyway.placeholders.#ANONYMIZED# -> #ANONYMIZED#
INFO:root:core - DEBUG: flyway.placeholders.#ANONYMIZED# -> #ANONYMIZED#
INFO:root:core - DEBUG: flyway.schemas -> CORE
INFO:root:core - DEBUG: flyway.table -> SCHEMA_VERSION
INFO:root:core - DEBUG: flyway.url -> jdbc:snowflake://#ANONYMIZED#.snowflakecomputing.com/?warehouse=#ANONYMIZED#&db=#ANONYMIZED#&schema=core&role=#ANONYMIZED#
INFO:root:core - DEBUG: flyway.user -> ****
INFO:root:core - DEBUG: Scanning for classpath resources at 'classpath:db/callback' ...
INFO:root:core - DEBUG: Determining location urls for classpath:db/callback using ClassLoader java.net.URLClassLoader@5afa04c ...
INFO:root:core - DEBUG: Unable to resolve location classpath:db/callback.
INFO:root:core - Flyway Community Edition 7.7.0 by Redgate
INFO:root:core - DEBUG: AWS SDK available: false
INFO:root:core - DEBUG: Google Cloud Storage available: false
INFO:root:core - DEBUG: Scanning for filesystem resources at '/var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core'
INFO:root:core - DEBUG: Scanning for resources in path: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core (/var/lib/jenkins/workspace/_bbdata-qa-fw7/cloud_data_platform/core/migrations/core)
INFO:root:core - DEBUG: Scanning for resources in path: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core/repeatable (/var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core)
INFO:root:core - DEBUG: Scanning for resources in path: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core/versioned (/var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core)
INFO:root:core - DEBUG: Found filesystem resource: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core/repeatable/#ANONYMIZED#
INFO:root:core - DEBUG: Found filesystem resource: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core/repeatable/#ANONYMIZED#
INFO:root:core - DEBUG: Found filesystem resource: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core/versioned/#ANONYMIZED#
INFO:root:core - DEBUG: Found filesystem resource: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core/versioned/#ANONYMIZED#
INFO:root:Flyway migration error log:
INFO:root:core - ERROR: Unexpected error
INFO:root:core - org.flywaydb.core.internal.exception.FlywaySqlException: 
INFO:root:core - Unable to obtain connection from database (jdbc:snowflake://#ANONYMIZED#.snowflakecomputing.com/?warehouse=#ANONYMIZED#&db=#ANONYMIZED#&schema=core&role=#ANONYMIZED#) for user ****: Incorrect username or password was specified.
INFO:root:core - ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INFO:root:core - SQL State  : 08001
INFO:root:core - Error Code : 390100
INFO:root:core - Message    : Incorrect username or password was specified.
INFO:root:core - 
INFO:root:core - 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:68)
INFO:root:core - 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:69)
INFO:root:core - 	at org.flywaydb.core.Flyway.execute(Flyway.java:507)
INFO:root:core - 	at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
INFO:root:core - 	at org.flywaydb.commandline.Main.executeOperation(Main.java:223)
INFO:root:core - 	at org.flywaydb.commandline.Main.main(Main.java:144)
INFO:root:core - Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: Incorrect username or password was specified.
INFO:root:core - 	at net.snowflake.client.core.SessionUtil.newSession(SessionUtil.java:602)
INFO:root:core - 	at net.snowflake.client.core.SessionUtil.openSession(SessionUtil.java:279)
INFO:root:core - 	at net.snowflake.client.core.SFSession.open(SFSession.java:435)
INFO:root:core - 	at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initialize(DefaultSFConnectionHandler.java:103)
INFO:root:core - 	at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initializeConnection(DefaultSFConnectionHandler.java:79)
INFO:root:core - 	at net.snowflake.client.jdbc.SnowflakeConnectionV1.initConnectionWithImpl(SnowflakeConnectionV1.java:116)
INFO:root:core - 	at net.snowflake.client.jdbc.SnowflakeConnectionV1.<init>(SnowflakeConnectionV1.java:96)
INFO:root:core - 	at net.snowflake.client.jdbc.SnowflakeDriver.connect(SnowflakeDriver.java:164)
INFO:root:core - 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:325)
INFO:root:core - 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:289)
INFO:root:core - 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:59)
INFO:root:core - 	... 5 more`

**Comment by Rixium** [comment] 2021-03-17 13:23
Hey @filiprichtarik ,

Can you provide a set of reproduction steps and a snowflake configuration, if possible?
We've tested this locally, and haven't been able to reproduce.

Thanks

**Comment by filiprichtarik** [comment] 2021-03-17 13:58
not sure what other reproduction steps do you have in mind

we basically download fw cmdline archive, unzip it, replace contents of flyway.conf and run migrate with params described in previous comment, nothing more, nothing less

what snowflake configuration do you mean - account parameters or sth else?

**Comment by Rixium** [comment] 2021-03-17 17:42
Hey @filiprichtarik ,

Your log looks fine to me.
Can you confirm that the output makes sense for both the password and the username, as set in your environment variables? (We obfuscate the password in the ouput with a matching length of asterisks, so its length should match your password length).

We don't seem to do the same for the user, so I'm assuming you've obfuscated that yourself in the output.

Can you also verify that the config file is the correct one that it's using:
/var/lib/jenkins/workspace/#ANONYMIZED#/flyway/conf/flyway.conf

It may be helpful if you can provide the debug (-X) output for one of the previous (working) versions too, so I can see if I can spot anything there,

Thanks!

**Comment by filiprichtarik** [comment] 2021-03-17 18:15
Hey @Rixium . 

creds are correct, obfuscation on fw side is ok, length of pwd vs asterisks matches, 
user is obfuscated only in console log and via security rules on jenkins, the value at the moment of execution is correct. 

Confirmed that by moving creds from env variables to flyway.conf - migration fails on the same step , i can see that config file was last edited before migration started, so there is no funky bussiness going on with them during the migration either.

Made sure that this is the only conf file available, and logged values match to the content of file, so we can rule this one out too. 

i'll switch back to 6.5.7 and run again, output will be in the next comment

**Comment by filiprichtarik** [comment] 2021-03-17 18:52
while i am waiting. 

i wonder if there was not change in encoding of the credentials or sth else, on the other hand, we don't use any special characters, except underscore in username "_"

once again anonymized, fw 6.5.7, 

`
INFO:root:core - DEBUG: Loading config file: /var/lib/jenkins/workspace/#ANONYMIZED#/flyway/conf/flyway.conf
INFO:root:core - DEBUG: Unable to load config file: /var/lib/jenkins/flyway.conf
INFO:root:core - DEBUG: Unable to load config file: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/scripts/flyway.conf
INFO:root:core - DEBUG: Using configuration:
INFO:root:core - DEBUG: flyway.jarDirs -> /var/lib/jenkins/workspace/#ANONYMIZED#/flyway/jars
INFO:root:core - DEBUG: flyway.locations -> filesystem:/var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core
INFO:root:core - DEBUG: flyway.password -> ***************
INFO:root:core - DEBUG: flyway.placeholderPrefix -> @{
INFO:root:core - DEBUG: flyway.placeholderSuffix -> }
INFO:root:core - DEBUG: flyway.placeholders.#ANONYMIZED# -> #ANONYMIZED#
INFO:root:core - DEBUG: flyway.placeholders.#ANONYMIZED# -> #ANONYMIZED#
INFO:root:core - DEBUG: flyway.placeholders.#ANONYMIZED# -> #ANONYMIZED#
INFO:root:core - DEBUG: flyway.schemas -> CORE
INFO:root:core - DEBUG: flyway.table -> SCHEMA_VERSION
INFO:root:core - DEBUG: flyway.url -> jdbc:snowflake://#ANONYMIZED#.snowflakecomputing.com/?warehouse=#ANONYMIZED#&db=#ANONYMIZED#&schema=core&role=#ANONYMIZED#
INFO:root:core - DEBUG: flyway.user -> ****
INFO:root:core - DEBUG: Adding location to classpath: /var/lib/jenkins/workspace/#ANONYMIZED#/flyway/drivers/snowflake-jdbc-3.12.12.jar
INFO:root:core - Flyway Community Edition 6.5.7 by Redgate
INFO:root:core - DEBUG: Scanning for filesystem resources at '/var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core'
INFO:root:core - DEBUG: Scanning for resources in path: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core (/var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core)
INFO:root:core - DEBUG: Scanning for resources in path: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core/repeatable (/var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core)
INFO:root:core - DEBUG: Scanning for resources in path: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core/versioned (/var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core)
INFO:root:core - DEBUG: Found filesystem resource: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core/repeatable/#ANONYMIZED#
INFO:root:core - DEBUG: Found filesystem resource: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core/versioned/#ANONYMIZED#
INFO:root:core - Database: jdbc:snowflake://#ANONYMIZED#.snowflakecomputing.com:443/ (Snowflake 5.7)
INFO:root:core - DEBUG: Driver  : Snowflake 3.12.12
INFO:root:core - DEBUG: DDL Transactions Supported: false
INFO:root:core - DEBUG: Schemas: CORE
INFO:root:core - DEBUG: Default schema: null
INFO:root:core - WARNING: Flyway upgrade recommended: Snowflake 5.7 is newer than this version of Flyway and support has not been tested. The latest supported version of Snowflake is 4.2.
INFO:root:core - DEBUG: Scanning for SQL callbacks ...
INFO:root:core - DEBUG: Filtering out resource: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core/repeatable/#ANONYMIZED# (filename: #ANONYMIZED#)
INFO:root:core - DEBUG: Filtering out resource: /var/lib/jenkins/workspace/#ANONYMIZED#/#ANONYMIZED#/core/migrations/core/versioned/#ANONYMIZED# (filename: #ANONYMIZED#)
INFO:root:core - DEBUG: Creating schema: "CORE"
INFO:root:core - Creating schema "CORE" ...
INFO:root:core - Creating Schema History table "CORE"."SCHEMA_VERSION" ...
INFO:root:core - DEBUG: Parsing  ...   
...... rest is just execution
`

**Comment by filiprichtarik** [comment] 2021-03-17 20:58
IMHO i started to dig in repo history and i believe it has sth to do with this change https://github.com/flyway/flyway/commit/129578ce6861f5a7726f2175a41b8fc3fdf3b945

**Comment by Rixium** [comment] 2021-03-18 11:09
Hey @filiprichtarik ,

I tried to reproduce the issue again this morning, but I'm still not managing to.
I ran flyway using a schema, and a role as specified in your JDBC URL, and it worked in both 6.5.7 and our latest version.

Is it possible you can try in a different environment?

Thanks!

**Comment by Rixium** [comment] 2021-03-18 11:23
If possible, can you also try a reproduction outside of Jenkins? As we don't maintain that.

**Comment by DoodleBobBuffPants** [comment] 2021-03-22 18:33
Closing until we can get a reproduction

**Closed by DoodleBobBuffPants** 2021-03-22 18:33 UTC
Labels: s: waiting for feedback

**Comment by frichtarik** [comment] 2021-06-04 10:27
Finally had time to get back to this. 
i've tested described scenario on brand new linux worker VM on jenkins, on my Catalina mac with latest cmdline package (Community Edition 7.9.2 by Redgate), I even tried to run it via your official Docker image latest. 

result is every time the same (on all our SF regions) even though the credentials work 

Incorrect username or password was specified.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 390100
Message    : Incorrect username or password was specified.

	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:71)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:68)
	at org.flywaydb.core.Flyway.execute(Flyway.java:510)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:170)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:228)
	at org.flywaydb.commandline.Main.main(Main.java:149)
Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: Incorrect username or password was specified.
	at net.snowflake.client.core.SessionUtil.newSession(SessionUtil.java:602)
	at net.snowflake.client.core.SessionUtil.openSession(SessionUtil.java:279)
	at net.snowflake.client.core.SFSession.open(SFSession.java:435)
	at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initialize(DefaultSFConnectionHandler.java:103)
	at net.snowflake.client.jdbc.DefaultSFConnectionHandler.initializeConnection(DefaultSFConnectionHandler.java:79)
	at net.snowflake.client.jdbc.SnowflakeConnectionV1.initConnectionWithImpl(SnowflakeConnectionV1.java:116)
	at net.snowflake.client.jdbc.SnowflakeConnectionV1.<init>(SnowflakeConnectionV1.java:96)
	at net.snowflake.client.jdbc.SnowflakeDriver.connect(SnowflakeDriver.java:164)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:263)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:227)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:55)

next i'm going to debug the issue with v7 and v6 flyway so we can be sure it's not in your code (some distortion of credentials at the moment of passing them to jdbc driver)
and depending on the result i'll reopen this issue or create issue for snowflake dev team (possible issue in jdbc or our sf instances setup)

**Comment by filiprichtarik** [comment] 2021-06-06 22:25
Hello @Rixium @DoodleBobBuffPants, could you please reopen this issue?

i got interesting output of debugging session proving that issue is in flyway code 

we are using **placeholders** in our files (values set in config file) and i'm guessing your internal tests don't, that§s why they don't fail

crap hits the fan only when they are in config, when i removed the values, voila, connection success

i was able to figure out that dataSource -> additionalProperties hashmap contains placeholders if they are in config and it screws sth while creating connection, no idea what though

we use the same placeholders since flyway v4 came out, so i can vouch that it worked until now (we are still stuck on v6 because of this)

**Comment by DoodleBobBuffPants** [comment] 2021-06-07 08:12
Thanks for investigating this

What you're experiencing is likely one of the breaking changes we made in Flyway V7. Placeholders are now supplied to the JDBC driver when creating a connection, so special values such as `password` will be picked up by the driver and used. Could you try renaming your placeholders?

If this is the case, we likely won't change this behavior unless there is more interest in doing so

**Comment by filiprichtarik** [comment] 2021-06-07 09:08
great piece of advice, when i focused on the names of placeholders, it seems that only issue is with "ACCOUNT"
possibly reserved keyword in snowflake jdbc (maybe others too)

we'll rename it (pain but viable), but this should be at least mentioned on the placeholder doc page, 
https://flywaydb.org/documentation/configuration/placeholder
