### ISSUE TITLE
Problem with quoted Strings ending with N

### ISSUE THREAD

**Issue by soemeier** [flyway/flyway#972] opened 2015-03-19 07:20 UTC
If I try to create an Migration File for oracle the the following:

    insert into table (COLUMN) values ('TESTWITH_ENDING_N');
    insert into table (COLUMN) values ('some other quoted string');

The script fails because flyway does not terminate the first statement correctly. I will also provide a pull request to actually fix the problem.

**Comment by axelfontaine** [comment] 2015-03-20 10:45
duplicate of #971

**Closed by axelfontaine** 2015-03-20 10:45 UTC
Labels: bug, Core, Oracle
