### ISSUE TITLE
How to handle multiple independent components sharing same schema, in case of multi tenant scenario and specific component want to perform clean ? 

### ISSUE THREAD

**Issue by ankireddy501** [flyway/flyway#1473] opened 2016-11-22 02:56 UTC
we have several components maintaining the database migration scripts independently but sharing the same schema, and during the database restore we would like to clean only specific component tables since database restore is component specific. 
do you have plan to support clean with some kind of regular expression, which helps to select specific tables ?
SCHMEA_VERSION table do we allow to add additional column like component ?

**Comment by axelfontaine** [comment] 2017-01-31 17:18
Duplicate of #848

**Closed by axelfontaine** 2017-01-31 17:18 UTC
