### ISSUE TITLE
Allow creation of schema history table on non-empty schemas

### ISSUE THREAD

**Issue by Randgalt** [flyway/flyway#3184] opened 2021-05-29 08:47 UTC
###### Which version and edition of Flyway are you using?

7.9.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

Postrgres 11

###### Which operating system are you using?

MacOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We have libraries that need to do a separate migration flow in the same database as the main application. The obvious solution is to have libraries run their own Flyway flow with an alternate history table name. However, this is currently not possible with Flyway because Flyway will throw an exception when the schema is not empty and the history table is missing.

PR: https://github.com/flyway/flyway/pull/3185

**Comment by DoodleBobBuffPants** [comment] 2021-06-01 11:05
In this case, you should migrate with [`baselineOnMigrate`](https://flywaydb.org/documentation/configuration/parameters/baselineOnMigrate) set to true, as you need to baseline when creating the schema history table in a non-empty schema

Does this work for you?

**Comment by Randgalt** [comment] 2021-06-01 11:09
I tried that but then my scripts aren’t run. I couldn’t find good documentation on this. So, no, it didn’t work for me.

**Comment by DoodleBobBuffPants** [comment] 2021-06-01 11:13
Could you provide a reproduction where the scripts aren't run when migrating with `baselineOnMigrate` enabled?

It might be due to the version you have baselined at, in which case [`baselineVersion`](https://flywaydb.org/documentation/configuration/parameters/baselineVersion) needs to be lower than the version of the first migration you want to run

**Comment by DoodleBobBuffPants** [comment] 2021-06-07 08:25
Closing until further activity

**Closed by DoodleBobBuffPants** 2021-06-07 08:25 UTC
Labels: s: waiting for feedback

**Comment by Randgalt** [comment] 2021-06-07 10:50
OK - I have the baseline version working. While cumbersome, it works. The fact that I have to set the baseline version to "0" and my first script has to start at "1" is an oddity that should be addressed someday. For anyone looking here, here's how you configure things so that an "embedded" library can do it's own bespoke migration:

```java
new FluentConfiguration()
   ... // whatever you want here as needed
   .table(customSchemaHistoryTableName)
   .locations(pathInYourLibrary)
   .baselineOnMigrate(true)
   .baselineVersion("0")
```

Note: your migration script must start at version "1"
