### ISSUE TITLE
Unable to create type  using inheritance  with "UNDER" keyword 

### ISSUE THREAD

**Issue by BaburaoLad** [flyway/flyway#3169] opened 2021-05-11 20:42 UTC
###### Which version and edition of Flyway are you using?

Flyway Community Edition 7.3.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

yes we tried latest 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

JAVA API

###### Which database are you using? (Type & version)
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

CREATE OR REPLACE TYPE BASE_TYPE AS OBJECT
(item_id            number
,item_code          varchar2(20)
,CONSTRUCTOR FUNCTION BASE_TYPE RETURN SELF AS RESULT
) NOT FINAL
/

CREATE OR REPLACE TYPE BODY BASE_TYPE  AS
  CONSTRUCTOR FUNCTION BASE_TYPE RETURN SELF AS RESULT AS
  BEGIN
    RETURN;
  END;
END;
/

CREATE OR REPLACE TYPE CHILD1_TYPE UNDER BASE_TYPE 
(var1              varchar2(20)
,CONSTRUCTOR FUNCTION CHILD1_TYPE RETURN SELF AS RESULT
)
/

CREATE OR REPLACE TYPE BODY CHILD1_TYPE AS
  CONSTRUCTOR FUNCTION CHILD1_TYPE RETURN SELF AS RESULT AS
  BEGIN
    RETURN;
  END;
END;

###### What did you expect to see?

Types should be created successfully 

###### What did you see instead?

Flyway get stuck on to this script and finally shows locking error .

**Comment by DoodleBobBuffPants** [comment] 2021-05-12 09:39
I'm unable to reproduce this, executing the above script succeeds

Could you provide exact reproduction steps or a reproduction project?

**Comment by BaburaoLad** [comment] 2021-05-12 11:43
sorry i have provided incomplete script  , please try below 
1. Run flyway migrate with below script .
2. change the file so that flyway will run it again .
3.  expected result : flyway should come back in seconds  , Actual  : flyway takes 15 min to compile in second time 


begin
execute immediate 'DROP TYPE CHILD2_TYPE FORCE';
exception 
 when others then null;
end;
/

begin
execute immediate 'DROP TYPE CHILD1_TYPE FORCE';
exception 
 when others then null;
end;
/
begin
execute immediate 'DROP TYPE BASE_TYPE FORCE';
exception 
 when others then null;
end;
/

CREATE OR REPLACE TYPE BASE_TYPE AS OBJECT
(item_id number
,item_code varchar2(20)
,CONSTRUCTOR FUNCTION BASE_TYPE RETURN SELF AS RESULT
) NOT FINAL
/

CREATE OR REPLACE TYPE BODY BASE_TYPE AS
CONSTRUCTOR FUNCTION BASE_TYPE RETURN SELF AS RESULT AS
BEGIN
RETURN;
 END;
END;
/

CREATE OR REPLACE TYPE CHILD1_TYPE UNDER BASE_TYPE
(var1 varchar2(20)
,CONSTRUCTOR FUNCTION CHILD1_TYPE RETURN SELF AS RESULT
)
/

CREATE OR REPLACE TYPE BODY CHILD1_TYPE AS
CONSTRUCTOR FUNCTION CHILD1_TYPE RETURN SELF AS RESULT AS
BEGIN
RETURN;
END;
END;
/

CREATE OR REPLACE TYPE CHILD2_TYPE UNDER BASE_TYPE
(var1 varchar2(20),
var2 CHILD1_TYPE,
CONSTRUCTOR FUNCTION CHILD2_TYPE RETURN SELF AS RESULT
)
/

CREATE OR REPLACE TYPE BODY CHILD2_TYPE AS
CONSTRUCTOR FUNCTION CHILD2_TYPE RETURN SELF AS RESULT AS
BEGIN
RETURN;
END;
END;
/

**Comment by DoodleBobBuffPants** [comment] 2021-05-12 12:23
I'm still unable to reproduce this. Is there a particular modification you are making before migrating a second time?

**Comment by BaburaoLad** [comment] 2021-05-12 15:37
No just make some changes so that flyway can run it second time

**Comment by DoodleBobBuffPants** [comment] 2021-05-13 08:09
I'm still unable to get a reproduction. Could you provide a minimal reproduction project and steps with exact configuration and scripts?

**Comment by DoodleBobBuffPants** [comment] 2021-05-18 08:40
Closing until we are able to reproduce

**Closed by DoodleBobBuffPants** 2021-05-18 08:40 UTC
Labels: d: Oracle, s: waiting for feedback
