### ISSUE TITLE
Flyway does not print DBMS_OUTPUT logs in debug mode

### ISSUE THREAD

**Issue by umapathy08** [flyway/flyway#1665] opened 2017-06-09 18:38 UTC
###### What version of Flyway are you using?

Flyway 4.1.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command line

###### What database are you using (type & version)?

Oracle 11g

###### What operating system are you using?

RHEL 5.x

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

create or replace procedure getcount(cout out number)
is
begin
dbms_output.enable();
select count(*) into cout from users;
end;
/

declare
cout number;
begin
getcount(cout);
DBMS_OUTPUT.PUT_LINE('count: ' || cout);
end;
/

###### What did you expect to see?

I expect flyway to print as like below:

count : 100

I was able to get the above output if I provide "SET SERVEROUTPUT ON" before executing the sql using Oracle SQL developer. I also do understand that command is a client specific one. Is it a right ask to get a similar command in flyway to get the output logs. ?

###### What did you see instead?

DEBUG: Scanning for SQL callbacks ...
DEBUG: Scanning for filesystem resources at 'sql' (Prefix: '', Suffix: '')
DEBUG: Scanning for resources in path: sql (sql)
DEBUG: Found filesystem resource: sql/V1_12_9__create_procedure_select_v2.sql
DEBUG: Schema "test" already exists. Skipping schema creation.
DEBUG: Locking table "test"."schema_version"...
DEBUG: Lock acquired for table "test"."schema_version"
DEBUG: Scanning for filesystem resources at 'sql' (Prefix: 'V', Suffix: '')
DEBUG: Scanning for resources in path: sql (sql)
DEBUG: Found filesystem resource: sql/V1_12_9__create_procedure_select_v2.sql
DEBUG: Scanning for filesystem resources at 'sql' (Prefix: 'R', Suffix: '')
DEBUG: Scanning for resources in path: sql (sql)
DEBUG: Filtering out resource: sql/V1_12_9__create_procedure_select_v2.sql (filename: V1_12_9__create_procedure_select_v2.sql)
Current version of schema "test": 1.12.3
DEBUG: Found statement at line 1: create or replace procedure getcount(cout out number)
is
begin
select count(*) into cout from users;
end;

DEBUG: Found statement at line 8: declare
cout number;
begin
getcount(cout);
DBMS_OUTPUT.PUT_LINE('count: ' || cout);
end;

Migrating schema "test" to version 1.12.9 - create procedure select v2.sql
DEBUG: Executing SQL: create or replace procedure getcount(cout out number)
is
begin
select count(*) into cout from users;
end;

DEBUG: Update Count: 0
DEBUG: Executing SQL: declare
cout number;
begin
getcount(cout);
DBMS_OUTPUT.PUT_LINE('count: ' || cout);
end;

DEBUG: Successfully completed migration of schema "test" to version 1.12.9 - create procedure select v2.sql
DEBUG: MetaData table "test"."schema_version" successfully updated to reflect changes
DEBUG: Locking table "test"."schema_version"...
DEBUG: Lock acquired for table "test"."schema_version"
Successfully applied 1 migration to schema "test" (execution time 00:01.098s).

**Comment by umapathy08** [comment] 2017-06-15 22:46
Hey @axelfontaine , thank you for acknowledging and tagging it for the next release. It would be much helpful for our automation team.!

**Comment by axelfontaine** [comment] 2017-11-29 15:37
@umapathy08 We unfortunately have to bump this to 5.1, but I can guarantee you it is coming then as it is a natural extension to #1845

**Comment by axelfontaine** [comment] 2017-11-29 23:08
We did manage to fit it in after all. 

Duplicate of #1845.

**Closed by axelfontaine** 2017-11-29 23:08 UTC
Labels: d: Oracle, t: feature

**Comment by markgargan** [comment] 2018-02-15 15:48
Hi Axel, how is this a duplicate of #1845? The DBMS output isn't mentioned in the issue? 
I've tried with the simplest I can 
DECLARE
BEGIN

  DBMS_OUTPUT.put_line('hello');

END;
/

and the only 'hello' in the output is from the 'Found statement' and the 'Executing sql' statement. I thought the actual DBMS_OUTPUT woudl appear seperately in the log? This way we can build up sql dynamically on the fly and output it just before we execute it to see what's actually executing. 

thanks,
Mark.

**Comment by axelfontaine** [comment] 2018-02-15 15:52
@markgargan You need to have a `SET SERVEROUTPUT ON` statement first in your script (support for this was added in #1845). After that `DBMS_OUTPUT` will be displayed as expected. This is identical to the SQL*Plus behavior.

**Comment by markgargan** [comment] 2018-02-15 16:02
Thanks for lightning response Axel, fair play to you! I tried this earlier and got the exception below. Script is the same as above except with the SET SERVEROUTPUT ON on the line above the declare. 

Flyway version: 5.0.7
Oracle driver version: 12.1.0.1


Statement  : SET SERVEROUTPUT ON
DECLARE
BEGIN

  DBMS_OUTPUT.put_line('hello');

END;


        at org.flywaydb.maven.AbstractFlywayMojo.execute(AbstractFlywayMojo.java:603)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.sql.SQLSyntaxErrorException: ORA-00922: missing or invalid option

Thanks,
Mark.

**Comment by axelfontaine** [comment] 2018-02-15 16:04
@markgargan Please file a new issue for this with steps to reproduce.
