### ISSUE TITLE
Flyway# clean not working on queue table from other schema 

### ISSUE THREAD

**Issue by WeronikaStoczek** [flyway/flyway#1306] opened 2016-05-09 08:56 UTC
version of Flyway: 3.2.1
oracle 10g

I have two users in DB with diffrent permissions one for appliaction and one for flyway. The Flywaly's user has  'DBA' permissions. I have a Queue Table that belogns to appliaction user.   

Flyway clean is not working : 

Caused by: org.flywaydb.core.api.FlywayException: Unable to drop "XXXX"."XXXX"
    at org.flywaydb.core.internal.dbsupport.SchemaObject.drop(SchemaObject.java:82) ~[flyway-core-3.2.1.jar:na]
    at org.flywaydb.core.internal.dbsupport.oracle.OracleSchema.doClean(OracleSchema.java:126) ~[flyway-core-3.2.1.jar:na]
    at org.flywaydb.core.internal.dbsupport.Schema.clean(Schema.java:148) ~[flyway-core-3.2.1.jar:na]
    at org.flywaydb.core.internal.command.DbClean$4.doInTransaction(DbClean.java:154) ~[flyway-core-3.2.1.jar:na]
    at org.flywaydb.core.internal.command.DbClean$4.doInTransaction(DbClean.java:152) ~[flyway-core-3.2.1.jar:na]
    at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72) ~[flyway-core-3.2.1.jar:na]
    at org.flywaydb.core.internal.command.DbClean.cleanSchema(DbClean.java:152) ~[flyway-core-3.2.1.jar:na]
    at org.flywaydb.core.internal.command.DbClean.clean(DbClean.java:106) ~[flyway-core-3.2.1.jar:na]
    at org.flywaydb.core.Flyway.doValidate(Flyway.java:1106) ~[flyway-core-3.2.1.jar:na]
    at org.flywaydb.core.Flyway.access$300(Flyway.java:62) ~[flyway-core-3.2.1.jar:na]
    at org.flywaydb.core.Flyway$1.execute(Flyway.java:1012) ~[flyway-core-3.2.1.jar:na]
    at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006) ~[flyway-core-3.2.1.jar:na]
    at org.flywaydb.core.Flyway.execute(Flyway.java:1418) ~[flyway-core-3.2.1.jar:na]
    at org.flywaydb.core.Flyway.migrate(Flyway.java:1006) ~[flyway-core-3.2.1.jar:na]
    at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-1.3.0.RELEASE.jar:1.3.0.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    ... 54 common frames omitted
Caused by: java.sql.SQLException: ORA-24005: Zum Löschen von Queue-Tabellen muss DBMS_AQADM.DROP_QUEUE_TABLE verwendet werden

The clean works perfectly when flyway is using the application user but i want to have separate users with diffrent permissions for this purpouses...

**Comment by axelfontaine** [comment] 2016-05-10 08:06
Can you also test this with Flyway 4.0.1?

**Comment by WeronikaStoczek** [comment] 2016-05-12 08:23
I have treid with version 4.0.1 but it makes no diffrence the problem is still there

**Comment by axelfontaine** [comment] 2016-06-08 16:57
The reason is this is like that is because the DBMS_AQADM procedure does not support passing a schema.

This is the code we use: `begin DBMS_AQADM.drop_queue_table (queue_table=> '" + queueTblName + "', FORCE => TRUE);`

Pull request for alternative solution welcome.

**Comment by vosolovskiy** [comment] 2017-04-11 20:31
@axelfontaine this issue is actually fixed with #1573

**Comment by axelfontaine** [comment] 2017-04-11 21:30
Duplicate of #1573

**Closed** 2017-04-11 21:30 UTC
Labels: c: clean(), d: Oracle, m: Core, s: pull request welcome
