### ISSUE TITLE
flyway-sbt is not resolved

### ISSUE THREAD

**Issue by tsaekisep** [flyway/flyway#1281] opened 2016-04-14 06:07 UTC
###### What version of Flyway are you using?
3.2.1

###### What database are you using (type & version)?
MySQL 5.6.30

###### What operating system are you using?
Amazon linux
```
$ cat /etc/system-release
Amazon Linux AMI release 2016.03
```
sbt:
```
$ sbt
> sbt-version
[info] 0.13.8
```

java:
```
$ java -version
openjdk version "1.8.0_77"
OpenJDK Runtime Environment (build 1.8.0_77-b03)
OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)
```

###### What did you do?
To add flyway-sbt

```
resolvers ++= Seq(
  "Flyway" at "https://flywaydb.org/repo",
)

addSbtPlugin("org.flywaydb" % "flyway-sbt" % "3.2.1")
```

###### What did you expect to see?
flyway-sbt is resolved successfully

###### What did you see instead?

```
[info] Resolving org.flywaydb#flyway-sbt;3.2.1 ...
[error] Server access Error: Received fatal alert: handshake_failure url=https://flywaydb.org/repo/org/flywaydb/flyway-sbt_2.10_0.13/3.2.1/flyway-sbt-3.2.1.pom
[warn] 	module not found: org.flywaydb#flyway-sbt;3.2.1
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/3.2.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/3.2.1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/test/.ivy2/local/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/3.2.1/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   /opt/test/testing/backend/repository/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/3.2.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/flywaydb/flyway-sbt_2.10_0.13/3.2.1/flyway-sbt-3.2.1.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/org/flywaydb/flyway-sbt_2.10_0.13/3.2.1/flyway-sbt-3.2.1.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/3.2.1/ivys/ivy.xml
[warn] ==== Typesafe repository: tried
[warn]   https://repo.typesafe.com/typesafe/releases/org/flywaydb/flyway-sbt_2.10_0.13/3.2.1/flyway-sbt-3.2.1.pom
[warn] ==== Flyway: tried
[warn]   https://flywaydb.org/repo/org/flywaydb/flyway-sbt_2.10_0.13/3.2.1/flyway-sbt-3.2.1.pom
[warn] ==== Sonatype OSS Release Repository: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/org/flywaydb/flyway-sbt_2.10_0.13/3.2.1/flyway-sbt-3.2.1.pom
[warn] ==== Seasar Repository: tried
[warn]   http://maven.seasar.org/maven2/org/flywaydb/flyway-sbt_2.10_0.13/3.2.1/flyway-sbt-3.2.1.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.flywaydb#flyway-sbt;3.2.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by sourcesmith** [comment] 2016-04-14 08:17
#1276

**Comment by tsaekisep** [comment] 2016-04-14 08:36
@sourcesmith 
Thanks

**Comment by axelfontaine** [comment] 2016-04-14 08:50
Duplicate of #1276

**Closed by axelfontaine** 2016-04-14 08:50 UTC

**Comment by AlexanderRay** [comment] 2016-05-07 18:06
Hi, it works for 

resolvers += "Flyway" at "https://flywaydb.org/repo"

addSbtPlugin("org.flywaydb" % "flyway-sbt" % "4.0")

that jar is there: https://flywaydb.org/repo/org/flywaydb/flyway-sbt_2.10_0.13/4.0/flyway-sbt-4.0.ja

bur doesn't work for

resolvers += "Flyway" at "https://flywaydb.org/repo"

addSbtPlugin("org.flywaydb" % "flyway-sbt" % "4.0.1")

```
[warn]   https://flywaydb.org/repo/org/flywaydb/flyway-sbt_2.10_0.13/4.0.1/flyway-sbt-4.0.1.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.flywaydb#flyway-sbt;4.0.1!flyway-sbt.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: download failed: org.flywaydb#flyway-sbt;4.0.1!flyway-sbt.jar

```

**Comment by axelfontaine** [comment] 2016-05-08 12:34
@AlexanderRay Thanks for pointing this out. Changes pushed out now. Everything is now working as expected.

**Comment by ggonchar** [comment] 2016-08-09 15:56
For some reason I see this issue right now with any of `4.0`-`4.0.3`. Any ideas?

```
resolvers += "Flyway" at "https://flywaydb.org/repo"
addSbtPlugin("org.flywaydb" % "flyway-sbt" % "4.0.3")
//addSbtPlugin("org.flywaydb" % "flyway-sbt" % "4.0")
//addSbtPlugin("org.flywaydb" % "flyway-sbt" % "4.0.1")
```

```
lang.modules#scala-xml_2.11;1.0.4 ...
[info] Resolving jline#jline;2.12.1 ...
[info] Resolving org.aspectj#aspectjweaver;1.8.6 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.flywaydb#flyway-sbt;4.0.3: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by long-lx** [comment] 2016-12-12 03:05
Hi, we met this error again.

java -version
```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
```

OS : Amazon Linux AMI 2016.09-release

```
[info] Resolving org.flywaydb#flyway-sbt;4.0.3 ...
[error] Server access Error: Received fatal alert: handshake_failure url=https://flywaydb.org/repo/org/flywaydb/flyway-sbt_2.10_0.13/4.0.3/flyway-sbt-4.0.3.pom
[warn] 	module not found: org.flywaydb#flyway-sbt;4.0.3
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/4.0.3/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/4.0.3/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/test/.ivy2/local/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/4.0.3/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/flywaydb/flyway-sbt_2.10_0.13/4.0.3/flyway-sbt-4.0.3.pom
[warn] ==== activator-launcher-local: tried
[warn]   /opt/play/lib/activator-1.3.2-minimal/repository/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/4.0.3/ivys/ivy.xml
[warn] ==== typesafe-releases: tried
[warn]   https://repo.typesafe.com/typesafe/releases/org/flywaydb/flyway-sbt_2.10_0.13/4.0.3/flyway-sbt-4.0.3.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/4.0.3/ivys/ivy.xml
[warn] ==== Flyway: tried
[warn]   https://flywaydb.org/repo/org/flywaydb/flyway-sbt_2.10_0.13/4.0.3/flyway-sbt-4.0.3.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.flywaydb#flyway-sbt;4.0.3: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		org.flywaydb:flyway-sbt:4.0.3 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.flywaydb:flyway-sbt:4.0.3 (scalaVersion=2.10, sbtVersion=0.13) (/opt/test/web/project/plugins.sbt#L8-9)
[warn] 		  +- default:web-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: org.flywaydb#flyway-sbt;4.0.3: not found
```

**Comment by NightFantomJ2** [comment] 2017-11-08 07:19
Hi, I think I have the same issue: it's trying to download flyway from
https://repo1.maven.org/maven2/org/flywaydb/flyway-sbt_2.10_0.13/4.0.3/flyway-sbt-4.0.3.jar
instead of from
https://repo1.maven.org/maven2/org/flywaydb/flyway-sbt/4.0.3/flyway-sbt-4.0.3.jar

[warn] 	[NOT FOUND  ] org.flywaydb#flyway-sbt;4.0.3!flyway-sbt.jar (10ms)
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/flywaydb/flyway-sbt_2.10_0.13/4.0.3/flyway-sbt-4.0.3.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.flywaydb#flyway-sbt;4.0.3!flyway-sbt.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
