### ISSUE TITLE
Support for Oracle 18c

### ISSUE THREAD

**Issue by coredigitalmedia** [flyway/flyway#2394] opened 2019-05-21 12:19 UTC
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by coredigitalmedia** [comment] 2019-05-21 12:20
Hello:

we are upgrading our oracle database from 12c to 18c. will pro edition be supported for 18c?

**Comment by axelfontaine** [comment] 2019-05-21 12:21
This has been supported since 5.2.0

Duplicate of #2093

**Closed by axelfontaine** 2019-05-21 12:21 UTC
