### ISSUE TITLE
Existence of fallback table always results in a warning even if flyway.table is provided

### ISSUE THREAD

**Issue by chrischall** [flyway/flyway#1860] opened 2017-12-07 17:36 UTC
After upgrading `flyway-maven-plugin` to `5.0.1`, I was warned that I should provide a value for `flyway.table` since the default table is changing.

> [WARNING] Could not find schema history table "public"."flyway_schema_history", but found "public"."schema_version" instead. You are seeing this message because Flyway changed its default for flyway.table in version 5.0.0 to flyway_schema_history and you are still relying on the old default (schema_version). Set flyway.table=schema_version in your configuration to fix this. This fallback mechanism will be removed in Flyway 6.0.0.

I provided `flyway.table=schema_version` via my plugin configuration:
```
<configuration>
	<fork>true</fork>
	<skip>false</skip>
	<table>schema_version</table>
    ...
</configuration>
```

However, I now receive the following warning.

> [WARNING] Could not find schema history table "public"."schema_version", but found "public"."schema_version" instead. You are seeing this message because Flyway changed its default for flyway.table in version 5.0.0 to flyway_schema_history and you are still relying on the old default (schema_version). Set flyway.table=schema_version in your configuration to fix this. This fallback mechanism will be removed in Flyway 6.0.0.

I think this is due to code in `JdbcTableSchemaHistory` not inspecting whether or not `flyway.table` has been set.

https://github.com/flyway/flyway/blob/000bcc7b6effe8ab49505e1302142201034a4a93/flyway-core/src/main/java/org/flywaydb/core/internal/schemahistory/JdbcTableSchemaHistory.java#L102

**Comment by axelfontaine** [comment] 2017-12-07 17:38
Thanks for reporting. Consider this fixed in the next patch release.

Duplicate of #1859

**Closed by axelfontaine** 2017-12-07 17:38 UTC

**Comment by maxdietrich** [comment] 2018-05-16 14:46
Hey, I just updated to version 5.0.7 and have the same problem again. `flyway.table="schema_version"` is set in the configuration, but I still get the warning that I should set it. Did that fix maybe get lost during a refactoring here? https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/schemahistory/JdbcTableSchemaHistory.java#L91

**Comment by axelfontaine** [comment] 2018-05-17 19:56
@maxdietrich I can't reproduce this. Are you sure your config is being used. Please debug and open a new issue with exact steps how to reproduce if the problem persists.
