### ISSUE TITLE
baseline: Unable to baseline schema history table

### ISSUE THREAD

**Issue by boha11oran** [flyway/flyway#1952] opened 2018-03-13 16:22 UTC
###### Which version and edition of Flyway are you using?

Flyway Trial Edition 5.0.7 by Boxfuse

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
PostgreSQL 9.6

###### Which operating system are you using?

On client MACOS
BOS1002962L:flyway bohalloran$ uname -a
Darwin BOS1002962L 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
BOS1002962L:flyway bohalloran$ 

On Server
CentOS Linux release 7.3.1611 (Core)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

BOS1002962L:flyway bohalloran$ ./flyway baseline -url=jdbc:postgresql://xxx.chewy.com:5432/denver -baselineVersion=3 -installedBy=bohalloran -baselineDescription='version 3 applied manually'
Flyway Trial Edition 5.0.7 by Boxfuse
WARNING: You are using the 30 day limited Flyway Trial Edition. After 30 days you must remove this version and either upgrade to Flyway Pro Edition or Flyway Enterprise Edition or downgrade to Flyway Community Edition.

Database password: 
Database: jdbc:postgresql://xxx.chewy.com:5432/denver (PostgreSQL 9.6)
ERROR: Unable to baseline schema history table "public"."schema_version" with (3,version 3 applied manually) as it has already been initialized with (1,Base)
BOS1002962L:flyway bohalloran$ 

###### What did you expect to see?

Since version 3 has already been applied manually (not using flyway) the migrate fails with 'ERROR: schema "xxx" already exists' so I'd like to make that version 3 the new baseline.  There are several other manually applied downstream migrations that have already been applied and so I can imagine we'd have to sun a similar procedure on them.

+-----------+------------+-----------------------------------------+----------+---------------------+---------+----------+
| Category  | Version    | Description                             | Type     | Installed On        | State   | Undoable |
+-----------+------------+-----------------------------------------+----------+---------------------+---------+----------+
| Versioned | 1          | Base                                    | BASELINE | 2015-09-12 17:54:16 | Success | No       |
| Versioned | 2          | update fraudcheck generatetickler colum | SQL      | 2016-01-12 16:22:26 | Success | No       |
| Versioned | 3          | audit loggedactions                     | SQL      |                     | Pending | No       |
| Versioned | 4          | member group promo                      | SQL      |                     | Pending | No       |
| Versioned | 5          | petprofile                              | SQL      |                     | Pending | No       |

###### What did you see instead?

ERROR: Unable to baseline schema history table "public"."schema_version" with (3,version 3 applied manually) as it has already been initialized with (1,Base)

**Comment by axelfontaine** [comment] 2018-03-13 16:50
Duplicate of #1737 

The easiest workaround is to drop the schema history table and run baseline again.

**Closed by axelfontaine** 2018-03-13 16:50 UTC

**Comment by boha11oran** [comment] 2018-03-13 17:34
@axelfontaine shouldn't i be able to baseline any version "Baseline is for introducing Flyway to existing databases by baselining them at a specific version. The will cause Migrate to ignore all migrations upto and including the baseline version. Newer migrations will then be applied as usual."

**Comment by axelfontaine** [comment] 2018-03-13 17:59
The feature is currently designed so that baseline is only performed once at the very beginning.
