### ISSUE TITLE
Java based repeatable  migration execute again even if checksum did not change 

### ISSUE THREAD

**Issue by BaburaoLad** [flyway/flyway#3209] opened 2021-06-15 22:09 UTC
###### Which version and edition of Flyway are you using?

Flyway Community Edition 7.3.2 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

Oracle DB 19c 

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We have java classes generated for few of the JSON format scripts , we pass the instance of all java objects for those json scripts .
Flyway execute them again and again even if the JSON file  content is same , we calculate checksum based on json file content to  decide execution .

###### What did you expect to see?

if checksum and file name is same then it should not execute migrate method from that java class .

###### What did you see instead?

Flyway execute migrate  method even if the checksum is same

**Comment by BaburaoLad** [comment] 2021-06-15 22:11
![image](https://user-images.githubusercontent.com/75744755/122130089-1a84c800-ce05-11eb-8488-9debd6532e44.png)

**Comment by BaburaoLad** [comment] 2021-06-15 22:14
If you see above image , i executed same file multiple times with flyway JAVA API and it ran again and again even if the checksum is same

**Comment by DoodleBobBuffPants** [comment] 2021-06-16 08:56
I've been unable to reproduce this

Could you try to reproduce this on the latest version of Flyway, and if that fails, could you provide a sample migration that reproduces this?

**Comment by BaburaoLad** [comment] 2021-06-16 10:30
This is not happening for  all the times but it happens constantly for one DB migration , please see below o/p latest which prints checksum for the file but same checksum exist for same file in DB but still executing

**Comment by BaburaoLad** [comment] 2021-06-16 10:42
If you see in above image , i ran the migration again and printed calculated checksum from Java class getChecksum method , checksum did not change but still for somehow flyway does not recognized the checksum

**Comment by DoodleBobBuffPants** [comment] 2021-06-16 12:21
Could you provide a migration that reproduces this behavior, as we are unable to reproduce it based on the information provided

**Comment by DoodleBobBuffPants** [comment] 2021-06-23 10:49
Closing until we can get a reproduction

**Closed by DoodleBobBuffPants** 2021-06-23 10:49 UTC
Labels: s: waiting for feedback
