### ISSUE TITLE
Cannot disable placeholderReplacement in command-line flyway

### ISSUE THREAD

**Issue by czandee** [flyway/flyway#1273] opened 2016-04-07 10:32 UTC
###### What version of Flyway are you using?
4.0

###### What database are you using (type & version)?
MS SQL Server 2012

###### What operating system are you using?
Windows 7 Enterprise

###### What did you do?
In the file to be migrated I insert content into a table:
```
update z_test 
  set z_value='placeholder test: ${user.initials}'
  where z_key = 1;
```

In the flyway.conf property file I disable placeholderReplacement
```
flyway.placeholderReplacement=false
```

Then I tryto migrate on command line
```
flyway -X -configFile=conf\flyway.conf -locations=filesystem:sql migrate
```

###### What did you expect to see?
Successful migration of the above sql statement (previous version without the placeholder
text worked and was committed into the database)

###### What did you see instead?
Somehow I cannot get the placeholderReplacement property to be accepted. Neither on command line nor in the flyway configuration file. The result is always as seen below, "unknown configuration property"

```
C:\jp\flyway-test\z_test>flyway -X -configFile=conf\flyway.conf -locations=filesystem:sql migrate
Flyway 4.0 by Boxfuse

DEBUG: Java 1.8.0_74 (Oracle Corporation)
DEBUG: Windows 7 6.1 amd64

[...]
DEBUG: flyway.placeholderReplacement -> false
[...]
WARNING: Unknown configuration property: flyway.placeholderReplacement
[...]
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: No value provided for placeholder expressions: ${user.initials}.  Check your configuration!
        at org.flywaydb.core.internal.util.PlaceholderReplacer.checkForUnmatchedPlaceholderExpression(PlaceholderReplacer.java:106)
        at org.flywaydb.core.internal.util.PlaceholderReplacer.replacePlaceholders(PlaceholderReplacer.java:83)
        at org.flywaydb.core.internal.dbsupport.SqlScript.<init>(SqlScript.java:79)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:70)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrate(DbMigrate.java:352)
        at org.flywaydb.core.internal.command.DbMigrate.access$1100(DbMigrate.java:47)
        at org.flywaydb.core.internal.command.DbMigrate$4.doInTransaction(DbMigrate.java:308)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:305)
        at org.flywaydb.core.internal.command.DbMigrate.access$1000(DbMigrate.java:47)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:230)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:173)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:173)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:959)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1361)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:139)
        at org.flywaydb.commandline.Main.main(Main.java:102)

```

**Comment by axelfontaine** [comment] 2016-04-07 10:38
Duplicate of #1233

**Closed by axelfontaine** 2016-04-07 10:38 UTC

**Comment by czandee** [comment] 2016-04-07 11:09
Sorry about, didn't see this one...
