### ISSUE TITLE
Apache Phoenix support

### ISSUE THREAD

**Issue by rparatc** [flyway/flyway#1070] opened 2015-07-30 15:07 UTC
I will appreciate if you add support for Apache Phoenix as it is JDBC driver over HBase

**Comment by JamesRTaylor** [comment] 2015-08-25 23:22
+1. Would love to see Phoenix support as well. The pull request is here: https://github.com/flyway/flyway/pull/1012

**Comment by axelfontaine** [comment] 2015-10-27 20:40
Duplicate of #929

**Closed by axelfontaine** 2015-10-27 20:40 UTC
Labels: t: feature
