### ISSUE TITLE
Multiple connections during database migration since 7.3.1

### ISSUE THREAD

**Issue by henricook** [flyway/flyway#3058] opened 2021-01-20 14:54 UTC
###### Which version and edition of Flyway are you using?
7.5.0 and 7.3.2 show the problem, it's not there in 7.3.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
I'm using this with play framework/Hikari CP

###### Which database are you using? (Type & version)
Postgres 10.5

###### Which operating system are you using?
Ubuntu 20.10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

When starting our play application, which runs Flyway migrate we've been observing a connection leak warning/timeout trying to get a connection since upgrading to Flyway 7.3.2. We've reverted to 7.3.1 after also checking on 7.5.0 and the problem remains.

We purposefully limit our local machines to one connection in the pool.

I'm sorry this is sparse on analysis but I can only guess something about Flyway migrate now tries to use two connections during migration which causes one to fail?

```
[2021-01-20T14:49:23,398] [warn] c.z.h.p.ProxyLeakTask - Connection leak detection triggered for org.postgresql.jdbc.PgConnection@a01aebc on thread scala-execution-context-global-1653, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:59)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:69)
	at org.flywaydb.core.Flyway.execute(Flyway.java:507)
	at org.flywaydb.core.Flyway.info(Flyway.java:380)
	at my.app..DatabaseMigrator.$anonfun$migrate$7(DatabaseMigrator.scala:34)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:189)
	at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
	at monix.eval.internal.TaskRestartCallback$WithLocals.syncOnSuccess(TaskRestartCallback.scala:176)
	at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:74)
```
`DatabaseMigrator.scala:34` is our file and contains:

```scala
    def runMigration: Task[Unit] = {
      for {
        flyway <- Task {
                    Flyway.configure
                      .dataSource(ds)
                      .locations("sql/migrations")
                      .load()
                  }
        _                 <- logger.info("Running database migrations (if any)...")
        migrations        <- Task.eval(Try(flyway.migrate())).flatMap(Task.fromTry).executeOn(IOScheduler).asyncBoundary
        pendingMigrations  = flyway.info.pending().length
        migrationsOccurred = migrations.migrationsExecuted > 0
```

Line 34 is `        pendingMigrations  = flyway.info.pending().length`

###### What did you expect to see?
No error whilst migrating

###### What did you see instead?
An error whilst migration and small delay as the procedure trying to get a connection timed out. Migration was delayed whilst htis happened.

**Comment by DoodleBobBuffPants** [comment] 2021-01-20 15:27
First, it seems you are calling info incorrectly, and it should be `flyway.info().pending().length`

Is migrate running asynchronously? This could be the cause. We haven't changed anything about how we acquire connections, but we added a new callback before each command returns, which might cause this problem if you are running migrate asynchronously

**Comment by henricook** [comment] 2021-01-20 15:52
Thanks for the tip on `info` @DoodleBobBuffPants - I imagine that's Scala magically ignoring empty `()` for us as it's been working thus far. Nevertheless i've fixed it so it look right, nice one 👍🏻 

Migrate is running asynchronously in that [Monix Task](https://monix.io/docs/current/eval/task.html) is a virtual thread-like abstraction - but everything in our application runs inside one of those.

In the snippet above:

```scala
  migrations        <- Task.eval(Try(flyway.migrate())).flatMap(Task.fromTry).executeOn(IOScheduler).asyncBoundary
        pendingMigrations  = flyway.info.pending().length
        migrationsOccurred = migrations.migrationsExecuted > 0
```

The migration will have to finish and write a value to the `migrations` variable before the next two lines are executed

**Comment by DoodleBobBuffPants** [comment] 2021-01-21 09:23
I tested Flyway with HikariCP in a plain Java project, and was unable to reproduce the warning

This is therefore likely something to do with Play or Monix Tasks. We don't officially support either of these, however there is the community-maintained [flyway-play](https://github.com/flyway/flyway-play)

That being said, you could try to narrow down where this connection leak is coming from - if you run `migrate` or `info` on their own, does the warning still appear, or does it only appear when they're called one after another? This might suggest we're not closing the connection, although if that were the case then this should've been caught in Java too. Could you also try this without Monix Tasks to see if that is causing weird behavior?

**Comment by henricook** [comment] 2021-01-21 09:30
Sure thing, thank you for doing that testing - I'll carve out some time to examine this

**Comment by DoodleBobBuffPants** [comment] 2021-01-28 08:53
Closing until further activity

**Closed by DoodleBobBuffPants** 2021-01-28 08:53 UTC
Labels: s: waiting for feedback

**Comment by henricook** [comment] 2021-01-28 09:25
@DoodleBobBuffPants This seems to have disappeared in 7.5.0. Thanks for your efforts.
