### ISSUE TITLE
Publish deb package for Ubuntu

### ISSUE THREAD

**Issue by ikle-tiskok** [flyway/flyway#1258] opened 2016-03-29 05:53 UTC
Is it possible?

**Comment by axelfontaine** [comment] 2016-03-29 07:25
Not that I know of. Want to step up and create a package?

**Comment by ckchow** [comment] 2017-01-19 20:47
I could do this, but setting up the deploy from Travis to Launchpad should probably be done by the maintainer since you have to generate some keys on github.  https://docs.travis-ci.com/user/deployment/launchpad/

**Comment by axelfontaine** [comment] 2017-02-07 16:45
Duplicate of #734

**Closed by axelfontaine** 2017-02-07 16:45 UTC
Labels: t: feature
