### ISSUE TITLE
Invalid SQL filenames found

### ISSUE THREAD

**Issue by misterquestions** [flyway/flyway#3541] opened 2022-10-18 22:01 UTC
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
MariaDB

###### Which operating system are you using?
Linux/Docker

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Run migrations on app startup, created jar using shadowJar, all the contents seems to be there just fine.

###### What did you expect to see?
Migrations run properly when using the direct run from IntelliJ.

###### What did you see instead?
```
18-10-2022 16:56:03 | DEBUG |     o.f.c.i.s.classpath.ClassPathScanner | Determining location urls for classpath:db/migration using ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@42110406 ...
18-10-2022 16:56:03 | DEBUG |     o.f.c.i.s.classpath.ClassPathScanner | Scanning URL: jar:file:/home/container/ori.jar!/db/migration
18-10-2022 16:56:03 | DEBUG |   o.f.core.internal.util.FeatureDetector | JBoss VFS v2 available: false
18-10-2022 16:56:03 | DEBUG |     o.f.c.i.s.classpath.ClassPathScanner | Found resource: db/migration/
18-10-2022 16:56:03 | DEBUG |     o.f.c.i.s.classpath.ClassPathScanner | Found resource: db/migration/V1__Create_Settings_Table.sql
18-10-2022 16:56:03 | DEBUG |     o.f.c.i.s.classpath.ClassPathScanner | Found resource: db/migration/V2__Create_Halloween_Drops_Table.sql
18-10-2022 16:56:03 | DEBUG |     o.f.c.i.s.classpath.ClassPathScanner | Found resource: db/migration/V3__Create_Hallowen_Ranks_Table.sql
18-10-2022 16:56:03 | DEBUG |     o.f.c.i.s.classpath.ClassPathScanner | Scanning for classes at classpath:db/migration
18-10-2022 16:56:03 | DEBUG | o.flywaydb.core.internal.scanner.Scanner | Filtering out resource: db/migration/ (filename: )
18-10-2022 16:56:03 | DEBUG |   o.f.c.i.resource.ResourceNameValidator | Validating V2__Create_Halloween_Drops_Table.sql
18-10-2022 16:56:03 | DEBUG |   o.f.c.i.resource.ResourceNameValidator | Validating V3__Create_Hallowen_Ranks_Table.sql
18-10-2022 16:56:03 | DEBUG |   o.f.c.i.resource.ResourceNameValidator | Validating V1__Create_Settings_Table.sql
org.flywaydb.core.api.FlywayException: Invalid SQL filenames found:
Unrecognised migration name format: V2__Create_Halloween_Drops_Table.sql
Unrecognised migration name format: V3__Create_Hallowen_Ranks_Table.sql
Unrecognised migration name format: V1__Create_Settings_Table.sql
```

![image](https://user-images.githubusercontent.com/19508549/196553165-4faa2390-12e8-4ae0-9ba8-ff38ac7964ba.png)

**Comment by Barry-RG** [comment] 2022-10-20 14:28
Unfortunately we are unable to reproduce this issue, are you able to provide us with a minimal reproduction project?

**Comment by Barry-RG** [comment] 2022-10-26 14:11
Closing till further interest

**Closed by Barry-RG** 2022-10-26 14:11 UTC
Labels: s: waiting for feedback

**Comment by janek515** [comment] 2022-11-13 19:50
The same problem flyway-9.8.1 cli on an Oracle DB. OS: Windows 11
```
DEBUG: Validating U1__init.sql
DEBUG: Validating V1__init.sql
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Invalid SQL filenames found:
Unrecognised migration name format: U1__init.sql
        at org.flywaydb.core.internal.resource.ResourceNameValidator.validateSQLMigrationNaming(ResourceNameValidator.java:59)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:144)
        at org.flywaydb.core.Flyway.info(Flyway.java:193)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:285)
        at org.flywaydb.commandline.Main.main(Main.java:179)
```

**Comment by ClaraPaiva** [comment] 2023-11-16 10:23
Hello, 

Has any solution been found?
I have the same problem: 

**Technical context**:
- Java 17
- Spring Boot 3.1.2
- I'm trying to use Flyway on a small in-memory database of type H2. I want Flyway to run for creating a table and data-fill it based on 2 .sql files I prepared (for subsequent automatic end-to-end testing with Cypress).

**Error message:** on Spring Boot application launch on my 'e2e' spring profile
`11:00:03.521 ERROR [o.springframework.boot.SpringApplication] Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invalid SQL filenames found:
Invalid versioned migration name format: V1__qualification_data_insertion.sql (could not recognise version number V1)
Invalid versioned migration name format: V1__qualification_table_creation.sql (could not recognise version number V1)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	(...)
	Caused by: org.flywaydb.core.api.FlywayException: Invalid SQL filenames found:
Invalid versioned migration name format: V1__qualification_data_insertion.sql (could not recognise version number V1)
Invalid versioned migration name format: V1__qualification_table_creation.sql (could not recognise version number V1)
	at org.flywaydb.core.internal.resource.ResourceNameValidator.validateSQLMigrationNaming(ResourceNameValidator.java:59)`

If of any use: here are my properties for the given e2e profile (e2e.properties):
`spring.datasource.url=jdbc:h2:mem:grj
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.url=jdbc:h2:mem:grj
spring.flyway.user=sa
spring.flyway.password=password
spring.flyway.validateMigrationNaming=true
spring.flyway.locations=classpath:db/migration/e2e
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

logging.level.ch.ge.pj.grj=DEBUG`


If I turn `spring.flyway.validateMigrationNaming` to false, it fails silently (i.e it does not complain; the app launches but no SQL script seems to have been executed)

I think the files I have are named as expected?

- V1__qualification_data_insertion.sql
- V1__qualification_table_creation.sql
and they are placed in a folder: back-end\src\main\resources\db\migration\e2e  as stated on the properties file.

What I am doing wrong?
