### ISSUE TITLE
Migrate multiple schemas like clean.

### ISSUE THREAD

**Issue by marcbeckers** [flyway/flyway#949] opened 2015-02-12 19:57 UTC
I want to use Flyway to migrate multiple (almost 2.000) identical schemas (different customers; same structure, but physically separated data). I know the "flyway.schemas" property, but that only works with clean. I would like to see it also works with migrate. Please help!

**Comment by axelfontaine** [comment] 2015-02-13 08:51
Duplicate of #467

**Closed by axelfontaine** 2015-02-13 08:51 UTC
