### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0 at org.flywaydb.core.internal.configuration.ConfigUtils.<clinit>(ConfigUtils.java:61)

### ISSUE THREAD

**Issue by AlejandroYuste** [flyway/flyway#3793] opened 2023-11-09 12:52 UTC
###### Which version and edition of Flyway are you using?
flyway open source 10.0.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API on a Kotlin project.

###### Which database are you using? (Type & version)
Postgresql 16 or 15. It doesn't matter.

###### Which operating system are you using?
Ubuntu latest.

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
It fails in the docker container when trying to load the database to run the migrations.

Gradle configuration:

```
    implementation("org.flywaydb:flyway-core:10.0.0")
    implementation("org.flywaydb:flyway-database-postgresql:10.0.0")
```

Connection.
```
        val flyway = Flyway.configure()
            .driver(DATABASE_DRIVER)
            .dataSource(jdbcUrlString, config[Db.user], config[Db.pass])
            .defaultSchema("public")
            .validateMigrationNaming(true)
            .validateOnMigrate(true)
            .load()

        flyway.baseline()
        flyway.migrate()
```

It fails on an internal library code.

```
app  | Exception in thread "main" java.lang.ExceptionInInitializerError
app  | 	at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1414)
app  | 	at org.flywaydb.core.api.configuration.ClassicConfiguration.configureFromConfigurationProviders(ClassicConfiguration.java:1854)
app  | 	at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1285)
app  | 	at org.flywaydb.core.api.configuration.ClassicConfiguration.<init>(ClassicConfiguration.java:224)
app  | 	at org.flywaydb.core.Flyway.<init>(Flyway.java:111)
app  | 	at org.flywaydb.core.api.configuration.FluentConfiguration.load(FluentConfiguration.java:59)
app  | 	at .app.infrastructure.database.Database.init(Database.kt:24)
app  | 	at app.ApplicationKt.main(Application.kt:96)
app  | 	at app.ApplicationKt.main(Application.kt)
app  | Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
app  | 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
app  | 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
app  | 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
app  | 	at java.base/java.util.Objects.checkIndex(Objects.java:359)
app  | 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
app  | 	at org.flywaydb.core.internal.configuration.ConfigUtils.<clinit>(ConfigUtils.java:61)
app  | 	... 9 more
```

Docker container from openjdk:17 and application build with gradle 8.4 jdk 17

###### What did you expect to see?
Migrations running properly.

###### What did you see instead?
Error on internal flyway library.

**Comment by tiafiring** [comment] 2023-11-09 14:05
We have a similar setup and we are experiencing the same issue when upgrading from version 9.22.3. We use the Java API in a Kotlin project, JDK 17, gradle 8.3, flyway 10.0.0 and Postgresql 14.9. 


```
        Flyway.configure()
            .dataSource(dataSource)
            .load()
            .migrate()
```
I think the exception originates from this, but I haven't figured out why the list is empty: 
```
    public static final Class<? extends LicensingConfigurationExtensionStub> LICENSE_CONFIG_EXTENSION_CLASS = new FluentConfiguration().getPluginRegister()
                                                                                                                                       .getPlugins(LicensingConfigurationExtensionStub.class)
                                                                                                                                       .get(0)
                                                                                                                                       .getClass();
```

**Comment by JasonLuo-Redgate** [comment] 2023-11-10 14:25
Hi @AlejandroYuste @tiafiring , it looks like both of you are using Flyway in a Kotlin project. 
Can this issue be reproduced if you use Flyway API through any Java project?

**Comment by AlejandroYuste** [comment] 2023-11-11 10:33
I don't know :/ 
Does this mean kotlin is not supported? That's weird as everything gets compiled as part of the same java byte code...

**Comment by Barry-RG** [comment] 2023-11-13 09:49
@AlejandroYuste I am trying to find out more information to help. Although your statement about Kotlin and Java byte code basicly being the same, this is to do with Service/Class Loading. Would you be able to tell us what specific JRE you are using? This should help to resolving this.

**Comment by AlejandroYuste** [comment] 2023-11-13 10:24
Hello! 

Nope, I was trying to add flyway for the first time. I tried different versions and I got the same error from all of them.
It doesn't happen when I run the project locally. It only happens when it runs inside a docker container. Here is the Dockerfile:

```
FROM gradle:8.4.0-jdk17 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle buildFatJar --no-daemon

FROM openjdk:17
EXPOSE 8080:8080

RUN mkdir /app
COPY documentation/swagger.yaml /app/documentation/swagger.yaml

WORKDIR /app
COPY --from=build /home/gradle/src/build/libs/*.jar /app/
ENTRYPOINT ["java","-jar","/app/app-all.jar"]
```

I tried lots of different images with java 17 and it failed for all of them.

**Comment by tiafiring** [comment] 2023-11-14 08:30
We are currently using flyway version 9.22.3 without any problems in my project. When upgrading to 10.0.0 or 10.0.1 we get the same error as @AlejandroYuste .

**Comment by klundby** [comment] 2023-11-15 07:12
Same here. Working fine with 9.22.3, but getting the error above when upgrading

**Comment by JasonLuo-Redgate** [comment] 2023-11-15 09:25
Hi @klundby , are you also using Flyway in a Kotlin environment or a Java environment ?

**Comment by klundby** [comment] 2023-11-15 10:06
This is in a Kotlin environment

**Comment by attiand** [comment] 2023-11-16 13:07
We have the folllowing depdency in a pure java-maven project creating a runnable jar with maven-assembly-plugin:

```xml
<dependency>
    <groupId>org.flywaydb</groupId>
    <artifactId>flyway-database-postgresql</artifactId>
    <version>10.0.1</version>
</dependency>
```

The problem is that both flyway-database-postgresql and flyway-core has a service loader file with the same name (META-INF/services/org.flywaydb.core.extensibility.Plugin). Only the one in flyway-core includes LicensingConfigurationExtensionStub. 

The maven-assembly-plugin only adds one of the files. In our case only the one from flyway-database-postgresql was included (which does not include LicensingConfigurationExtensionStub)

The application runs fine from the IDE.

**Comment by Giuliopime** [comment] 2023-11-17 10:36
Same issue here

**Comment by JasonLuo-Redgate** [comment] 2023-11-17 11:26
Hi @attiand , so many thanks for the findings. 
Does this mean your project does not include dependency on `flyway-core`?

**Comment by attiand** [comment] 2023-11-17 12:14
@JasonLuo-Redgate, Yes `flyway-core` is included as it is a depedency for `flyway-database-postgresql`.

**Comment by JasonLuo-Redgate** [comment] 2023-11-20 10:16
Hi @attiand , just would like to know more info. Is there any specific reason why you prefer not to include `flyway-core` directly?

**Comment by attiand** [comment] 2023-11-20 10:22
Hi @JasonLuo-Redgate. No I'm just lazy, the effective pom will be the same.

**Comment by JasonLuo-Redgate** [comment] 2023-11-20 14:19
Hi @attiand , thanks to your detailed description, I can locally reproduce this issue now.

**Comment by gloeglm** [comment] 2023-11-20 15:26
We had the same error, seems to be related to service definition META-INF files, as @attiand mentioned.

For us adding
```
tasks.withType<ShadowJar> {
    mergeServiceFiles()
    archiveBaseName = project.name
    archiveVersion = ""
}
```

to our build.gradle.kts fixed the issue

We had both flyway-core and flyway-database-postgres as direct dependencies

**Comment by AlejandroYuste** [comment] 2023-11-20 15:34
> either

I had both dependencies: core and postgresql. I tried today to remove the core one and I got the same error.

**Closed** 2023-11-22 14:18 UTC
Labels: s: needs investigation
