### ISSUE TITLE
How do you create the schema after many fix?

### ISSUE THREAD

**Issue by teopost** [flyway/flyway#1055] opened 2015-07-16 12:09 UTC
I have these files:

    V1_0_Base_schema.sql
    V1_1_fix_description.sql
    V1_2_fix_description.sql
    V1_3_fix_description.sql

...and after 1 year...

    V1_9999999_fix_description.sql

After 1 year, if I have to create a new scheme, I don't want to apply all the fixes.
Some of them may take a long time.

Then I would be able to create, a new structure for V2 version, then:

    V2_0_Base_schema.sql
    V2_1_fix_description.sql
    V2_2_fix_description.sql
    V2_3_fix_description.sql

Currently I could not handle this case.
In fact, in a schema which I applied changes, I can't create baseline between.

How would I handle this?

**Comment by axelfontaine** [comment] 2015-10-28 11:38
Duplicate of #470

**Closed by axelfontaine** 2015-10-28 11:38 UTC
