### ISSUE TITLE
Missing Comments at beginning  of a Storedprocedure

### ISSUE THREAD

**Issue by anandav** [flyway/flyway#1489] opened 2016-12-12 08:33 UTC
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
CLI

###### What database are you using (type & version)?
MS SQL 2014

###### What operating system are you using?
Windows

###### What did you do?
In Flyway sql files to created an Store procedure i followed the same syntax looks like 

```sql 
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE <Procedure_Name, sysname, ProcedureName> 
@param ...................
...........
END
```

But after ``` Flyway Migrate``` when i open the SP i can't see the Comments at the beginning of the SP
 

###### What did you see instead?
```sql 
CREATE PROCEDURE <Procedure_Name, sysname, ProcedureName> 
@param ...................
...........
END
```

**Comment by axelfontaine** [comment] 2017-01-31 17:23
Duplicate of #1362

**Closed by axelfontaine** 2017-01-31 17:23 UTC
