### ISSUE TITLE
'sqlMigrationSuffix' is not working for empty

### ISSUE THREAD

**Issue by nrvmodi** [flyway/flyway#1437] opened 2016-09-21 11:23 UTC
###### What version of Flyway are you using?
3.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Maven plugin

###### What database are you using (type & version)?
MySql 5.6.22

###### What operating system are you using?
Windows-10

###### What did you do?
I have one sql file name is 'sample_new_script.sql'
<sqlMigrationSuffix></sqlMigrationSuffix>

###### What did you expect to see?
I am expecting that it will return me in the schema_version tables's description column 
'sample new script.sql'

###### What did you see instead?
But currently I am seeing that it will not taking empty tag and return me the 'sample new script' instead of 'sample new script.sql' 

<sqlMigrationSuffix></sqlMigrationSuffix>

Actual output of my configuration is

[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:3.2.1:migrate (default) on project local-deploy: org.flywaydb.core.api.FlywayException: Validate failed. Migration Description mismatch for migration 002
[ERROR] -> Applied to database : add PASSWORD DEPRECATED column to MIO USER .sql
[ERROR] -> Resolved locally    : add PASSWORD DEPRECATED column to MIO USER
[ERROR] -> [Help 1]
[ERROR]

So I am expecting that when I put <sqlMigrationSuffix></sqlMigrationSuffix> empty tag then it should return me description as 'add PASSWORD DEPRECATED column to MIO USER .sql' and it will match with schema_version table's description.

**Comment by axelfontaine** [comment] 2016-09-22 08:04
Duplicate of #403

**Closed by axelfontaine** 2016-09-22 08:04 UTC
