### ISSUE TITLE
Flyway Migration fails with 'from' in sql script

### ISSUE THREAD

**Issue by canbara** [flyway/flyway#1148] opened 2015-12-14 15:34 UTC
Flyway migration fails when using 'from' in quotes. Also similar strings starting with 'from like 'from-address', 'from-mail' etc.

Work around is: use q'[from]' 

[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:3.2.1:migrate (default-cli) on project gateway: org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException:
[ERROR] Migration V4.0.2.0__flyway_from_issue.sql failed
[ERROR] ------------------------------------------------
[ERROR] SQL State  : 22019
[ERROR] Error Code : 911
[ERROR] Message    : ORA-00911: invalid character
[ERROR] Location   : /xxxxx/src/main/resources/db/localdev/comp_dml/V4.0.2.0__flyway_from_issue.sql (/xxxxx/xxx/src/main/resources/db/localdev/comp_dml/V4.0.2.0__flyway_from_issue.sql)
[ERROR] Line       : 2
[ERROR] Statement  : INSERT INTO drb_bundle(BUNDLE, LOCALE, KEY, VALUE, LAST_MODIFIED_TS, USER_ID, CLOB_VALUE)
[ERROR] VALUES('PROCESS_INBOUND_EMAIL.EAST', '_', 'from', 'Error', SYSTIMESTAMP, NULL, NULL);
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.flywaydb:flyway-maven-plugin:3.2.1:migrate (default-cli) on project gateway: org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Migration V4.0.2.0__flyway_from_issue.sql failed
------------------------------------------------
SQL State  : 22019
Error Code : 911
Message    : ORA-00911: invalid character
Location   : /xxxx/src/main/resources/db/localdev/comp_dml/V4.0.2.0__flyway_from_issue.sql (/xxxxx/src/main/resources/db/localdev/comp_dml/V4.0.2.0__flyway_from_issue.sql)
Line       : 2
Statement  : INSERT INTO drb_bundle(BUNDLE, LOCALE, KEY, VALUE, LAST_MODIFIED_TS, USER_ID, CLOB_VALUE)
VALUES('PROCESS_INBOUND_EMAIL.EAST', '_', 'from', 'Error', SYSTIMESTAMP, NULL, NULL);

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Migration V4.0.2.0__flyway_from_issue.sql failed

flyway version : 3.2.1
flyway maven plugin: 3.2.1
maven : 3.2.1
java : 1.8.0_25
DB: Oracle 11g

**Comment by axelfontaine** [comment] 2015-12-14 17:15
Duplicate of #1080

**Closed by axelfontaine** 2015-12-14 17:15 UTC
