### ISSUE TITLE
CockroachDB 2.0.0: Unable to determine deployed schemas resulting repeated attempts to create schema

### ISSUE THREAD

**Issue by bw-smarkwell** [flyway/flyway#1993] opened 2018-04-23 21:34 UTC
###### Cause

The following code from CockroachDBSchema fails in CockroachDB 2.0.0
```
    @Override
    protected boolean doExists() throws SQLException {
        return jdbcTemplate.queryForInt("SELECT COUNT(*) FROM pg_namespace WHERE nspname=?", name) > 0;
    }
```
This issue is exposed due to a defect (I believe) introduced in CockroachDB 2.0. 
I have opened an issue with CockroachDB See [25018](https://github.com/cockroachdb/cockroach/issues/25018)

While CockroachDB should correctly support this SQL Statement, I would expect flyway to produce an exception with appropriate details instead of blindly continuing. 

###### Which version and edition of Flyway are you using?

5.0.7

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

CockroachDB 2.0.0

###### Which operating system are you using?

Windows Pro 1709

###### What did you do?

```
Flyway flyway = new Flyway();
//Limit Flyway's ability to negatively impact a database. 
flyway.setCleanDisabled(true);
flyway.setCleanOnValidationError(false);
flyway.setDataSource(dataSource);		
flyway.setSchemas("perception");
		
flyway.migrate();	
```

###### What did you expect to see?

CockroachDBSchema#doExists() should throw an error if the Prepared Statement does not succeed.

###### What did you see instead?

```
2018-04-23 14:08:32 [main] org.flywaydb.core.internal.util.logging.slf4j.Slf4jLog.info()
INFO: Creating schema "test" ...
2018-04-23 14:08:33 [main] org.flywaydb.core.internal.util.logging.slf4j.Slf4jLog.info()
INFO: Creating schema "test" ...
2018-04-23 14:08:34 [main] org.flywaydb.core.internal.util.logging.slf4j.Slf4jLog.info()
INFO: Creating schema "test" ...
2018-04-23 14:08:35 [main] org.flywaydb.core.internal.util.logging.slf4j.Slf4jLog.info()
INFO: Creating schema "test" ...
2018-04-23 14:08:36 [main] org.flywaydb.core.internal.util.logging.slf4j.Slf4jLog.info()
INFO: Creating schema "test" ...
2018-04-23 14:08:37 [main] org.flywaydb.core.internal.util.logging.slf4j.Slf4jLog.info()
INFO: Creating schema "test" ...
2018-04-23 14:08:38 [main] org.flywaydb.core.internal.util.logging.slf4j.Slf4jLog.info()
INFO: Creating schema "test" ...
2018-04-23 14:08:39 [main] org.flywaydb.core.internal.util.logging.slf4j.Slf4jLog.info()
INFO: Creating schema "test" ...
2018-04-23 14:08:40 [main] org.flywaydb.core.internal.util.logging.slf4j.Slf4jLog.info()
INFO: Creating schema "test" ...
2018-04-23 14:08:41 [main] org.flywaydb.core.internal.util.logging.slf4j.Slf4jLog.info()
INFO: Creating schema "test" ...
```

**Comment by axelfontaine** [comment] 2018-04-26 07:38
Duplicate of #1970

**Closed by axelfontaine** 2018-04-26 07:38 UTC
