### ISSUE TITLE
Unsupported Database: Apache Phoenix

### ISSUE THREAD

**Issue by hortovanyi** [flyway/flyway#1332] opened 2016-06-04 00:05 UTC
###### What version of Flyway are you using?

4.0.1
###### What database are you using (type & version)?

Apache Phoenix - 4.8.0-HBase-1.2-SNAPSHOT"
###### What operating system are you using?

OSX
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Using the thin client driver org.apache.phoenix.queryserver.client.Driver to connect to the Phoenix Query Server
###### What did you expect to see?

Apache Phoenix connection
###### What did you see instead?

[info] Flyway 4.0.1 by Boxfuse
[info] Database: jdbc:phoenix:thin:url=http://localhost:8765;serialization=PROTOBUF (Apache Phoenix 0.0)
org.flywaydb.core.api.FlywayException: Unsupported Database: Apache Phoenix 0.0
    at org.flywaydb.core.internal.dbsupport.DbSupportFactory.createDbSupport(DbSupportFactory.java:141)
    at org.flywaydb.core.Flyway.execute(Flyway.java:1321)
    at org.flywaydb.core.Flyway.info(Flyway.java:1032)
    at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$39$$anonfun$apply$6.apply(FlywayPlugin.scala:191)
    at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$39$$anonfun$apply$6.apply(FlywayPlugin.scala:190)
    at org.flywaydb.sbt.FlywayPlugin$.withContextClassLoader(FlywayPlugin.scala:227)
    at org.flywaydb.sbt.FlywayPlugin$.org$flywaydb$sbt$FlywayPlugin$$withPrepared(FlywayPlugin.scala:210)
    at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$39.apply(FlywayPlugin.scala:190)
    at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$39.apply(FlywayPlugin.scala:190)
    at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
    at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error](*:flywayInfo) org.flywaydb.core.api.FlywayException: Unsupported Database: Apache Phoenix 0.0

**Comment by axelfontaine** [comment] 2016-06-04 09:13
@jmahonin Thoughts?

**Comment by jmahonin** [comment] 2016-06-07 13:06
Looks like the connection string is using the thin client for the query server, rather than the full JDBC client. Note DB URL starting with 'jdbc:phoenix:thin'.

I suspect it should be not much work to implement support for that, but at present it's an unsupported run mode. Note the default driver 'org.apache.phoenix.jdbc.PhoenixDriver' from https://flywaydb.org/documentation/database/phoenix

**Comment by DoodleBobBuffPants** [comment] 2020-10-16 14:11
Duplicate of https://github.com/flyway/flyway/issues/2112

**Closed by DoodleBobBuffPants** 2020-10-16 14:11 UTC
Labels: d: Phoenix, t: bug, t: database support
