### ISSUE TITLE
ERROR: Unable to connect to the database. Configure the url, user and password! When running flyway migrate

### ISSUE THREAD

**Issue by sookyee** [flyway/flyway#3526] opened 2022-09-14 10:14 UTC
###### Which version and edition of Flyway are you using?

9.3.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

Postgresql 11.16

###### Which operating system are you using?
Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I updated the conf file with these settings. The credentials are definitely correct as these are the same credentials used by my django app backend to connect to the db.
flyway.url= jdbc:postgresql://localhost:5432/postgres
flyway.password=password
flyway.user=postgres
type command flyway migrate -X

Put file V1__Create_product_table.sql in sql folder

###### What did you expect to see?
migration success

###### What did you see instead?
![image](https://user-images.githubusercontent.com/69225951/190126934-aa418bac-e0ef-4c68-8952-4f9fdf63b4d8.png)

**Comment by Barry-RG** [comment] 2022-09-15 09:22
Can you confirm if this is an issue in your example in your issue, but there appears to be a space between your `=` and your `jdbc:postgresql://localhost:5432/postgres` for `flyway.url`?
`flyway.url= jdbc:postgresql://localhost:5432/postgres` should look like `flyway.url=jdbc:postgresql://localhost:5432/postgres`

**Comment by sookyee** [comment] 2022-09-19 03:47
No, in my conf file there was no space.Double confirmed this and the error is still the same. Are there any JREs or drivers i need to install additionally in my environment to get it running?

**Comment by sookyee** [comment] 2022-09-26 05:56
Yes that's the default config file & I added my config there...

**Comment by Barry-RG** [comment] 2022-09-26 09:36
Could you give us a copy of your config file to validate as the section given in the issue is not as suggested before?

**Comment by jiannan-lu-kana** [comment] 2022-09-26 16:10
same error here, then I realized it is due to the location of the conf

try to move your  
C:\User\sookyee.lim\Downloads\flyway-commandline-9.3.0-windows-x64\flyway-9.3.0\conf\flyway.conf
to
C:\User\sookyee.lim\Downloads\flyway-commandline-9.3.0-windows-x64\flyway-9.3.0\flyway.conf

**Comment by sookyee** [comment] 2022-10-01 10:07
I have moved the config file one level up and it still doesn't seem to work. One question, if my pgadmin has a master password and i didn't configure a password with my db, what password should i put in the config file?

**Comment by Barry-RG** [comment] 2022-10-03 10:38
The password you would require is likely the password generated during the initialisation of your DB which should have been outputted in the logs during initialisation.

**Comment by DoodleBobBuffPants** [comment] 2022-10-05 10:10
Could you provide a minimal reproduction project?

It's likely your configuration is in the wrong place, as this is something many more people would encounter if it was a Flyway issue, so we'll be closing this until we can get a reproduction

**Closed by DoodleBobBuffPants** 2022-10-05 10:10 UTC
Labels: s: waiting for feedback
