### ISSUE TITLE
Flyway cannot access Cockroach with certificate authentication

### ISSUE THREAD

**Issue by jack-hughes** [flyway/flyway#3120] opened 2021-03-22 12:38 UTC
###### Which version and edition of Flyway are you using?
Client version 7.7.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Tried both the docker container and the linux binary (cli)

###### Which database are you using? (Type & version)
Cockroach Version 20.2.3

###### Which operating system are you using?
Description:	Ubuntu 20.04.1 LTS
Release:	20.04

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I have created a cockroach cluster on my Kubernetes control plane and generated certificates.
I run `cockroach sql --host=localhost --certs-dir=certs` with those certificates after port forwarding to the first instance of cockroach and successfully connect.

I use the following connection parameters to cockroach with Flyway:

```
flyway.url=jdbc:postgresql://localhost:26257/defaultdb?sslmode=verify-full&sslrootcert=certs/ca.crt&sslcert=certs/client.root.crt&sslkey=certs/client.root.key
flyway.user=root
```

###### What did you expect to see?
I run `flyway info` and expect to see connectivity to the database without prompt for a password.

###### What did you see instead?
```
ERROR: 
Unable to obtain connection from database (jdbc:postgresql://localhost:26257/defaultdb?sslmode=verify-full&sslrootcert=certs/ca.crt&sslcert=certs/client.root.crt&sslkey=certs/client.root.key) for user 'root': ERROR: password authentication failed for user root
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : XXUUU
Error Code : 0
Message    : ERROR: password authentication failed for user root

Caused by: org.postgresql.util.PSQLException: ERROR: password authentication failed for user root
```

**Comment by MikielAgutu** [comment] 2021-03-25 14:28
JDBC urls that allow you to connect without specifying username/password often cause Flyway to 'helpfully' prompt for these values, as it assumes they're still necessary.

In such cases, the workaround is to supply an empty username and password (i.e. `flyway.user=` and `flyway.password=`). This will prevent the prompt from appearing.

We're going to make Flyway smarter about this as we discover more cases, so it only prompts when necessary. In the meantime you can use this workaround.

**Comment by jack-hughes** [comment] 2021-03-25 16:02
> JDBC urls that allow you to connect without specifying username/password often cause Flyway to 'helpfully' prompt for these values, as it assumes they're still necessary.
> 
> In such cases, the workaround is to supply an empty username and password (i.e. `flyway.user=` and `flyway.password=`). This will prevent the prompt from appearing.
> 
> We're going to make Flyway smarter about this as we discover more cases, so it only prompts when necessary. In the meantime you can use this workaround.

I can confirm that this also does not work with flyway, see the following error trace:

```
Unable to obtain connection from database (jdbc:postgresql://localhost:26257/defaultdb?ssl=on&sslmode=require&sslrootcert=certs/ca.crt&sslkey=certs/client.root.key&sslcert=certs/client.root.crt) for user '': ERROR: password authentication failed for user 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : XXUUU
Error Code : 0
Message    : ERROR: password authentication failed for user

Caused by: org.postgresql.util.PSQLException: ERROR: password authentication failed for user
```

For the config:

```
flyway.url=jdbc:postgresql://localhost:26257/defaultdb?ssl=on&sslmode=require&sslrootcert=certs/ca.crt&sslkey=certs/client.root.key&sslcert=certs/client.root.crt
flyway.user=
flyway.password=
flyway.defaultSchema=flyway
flyway.locations=filesystem:~/workspace/cockroach/flyway/sql
```

**Comment by DoodleBobBuffPants** [comment] 2021-05-17 14:22
I've been unable to reproduce this

A couple of things to note:
- You still need to provide the username to `flyway.user`
- As per [this](https://forum.cockroachlabs.com/t/connecting-to-an-ssl-secure-server-using-jdbc-java-and-client-certificate-authentication/400) post, you need to change the format of the `crt` and `key` files and use `sslmode=require&ssl=true`

**Comment by DoodleBobBuffPants** [comment] 2021-06-01 11:06
Closing until further activity/can get a reproduction

**Closed by DoodleBobBuffPants** 2021-06-01 11:06 UTC
Labels: d: CockroachDB, s: waiting for feedback
