### ISSUE TITLE
Constraint »uk6dxr3dqx2ktj8tp469m8tiicn« von Relation »bfp_mail_template« existiert nicht, wird übersprungen

### ISSUE THREAD

**Issue by camproto** [flyway/flyway#3324] opened 2021-11-10 10:10 UTC
###### Which version and edition of Flyway are you using?
Flyway Community Edition 7.7.3 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Spring Boot v2.5.3, 
Spring v5.3.9
Hibernate ORM core version 5.4.32.Final

###### Which database are you using? (Type & version)

PostgreSQL 13.3

###### Which operating system are you using?
windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

with this table 
CREATE TABLE bfp_mail_template (
	id int8 NOT NULL,
	created_date timestamp NOT NULL,
	modified_date timestamp NULL,
	channel varchar(255) NULL,
	"content" text NULL,
	receiver varchar(255) NULL,
	subject varchar(255) NULL,
	tenant_id varchar(255) NULL,
	CONSTRAINT bfp_mail_template_pkey PRIMARY KEY (id),
	CONSTRAINT uk6dxr3dqx2ktj8tp469m8tiicn UNIQUE (tenant_id, receiver, channel)
);

###### What did you expect to see?
I want to drop the contraint
alter table bfp_mail_template
    drop constraint "uk6dxr3dqx2ktj8tp469m8tiicn";

constraint is dropped
###### What did you see instead?
but is not, with warning 
Constraint »uk6dxr3dqx2ktj8tp469m8tiicn« von Relation »bfp_mail_template« existiert nicht, wird übersprungen

**Comment by DoodleBobBuffPants** [comment] 2021-11-10 10:20
I am unable to reproduce this, could you provide exact reproduction steps?

**Comment by camproto** [comment] 2021-11-10 10:31
I created this table with a migration V7. With a migration V14 I want to drop this strange named constraint. seems to me, that this constraint name was generated somehow. 
all migrations are running by flyway within spring boot context, but with V14 migration ths constraint is not dropped with  the warning, that the constraint could not be found and the drop will be ignored.

**Comment by DoodleBobBuffPants** [comment] 2021-11-10 12:30
I'm still unable to reproduce this, could you provide a minimal reproduction project with steps to achieve this?

**Comment by camproto** [comment] 2021-11-10 12:32
what do you mean with could not reproduce? is a constraint with such a strange name (how do you get to it?) really dropped at your side?

**Comment by DoodleBobBuffPants** [comment] 2021-11-10 12:38
I created and dropped the constraint using the SQL provided

If the constraint is auto-generated, then you may not have permission to drop it

In this case, Flyway is behaving as expected so closing until we can reproduce an error in Flyway

**Closed by DoodleBobBuffPants** 2021-11-10 12:38 UTC
Labels: s: waiting for feedback

**Comment by camproto** [comment] 2021-11-10 13:23
missing privileges is a good idea
