### ISSUE TITLE
Flyway can't execute scripts out of order (sort gone wrong)

### ISSUE THREAD

**Issue by fieona** [flyway/flyway#1274] opened 2016-04-07 11:51 UTC
###### What version of Flyway are you using?
4.0

###### What database are you using (type & version)?
Oracle 11.0.2

###### What operating system are you using?
Ubuntu 14.0.4

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
We are trying to do an **out of order** migration, but the order Flyway tries to execute the scripts, is wrong.

###### What did you expect to see?
The correct order (a successful migration)

###### What did you see instead?
I got an error message saying the table does not exist (A previous migration script that creates the table was not executed, because the scripts are in the wrong order)

We looked into the flyway source code and found a code change in the comparator. When we removed the comparison on installed_rank, everything worked as expected.

I added some textfiles containing output before the sort, and after the sort. 

Flyway tries to execute this script first: 20160301.001 (=modification of table XYZ) instead of this: 20160212.002 (=creation of table XYZ).

[before.sort.txt](https://github.com/flyway/flyway/files/208267/before.sort.txt)
[after.sort.txt](https://github.com/flyway/flyway/files/208268/after.sort.txt)

Thanks in advance for looking into this!

**Comment by axelfontaine** [comment] 2016-04-07 13:07
Something doesn't seem right here. How can you have null values for installed_rank? Flyway always creates this column as not null...

**Comment by fieona** [comment] 2016-04-09 07:14
Those are new migrations... 
I checked out the source code and added a system.out.println of "installed rank + version" of all migrations, before and after Collections.sort() 
(in MigrationInfoServiceImpl#mergeAvailableAndAppliedMigrations)

Sorry for the confusion :-)

**Comment by ennru** [comment] 2016-04-13 12:55
We experience the same problem with out of order migrations, when migrations with older version numbers need to be run.

**Comment by panchenko** [comment] 2016-04-16 05:55
It seems like this is caused by #1249

**Comment by axelfontaine** [comment] 2016-04-18 14:21
Duplicate of #1249

**Closed by axelfontaine** 2016-04-18 14:21 UTC
Labels: s: waiting for feedback, t: bug
