### ISSUE TITLE
Output to sql file instead of commiting against the DB

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#87] opened 2013-06-25 09:56 UTC
_Original author: sylvain....@gmail.com (March 18, 2013 05:59:16)_

HI,

We're just starting to use flyway in our project and so far it looks really good. It's gonna help us a lot automatically upgrade all of our different environments.

One thing that would be nice is way to combine all or specific sql versions into one sql file. We would use this because we can't tell our client's IT department (big client) to use flyway for upgrading the prod database and we obviously don't have access to that database.
Currently the only way we can get the database upgraded is by sending them an SQL file (which they run on their stage before prod).

In theory we could manually combine all the relevant files ourselves but that could be a bit cumbersome and error-prone. Also things like placeholders would need to be replaced manually (search &amp; replace but still) with the proper value, again error-prone.

We use maven so a new goal should do it.

That said thanks for the great work!

_Original issue: http://code.google.com/p/flyway/issues/detail?id=452_

**Comment by b-long** [comment] 2015-02-10 22:40
+1

**Comment by vbazagad** [comment] 2015-02-21 22:18
+1

**Comment by neylorsousa** [comment] 2015-02-24 00:15
+1

**Comment by alxmrtn** [comment] 2015-02-27 21:03
+1

**Comment by alexeev** [comment] 2015-03-25 11:00
+1

**Comment by facuerregue** [comment] 2015-04-06 12:28
+1

**Comment by vvitayau** [comment] 2015-04-07 03:57
+1

**Comment by jaytradertee** [comment] 2015-06-22 14:30
+1

**Comment by advancedgithub** [comment] 2015-06-25 04:02
+1

**Comment by advancedatolompoiko** [comment] 2015-06-25 04:04
+1

This would be the only missing feature that would allow us to use it in production

**Comment by johnhindley96** [comment] 2015-07-17 16:18
+1

**Comment by svoeller99** [comment] 2015-07-17 19:27
+1

**Comment by mgamer** [comment] 2015-07-20 19:04
+1

**Comment by tihomirsmudj** [comment] 2015-12-04 14:55
+1

**Comment by ThiyaguE** [comment] 2016-01-22 07:42
+1, This is the most wanted one for a fortune 30 telecom company, to use flyway in enterprise level production systems !

**Comment by axelfontaine** [comment] 2016-01-22 08:00
@ThiyaguE Feel free to get in touch by email about [sponsoring this issue](http://flywaydb.org/support/#sponsor) for Flyway 4.1 ...

**Comment by carllindelof** [comment] 2016-03-01 12:57
+1

**Comment by lijo-jacob** [comment] 2016-05-20 20:08
Any medium to large business would definitely need this feature. Enterprise DBA teams are not going to let flyway migrate the production databases (at least any time soon). They will have to execute the migrations themselves in production. 

+1

**Comment by lijo-jacob** [comment] 2016-05-20 20:12
+1

**Comment by kerryland** [comment] 2016-05-20 22:09
On 21 May 2016 at 08:09, Lijo Jacob <notifications@github.com> wrote:

> Enterprise DBA teams are not going to let flyway migrate the production
> databases (at least any time soon). They will have to execute the
> migrations themselves in production.


Because humans never make mistakes running SQL manually. Sigh.

That said, you're right. I've worked in those environments, and have had to
deal with Enterprise DBA teams on power-trips who think they add value by
typing in whatever I tell them to. Flyway is much safer, especially if you
have decent testing and staging environments.

**Comment by gimoteco** [comment] 2016-06-03 21:47
+1

**Comment by schaefec** [comment] 2016-07-19 11:18
+1

**Comment by timvl** [comment] 2016-08-31 07:53
+1

**Comment by jnus** [comment] 2016-09-12 09:42
+1

**Comment by deusaquilus** [comment] 2016-09-23 06:37
+1

**Comment by trumpetx** [comment] 2016-10-18 22:02
+1

**Comment by chris03** [comment] 2016-10-20 13:23
+42

**Comment by trumpetx** [comment] 2016-10-20 17:46
Hey everyone with a +1, I could use some help validating my implementation of "Dry Run".  Did I miss anything?

https://github.com/flyway/flyway/pull/1454

**Comment by cleverdeveloper** [comment] 2016-11-10 21:28
I would be happy to test it, but so far having difficulties to build it with or without your pull request.

**Comment by trumpetx** [comment] 2016-11-10 21:43
@cleverdeveloper - that was my biggest challenge when changing the code, here's how to build by skipping tests:

mvn install -P-CommercialDBTest -P-CommandlinePlatformAssemblies -DskipTests=true

Once built, the version will be 0-SNAPSHOT if I recall correctly...

**Comment by cleverdeveloper** [comment] 2016-11-11 11:12
I am in the process of trying it out, but I wonder if it does output to file as it says in the title or this would be a next step to implement?

**Comment by trumpetx** [comment] 2016-11-11 13:47
You know what, I didn't implement the fix to this issue exactly... interesting.  I found another issue which was closed as a duplicate of this issue and I guess I sort of just implemented the other one.  This quite simply runs a "dry run" (using transactions) against a database to test upgrades before they happen.  I guess maybe I should open a new issue that's distinct from this one (or reopen the other one)

**Comment by who** [comment] 2017-02-07 22:19
+1

**Comment by thebhushanp** [comment] 2017-03-27 04:58
+1

**Comment by myhau** [comment] 2017-03-31 10:06
+1

**Comment by akikhtenko** [comment] 2017-05-24 09:09
+1

**Comment by lichnost** [comment] 2017-06-05 06:40
+1

**Comment by odinsy** [comment] 2017-06-24 15:16
+1

**Comment by ligasgr** [comment] 2017-06-28 12:35
+1

**Comment by shoutcool** [comment] 2017-07-18 21:04
this issue is a show-stopper for using flyway in production environments

**Comment by zeidlermicha** [comment] 2017-07-30 20:23
+1

**Comment by marbon87** [comment] 2017-08-18 06:45
+1

**Comment by rvillars** [comment] 2017-10-03 11:36
+1

**Comment by agusmba** [comment] 2017-10-23 10:50
Maybe using [log4jdbc](https://github.com/arthurblake/log4jdbc) or one of its [more recent forks](https://github.com/Jurrie/log4jdbc/tree/feature/Add_XA_support)?.

You'd need a copy of the staging/production database though (at least its schema and flyway tables...)

**Closed** 2017-11-24 12:01 UTC
Labels: m: Core, t: feature
