### ISSUE TITLE
ALTER TABLE ADD COLUMN in java flyway, automatically adds a CONSTRIANT NOT NULL

### ISSUE THREAD

**Issue by haurel56** [flyway/flyway#3078] opened 2021-02-10 14:00 UTC
###### Which version and edition of Flyway are you using?
Fkyway core 6.0.8

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Did not try

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
PostGreSQL 9.6

###### Which operating system are you using?
Win 10 1909

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
In order to avoid too much flyway sql files, we want to add some columns, and do data migration in java file.
Thus, I have this lines of code
        String sql = "ALTER TABLE mytable ADD COLUMN uidpublic UUID NOT NULL, ADD COLUMN type varchar(256) COLLATE \"POSIX\"";
        jdbcTemplate.execute(sql);

The migration is okay, my table is altered. But a constraint NOT NULL is added on my column type, which make some tests failed.
I executed this SQL in PGAdmin, and no constraint is added.
The create script for this table, returned by PGAdmin is 
CREATE TABLE mytable 
(
    uidpublic uuid NOT NULL,
    type character varying(256) COLLATE pg_catalog."POSIX" NOT NULL,
    uidpublic_target2 uuid NOT NULL
}

###### What did you expect to see?
no error

###### What did you see instead?
I may have null values for this field, so when I try to insert data with a null value
Caused by: org.postgresql.util.PSQLException: ERREUR: une valeur NULL viole la contrainte NOT NULL de la colonne « type»
  Detail: La ligne en échec contient (04997ba7-6d1f-4d47-9d05-45cc1c28e2a5, 477a85cd-8cd4-4fb7-9404-be442ec84e85, 477a85cd-8cd4-4fb7-9404-be442ec84e85, null, null, null)

**Comment by DoodleBobBuffPants** [comment] 2021-02-10 15:52
Are you able to reproduce this in the latest version of Flyway, and if so can you provide the SQL scripts that reproduce this, since I am unable to get a reproduction, and it may be an old bug that has already been fixed

**Comment by haurel56** [comment] 2021-02-10 16:48
Hello
I am not able to easilly test with last version, and I can't give you SQL scripts :(
Btw, I made a lot of another tests, with some flyway scripts (SQL and/or java)
Before migration, my table is only composed of 2 UUIDS, with a Primary key composite with these 2 UUIDS.
- First I drop the Primarykey on this table
- I add these 2 columns
- I run a java algorithm that populates these new columns. (I am sure this algoritm is good because it was tested before)
- and finally, i add the primary key which is a composte key of old UID, and these 2 new fields.
=> There i have my NOT NULL on my type column.
I dropped the schema, reseted and relaunch my flyways scripts without adding the primary key, the not null does not exist on the column type

**Comment by DoodleBobBuffPants** [comment] 2021-02-10 17:04
Flyway doesn't modify the SQL you provide, so it isn't adding the `NOT NULL`. A test you could try is to execute the SQL against your database using the PostgreSQL JDBC driver directly as a part of your whole process, as opposed to using Flyway, to see if it produces the same result

I'm not sure what you mean in your last bullet point. It sounds like you are expecting it to have `NOT NULL` because you're using it as part of a composite key?

Without any reproduction there isn't anything we can do, and it seems Flyway is behaving as expected in all tests I have tried, so closing until we have more to go on

**Closed by DoodleBobBuffPants** 2021-02-10 17:04 UTC
Labels: d: PostgreSQL, s: waiting for feedback

**Comment by haurel56** [comment] 2021-02-10 17:51
Yep, maybe a bug from postgres, i'll continue to investigate. Ty
