### ISSUE TITLE
Distributed transactions with WebLogic fail

### ISSUE THREAD

**Issue by drogin** [flyway/flyway#1444] opened 2016-10-03 11:01 UTC
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
SQL Server 2012

###### What operating system are you using?
Windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I run a Flyway migration thorugh an EJB in WebLogic 12c.
Our datasource to the database is a global transaction using Oracle SQL Non-XA Driver, paired with LLR.

###### What did you expect to see?
A successfull migration

###### What did you see instead?
I got the error:
java.sql.SQLException: Cannot call Connection.commit in distributed transaction.  Transaction Manager will commit the resource manager when the distributed transaction is committed.

Is this because flyway fail to recognize the source being a real XA, since we're using LLR?
Is there some property I have to set besides using the normal Flyway API? Or doesnt Flyway support distributed transactions?

**Comment by drogin** [comment] 2016-10-03 12:19
NOTE: I got it working using Bean-managed transactions with EJB rather than container based.
I suppose Flyway assumes bean-managed

**Comment by axelfontaine** [comment] 2016-10-11 08:52
Duplicate of #86

**Closed by axelfontaine** 2016-10-11 08:52 UTC

**Comment by bonsoftpl** [comment] 2017-09-03 12:40
I fixed the problem by placing flyway calls outside of a transaction.
