### ISSUE TITLE
Use Mulitple Config Files to execute scripts parallel in multiple database at once

### ISSUE THREAD

**Issue by GayathriRamalingam** [flyway/flyway#2076] opened 2018-07-13 15:11 UTC
###### Which version and edition of Flyway are you using?

Flyway 3.2.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

No. I checked with version 5.4.1 in Pro Edition(Trial Period)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

Oracle 11g 11.2.0

###### Which operating system are you using?

windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

flyway -configFiles=./conf/test.conf,./conf/dev1.conf,./conf/dev2.conf migrate

###### What did you expect to see?

I am trying to create a table V1_Create_table_HR_Test.sql in 3 database in test,dev1 and dev2 all at once using 3 config files in command line by invoking flyway just once, instead of invoking flyway each time to connect to different database. I have mentioned db username and password in all 3 config files.

###### What did you see instead?
Flyway is using only the last config file "./conf/dev2.conf" and creating table only in one database dev2.

**Comment by axelfontaine** [comment] 2018-08-01 17:54
Duplicate of #1039

**Closed by axelfontaine** 2018-08-01 17:54 UTC
