### ISSUE TITLE
Could I use pl/sql to define variable with flyways

### ISSUE THREAD

**Issue by Yiao** [flyway/flyway#2459] opened 2019-08-05 15:48 UTC
###### Which version and edition of Flyway are you using?
5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven and Java API

###### Which database are you using (type & version)?
Oracle DB 12.1.0.2.0
PL/SQL 12.1.0.2

###### Which operating system are you using?
windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I want to use variable constant plsql to replace some texts in flyway but I got syntaxe error

    DECLARE
       myname_test CONSTANT VARCHAR2(10) := 'SOME TEXT';
    BEGIN
       INSERT INTO MYTABLE(ID,NAME) VALUES (1,myname_test);
    END;

###### What did you expect to see?
DONE

###### What did you see instead?
SQL State  : 42000
Error Code : 42000
Message    : Erreur de syntaxe dans linstruction SQL {0}
Syntax error in SQL statement {0}; SQL statement:

**Comment by juliahayward** [comment] 2019-08-06 08:47
Hi! Thankyou for the report. Could you try upgrading to Flyway 5.2.4? I've tried to reproduce in that version but it seems to work as expected there.

**Comment by Yiao** [comment] 2019-08-06 09:44
I updated to Flyway 5.2.4 and FlaywayTest to 5.2.4 too, but I got the same problem

**Comment by juliahayward** [comment] 2019-08-06 09:46
OK, could you send a complete copy of the script file please?

**Comment by Yiao** [comment] 2019-08-06 10:14
This script isn't the first file sql of flyway

This part is in my V1.5.0.1_XXXX.sql
```
declare
    v_text CONSTANT VARCHAR2(20) := 'mytest';
begin
    insert into MYTABLE(ID, ATTRIBUT1, ATTRIBUT2) values (1,v_text , 'myattribut2');
    insert into MYTABLE(ID, ATTRIBUT1, ATTRIBUT2) values (15,v_text , 'myattribut2s');
    insert into MYTABLE(ID, ATTRIBUT1, ATTRIBUT2) values (16,v_text , 'myattribut2a');
end;
```

And when I run my test, I got an error :

```
MigrationV1.5.0.1_XXXX.sql failed
----------------------------------------------
SQL State  : 42001
Error Code : 42001
Message    : Erreur de syntaxe dans linstruction SQL {0}; attendu {1}
Syntax error in SQL statement {0}; expected {1}; SQL statement:

declare
    v_text CONSTANT VARCHAR2(20) := 'mytest';
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370)
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:284)

```

**Comment by juliahayward** [comment] 2019-08-06 10:25
OK, could you try again with 6.0.0-beta2? If that still fails, then could you share a small github repo that reproduces the problem?

**Comment by Yiao** [comment] 2019-08-06 10:36
I need to remake my test flyway configuration with flyway 6.0.0-beta2, I don't think this is a good idea for me

**Comment by juliahayward** [comment] 2019-09-05 09:28
Hi again... we now have the formal 6.0 release done (currently 6.0.1), will you be able to update to this version?

**Comment by alextercete** [comment] 2019-10-02 15:46
@Yiao Any news?

**Comment by Yiao** [comment] 2019-10-09 12:13
@alextercete  Nop

**Comment by alextercete** [comment] 2019-10-17 14:58
Closing due to lack of interest.

**Closed by alextercete** 2019-10-17 14:58 UTC
Labels: s: waiting for feedback
