### ISSUE TITLE
Migration of wrapped package leaves package into "malformed or corrupted wrapped unit"

### ISSUE THREAD

**Issue by BaburaoLad** [flyway/flyway#3032] opened 2020-12-17 16:37 UTC
###### Which version and edition of Flyway are you using?
Flyway Community Edition 7.3.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

JAVA API

###### Which database are you using (type & version)?

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

###### Which operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Tried to migrate wrapped package body code 

###### What did you expect to see?

successful migration 

###### What did you see instead?
when try to see invalid objects then found  "malformed or corrupted wrapped unit "

**Comment by BaburaoLad** [comment] 2020-12-17 16:45
Please find the wrapped and unwrapped package which we used for testing , i check the encoding its UTF-8 only but still shows error
[R__resv_recon_odt.zip](https://github.com/flyway/flyway/files/5710891/R__resv_recon_odt.zip)

**Comment by DoodleBobBuffPants** [comment] 2020-12-17 17:39
Could you explain a bit more about what happened? Did migrate fail? Could you also try this in 7.3.2?

**Comment by BaburaoLad** [comment] 2020-12-17 18:53
No migrate did not fail but it shows warning see attached  image 

![image](https://user-images.githubusercontent.com/75744755/102530656-4948fe00-406f-11eb-9400-db6b003824f3.png)

**Comment by BaburaoLad** [comment] 2020-12-17 18:54
I will try 7.3.2 now

**Comment by BaburaoLad** [comment] 2020-12-17 19:05
@DoodleBobBuffPants  We have tried using 7.3.2 but same error . Please note that if we migrate unwrapped version of this file then  it works fine with no invalid

**Comment by BaburaoLad** [comment] 2020-12-17 19:07
Unwrapped version is attached  in R__resv_recon_odt.zip .

**Comment by DoodleBobBuffPants** [comment] 2020-12-17 21:19
I get the same problem even when executing the SQL against a database directly, suggesting the problem is in the SQL. Does the same problem occur if you execute the wrapped SQL against the database directly?

**Comment by BaburaoLad** [comment] 2020-12-17 21:35
@DoodleBobBuffPants  If we execute same wrapped package code in DB it compiles successfully .

**Comment by DoodleBobBuffPants** [comment] 2020-12-17 22:20
When you run Flyway with debug output (run with `-X` or enable viewing debug output wherever you log to), you can see the parsed SQL that Flyway tries to execute. Could you try running this parsed script against the database directly too?

**Comment by BaburaoLad** [comment] 2020-12-18 02:55
@DoodleBobBuffPants  , We have tried to print parsed SQL for one of the package provided in zip file , we tried to compile printed package directly into database and it compiled successfully , please see below logs ,

D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2>flyway migrate -X
DEBUG: Loading config file: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\conf\flyway.conf
DEBUG: Unable to load config file: C:\Users\balad\flyway.conf
DEBUG: Unable to load config file: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\flyway.conf
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\aws-secretsmanager-jdbc-1.0.5.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\derby-10.15.2.0.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\derbyclient-10.15.2.0.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\derbyshared-10.15.2.0.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\derbytools-10.15.2.0.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\google-cloud-spanner-jdbc-1.16.0.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\google-cloud-storage-1.113.2.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\h2-1.4.200.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\hsqldb-2.5.0.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\jaybird-jdk18-3.0.8.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\jna-4.5.2.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\jna-platform-4.5.2.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\jtds-1.3.1.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\mariadb-java-client-2.6.0.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\mssql-jdbc-8.4.1.jre8.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\mysql-connector-java-8.0.20.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\ojdbc8-19.6.0.0.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\postgresql-42.2.14.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\snowflake-jdbc-3.12.0.jar
DEBUG: Adding location to classpath: D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\drivers\sqlite-jdbc-3.30.1.jar
DEBUG: Using configuration:
DEBUG: flyway.ignoreMissingMigrations -> true
DEBUG: flyway.jarDirs -> D:\GitRepo\flyway-commandline-6.4.3-windows-x64\flyway-7.3.2\jars
DEBUG: flyway.locations -> filesystem:sql
DEBUG: flyway.password -> ***********
DEBUG: flyway.sqlMigrationSuffixes -> pkb
DEBUG: flyway.url -> jdbc:oracle:thin:@//wfivm05632.us.oracle.com:1521/ALPHASRVC.us.oracle.com
DEBUG: flyway.user -> OCSMOKE_ASP
DEBUG: Scanning for classpath resources at 'classpath:db/callback' ...
DEBUG: Determining location urls for classpath:db/callback using ClassLoader java.net.URLClassLoader@66480dd7 ...
DEBUG: Unable to resolve location classpath:db/callback.
Flyway Community Edition 7.3.2 by Redgate
DEBUG: AWS SDK available: false
DEBUG: Google Cloud Storage available: false
DEBUG: Scanning for filesystem resources at 'sql'
DEBUG: Scanning for resources in path: sql (sql)
DEBUG: Scanning for resources in path: sql\pkb (sql)
DEBUG: Found filesystem resource: sql\pkb\R__resv_refresh_bi.pkb
DEBUG: Found filesystem resource: sql\put-your-sql-migrations-here.txt
Database: jdbc:oracle:thin:@//wfivm05632.us.oracle.com:1521/ALPHASRVC.us.oracle.com (Oracle 19.0)
DEBUG: Driver  : Oracle JDBC driver 19.6.0.0.0
DEBUG: DDL Transactions Supported: false
DEBUG: Schemas:
DEBUG: Default schema: null
DEBUG: Scanning for SQL callbacks ...
DEBUG: Filtering out resource: sql\put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
DEBUG: Validating migrations ...
DEBUG: Filtering out resource: sql\pkb\R__resv_refresh_bi.pkb (filename: R__resv_refresh_bi.pkb)
DEBUG: Filtering out resource: sql\put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
DEBUG: Filtering out resource: sql\put-your-sql-migrations-here.txt (filename: put-your-sql-migrations-here.txt)
Successfully validated 1056 migrations (execution time 00:09.074s)
Current version of schema "OCSMOKE_ASP": 1
DEBUG: Parsing R__resv_refresh_bi.pkb ...
DEBUG: Found statement at line 1: CREATE OR REPLACE PACKAGE BODY /* $Revision: 494895 $ */ resv_refresh_bi wrapped
a000000
b2
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
b
15b8 845
OGOzDHVZhDt2Y7VVUxpigr4qNWUwgw1UeSDlWo4ZcnOUt34gqds9Geh4MbrHt+l2jdjhiN2Y
P+zOZQ0aK7IOmC7kCBLJOcg10oMZVRsumW6xF//H//tyoPkh+AQyaLk2lVYx63UAr5oXe23I
zYwT/UZZ4LKKf+hh68fzq04Mt2ge/r+/vzkj5ECguoJBJIASM+Mv/CJh1IynmAEIiUqdaMwg
f/YuQ4YaPQESYYN+DzF7jWZiT5USb8Q0KeQBRZG9krJ5sJayoBBYDcWzIcSWEkZIs2I4+Bb0
3x6A0qWB7v5kD1A7PLzuUjPmxp5+sTVBSNp3hGFeNvbKrNbIdiBnSA6zrxAFN50WqllLgPi0
3jNSZwC3de92cGbYiHnIatzEOyP8Qb89Kh3P1C5n3amHn9QCYyyM10QebjK4cmwEoHHTXad7
4trb6O9zXwKIJ/P9UWHXl8wNAjavAKxz+w2Yhb2ApFl3BckvL5i25l0Cm4Shk3W/mLSwhAUo
xWU0b3pMBSUw7GV7mlZU5urM8Se+n1eJgx+NsJj1hLDee5Ak6zDE4Bj0QQBGdyfDKvCZibMG
TUGRlagiNY9ZUuSmpxI9DbhKyJTTmmyF06usZ+Ti0Ae0BheL0CaIOdGqJ6PWyRBfRnTsuJnc
vqg9mv7vPWOzcAbuT3wGnB5Dap/yiG2rfBprHFKAWgh/3ckf3B/1Rt3++44STBR9/Qn/f9qS
rMkQeic526B8MqRMCjP3iBKD219LzRvcEwynb3IOfQYRYQxY2N+R/sLH5JH44gc3YR1W3l/Y
ax6GiibIRMKsNM6ctZ4IJYYcy9g1zJTcjzw9p8h6LXGhTUmQhRg9c0uGW6JkfzzOaKbABMJ5
cwE40LdmBz010V3m5AlgKiJKSCeKLPjugC2xorCGexyUDd2+GhZ6AymslRZKT/09JV5db1aQ
YAo2Nh8yrHzg6D50dEWR9nWt1UXQtJoWh7lsUgpMtwc4FVL8I6u7PMekaHiMKlShKeGrE/u+
OZp/cE3eg+6mtqbsPF40QpSuKh2ky6WmUpls+33emy0wJ8qcbu9e+h5I2TLimyMx3m+3OMoa
9FhRy6xRIJw18G+IsnrF9IVS7i941eDdYBx+Q0j3HND0T9aON8dbOs325sQxQ/SPwKqOeieQ
8wXrgdKNQ8xWd7o6WY9ZK9NAvIpT+6C17ktZNwnoMZ2pE7hUt8pXNg7Gjd8UxmDf6N3c+bXu
UIzvivhL9imjB5/mmp+PCYlBPFB7mBSjAxQ1VeQhvlIRE888fRmFsIdes7PwOfHE6QgV4Hxl
HVV80aB9aq+rL3NOkGvb4e6ZCYQvootARzQoUWbxkjVc3BkWR8Ryxsp7Q1DGH6XiJQgnaTrf
lQVay94ohWsVQlLPlFTqWD1N1jqrbY203TVvk0s6uHFEjB5RxdzdyHZkRxShrJc56snhimJJ
DIOI6Hd5YEKajno+eVJQesEKVaxiEaDorrPFAS2HarA5JdFvZEBuCGkWK3jbQOhV+Qgp6hEK
shlz0aOtNWf11ArSjnDC3//EnfToAS4NYRrMvqFNA/nshO7jPEHyQ6LicOeaFgKW/zJNZtvq
0lGe0ApGqy5hWm5Q/TDP385tN7GJ6z2vwTwwObibJzl9dawGge+I5C/5T/oGHYCmIP3UlSLM
mlWqyw0SRA0LmeoSDGPXkVxitMVhGFV7MdfBfGhBn9WSYTmn4QE2MhvgU6frxYn/JlfsGDAI
Xgw0e9xtPdyKnkMim2FvcZ9wDOVM11Pk30o8Js++7WB6GYolEe008p8zcpvw0VGRvDE3bYxA
aw32B30tz2SvMa2vOqtNSbWWd7f+NQBCW3e3v4QA82kfhRzVkqsJum+BhNms2Rz1NspYD8rs
LXSlrSjEjIicTL3s5fnmgIEEp/+H4vjl65KDaSceV69x4SDukPRxzpVErNVIu1QhEwQZR32K
Lj+L87e/vguhxZ+7/hvbse+zJkYDUYKQex3qx7kKg+6SqDMd/HXvGQaSestd41df4HzBLAVH
SMTSAa5Owg5wRIWG1aydrU6HbhBiJR3TBrWLc0UXFQlunczVmjrKPz8MOqYlLQWd5JnAKuUO



DEBUG: Starting migration of schema "OCSMOKE_ASP" with repeatable migration "resv refresh bi." ...
Migrating schema "OCSMOKE_ASP" with repeatable migration "resv refresh bi."
DEBUG: Executing SQL: CREATE OR REPLACE PACKAGE BODY /* $Revision: 494895 $ */ resv_refresh_bi wrapped
a000000
b2
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
b
15b8 845
OGOzDHVZhDt2Y7VVUxpigr4qNWUwgw1UeSDlWo4ZcnOUt34gqds9Geh4MbrHt+l2jdjhiN2Y
P+zOZQ0aK7IOmC7kCBLJOcg10oMZVRsumW6xF//H//tyoPkh+AQyaLk2lVYx63UAr5oXe23I
zYwT/UZZ4LKKf+hh68fzq04Mt2ge/r+/vzkj5ECguoJBJIASM+Mv/CJh1IynmAEIiUqdaMwg
f/YuQ4YaPQESYYN+DzF7jWZiT5USb8Q0KeQBRZG9krJ5sJayoBBYDcWzIcSWEkZIs2I4+Bb0
3x6A0qWB7v5kD1A7PLzuUjPmxp5+sTVBSNp3hGFeNvbKrNbIdiBnSA6zrxAFN50WqllLgPi0
3jNSZwC3de92cGbYiHnIatzEOyP8Qb89Kh3P1C5n3amHn9QCYyyM10QebjK4cmwEoHHTXad7
4trb6O9zXwKIJ/P9UWHXl8wNAjavAKxz+w2Yhb2ApFl3BckvL5i25l0Cm4Shk3W/mLSwhAUo
xWU0b3pMBSUw7GV7mlZU5urM8Se+n1eJgx+NsJj1hLDee5Ak6zDE4Bj0QQBGdyfDKvCZibMG
TUGRlagiNY9ZUuSmpxI9DbhKyJTTmmyF06usZ+Ti0Ae0BheL0CaIOdGqJ6PWyRBfRnTsuJnc
vqg9mv7vPWOzcAbuT3wGnB5Dap/yiG2rfBprHFKAWgh/3ckf3B/1Rt3++44STBR9/Qn/f9qS
rMkQeic526B8MqRMCjP3iBKD219LzRvcEwynb3IOfQYRYQxY2N+R/sLH5JH44gc3YR1W3l/Y
ax6GiibIRMKsNM6ctZ4IJYYcy9g1zJTcjzw9p8h6LXGhTUmQhRg9c0uGW6JkfzzOaKbABMJ5
cwE40LdmBz010V3m5AlgKiJKSCeKLPjugC2xorCGexyUDd2+GhZ6AymslRZKT/09JV5db1aQ
YAo2Nh8yrHzg6D50dEWR9nWt1UXQtJoWh7lsUgpMtwc4FVL8I6u7PMekaHiMKlShKeGrE/u+
OZp/cE3eg+6mtqbsPF40QpSuKh2ky6WmUpls+33emy0wJ8qcbu9e+h5I2TLimyMx3m+3OMoa
9FhRy6xRIJw18G+IsnrF9IVS7i941eDdYBx+Q0j3HND0T9aON8dbOs325sQxQ/SPwKqOeieQ
8wXrgdKNQ8xWd7o6WY9ZK9NAvIpT+6C17ktZNwnoMZ2pE7hUt8pXNg7Gjd8UxmDf6N3c+bXu
UIzvivhL9imjB5/mmp+PCYlBPFB7mBSjAxQ1VeQhvlIRE888fRmFsIdes7PwOfHE6QgV4Hxl
HVV80aB9aq+rL3NOkGvb4e6ZCYQvootARzQoUWbxkjVc3BkWR8Ryxsp7Q1DGH6XiJQgnaTrf
lQVay94ohWsVQlLPlFTqWD1N1jqrbY203TVvk0s6uHFEjB5RxdzdyHZkRxShrJc56snhimJJ
DIOI6Hd5YEKajno+eVJQesEKVaxiEaDorrPFAS2HarA5JdFvZEBuCGkWK3jbQOhV+Qgp6hEK
shlz0aOtNWf11ArSjnDC3//EnfToAS4NYRrMvqFNA/nshO7jPEHyQ6LicOeaFgKW/zJNZtvq
0lGe0ApGqy5hWm5Q/TDP385tN7GJ6z2vwTwwObibJzl9dawGge+I5C/5T/oGHYCmIP3UlSLM
mlWqyw0SRA0LmeoSDGPXkVxitMVhGFV7MdfBfGhBn9WSYTmn4QE2MhvgU6frxYn/JlfsGDAI
Xgw0e9xtPdyKnkMim2FvcZ9wDOVM11Pk30o8Js++7WB6GYolEe008p8zcpvw0VGRvDE3bYxA
aw32B30tz2SvMa2vOqtNSbWWd7f+NQBCW3e3v4QA82kfhRzVkqsJum+BhNms2Rz1NspYD8rs
LXSlrSjEjIicTL3s5fnmgIEEp/+H4vjl65KDaSceV69x4SDukPRxzpVErNVIu1QhEwQZR32K
Lj+L87e/vguhxZ+7/hvbse+zJkYDUYKQex3qx7kKg+6SqDMd/HXvGQaSestd41df4HzBLAVH
SMTSAa5Owg5wRIWG1aydrU6HbhBiJR3TBrWLc0UXFQlunczVmjrKPz8MOqYlLQWd5JnAKuUO



WARNING: DB: Warning: execution completed with warning (SQL State: 99999 - Error Code: 17110)
DEBUG: Update Count: 0
DEBUG: Successfully completed migration of schema "OCSMOKE_ASP" with repeatable migration "resv refresh bi."
DEBUG: Schema History table "OCSMOKE_ASP"."flyway_schema_history" successfully updated to reflect changes
Successfully applied 1 migration to schema "OCSMOKE_ASP" (execution time 00:02.521s)
DEBUG: Memory usage: 17 of 512M

**Comment by DoodleBobBuffPants** [comment] 2020-12-18 10:00
The parsed SQL printed in these logs is what Flyway executes using the JDBC driver. Since it works successfully when executed against the database directly, this suggests the problem lies with the JDBC driver. I have also tried executing the SQL against a database using just the JDBC driver, and it still produces these warnings. As such, I don't believe this issue lies with Flyway

You are welcome to try executing the wrapped SQL against the database using the JDBC driver, and if you can get it to work I can come back to this, but closing this for now since there's not much more Flyway can do

**Comment by BaburaoLad** [comment] 2020-12-18 12:58
Thanks @DoodleBobBuffPants  for the information , when i tried same with sql developer gives me same error  "malfomred or couurped unit" , please see below 

![image](https://user-images.githubusercontent.com/75744755/102617147-b3f94880-4106-11eb-9cb2-8cd662f66413.png)

But when i add / at end of same code it worked fine , i can see in flyway debug text does not shows / at end even if we have it in file , is it something that we can fix it in flyway to consider that  ?

**Comment by BaburaoLad** [comment] 2020-12-18 12:59
Output when i put / at end in sql developer 

![image](https://user-images.githubusercontent.com/75744755/102617312-fd499800-4106-11eb-91ee-75bcafb845f1.png)

**Comment by DoodleBobBuffPants** [comment] 2020-12-18 13:58
Does every wrapped SQL script therefore fail for you? Since this works for unwrapped SQL, I'm wondering if there is something else going on, and adding the "/" is 'accidentally' fixing it

**Comment by DoodleBobBuffPants** [comment] 2020-12-18 14:45
Having tried with a trailing `/`, the JDBC driver still returns a warning, so this change doesn't fix the problem. From your output in SQL Developer it seems that the statement was ignored, so it may still actually fail.

Could you try running the wrapped SQL with a `/` on the end from a valid state, and see if it then continues to fail or not?

**Comment by BaburaoLad** [comment] 2020-12-18 16:24
@DoodleBobBuffPants  If we add / at end in the wrapped code then it worked in sql developer with warning but those warning are valid as there is dependent package not valid but it does not give ""malformed or corrupted unit" , my only question here is if we have / at end  in the wrapped file and if we provide same file to flyway in debug mode then the parsed SQL does not show / in the log ..i am suspecting that is the issue , please advise .

**Comment by DoodleBobBuffPants** [comment] 2020-12-18 16:58
The `/` delimiter at the end shouldn't matter when executing statements over JDBC. It is basically ignored and testing with other wrapped SQL scripts with and without the `/` confirms this

[This post](http://www.dba-oracle.com/t_pls_00753.htm#:~:text=PLS%2D00753%3A%20Malformed%20or%20corrupted%20wrapped%20unit.,modified%20after%20it%20was%20wrapped.) has some suggestions on how to deal with the 'malformed or corrupted wrapped unit' error, such as removing trailing spaces in your SQL

If none of those suggestions work, would you be able to try it with a valid dependent package? This may help in revealing the true underlying issue

**Comment by BaburaoLad** [comment] 2020-12-18 19:45
@DoodleBobBuffPants  If it is plain text then /  does not matter but for the wrapped code it does .

We tried same with sqlplus and it worked but in flyway it did not so can you please double check .

**Comment by DoodleBobBuffPants** [comment] 2020-12-18 19:59
Different clients behave differently. Could you also check using JDBC outside of Flyway? I have tried several wrapped SQL scripts - functions, packages, package bodies, and they all behave the same with and without a `/`.

If you have a sample script that behaves differently with JDBC and would be able to share it then that would be very helpful

**Comment by DoodleBobBuffPants** [comment] 2020-12-21 13:59
Closing until further activity

**Closed by DoodleBobBuffPants** 2020-12-21 13:59 UTC
Labels: d: Oracle, s: waiting for feedback, t: bug

**Comment by pviltard** [comment] 2022-01-13 10:41
Hi,

I have some troubles with wrapped package.
My Oracle version is 18XE on Windows
      flyway is a Community Edition 8.4.1
and java is 11.0.12 "2021-07-20 LTS"

The configuration file is :
flyway.url=jdbc:oracle:thin:@//localhost:1521/XEMC3
flyway.user=MXXXXXXXX
flyway.password=MZZZZ
flyway.locations=filesystem:C:\SharedFolder\Development\ORACLE\mc3production\flywaySql
flyway.encoding=UTF-8

But with this example file (https://docs.oracle.com/cd/B10500_01/appdev.920/a96624/c_wrap.htm)
CREATE OR REPLACE PACKAGE
-- Author: J. Hollings
-- Date:   10/15/99
banking AS
   minimum_balance CONSTANT REAL := 25.00;
   insufficient_funds EXCEPTION;
END banking;

Toad's wrap produce :
CREATE OR REPLACE PACKAGE
-- Author: J. Hollings
-- Date:   10/15/99
banking wrapped 
a000000
b2
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
9
6c ae
0Na/K8ZdCZiYRGh86kyoKaiP9OMwg5SXf57WZy9EUHdBBk/KWsoup46GV9XWuerCmMjc4Lbm
3ficBgqaZnuXcLQi+LXEqqi++8huQSej2lhGJ1BYvueZhxu2HK5oubFhshcyi6uMCv3Zq9X4
dBIKYpUXQNS0jLZK/6hxyxSndtU=

/

Sqlplus works fine.

I place it into a file, runs flyway -configFiles=.\configuration\oracle_mc3production.conf migrate into a batch windows file. Flyway reports an error : warning 99999 Error 17110. Compilation of the package fails.
The line is well inserts into the table flyway_schema_history

But the package is : pls-00753 malformed or corrupted wrapped unit
Oracle recommends using wrap iname=djfhjh.pks, get the plb file but still the same error. Under sqlplus without any problems.

With the command wrap (18xE) we have this
CREATE OR REPLACE PACKAGE
-- Author: J. Hollings
-- Date:   10/15/99
banking wrapped 
a000000
b2
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
9
6c ae
0Na/K8ZdCZiYRGh86kyoKaiP9OMwg5SXf57WZy9EUHdBBk/KWsoup46GV9XWuerCmMjc4Lbm
3ficBgqaZnuXcLQi+LXEqqi++8huQSej2lhGJ1BYvueZhxu2HK5oubFhshcyi6uMCv3Zq9X4
dBIKYpUXQNS0jLZK/6hxyxSndtU=

/

But still the same others
In different forums solutions are proposed but the result is identical.

Pascal
