### ISSUE TITLE
Cannot use JPA repository inside of AFTER_MIGRATE callback

### ISSUE THREAD

**Issue by nzaouesgi** [flyway/flyway#3239] opened 2021-07-26 21:07 UTC
I'm using Flyway 7.11.3.

I'm using the Java API with Spring Boot 2.5.2. JDK version is 11.

Database version: PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1)

I'm on Windows 10, database is inside a Docker container.

Here is my Flyway config inside my application.properties

```
spring.flyway.enabled=true
spring.flyway.group=true
spring.flyway.placeholder-replacement=false
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
spring.flyway.url=${spring.datasource.url}
spring.flyway.locations=classpath:migrations
```

Here is how i configure my callback:

```java
@Configuration
public class FlywayConfiguration {

    private final BootstrapCallback bootstrapCallback;

    public FlywayConfiguration(
        @Autowired BootstrapCallback bootstrapCallback
    ) {
        this.bootstrapCallback = bootstrapCallback;
    }

    @Bean
    public FlywayConfigurationCustomizer flywayConfigurationCustomizer(){
        return configuration -> {
            configuration
                .callbacks(
                    this.bootstrapCallback
                );
        };
    }
}
```

Here is my callback class:

```java
@Component
public class BootstrapCallback implements Callback {

    private final SomeServiceUsingJpaRepository someServiceUsingJpaRepository;

    public BootstrapCallback(
        // i had to use @Lazy to make injection work here.
        @Lazy SomeServiceUsingJpaRepository someServiceUsingJpaRepository
    ){
        this.someServiceUsingJpaRepository= someServiceUsingJpaRepository;
    }

    @Override
    public boolean canHandleInTransaction(Event event, Context context) {
        // i also tried with false
        return true;
    }

    @Override
    public String getCallbackName() {
        return this.getClass().getName();
    }

    @Override
    public void handle(Event event, Context context){
        // "no EntityManagerFactory set" error thrown here
        this.someServiceUsingJpaRepository.createSomeEntity();
    }

    @Override
    public boolean supports(Event event, Context context) {
        return event.equals(Event.AFTER_MIGRATE);
    }
}
```

I was expecting to be able to use my JPA repositories to insert/update data after the migrate operation is successful.

Migration is working fine, schema is created and logs indicate that everything worked fine. The exception only occurs during the AFTER_MIGRATE callback.

A `java.lang.IllegalStateException: No EntityManagerFactory set` is thrown 9 out of 10 times.

Also, if i disable the callback and i try to insert data at a later time, it works fine.

Current workaround is to use `context.getConnection()` and run raw queries, but it's really not practical in my use case.

Any idea why this is happening ?

Thank you...

**Comment by DoodleBobBuffPants** [comment] 2021-07-27 09:49
This could be due to connections being exhausted but without a reproduction it is hard to tell. Could you provide a reproduction project?

Could you also try setting `flyway.group=false`

**Comment by DoodleBobBuffPants** [comment] 2021-08-02 10:30
Closing until further activity

**Closed by DoodleBobBuffPants** 2021-08-02 10:30 UTC
Labels: s: waiting for feedback
