### ISSUE TITLE
Upgrading to flyway 10.0.0 (from 9.22.3) causes "No database found to handle jdbc:postgresql:..." error

### ISSUE THREAD

**Issue by xenomachina** [flyway/flyway#3775] opened 2023-10-31 19:53 UTC
###### Which version and edition of Flyway are you using?

10.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This only happens with the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle plugin

###### Which database are you using? (Type & version)

PostgreSQL 15

###### Which operating system are you using?

We've experienced this on both Linux and macOS.

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We have a Gradle task that starts up a `postgres:15-alpine` container on localhost with the following docker command:

``` bash
docker run -d \
    -e POSTGRES_PASSWORD=postgres \
    -e POSTGRES_USER=postgres \
    -e POSTGRES_DB=postgres \
    -p 10000:5432 \
    postgres:15-alpine
```

we then have a `flywayMigrate` task configured as:

``` groovy
flyway {
    url = "jdbc:postgresql://localhost:10000/postgres"
    user = 'postgres'
    password = 'postgres'
}
```

(We have tests and code generation tasks that run after this, working against the migrated DB in the container.)

###### What did you expect to see?

The `flywayMigrate` task should connect to the DB in the container and run our DB migrations, as it did on 9.22.3 and earlier:

```
> Task :our-module:startPostgres
Starting postgres:15-alpine container: 41ee37cae66126a7247994417370526a704093b677b5890a28251182a26aea7b
Waiting for it to be ready..ready

> Task :our-module:flywayMigrate
...
> Task :our-module:stopPostgres
...
BUILD SUCCESSFUL in 4s
```

###### What did you see instead?

When switching to 10.0.0 it says "No database found to handle" our JDBC URL:

```
> Task :our-module:startPostgres
Starting postgres:15-alpine container: d7c0d314a6cf2a3060545021d1f93577728f5b5f7edf5606f9ca7b87044052c8
Waiting for it to be ready..ready

> Task :our-module:flywayMigrate FAILED
> Task :our-module:stopPostgres
...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':our-module:flywayMigrate'.
> Error occurred while executing flywayMigrate
  No database found to handle jdbc:postgresql://localhost:10000/postgres
```

Note that this is with **no other changes**. If I flip the version of flyway between 9.22.3 and 10.0.0 it succeeds and fails, respectively.

``` diff 
plugins {
-    id 'org.flywaydb.flyway' version '10.0.0'
+    id 'org.flywaydb.flyway' version '9.22.3'
```

**Comment by Barry-RG** [comment] 2023-11-01 09:54
This seems to be a duplicate of another issue that the owner had closed, please see this issue for more details https://github.com/flyway/flyway/issues/3774

**Closed by Barry-RG** 2023-11-01 09:54 UTC
