### ISSUE TITLE
Error on handling umlaute

### ISSUE THREAD

**Issue by gmuc** [flyway/flyway#1149] opened 2015-12-14 17:26 UTC
My script is
UPDATE LOCATION SET name = 'Schweinfurt Eselshöhe' where LOCATION_ID = 154801;

I use: 
flyway-maven-plugin:3.1

Error was:
12:29:10 [WARNING] DB: Incorrect string value: '\xF6he' for column 'NAME' at row 1 (SQL State: HY000 - Error Code: 1366)
12:29:10 [ERROR] Migration of schema `cirrus` to version 6.5.0.5 failed! Please restore backups and roll back database and code!

My Skript is UTF8 encoded (intellij show this) my database ist UTF8. My script work fine if ein use mysql on commandline. If I change my script to:

UPDATE LOCATION SET name = CONCAT('Schweinfurt Eselsh', unhex('C3B6'), 'he') where LOCATION_ID = 154801;

it work fine too in flyway-maven-plugin:3.1. I think it's a bug in flyway-maven-plugin.

My email is gm.post01@gmail.com.

**Comment by axelfontaine** [comment] 2015-12-14 18:21
Is the same error present with 3.2.1?

**Comment by gmuc** [comment] 2015-12-14 21:40
> Am 14.12.2015 um 19:21 schrieb Axel Fontaine <notifications@github.com>:
> 
> Is the same error present with 3.2.1?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/flyway/flyway/issues/1149#issuecomment-164516559>.
> 

I hope try it tomorrow. I need today hours to delimit this problem. 

It’s safe 99% a flyway bug. If a minimal script work OK on commandline and contain correct characters (od -xc), it must be a problem of flyway.

;-) g e r d

**Comment by gmuc** [comment] 2015-12-15 09:19
flyway-maven-plugin:3.2.1 - same problem

**Comment by axelfontaine** [comment] 2017-02-07 13:11
Unable to reproduce. Closing.

**Closed by axelfontaine** 2017-02-07 13:11 UTC
Labels: s: waiting for feedback

**Comment by philipprawe** [comment] 2018-03-02 10:51
Reproduced with version flyway version 5.0.7

Mysql-DB version is 5.7.1
Flyway is used within an spring boot application. 
Tested on Mac and Ubuntu.

Query: "INSERT INTO countries (id, code, english, german) VALUES (13, 'AT', 'Austria', 'Österreich');"

Log: "2018-03-02 11:36:15 - DB: Incorrect string value: '\xD6sterr...' for column 'german' at row 1 (SQL State: HY000 - Error Code: 1366)"

Database character set is set default to utf-8, direct execution of the query works.
