### ISSUE TITLE
Clean need more options for DB safety

### ISSUE THREAD

**Issue by namvu80ap** [flyway/flyway#933] opened 2015-01-16 01:44 UTC
We recently setted up fllyway for trying to reducing redundant and manual work of network guys to Database.
We, developer, will take care all the change of Database through Flyway API, but we also setup Flyway Command for these guys ( in emergency case )
Then, we found that the "clean" command is very dangerous, because It can drop our Production Data by who can access to Production Server ( the way network guys alway do for some hotfix, that we want to avoid to protect our application ) 

So. I wonder, if it is better "Clean" command have some sub options, such as : drop scheme, tables, trigger, view, fucntions .... and a default is just drop the "schema_version" table ???

**Comment by axelfontaine** [comment] 2015-01-16 07:54
Duplicate of #458 

I currently do not plan on changing the behavior. You can wrap the shell script, intercept and no-op the clean command as a possible workaround.

Cheers
Axel

**Closed by axelfontaine** 2015-01-16 07:54 UTC

**Comment by amyro** [comment] 2015-09-24 13:47
Hello Axel,
i use flywaydb for gradle and also need some disable-option or at least some double checking for the clean command. You and your colleagues mentioned a workaround with a confirmation request. I tried to do this but unfortunately i was not able to add a command line prompt to the command. Can you give me a hint how to solve this or do you have some example for this?
Thanks a lot!
Cheers,
Amy
