### ISSUE TITLE
Cyclic dependency in SBT with flyway, jooq and compile

### ISSUE THREAD

**Issue by RohanPrabhuNomadly** [flyway/flyway#1053] opened 2015-07-15 08:56 UTC
This is the problem I have. Flyway applies a schema to a database, and jOOq generates code from that schema. Compile compiles the code. So this is how it looks like:

    Flyway runs -> jooq runs -> compilation

The problem is that, flyway for some reason, depends on `runtime:fullClasspath`, which in turn depends on `compile:compile`. I understand that flyway depends on compile for any Java migrations, but we don't have any Java migrations. Is there a way for flyway to have dependencies, such that, I can have

    (codegen in JOOQ) <<= (codegen in jOOQ) dependsOn flywayMigrate
    (compile in Compile) <<= (compile in Compile) dependsOn (codegen in jOOQ)

For some projects, we were facing similar problems with the gradle plugin, and it was solved with [Flyway Gradle plugin - Circular dependency](http://stackoverflow.com/questions/22129694/flyway-gradle-plugin-circular-dependency)

I made a fork, and changed all tasks to depend on `externalDependencyClasspath`, for ex.:

    flywayClean <<= (externalDependencyClasspath in Compile, flywayConfig, streams) map {
        (cp, config, s) => withPrepared(cp, s) { Flyway(config).clean() }
    }

But that ends up with a new problem:

    [error] (*:flywayMigrate) org.flywaydb.core.api.FlywayException: Unable to scan for SQL migrations in location: classpath:db/migration

Now, I (maybe) can circumvent the issue above by using a `filesystem:` location for migrations, but my project setup requires that I use `classpath` as some of my depedency jars have migration files in them.

Any help will be greatly appreciated.

**Comment by nafg** [comment] 2015-09-03 07:13
+1, ran into a similar problem (using slick codegen).

I expect that the workaround of keeping the migrations and models in their own subproject should work.

**Comment by axelfontaine** [comment] 2015-12-30 14:11
Duplicate of #979

**Closed by axelfontaine** 2015-12-30 14:11 UTC
