### ISSUE TITLE
can't create table if drop the table first in SqLite

### ISSUE THREAD

**Issue by luzhentao** [flyway/flyway#2264] opened 2019-01-16 12:08 UTC
###### Which version and edition of Flyway are you using?

5.2.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle plugin

###### Which database are you using (type & version)?

SqLite 3.22.0

###### Which operating system are you using?

windows/linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
DROP TABLE IF EXISTS cet_samples ; -- due to schema mismatch
CREATE TABLE "cet_samples" (

	`word_id`	INTEGER,

	`word`	TEXT NOT NULL UNIQUE,

	`cet4`	TEXT,

	`cet6`	TEXT,

	`kaoyan`	TEXT

);
CREATE TABLE "cet_samples1" (

	`word_id`	INTEGER,

	`word`	TEXT NOT NULL UNIQUE,

	`cet4`	TEXT,

	`cet6`	TEXT,

	`kaoyan`	TEXT

);

###### What did you expect to see?

I want't to see old table(cet_samples) is dropped and new cet_samples is created

###### What did you see instead?
cet_samples is dropped but not created. However, the same command can create cet_samples1.

**Comment by luzhentao** [comment] 2019-01-18 01:16
I found the error is caused by the comment "-- due to schema mismatch" at the end of the "DROP TABLE IF EXISTS cet_samples ; -- due to schema mismatch". Flyway think the following CREATE TABLE "cet_samples" as the continuation of comment and ignore the CREATE TABLE command.

**Comment by axelfontaine** [comment] 2019-01-20 18:13
Duplicate of #63

**Closed by axelfontaine** 2019-01-20 18:13 UTC
