### ISSUE TITLE
SQL Server: Some ALTER DATABASE commands lead to hang of flyway

### ISSUE THREAD

**Issue by jdoose** [flyway/flyway#1427] opened 2016-09-12 09:17 UTC
###### What version of Flyway are you using?

4.0.3
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line
###### What database are you using (type & version)?

MS SQL Server 2014
###### What operating system are you using?

Windows 10
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Running a single sql file with a single migration, setting some database options, including
`DISABLE_BROKER` and `DATE_CORRELATION_OPTIMIZATION`
###### What did you expect to see?

Flyway completes the migration with success
###### What did you see instead?

Flyway hangs and waits infinitely.

This is a limitation of SQL Server:

> To set DATE_CORRELATION_OPTIMIZATION to ON, there must be no active connections to the database except for the connection that is executing the ALTER DATABASE statement. Afterwards, multiple connections are supported

and

> ENABLE_BROKER requires an exclusive database lock. If other sessions have locked resources in the database, ENABLE_BROKER will wait until the other sessions release their locks
> (I guess this is also true for `DISABLE_BROKER`)

https://msdn.microsoft.com/en-us/library/bb522682.aspx

Due to another issue (#1426) the `single user`option cannot be set.

So I think this is not a bug per se, but more a documentation issue.

Unfortunately, both mentioned commands get scripted by MS SQL Server Management Studio when a newly created (and empty) database is scripted (Tasks-Generate Scripts), so this seems to be the default.

**Comment by jdoose** [comment] 2016-09-12 09:24
Or maybe Flyway is using more than one DB-Connection? That would lead to the same behaviour. In that case it would be a bug ;)

**Comment by axelfontaine** [comment] 2016-09-14 12:56
Flyway does use two connections: one for the metadata table and one for the actual migrations.

**Comment by axelfontaine** [comment] 2017-11-30 13:17
Duplicate of #1426

**Closed by axelfontaine** 2017-11-30 13:17 UTC
Labels: d: SQL Server, t: bug
