### ISSUE TITLE
Concurrent migrations are not safe/supported on MariaDB Galera Clusters

### ISSUE THREAD

**Issue by JohannesRudolph** [flyway/flyway#1975] opened 2018-04-06 11:49 UTC
###### Which version and edition of Flyway are you using?
3.2.1, 4.2.0, 5.07 (are all affected in one way or another)

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API & gradle

###### Which database are you using (type & version)?
MariaDB Galera Cluster 10.1

###### Which operating system are you using?
Linux

###### What did you do?
We deploy our Spring Boot Apps on Cloud Foundry, concurrently booting multiple instances of our application (usually 2). We were not concerned this would create problems as flyway explicitly mentions that it supports concurrent migrations by using proper lockings. 

###### What did you expect to see?
Migrations executing concurrently in a safe, transactional manner. 

###### What did you see instead?
Migrations interleave, resulting in failed migrations, deadlocks and other mis-behavior. 

####### Background

From what I can piece together (mainly based on @axelfontaine's comments in https://github.com/flyway/flyway/issues/1598), flyway uses: 
- `LOCK TABLES` up to 4.1.1
- `GET_LOCK` and `RELEASE_LOCK` afterwards

However, Galera [does not support](https://mariadb.com/kb/en/library/mariadb-galera-cluster-known-limitations/) these locks: 
> Unsupported explicit locking include LOCK TABLES, FLUSH TABLES {explicit table list} WITH READ LOCK, (GET_LOCK(), RELEASE_LOCK(),…). Using transactions properly should be able to overcome these limitations. Global locking operators like FLUSH TABLES WITH READ LOCK are supported.

Flyway should either document that concurrent migrations are not supported on Galera or find another way to execute them.

**Comment by axelfontaine** [comment] 2018-04-06 15:06
Hmmm this in combination with the note on that same page you linked about DDL and locking does not sound promising. The best strategy to get started is therefore probably to disable to locking logic and warn about it when running on a Galera cluster.

This then leads to the next question: what is the best way to detect one is running on a Galera Cluster and not a plain MariaDB instance?

**Comment by axelfontaine** [comment] 2018-05-03 16:28
Any news?

**Comment by JohannesRudolph** [comment] 2018-05-18 22:32
We currently work around this problem using the strategy described here: https://www.meshcloud.io/en/2018/05/18/migrating-a-galera-cluster-with-flywaydb/

We're aware that this is not an ideal situation but it's working good enough for us. However, to come up with a proper fix we should figure out what locking patterns are available in Galera and how flyway could use them to implement proper locking.

**Comment by pcornelissen** [comment] 2018-09-16 13:43
it is pretty sad that this has not been addressed yet. Why isn't there just a switch that is read from the config that uses simple table row based semaphores?

Example: 
- insert/update row => add for example UUID + lock timestamp
- then select table after transaction commit and check if your UUID is present, in this case migrate, otherwise wait for successful lock
- also remove locks that are too old

This way you can reliably lock even in clusters without table lock.

**Comment by pcornelissen** [comment] 2018-09-16 13:45
also this is a duplicate to #1740

**Comment by axelfontaine** [comment] 2018-09-20 08:59
Duplicate of #1740

**Closed by axelfontaine** 2018-09-20 08:59 UTC
Labels: d: MariaDB, m: Core
