### ISSUE TITLE
Exception when migration runs on multiple nodes against empty schema

### ISSUE THREAD

**Issue by stefanocke** [flyway/flyway#1357] opened 2016-07-08 11:24 UTC
###### What version of Flyway are you using?

3.2.1
###### What database are you using (type & version)?

Oracle DB  10.x
###### What operating system are you using?

Windows and RHEL
###### What did you do?

I ran the migration against an empty database at the same time from two different nodes. (I am using Spring Boot which runs flyway on startup)
###### What did you expect to see?

As the FAQs say, it should be okay to run the migration from multiple nodes, since there is appropriate locking applied.

My explanation for the exception below is, that the schema_version table is used for locking, but if two nodes try to create this table at the same time, there is no locking yet.

In other words,  the MetaDataTableImpl.createIfNotExists seems not to be atomic.

It would be nice if flyway handles this case more gracefully, since the exception below lets the migration fail.  
Instead, there could be something like a retry in this case or the exception could simply be ignored if a second check (in the exception handler) shows the table is already there.
###### What did you see instead?

SQL State : 42000
Error Code : 955
Message : ORA-00955: name is already used by an existing object
Line : 17
Statement : CREATE TABLE "INT_USER"."schema_version" (
"version_rank" INT NOT NULL,
"installed_rank" INT NOT NULL,
"version" VARCHAR2(50) NOT NULL,
"description" VARCHAR2(200) NOT NULL,
"type" VARCHAR2(20) NOT NULL,
"script" VARCHAR2(1000) NOT NULL,
"checksum" INT,
"installed_by" VARCHAR2(100) NOT NULL,
"installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
"execution_time" INT NOT NULL,
"success" NUMBER(1) NOT NULL
)
at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:117)
at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.createIfNotExists(MetaDataTableImpl.java:93)
at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.lock(MetaDataTableImpl.java:100)
at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:158)
at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156)
at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059)
at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)

**Comment by zoza** [comment] 2016-08-02 15:46
we have same issue..

+1 to fix

**Comment by IncredibleLou** [comment] 2016-11-21 14:49
Same here. It happened on production with us yesterday. Someone looking into this?

**Comment by axelfontaine** [comment] 2017-02-07 14:28
Duplicate of #1067

**Closed by axelfontaine** 2017-02-07 14:28 UTC
