### ISSUE TITLE
clean with extensions as not superuser

### ISSUE THREAD

**Issue by kwladyka** [flyway/flyway#1203] opened 2016-02-08 19:04 UTC
During clean command i get an error

`PSQLException ERROR: must be owner of function public.digest  org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse (QueryExecutorImpl.java:2182)`

Because of
```
STATEMENT:  DROP FUNCTION IF EXISTS "public"."digest"(text, text) CASCADE
ERROR:  must be owner of function public.digest
```

As a not superuser can't drop function obviously.

Please add option to clean to not drop extensions. Unless you have solution how to use flyway if you are not superuser?

---

I found next problem with that. I granted superuser access to user to test flyway and i get next problem:
```
PSQLException ERROR: cannot drop function digest(text,text) because extension pgcrypto requires it
  Hint: You can drop extension pgcrypto instead.  org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse (QueryExecutorImpl.java:2182)
```

**Comment by axelfontaine** [comment] 2016-02-08 23:46
Duplicate of #100

**Closed by axelfontaine** 2016-02-08 23:46 UTC
