### ISSUE TITLE
Add ignoreMissingMigrations flag

### ISSUE THREAD

**Issue by expeditioneer** [flyway/flyway#1447] opened 2016-10-07 09:29 UTC
###### What version of Flyway are you using?

4.0.3
###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API
###### What database are you using (type & version)?

h2 1.3.175
###### What operating system are you using?

Windows
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Removed already applied migration script
###### What did you expect to see?

Flyway ignoring the missing, but already applied migration
###### What did you see instead?

Validate failed: Detected applied migration not resolved locally

This was maybe introduced by accident with #988.

Possible solution:
Check also for the MigrationState.MISSING SUCCESS in MigrationInfoImpl::validate()

**Comment by axelfontaine** [comment] 2016-10-17 17:15
The solution here would be to have something like an `ignoreMissingMigrations` flag, set to `false` by default. You could then set it to `true`to get the behavior you want.

**Comment by gsaslis** [comment] 2016-11-14 16:04
👍  need this too

**Comment by sdrzazga** [comment] 2016-12-02 11:38
we need this too

**Comment by axelfontaine** [comment] 2017-01-31 13:50
Duplicate of #1352

**Closed by axelfontaine** 2017-01-31 13:50 UTC
Labels: t: feature
