### ISSUE TITLE
execute sql file with another sql file

### ISSUE THREAD

**Issue by vencoreguy** [flyway/flyway#1828] opened 2017-11-10 16:08 UTC
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
Oracle 12c

###### What operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I have a sql file v1_build_1.sql, with in this I need to execute test_proc.sql
@test_proc.sql

###### What did you expect to see?
it suppose to execute sql statements with in test_proc.sql.

###### What did you see instead?
Error: invalid sql statement

**Comment by axelfontaine** [comment] 2017-11-13 14:59
Duplicate of #705

**Closed by axelfontaine** 2017-11-13 14:59 UTC
