### ISSUE TITLE
Teradata Integration

### ISSUE THREAD

**Issue by asimibm** [flyway/flyway#1660] opened 2017-06-05 14:47 UTC
###### What version of Flyway are you using?
4.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API and Command-line

###### What database are you using (type & version)?
I want to build up the code for Teradata, my test will be done in Teradata 14.0 version.

###### What operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
This is not about issue, but I want to add the support for Teradata. I ran through documentation and assuming that to add new database support I need to first start with the Issue Tracker. Please correct me if my assumption is wrong. I will raise the DEVELOPMENT box access soon.

###### What did you expect to see?
Teradata support

###### What did you see instead?
No Support yet for Teradata

**Comment by axelfontaine** [comment] 2017-06-05 17:07
Duplicate of #1360

**Closed by axelfontaine** 2017-06-05 17:07 UTC
