### ISSUE TITLE
Support dashDB

### ISSUE THREAD

**Issue by bluemixgarage** [flyway/flyway#1529] opened 2017-02-13 19:06 UTC
###### What version of Flyway are you using?
4.1.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
All

###### What database are you using (type & version)?
dashDB (based on db2 10.5 running on Bluemix - the IBM cloud platform)

###### What operating system are you using?
MacOS

###### What did you do?
Do a migrate

###### What did you expect to see?
metadata table created

###### What did you see instead?
A dirty "DB2 SQL Error: SQLCODE=-1666, SQLSTATE=42613, SQLERRMC=CHECK, DRIVER=4.16.53"

###### How could you fix that?
Quickly: just add the "ORGANIZE BY ROW" directive in the createMetadataTable.sql script for db2:
CREATE TABLE ... ( ...) ORGANIZE BY ROW;

The row organization is the default mode for db2 but not for dashDB (column organization).

**Comment by axelfontaine** [comment] 2017-11-17 21:27
Duplicate of #1732

**Closed by axelfontaine** 2017-11-17 21:27 UTC
Labels: d: DB2, s: pull request welcome, t: feature
