### ISSUE TITLE
(DB2) clean fails due to sqlcode=476 following a DROP PROCEDURE statement 

### ISSUE THREAD

**Issue by franciskittu** [flyway/flyway#1722] opened 2017-07-26 10:55 UTC
###### What version of Flyway are you using?

Flyway 4.2.0 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?

DB2 LUW 9.7 FIXPACK 7 

###### What operating system are you using?

WINDOWS 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
**CLEAN** command with some schemas specified with _-schemas=SCHEMA1,SCHEMA2_

###### What did you expect to see?

correct operation execution, so an empty schema.

###### What did you see instead?
sqlcode 476 on a DROP PROCEDURE statement.
**-476 ->** _Reference to routine "<function-name>" was made without a signature, but the routine is not unique in its schema._

###### observation
On DB2, when there are multiple routine "versions", you should drop a specific one with the following command:

`DROP SPECIFIC PROCEDURE  <schemaname>.<specificname>;`

The specific name is available under the SPECIFICNAME column of the catalog view SYSCAT.ROUTINES.
Same as 
#1167

**Comment by axelfontaine** [comment] 2017-08-24 11:55
Duplicate of #1167

**Closed by axelfontaine** 2017-08-24 11:55 UTC
