### ISSUE TITLE
Migration scripts are sometimes skipped during concurrent Flyway runs across multiple schemas

### ISSUE THREAD

**Issue by sreekanthsnair** [flyway/flyway#1616] opened 2017-04-27 09:19 UTC
###### What version of Flyway are you using?

4.1.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?

Postgres 9.4

###### What operating system are you using?

Redhat Linux 6.5

###### What did you do?
Sometimes flyway scripts missed to execute, noticed the following warning as well
WARN [org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner] Unable to resolve location classpath:db/migration

We are using Wildfly 10.1.0.Final as application server. We are running parallel flyway migration to multiple schema's for the same files. We have around 100 schema's but it executed only for 40 schema's, if we restart the application server, it may run it couple more schema's as well.

###### What did you expect to see?

Earlier migrations where working properly after upgrading to 4.1.2 we are facing this issue and its blocker issue for us. 

We used to see messages migrations for all 100 schema's

###### What did you see instead?
 Now most of its showing the warning i have mentioned above.

We are using parallel stream to run the migration sample code as below

```
schemas.parallelStream().forEach(schema -> {
 Flyway flyway = new Flyway();
        flyway.setBaselineOnMigrate(true);
        flyway.setValidateOnMigrate(true);
        flyway.setOutOfOrder(true);
        flyway.setLocations("classpath:/db/migration/main/");
        flyway.setDataSource(dataSource);
        flyway.setSchemas(schema);
        flyway.migrate()
                });
```
We suspect its something to do with https://github.com/flyway/flyway/issues/1261

**Comment by kopax** [comment] 2017-11-07 15:53
I also have this issue when using multiple schema. For when in 5.0.0 scheduled?

**Comment by axelfontaine** [comment] 2017-11-20 09:28
Related to #1039

**Comment by Lyeeedar** [comment] 2020-02-03 14:39
Could you please try this with the latest version of flyway to confirm it is still a problem?

**Comment by juliahayward** [comment] 2020-02-25 11:20
Closing because of the age of the issue. Please open a new one if the problem reoccurs in Flyway 6.

**Comment by topgunjoe** [comment] 2022-03-28 22:29
Encountered the issue while running mvn clean package command. Postgres 13, Maven 3.8.3 

Not sure what the Flyway version is but the Spring boot version is 2.3.4.RELEASE

First migration was being skipped upon executing the command above, but when running the application, migrations are applied normally.

**Comment by DoodleBobBuffPants** [comment] 2022-08-26 12:39
@topgunjoe Could you provide a reproduction and/or some log outputs showing the issue?

**Closed** 2022-08-30 08:30 UTC
Labels: t: bug, d: PostgreSQL, s: waiting for feedback
