### ISSUE TITLE
Flyway and Apache Karaf

### ISSUE THREAD

**Issue by cooshal** [flyway/flyway#2452] opened 2019-08-01 07:49 UTC
###### Which version and edition of Flyway are you using?

5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API with apache Karaf

###### Which database are you using (type & version)?

h2db, and MS-SQL

###### Which operating system are you using?

Windows 10, Windows Server

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
I have shared my project here (https://github.com/cooshal/karaf-flyway)

I am trying to use Flyway API from an osgi bundle. The implementation works perfectly fine when I execute it as a standalone application I get an error.

This (https://github.com/cooshal/karaf-flyway/tree/master/db-migrations/flyway-provider) is my bundle where I am using flyway APIs.

Do I need to make special adjustments for Apache Karaf? I did follow some examples (https://github.com/FlavioF/fabric8-osgi-flyway-example/blob/master/fabric8-osgi-flyway/pom.xml), but that didn't help either.

###### What did you expect to see?

something like: 
```
INFO: Migrating schema "PUBLIC" to version 0.0.1 - Create Hosts Table
INFO: Successfully applied 1 migration to schema "PUBLIC" (execution time 00:00.122s)
```
###### What did you see instead?
```
Error executing command: java.lang.NoClassDefFoundError: Could not initialize class org.flywaydb.core.Flyway
```

The detailed form of this error is:

```
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.flywaydb.core.Flyway
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:?]
        at org.apache.felix.gogo.runtime.CommandSessionImpl$JobImpl.run(CommandSessionImpl.java:829) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.flywaydb.core.Flyway
        at com.example.db.migrations.FlywayDBMigrations.migrate(FlywayDBMigrations.java:16) ~[?:?]
        at com.example.flyway.command.MigrateDatabaseCommand.execute(MigrateDatabaseCommand.java:20) ~[?:?]
        at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:84) ~[?:?]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68) ~[?:?]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86) ~[?:?]
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:571) ~[?:?]
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:497) ~[?:?]
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:386) ~[?:?]
        at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:417) ~[?:?]
        at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229) ~[?:?]
        at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59) ~[?:?]
        ... 4 more
```

**Comment by juliahayward** [comment] 2019-08-01 09:09
This is a duplicate of #1007

**Closed by juliahayward** 2019-08-01 09:09 UTC
