### ISSUE TITLE
Flyway can't connect with MySQL 8.0

### ISSUE THREAD

**Issue by HenriquePereiraRosa** [flyway/flyway#2008] opened 2018-05-07 18:39 UTC
###### Which version and edition of Flyway are you using?
I hadn't added a version in my pom.xml so i'm presuming that the last version is installed.
   `
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>`

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Spring Boot in Netbeans 8.2 (x64)

###### Which database are you using (type & version)?
Hibernate

###### Which operating system are you using?
Windows 7 x64

###### What did you do?
The Flyway can't connect with MySQL 8.0. I've tested the same app with W10 but with MySQL 5.7 and works fine.

###### What did you expect to see?
My Schema and tables created in MySQL

###### What did you see instead?
nothing created.

**Comment by axelfontaine** [comment] 2018-05-07 20:14
Duplicate of #2000

**Closed by axelfontaine** 2018-05-07 20:14 UTC
