### ISSUE TITLE
flyway 3.2 fails with "ORA-00911: invalid character" if script contains default char value

### ISSUE THREAD

**Issue by specifice** [flyway/flyway#974] opened 2015-03-20 10:00 UTC
The following script fails with flyway 3.2
```
    CREATE TABLE TEST_TABLE (
        BOOL_FLAG1 CHAR(1 BYTE) DEFAULT 'N'
    );
```
on oracle XE 11 with
```
    java.sql.SQLSyntaxErrorException: ORA-00911: invalid character
```
Apparently, the character considered invalid is newline. 
Does not fail with Flyway 3.1, neither fails if "DEFAULT 'N'" part is removed.

**Comment by axelfontaine** [comment] 2015-03-20 10:45
Duplicate of #971

**Closed by axelfontaine** 2015-03-20 10:45 UTC
