### ISSUE TITLE
Full stops in flyway.locations path converted to slashes

### ISSUE THREAD

**Issue by okloecker** [flyway/flyway#1353] opened 2016-06-28 21:07 UTC
###### What version of Flyway are you using?
4.0.3

###### What database are you using (type & version)?
Postgres 9.5

###### What operating system are you using?
Windows 8 with Cygwin

###### What did you do?
Define path to sql files inside of project (not flyway conf location) in flyway.properties:
flyway.locations=/cygdrive/C/project/dir.with.full.stops/app/resources/sql

###### What did you expect to see?
Migration files picked up.

###### What did you see instead?
DEBUG: Scanning for classpath resources at 'classpath:cygdrive/C/project/dir/with/full/stops/app/resources/sql' (Prefix: '', Suffix: '.sql')
DEBUG: Determining location urls for classpath:cygdrive/C/project/dir/with/full/stops/app/resources/sql using ClassLoader sun.misc.Launcher$AppClassLoader@5c647e05 ...
WARNING: Unable to resolve location classpath:cygdrive/C/project/dir/with/full/stops/app/resources/sql

**Comment by okloecker** [comment] 2016-06-28 21:42
This looks to be specific to the "classpath:" prefix, not "filesystem:"
flyway.locations=classpath:app/resources.dir/sql turns into
WARNING: Unable to resolve location classpath:app/resources/dir/sql

A flyway.locations=filesystem:app/resources.dir/sql  stays app/resources.dir/sql

(apart from the fact that the current CWD has to be added as a classpath in the flyway shell script to enable searching for sql files relative to project CWD, like so: CP="$INSTALLDIR/lib/*:$INSTALLDIR/drivers/*:$PWD")

**Comment by axelfontaine** [comment] 2016-06-29 07:59
Duplicate of #982

**Closed by axelfontaine** 2016-06-29 07:59 UTC
