### ISSUE TITLE
Maven plugin for flyway does not prompt for password

### ISSUE THREAD

**Issue by VilleMiekkoja** [flyway/flyway#2802] opened 2020-05-02 13:54 UTC
###### Which version and edition of Flyway are you using?
6.4.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
It is the latest version as of writing this.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which database are you using (type & version)?
Postgresql 12.2

###### Which operating system are you using?
Mac

###### What did you do?
Configuration was in pom.xml:
```
	<plugin>
		<groupId>org.flywaydb</groupId>
		<artifactId>flyway-maven-plugin</artifactId>
		<version>6.4.1</version>
		<executions>
			<execution>
				<id>localAndStaging</id>
				<goals>
					<goal>migrate</goal>
				</goals>
				<configuration>
					<url>local-db-url</url>
					<user>local-db-user</user>
					<password>local-db-password</password>
				</configuration>
			</execution>
			<execution>
				<id>production</id>
				<goals>
					<goal>migrate</goal>
				</goals>
				<configuration>
					<url>database_url</url>
				</configuration>
			</execution>
		</executions>
	</plugin>
```

And then I run this flyway migrate command in terminal:
mvn flyway:migrate@production

###### What did you expect to see?
A prompt for password

###### What did you see instead?
Connection error:
org.postgresql.util.PSQLException: The server requested password-based authentication, but no password was provided

**Comment by MikielAgutu** [comment] 2020-05-04 10:56
Duplicate of https://github.com/flyway/flyway/issues/1417 (although that one was closed, so I'll keep this one open)

**Comment by MikielAgutu** [comment] 2020-09-30 10:36
Maven doesn't support this. The Flyway docs have suggestions about how to secure your production passwords: https://flywaydb.org/documentation/maven/#configuration.

**Closed by MikielAgutu** 2020-09-30 10:36 UTC
Labels: m: Maven, t: feature
