### ISSUE TITLE
ValidateOnMigrate should fail for unapplied migration when outOfOrder=false

### ISSUE THREAD

**Issue by PeeZu** [flyway/flyway#1363] opened 2016-07-13 13:04 UTC
###### What version of Flyway are you using?

4.1  via ANT (also tested in 4.3 => same behaviour)
###### What database are you using (type & version)?

Oracle 11.2.0.4
###### What operating system are you using?

Windows 7
###### What did you do?

(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

When we try to migrate with property flyway.validateOnMigrate=true, Flyway doesn't detect not applied migration:

Step to reproduce:
1. Create migrations files: V1.0_foo.sql + V2.0_bar.sql
2. run 'migrate' command
3. Create migration file: V1.1_foo.sql
4. run 'validate' command => Validate failed: Detected resolved migration not applied to database: 1.1 => Expected
5. run 'migrate' command with flyway.validateOnMigrate=true
###### What did you expect to see?

Same as step 4 above: Validate failed: Detected resolved migration not applied to database: 1.1 

Action to do:
Migrate should be run with flyway.outOfOrder=true
###### What did you see instead?

Schema "XXXX" is up to date. No migration necessary.

**Comment by rainoko** [comment] 2016-11-09 09:56
same behavior in v4.01 and v4.0.3
didnt try v4.0.2

**Comment by mmuth** [comment] 2016-11-29 14:27
We have the same issue with v4.0.3.
It's a pity that it doesn't detect the unapplied migrations, because it is one of the core features of Flyway...

**Comment by jkuipers** [comment] 2016-12-12 16:10
I just encountered this with v4.0.3 as well. This is a very serious bug, as it means that the guarantees Flyway is supposed to provide no longer hold. We ran into this when someone had forgotten to merge a migration to a release branch, so it only showed up later after newer migrations had already been applied. 
We have not enabled out-of-order, so Flyway should detect that there's an unapplied migration file that can no longer be applied, but it simply ignores the file.

I'd be happy to contribute a patch if I knew where the error should be thrown in the case of validating while migrating. Right now the code in `MigrationInfoImpl#validate` only performs the check to detect the `IGNORED` migration if `context.pending` is `false`, but it's set to `true` by `Flyway#migrate` when calling the `doValidate` method.

Should the `DbMigrate#migrate` method then somehow detect this migration? Or should the validation already catch this?

**Comment by jkuipers** [comment] 2016-12-12 16:12
BTW, this seems like a duplicate of https://github.com/flyway/flyway/issues/1364 (filed by the same user)

**Comment by mmuth** [comment] 2016-12-15 13:31
@jkuipers great! I hope it will be merged soon 👍

**Comment by PeeZu** [comment] 2016-12-20 10:12
@jkuipers, thanks for the fix, work fine for #1363, but same issue occur on #1364

**Comment by mmuth** [comment] 2017-01-24 15:36
@axelfontaine what do you think about that Pull Request :) ??

**Comment by axelfontaine** [comment] 2017-01-30 16:10
@jkuipers Thanks for the fix! Merged.

**Closed by axelfontaine** 2017-01-30 16:10 UTC
Labels: c: migrate(), c: validate(), m: Core, t: bug
