### ISSUE TITLE
Unable to create oracle packages with a migration

### ISSUE THREAD

**Issue by juanheyns** [flyway/flyway#3828] opened 2024-01-31 21:08 UTC
###### Which version and edition of Flyway are you using?
10.7.0 Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Latest version used

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
JAVA API

###### Which database are you using? (Type & version)
AWS RDS
Oracle 19.0.0.0.ru-2023-10.rur-2023-10.r1

###### Which operating system are you using?
Client is on MacOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Ran a migration for oracle package
```sql
CREATE OR REPLACE PACKAGE HelloWorldPkg AS
    -- Public procedure declaration
    PROCEDURE PrintHelloWorld;
END HelloWorldPkg;
CREATE OR REPLACE PACKAGE BODY HelloWorldPkg AS

    -- Implementation of the procedure
    PROCEDURE PrintHelloWorld IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('Hello, World!');
    END PrintHelloWorld;

END HelloWorldPkg;
```

###### What did you expect to see?
I expected the migration to complete

###### What did you see instead?
I got this exception instead:

```
org.flywaydb.core.api.FlywayException: Unable to parse statement in /tmp/sql/V1.0.4__packages.sql at line 1 col 1. See https://rd.gt/3ipi7Pm for more information: Flyway parsing bug: unable to decrease block depth below 0
	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:299)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:729)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:694)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.parse(ParserSqlScript.java:71)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.validate(ParserSqlScript.java:112)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.executeInTransaction(ParserSqlScript.java:177)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.canExecuteInTransaction(SqlMigrationExecutor.java:70)
	at org.flywaydb.core.internal.command.DbMigrate.isExecuteGroupInTransaction(DbMigrate.java:302)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:267)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:36)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:31)
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:102)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97)
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:202)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:200)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:147)
	at edu.mit.flywaydb_schema_migrations.FlywayAdapter.runFlywayCommand(FlywayAdapter.java:113)
	at edu.mit.flywaydb_schema_migrations.FlywayAdapter.execute(FlywayAdapter.java:69)
	at edu.mit.flywaydb_schema_migrations.App.main(App.java:42)
Caused by: org.flywaydb.core.api.FlywayException: Flyway parsing bug: unable to decrease block depth below 0
	at org.flywaydb.core.internal.parser.ParserContext.decreaseBlockDepth(ParserContext.java:61)
	at org.flywaydb.database.oracle.OracleParser.adjustBlockDepth(OracleParser.java:528)
	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:218)
	... 23 more
```

**Comment by juanheyns** [comment] 2024-01-31 21:41
I have found if I add a `\` statement this does work. Wondering why that would be required. I.e.:

```sql
CREATE OR REPLACE PACKAGE HelloWorldPkg AS
    -- Public procedure declaration
    PROCEDURE PrintHelloWorld;
END HelloWorldPkg;
/

CREATE OR REPLACE PACKAGE BODY HelloWorldPkg AS

    -- Implementation of the procedure
    PROCEDURE PrintHelloWorld IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('Hello, World!');
    END PrintHelloWorld;

END HelloWorldPkg;
/
```

**Comment by tjs145** [comment] 2024-02-01 14:58
Flyway requires most PL/SQL blocks and SQL*Plus statements to be delimited by `/` to ease parsing and to be slightly more consistent with SQL*Plus standards. Though standard SQL statements work with just `;`. 

We could probably document this a bit more clearly. Thanks for bringing this up. 

Closing this issue for now since it's expected behavior.

**Closed by tjs145** 2024-02-01 14:58 UTC
