### ISSUE TITLE
Flyway reports no feedback on SSL timeout until all attempts are exhausted

### ISSUE THREAD

**Issue by busches** [flyway/flyway#3439] opened 2022-05-02 14:18 UTC
###### Which version and edition of Flyway are you using?
8.5.3+, This is using the community edition, but we do have a teams license as well.

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes, the issue starts in 8.5.3,[ likely due to the driver upgrade](https://github.com/flyway/flyway/issues/3405), and is still present in 8.5.10

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command Line via Docker Image

###### Which database are you using? (Type & version)
```
Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64) 
	Jan 12 2022 22:30:08 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 18.04.6 LTS) <X64>
```

###### Which operating system are you using?
Running the client on OSX and Linux (Debian and Alpine)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Running the following command via docker-compose:

```
services:
  flyway:
    image: flyway/flyway:8.5.10
    command: -url="jdbc:sqlserver://10.128.16.7;database=MyDatabase;" -locations=filesystem:/flyway/sql/migrations -user=sa -password=Password#123 -connectRetries=10 -baselineOnMigrate=true -table=flyway_schema_history_bs migrate
    volumes:
      - ./migrations:/flyway/sql
```

The first migration is a simple `INSERT INTO`, which correctly works on 8.5.2.

###### What did you expect to see?
- Log output
- Flyway to complete or fail
- The docker container to exit

###### What did you see instead?
With version 8.5.3 -> 8.5.10
- No log output
- Docker container never exits 

8.5.2 is the last working version. [8.5.3 upgrades the MSSQL driver](https://github.com/flyway/flyway/issues/3405) and sets `encrypt=true`, which should not be an issue.

I see no login attempt from the database logs either.

Note: We've had no issues upgrading to 8.5.10 with our Postgres Databases, so it appears to be a specific issue to MSSQL, which is all but confirmed by the driver upgrade done in 8.5.3.

Update, after coming back to the container, logs were finally flushed:
```
2022-05-02T14:23:01.313596601Z WARNING: Connection error: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:1489580a-55c6-4577-a4be-acee34ecb784
2022-05-02T14:23:01.313642381Z (Caused by unable to find valid certification path to requested target)
2022-05-02T14:23:01.313648178Z Retrying in 1 sec...
2022-05-02T14:23:01.313651519Z WARNING: Connection error: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:52173bef-2629-473d-98a0-09207307a78a
2022-05-02T14:23:01.313655086Z (Caused by unable to find valid certification path to requested target)
2022-05-02T14:23:01.313658018Z Retrying in 2 sec...
2022-05-02T14:23:01.313661093Z WARNING: Connection error: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:6dd87706-efca-4396-87a3-8750de0e4c3a
2022-05-02T14:23:01.313664517Z (Caused by unable to find valid certification path to requested target)
2022-05-02T14:23:01.313667340Z Retrying in 4 sec...
2022-05-02T14:23:01.313670109Z WARNING: Connection error: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:9bc3a3aa-4d99-4665-9b6b-a2482be59f69
2022-05-02T14:23:01.313673370Z (Caused by unable to find valid certification path to requested target)
2022-05-02T14:23:01.313676088Z Retrying in 8 sec...
2022-05-02T14:23:01.313679560Z WARNING: Connection error: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:efb50ac7-3cd1-424b-85b2-b76ec30f95f4
2022-05-02T14:23:01.313683039Z (Caused by unable to find valid certification path to requested target)
2022-05-02T14:23:01.313685812Z Retrying in 16 sec...
2022-05-02T14:23:01.313688599Z WARNING: Connection error: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:e422e2cf-b5d8-4fe3-8c87-6be8015b4595
2022-05-02T14:23:01.313691798Z (Caused by unable to find valid certification path to requested target)
2022-05-02T14:23:01.313694505Z Retrying in 32 sec...
2022-05-02T14:23:01.313697205Z WARNING: Connection error: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:1a087786-bb07-4c6f-84fe-edfee0fb5e9a
2022-05-02T14:23:01.313720198Z (Caused by unable to find valid certification path to requested target)
2022-05-02T14:23:01.314221876Z Retrying in 64 sec...
2022-05-02T14:23:01.314288891Z WARNING: Connection error: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:ddb4f514-145a-423b-8b09-d98ef665b2fc
2022-05-02T14:23:01.314322919Z (Caused by unable to find valid certification path to requested target)
2022-05-02T14:23:01.314343765Z Retrying in 120 sec...
2022-05-02T14:23:01.314346908Z WARNING: Connection error: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:b8a43ba4-6351-4e1f-9e85-4c7e4f06e9fb
2022-05-02T14:23:01.314350164Z (Caused by unable to find valid certification path to requested target)
2022-05-02T14:23:01.314352830Z Retrying in 120 sec...
2022-05-02T14:23:01.314355468Z WARNING: Connection error: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:4988121d-85ec-45ee-95f5-ebc2a5864564
2022-05-02T14:23:01.314358433Z (Caused by unable to find valid certification path to requested target)
2022-05-02T14:23:01.314360899Z Retrying in 120 sec...
2022-05-02T14:23:01.314225700Z ERROR: Unable to obtain connection from database (jdbc:sqlserver://10.128.16.7;database=MyDatabase;integratedSecurity=false;user=sa;password=************;encrypt=true;) for user 'null': The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:f5db07f4-694f-4115-848e-3e6bca046507
2022-05-02T14:23:01.314370551Z --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2022-05-02T14:23:01.314373733Z SQL State  : 08S01
2022-05-02T14:23:01.314376221Z Error Code : 0
2022-05-02T14:23:01.314378693Z Message    : The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:f5db07f4-694f-4115-848e-3e6bca046507
2022-05-02T14:23:01.314436032Z 
2022-05-02T14:23:01.314439209Z Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:f5db07f4-694f-4115-848e-3e6bca046507
2022-05-02T14:23:01.314442163Z Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2022-05-02T14:23:01.314445226Z Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2022-05-02T14:23:01.314447954Z Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

And because of that error if I update the JDBC connection string to have `;encrypt=false`, then it connects immediately, but the SSL cert used by MSSQL should be supported by flyway.

Also, I don't understand why this breaking change was in a patch version. 😿

**Comment by DoodleBobBuffPants** [comment] 2022-06-06 11:37
The original issue is driver related as you identified

As for the logs, this is likely to do with standard out being buffered - we don't do any buffering of output on our end. You can take a look at disabling output buffering for your OS

**Comment by busches** [comment] 2022-06-06 14:44
My OS would be the one in the docker image, you don't think this would be helpful to fix in the image?

**Comment by abscondment** [comment] 2022-06-14 23:32
I'm also seeing this in flyway 8.5.11 connecting to MySQL.

```
[...]
WARNING: Connection error: Could not connect to address=(host=qaproxysql-lb)(port=3306)(type=master) : Could not connect to qaproxysql-lb:3306 : PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
(Caused by unable to find valid certification path to requested target)
Retrying in 120 sec...
```

**Comment by julielerman** [comment] 2022-09-07 20:44
I'm having this issue with latest (which IIRC is 9.2.2) and explicitly with 9.2.3.

I'm on macOS Monterey latest. Using this with SQL Server image  latest.

If I explicitly tag flyway/flyway:8.5.2 (which I chose based on above conversation) my connection, migration etc work just fine. But if I let it pick up latest or explicitly tag 9.2.3, I am also having the SSL problems.

I am only doing this on my development machine and not using any explicit certs.

Preparing for a conference session so I'm happy to have found this thread.

**Comment by DoodleBobBuffPants** [comment] 2022-09-08 12:43
We've investigated the issue and it seems to be a problem with `docker compose` buffering the output. Running with `docker run` doesn't cause this issue

We also verified that using `docker compose` with the latest version of Flyway doesn't seem to be reproducing this issue. As it's also an issue with `docker compose` it's not something we would be able to fix, so closing

**Closed by DoodleBobBuffPants** 2022-09-08 12:43 UTC

**Comment by julielerman** [comment] 2022-09-08 13:08
latest version of flyway as in 9.2.3? I will try that again

**Comment by julielerman** [comment] 2022-09-08 14:44
For others finding there way to this issue: I reduced the terms in teh search, this is a common problem related to the jdbc driver. I have tried the suggestions of adding encrypt=false and trustServerCertificate=true to the jdbc connection string. I have found this workaround for SQL Server (what I'm using) which walks through a fix on windows but will try to adapt to macOS https://techcommunity.microsoft.com/t5/azure-database-support-blog/pkix-path-building-failed-unable-to-find-valid-certification/ba-p/2591304

**Comment by reecebradley** [comment] 2022-10-05 15:21
My 2 cents, I am encountering this issue and the latest container image says `9.3.1`, so is this really fixed? What do you need from me to confirm? My `docker-compose.yml` mirrored a little where the docker image [explanation states](https://github.com/flyway/flyway-docker#docker-compose)

```yaml
version: "3"
services:
  flyway:
    image: flyway/flyway
    command: baseline -url=jdbc:sqlserver://db;databaseName=Canary;user=sa;password=Passw0rd;encrypt=false; -connectRetries=160 
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      SA_PASSWORD: Passw0rd
      ACCEPT_EULA: Y
```

Here is all the gory error:
```
--------------------------------------------------------------------------------------------------------------------------
SQL State  : 08S01
Error Code : 0
Message    : The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:27d6b7af-80a8-48db-8dee-2801a706e773

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:27d6b7af-80a8-48db-8dee-2801a706e773
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

As extra info, the db runs fine, so I don't see any issues there.

I found the article earlier that @julielerman also found, just haven't given it a go. 

@DoodleBobBuffPants are we sure this is fixed?

**Comment by julielerman** [comment] 2024-06-23 15:27
How have I found my way back here two years later? None of this has been resolved? Do I really need to continue use v8? :(

**Comment by julielerman** [comment] 2024-06-23 18:03
Update: hours and hours later: I needed to put the url parameter in single quotes FFS. I discovered it after reading and experimenting a lot. There was nothing in docs or anywhere that suggested to do this.

`  command:  -user=sa -password=P@ssword1 -mixed=true -connectRetries=20 -url='jdbc:sqlserver://db;databaseName=master;trustServerCertificate=true'`

Guessing its because of the semi-colons.

**Comment by sakshivij** [comment] 2024-09-10 17:36
> Update: hours and hours later: I needed to put the url parameter in single quotes FFS. I discovered it after reading and experimenting a lot. There was nothing in docs or anywhere that suggested to do this.
> 
> ` command: -user=sa -password=P@ssword1 -mixed=true -connectRetries=20 -url='jdbc:sqlserver://db;databaseName=master;trustServerCertificate=true'`
> 
> Guessing its because of the semi-colons and related to a change in Java? (I'm a c# dev so ....¯_(ツ)_/¯ )

This works. Thanks for saving alot of time
