### ISSUE TITLE
Connecting to oracle via ldaps 

### ISSUE THREAD

**Issue by kausku** [flyway/flyway#2521] opened 2019-10-01 19:37 UTC
###### Which version and edition of Flyway are you using?
6.0.4 (also tried 5.2.4)
with 
Gradle 5.6.2
JDK 11

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
gradle plugin

###### Which database are you using (type & version)?
oracle 12

###### Which operating system are you using?
macOS / linux

###### What did you do?
command: ./gradlew flywayInfo

Seems like gradle plugin is not using the correct driver when trying to connect via ldap. It throws an error that we see when trying to connect to oracle with an incorrect driver. Is there any way to specify which driver we want the plugin to use? or is the issue completely different?

url: jdbc:oracle:thin:@ldaps://host:port/tns,CN=OracleContext,dc=name,dc=com

gradle build file:
dependencies {
    compile "org.flywaydb:flyway-core:6.0.4"
    compile "com.oracle:ojdbc8:12.2.0.2"
}

error:
SQL State  : 08006
Error Code : 17002
Message    : IO Error: JNDI Package failure javax.naming.CommunicationException: <host>:<port> [Root exception is java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory]

        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
        at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:72)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1670)
        at org.flywaydb.core.Flyway.info(Flyway.java:1521)
        at org.flywaydb.gradle.task.FlywayInfoTask.run(FlywayInfoTask.java:32)
        at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.java:489)
        .....
        Caused by: java.sql.SQLRecoverableException: IO Error: JNDI Package failure javax.naming.CommunicationException: <host>:<port> [Root exception is java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory]
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:774)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:433)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:399)
        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
        .....
        Caused by: oracle.net.ns.NetException: JNDI Package failure javax.naming.CommunicationException: <host>:<port> [Root exception is java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory]
        at oracle.net.jndi.JndiAttrs.initializeLDAPContext(JndiAttrs.java:183)
        at oracle.net.jndi.JndiAttrs.<init>(JndiAttrs.java:162)
        at oracle.net.resolver.AddrResolution.<init>(AddrResolution.java:233)
        at oracle.net.ns.NSProtocol.connect(NSProtocol.java:233)
        at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1474)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:518)
        .....
        Caused by: javax.naming.CommunicationException: <host>:<port> [Root exception is java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory]
        at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:237)
        at java.naming/com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
        at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1610)
        at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2752)
        at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:320)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
        at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
        at oracle.net.jndi.JndiAttrs.initializeLDAPContext(JndiAttrs.java:175)
        ....
        Caused by: java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory
        at java.naming/com.sun.jndi.ldap.VersionHelper.loadClass(VersionHelper.java:76)
        at java.naming/com.sun.jndi.ldap.Connection.createSocket(Connection.java:275)
        at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:216)

###### What did you expect to see?
flyway command running successfully

**Comment by MikielAgutu** [comment] 2019-10-02 10:25
> Is there any way to specify which driver we want the plugin to use?

You can specify the JDBC driver with the `flyway.driver` config option. Drivers are loaded from the `/drivers` directory in the Flyway installation directory.

It may well be that Flyway is using an incorrect driver. To confirm, can you use a different driver and see if it works?

Relevant docs pages:
- https://flywaydb.org/documentation/gradle/#extending-the-default-classpath
- https://flywaydb.org/documentation/configfiles

**Comment by kausku** [comment] 2019-10-02 15:44
umm I am not sure what you mean... isnt the /drivers directory for the command-line-tool? 
I am using the gradle plugin.

Anyways here's what i tried:

- created a drivers directory same level as the build.gradle file and placed the driver jar there
- then ran flyInfo with flyway.driver option set to oracle.jdbc.driver.OracleDriver

Still same result

**Comment by MikielAgutu** [comment] 2019-10-02 16:34
Sorry the guidance wasn't clear. Can you try the following:

- Create a new directory `drivers` for your gradle project
- In your `build.gradle` file add `drivers` as a [`flatDir` repository](https://docs.gradle.org/current/userguide/repository_types.html)
- Add a classpath dependency for your driver (e.g. `dependencies { classpath "org.oracle...:name-of-jar-file" }`)
- Add the flyway gradle property `driver` with the class name for the JDBC driver (e.g `driver = oracle.jdbc.driver.OracleDriver`)

It may also be simpler to try the command line way also, just for the sake of testing if this will work at all.

**Comment by kausku** [comment] 2019-10-02 19:20
Thanks tried all that and got the same error.
Got the same error with command-line-tool as well.

Finally, i tried with direct creds and without SSL or Ldap and got a meaningful error:

Flyway Community Edition 6.0.2 by Redgate
Database: jdbc:oracle:thin:........ ,dc=com (Oracle 12.1)
ERROR: Flyway Enterprise Edition or Oracle upgrade required: Oracle 12.1 is no longer supported by Flyway Community Edition, but still supported by Flyway Enterprise Edition.

Wish i had known that earlier lol

**Comment by MikielAgutu** [comment] 2019-10-03 08:21
Well that would explain things :) Although I'm still slightly suspicious of the ldaps error message, given that it's so vague. [Oracle 12.2 is supported by community edition](https://flywaydb.org/documentation/database/oracle). If possible it might be worth checking if you can connect to a 12.2 DB with this connection string just to confirm the licensing isn't the only issue.

**Comment by kausku** [comment] 2019-10-03 17:41
I have no way of upgrading oracle right now but I tested the same connect string with flyway 4.0.3 and that worked.

**Comment by MikielAgutu** [comment] 2019-10-07 08:54
Oracle 12.1 support became [Enterprise only in 5.2.0](https://flywaydb.org/documentation/releaseNotes#5.2.0). So that would explain why 4.0.3 works - if indeed the issue is to do with licensing. I am still suspicious of a regression perhaps between V4 and V5. Sorry to be a pain, but could you check if 4.0.3 works too?

As for your second question, `jvm_opts` looks to be Oracle's specific implementation of the `JAVA_OPTS` convention: https://stackoverflow.com/a/5241791/5437021

>`JAVA_OPTS` is the standard environment variable that some servers and other java apps append to the call that executes the java command.

Flyway currently doesn't support it. However we may be able to support TLS via a different mechanism. Could you create another issue with more detail so we can better track this problem?

**Comment by kausku** [comment] 2019-10-07 15:49
Yes you are right.
version 4.0.3 works with oracle 12.1 both ldap and ldaps urls
version 5.1.4 only works with ldap and doesnt with ldaps

I will create a different issue.

**Comment by MikielAgutu** [comment] 2019-10-08 09:28
Thanks for testing that out and coming up with repro steps. I'll close this one since it's getting a bit polluted and the bug is now captured in #2526.

**Closed by MikielAgutu** 2019-10-08 09:28 UTC
Labels: d: Oracle, t: bug
