### ISSUE TITLE
Gradle plugin does not resolve `implementation`-scoped artifacts, only `compile`

### ISSUE THREAD

**Issue by o-nix** [flyway/flyway#2272] opened 2019-01-23 10:26 UTC
###### Which version and edition of Flyway are you using?

5.2.4 latest release

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle plugin

###### Which database are you using (type & version)?

MariaDB 10.1.37

###### Which operating system are you using?

macOS High Sierra 10.13.6

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

When I run `./gradlew flywayMigrate` against an artifact with migration files attached in `implementation project(':migrations')` the plugin cannot find migration resources.
In the other hand when I change the scope to `compile` it works.
Migration files are found in the production-ready artifact because Gradle itself is able to include every `implementation` dependency.

###### What did you expect to see?

I expect that my project's artifact dependencies are resolved correctly in runtime.

###### What did you see instead?

An error related to not resolved or missing migrations.

**Comment by axelfontaine** [comment] 2019-01-23 12:52
Could you post a small example `build.gradle` file that reproduces this?

**Comment by zhogov** [comment] 2019-04-03 20:34
["compile" configuration is deprecated per Gradle docs](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation):

> The compile configuration still exists but should not be used as it will not offer the guarantees that the api and implementation configurations provide. 

[But still used per Flyway docs:
](https://flywaydb.org/documentation/gradle/#extending-the-default-classpath)

> By default the Flyway Gradle plugin uses a classpath consisting of the **compile**, runtime, testCompile and testRuntime Gradle configurations for loading drivers, migrations, resolvers, callbacks, etc.

Example `build.gradle`:
```
plugins {
    id "org.flywaydb.flyway" version "5.2.4"
    id "java"
}

repositories { mavenCentral() }

dependencies {
    implementation group: 'postgresql', name: 'postgresql', version: '9.0-801.jdbc4'
}

flyway {
    url = 'jdbc:postgresql://localhost:5432/mydb'
}
```
I get following error:
```
$ ./gradlew flywayMigrate
> Task :flywayMigrate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flywayMigrate'.
> Error occurred while executing flywayMigrate
  Unable to instantiate JDBC driver: org.postgresql.Driver => Check whether the jar file is present
  Unable to instantiate class org.postgresql.Driver : org.postgresql.Driver
  org.postgresql.Driver

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
```

Works if I replace `implementation` with `compile`:
```
$ ./gradlew flywayMigrate
> Task :flywayMigrate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flywayMigrate'.
> Error occurred while executing flywayMigrate

  Unable to obtain connection from database (jdbc:postgresql://localhost:5432/mydb) for user 'null': The server requested password-based authentication, but no password was provided.
  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  SQL State  : 08004
  Error Code : 0
  Message    : The server requested password-based authentication, but no password was provided.

  The server requested password-based authentication, but no password was provided.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

**Comment by zhogov** [comment] 2019-04-03 20:36
So as per @o-nix this can be fixed by changing [AbstractFlywayTask.java](https://github.com/flyway/flyway/blob/master/flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java#L59)

**Comment by sdwarwick** [comment] 2019-04-14 19:33
ran into this as well - need to add Implementation!

**Comment by johannesloher** [comment] 2019-06-18 13:23
I also just ran into this. Is what @o-nix and @zhogov suggested really all that is required to fix this issue?

**Comment by axelfontaine** [comment] 2019-06-18 14:26
This is configurable as described in the docs: https://flywaydb.org/documentation/gradle/#extending-the-default-classpath

**Comment by o-nix** [comment] 2019-06-18 14:49
@axelfontaine why do you still think this is a documentation problem? It's a default configuration one.

**Comment by johannesloher** [comment] 2019-06-18 15:26
@axelfontaine I tried adding "implementation" as a configuration as described in the docs which you linked to. This does not seem to work however, I get the following error message:

```
Resolving configuration 'implementation' directly is not allowed [...]
```

Also I think that it should work out of the box with "implementation" and "api" because "compile" has been deprecated and is supposed to be replaced by "implementation" or "api" depending on the context.

**Comment by axelfontaine** [comment] 2019-06-18 15:43
@johannesloher The new set of configurations is available here: https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_plugin_and_dependency_management

It's interesting that the Gradle team decided to make some of them non-resolvable. Would you like to dig into the plugin code to see how this could be fixed?

**Comment by sdwarwick** [comment] 2019-06-21 14:13
@axelfontaine this is a blocking bug for using the gradle plugin on the current version of gradle.

**Comment by axelfontaine** [comment] 2019-06-21 14:15
@sdwarwick Would you like to dig in and look how this could be resolved?

**Closed** 2019-06-21 14:57 UTC
Labels: m: Gradle

**Comment by axelfontaine** [comment] 2019-06-21 15:00
Made defaults vary based on Gradle version. New default configuration names for Gradle 4.x and newer are now `compileClasspath`, `runtimeClasspath`, `testCompileClasspath`, `testRuntimeClasspath` and can already be configured in existing versions of the plugin as described in the docs: https://flywaydb.org/documentation/gradle/#extending-the-default-classpath
