### ISSUE TITLE
Validating files versions during build

### ISSUE THREAD

**Issue by abbasadel** [flyway/flyway#2388] opened 2019-05-18 15:05 UTC
Hi, 

I sometimes get into the situation where multiple branches with different migration files with the same version are merged to the main branch and then we discover the issue during the release on the production.

It would be great if the maven/Gradle plugin validates the files versioning sequence during the CI build time (maybe maven validate phase).

I'm winning to contribute the feature.

Thanks 
Abbas

**Comment by axelfontaine** [comment] 2019-05-18 15:16
Duplicate of #986

**Closed by axelfontaine** 2019-05-18 15:16 UTC
