### ISSUE TITLE
script name need not be described

### ISSUE THREAD

**Issue by wenzis** [flyway/flyway#1516] opened 2017-02-04 07:06 UTC
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
mysql-5.6.34

###### What operating system are you using?
linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I want the script file name does not contain descriptive information, because I put the description of the information in a document in a unified maintenance

###### What did you expect to see?
V0_0_1.sql

###### What did you see instead?
V0_0_1__description.sql

**Comment by wenzis** [comment] 2017-02-06 06:48
Is anyone here?

**Comment by axelfontaine** [comment] 2017-02-06 11:01
Duplicate of #936

**Closed by axelfontaine** 2017-02-06 11:01 UTC
