### ISSUE TITLE
Syntax error "[*]￿" with empty sql script

### ISSUE THREAD

**Issue by kevcodez** [flyway/flyway#2065] opened 2018-07-03 18:45 UTC
###### Which version and edition of Flyway are you using?

5.1.3 Community Edition

###### Which database are you using (type & version)?

H2 embedded

###### Which operating system are you using?

Windows

########

I tried to upgrade Flyway to 5.1.3 in Spring-Boot. I migrated the deprecated classes. The tests in the spring-boot-autoconfiguration module have empty V1__xxx.sql scripts. Those fail due to an syntax error. Not sure if this is an error that only appears on Windows, but the tests work fine with the older version 5.0.7.

I tracked it down to the DefaultLineReader#readLine, that reads a single character '\uFFFF' 65535, even though the file is empty. When adding one empty line to the .sql file, it works fine.

Branch containing the bug: https://github.com/kevcodez/spring-boot/tree/upgrade-flyway

Test to run: org.springframework.boot.autoconfigure.flyway.FlywayAutoConfigurationTests

Error log:

```
2018-07-03 20:38:53.511 ERROR   --- [           main] o.f.core.internal.command.DbMigrate      : Migration of schema "PUBLIC" to version 1 - init failed! Please restore backups and roll back database and code!
2018-07-03 20:38:53.524  WARN   --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V1__init.sql failed
-----------------------------
SQL State  : 42000
Error Code : 42000
Message    : Syntax Fehler in SQL Befehl "[*]￿"
Syntax error in SQL statement "[*]￿"; SQL statement:
￿ [42000-197]
Location   : db/migration/V1__init.sql (C:\Users\Kevin\Documents\GitHub\spring-boot\spring-boot-project\spring-boot-autoconfigure\target\test-classes\db\migration\V1__init.sql)
Line       : 1
Statement  : ￿

2018-07-03 20:38:53.524  INFO   --- [           main] o.s.j.d.e.EmbeddedDatabaseFactory        : Shutting down embedded database: url='jdbc:h2:mem:7661f1c2-2e30-4650-b61e-4b95517b3f0d;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false'

java.lang.AssertionError: 
Expecting:
 <Unstarted application context org.springframework.boot.test.context.assertj.AssertableApplicationContext[startupFailure=org.springframework.beans.factory.BeanCreationException]>
to have a single bean of type:
 <org.flywaydb.core.Flyway>:
but context failed to start:
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
 Migration V1__init.sql failed
 -----------------------------
 SQL State  : 42000
 Error Code : 42000
 Message    : Syntax Fehler in SQL Befehl "[*]￿"
 Syntax error in SQL statement "[*]￿"; SQL statement:
 ￿ [42000-197]
 Location   : db/migration/V1__init.sql (C:\Users\Kevin\Documents\GitHub\spring-boot\spring-boot-project\spring-boot-autoconfigure\target\test-classes\db\migration\V1__init.sql)
 Line       : 1
 Statement  : ￿
 
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1726)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
 	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.configureContext(AbstractApplicationContextRunner.java:340)
 	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.createAndLoadContext(AbstractApplicationContextRunner.java:317)
 	at org.springframework.boot.test.context.assertj.AssertProviderApplicationContextInvocationHandler.getContextOrStartupFailure(AssertProviderApplicationContextInvocationHandler.java:62)
 	at org.springframework.boot.test.context.assertj.AssertProviderApplicationContextInvocationHandler.<init>(AssertProviderApplicationContextInvocationHandler.java:49)
 	at org.springframework.boot.test.context.assertj.ApplicationContextAssertProvider.get(ApplicationContextAssertProvider.java:111)
 	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.createAssertableContext(AbstractApplicationContextRunner.java:310)
 	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.lambda$null$0(AbstractApplicationContextRunner.java:278)
 	at org.springframework.boot.test.util.TestPropertyValues.applyToSystemProperties(TestPropertyValues.java:130)
 	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.lambda$run$1(AbstractApplicationContextRunner.java:277)
 	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.withContextClassLoader(AbstractApplicationContextRunner.java:289)
 	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.run(AbstractApplicationContextRunner.java:276)
 	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfigurationTests.defaultFlyway(FlywayAutoConfigurationTests.java:140)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
 Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
 Migration V1__init.sql failed
 -----------------------------
 SQL State  : 42000
 Error Code : 42000
 Message    : Syntax Fehler in SQL Befehl "[*]￿"
 Syntax error in SQL statement "[*]￿"; SQL statement:
 ￿ [42000-197]
 Location   : db/migration/V1__init.sql (C:\Users\Kevin\Documents\GitHub\spring-boot\spring-boot-project\spring-boot-autoconfigure\target\test-classes\db\migration\V1__init.sql)
 Line       : 1
 Statement  : ￿
 
 	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:355)
 	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:53)
 	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:282)
 	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
 	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:279)
 	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
 	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:53)
 	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:163)
 	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:160)
 	at org.flywaydb.core.internal.database.Connection$1.call(Connection.java:145)
 	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
 	at org.flywaydb.core.internal.database.Connection.lock(Connection.java:141)
 	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:150)
 	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:160)
 	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:138)
 	at org.flywaydb.core.Flyway$1.execute(Flyway.java:947)
 	at org.flywaydb.core.Flyway$1.execute(Flyway.java:910)
 	at org.flywaydb.core.Flyway.execute(Flyway.java:1238)
 	at org.flywaydb.core.Flyway.migrate(Flyway.java:910)
 	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1785)
 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1722)
 	... 48 more
 Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: 
 Migration V1__init.sql failed
 -----------------------------
 SQL State  : 42000
 Error Code : 42000
 Message    : Syntax Fehler in SQL Befehl "[*]￿"
 Syntax error in SQL statement "[*]￿"; SQL statement:
 ￿ [42000-197]
 Location   : db/migration/V1__init.sql (C:\Users\Kevin\Documents\GitHub\spring-boot\spring-boot-project\spring-boot-autoconfigure\target\test-classes\db\migration\V1__init.sql)
 Line       : 1
 Statement  : ￿
 
 	at org.flywaydb.core.internal.database.ExecutableSqlScript.handleException(ExecutableSqlScript.java:325)
 	at org.flywaydb.core.internal.database.ExecutableSqlScript.executeStatement(ExecutableSqlScript.java:301)
 	at org.flywaydb.core.internal.database.ExecutableSqlScript.execute(ExecutableSqlScript.java:243)
 	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:91)
 	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:352)
 	... 69 more
 Caused by: org.h2.jdbc.JdbcSQLException: Syntax Fehler in SQL Befehl "[*]￿"
 Syntax error in SQL statement "[*]￿"; SQL statement:
 ￿ [42000-197]
 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
 	at org.h2.message.DbException.get(DbException.java:179)
 	at org.h2.message.DbException.get(DbException.java:155)
 	at org.h2.message.DbException.getSyntaxError(DbException.java:203)
 	at org.h2.command.Parser.getSyntaxError(Parser.java:548)
 	at org.h2.command.Parser.getSpecialType(Parser.java:4161)
 	at org.h2.command.Parser.read(Parser.java:3651)
 	at org.h2.command.Parser.parse(Parser.java:334)
 	at org.h2.command.Parser.parse(Parser.java:311)
 	at org.h2.command.Parser.prepareCommand(Parser.java:278)
 	at org.h2.engine.Session.prepareLocal(Session.java:611)
 	at org.h2.engine.Session.prepareCommand(Session.java:549)
 	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
 	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
 	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:205)
 	at org.flywaydb.core.internal.util.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:259)
 	at org.flywaydb.core.internal.database.StandardSqlStatement.execute(StandardSqlStatement.java:44)
 	at org.flywaydb.core.internal.database.ExecutableSqlScript.executeStatement(ExecutableSqlScript.java:280)
 	... 72 more


	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfigurationTests.lambda$defaultFlyway$6(FlywayAutoConfigurationTests.java:141)
	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.accept(AbstractApplicationContextRunner.java:345)
	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.lambda$null$0(AbstractApplicationContextRunner.java:279)
	at org.springframework.boot.test.util.TestPropertyValues.applyToSystemProperties(TestPropertyValues.java:130)
	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.lambda$run$1(AbstractApplicationContextRunner.java:277)
	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.withContextClassLoader(AbstractApplicationContextRunner.java:289)
	at org.springframework.boot.test.context.runner.AbstractApplicationContextRunner.run(AbstractApplicationContextRunner.java:276)
	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfigurationTests.defaultFlyway(FlywayAutoConfigurationTests.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
```

**Comment by axelfontaine** [comment] 2018-07-04 07:04
Duplicate of #2052

**Closed by axelfontaine** 2018-07-04 07:04 UTC
